g_tTotur = {}
g_tTotur.OnReload = function() end --空函数，使ReloadScript默认重载逻辑不执行
g_tTotur.tTest = {}
g_tTotur.tComment = {}
g_tTotur.tMove = {}
g_tTotur.tFight = {}
g_tTotur.tShop = {}
g_tTotur.tOperator = {}
g_tTotur.tCollect = {}
g_tTotur.tSkill = {}
g_tTotur.tMap = {}
g_tTotur.tQuest = {}
g_tTotur.tOperato = {}

g_tTotur.tTest.IMG_TEST = {Text = "<font size='24'><img src='UIAtlas2_Public_PublicSchool_PublicSchool_iocn_school_cangjainshanzhuang' width='20' height='20'/>图片<color=#FF0000>测试</color><img src='UIAtlas2_Public_PublicSchool_PublicSchool_iocn_school_mingjiao' width='50' height='50'/>测试<img src='UIAtlas2_Public_PublicSchool_PublicSchool_iocn_school_qixiufang' width='50' height='50'/></font>", Level = 0}
g_tTotur.tComment.CLICK_INTERACTIVE = {Text = "<font size='24'>点击与附近人物<color=#F0DC82>对话</color></font>", Level = 1}
g_tTotur.tMove.FOLLOW_GUIDE = {Text = "<font size='24'>跟随<img src='UIAtlas2_Public_PublicIcon_PublicIcon1_icon_mubiao' width='48' height='48'/><color=#F0DC82>路引</color>可前往目的地</font>", Level = 1}
g_tTotur.tMove.Slider_Screen_DXC = {Text = "<font size='24'>滑动屏幕<color=#F0DC82>调整视角</color>面向<color=#F0DC82>阿诛</color></font>", Level = 1}
g_tTotur.tFight.Attack_Change = {Text = "<font size='24'>点击切换到<color=#F0DC82>攻击模式</color></font>", Level = 1}
g_tTotur.tMove.MOVE_FORWARD = {Text = "<font size='24'>滑动摇杆可<color=#F0DC82>向前移动</color></font>", Level = 1}
g_tTotur.tComment.QUEST_ACCESS = {Text = "<font size='24'>点击按钮<color=#F0DC82>接受任务</color></font>", Level = 1}
g_tTotur.tComment.QUEST_RPG = {Text = "<font size='24'>点击任意位置与其<color=#F0DC82>对话</color></font>", Level = 1}
g_tTotur.tFight.SELECT_TARGET = {Text = "<font size='24'>切换到<color=#F0DC82>攻击模式</color>释放技能攻击附近的<color=#F0DC82>混混</color></font>", Level = 1}
g_tTotur.tShop.Npc_Buy1 = {Text = "<font size='24'>点击<color=#F0DC82>购买</color>即可获得商品</font>", Level = 1}
g_tTotur.tOperator.FirstSpring = {Text = "<font size='20'>持续使用轻功跳跃需要消耗气力值，停止后可缓慢回复。</font>", Level = 1}
g_tTotur.tCollect.Collect_NXC = {Text = "<font size='24'>点击<color=#F0DC82>凝血草</color>进行<color=#F0DC82>采集</color></font>", Level = 1}
g_tTotur.tComment.FIRST_TEAM = {Text = "<font size='24'>点击可查看队伍<color=#F0DC82>详细信息</color></font>", Level = 1}
g_tTotur.tOperator.Flying_Skill1 = {Text = "<font size='26'>点击<img src='UIAtlas2_MainCity_MainCitySkill1_icon_qinggong_01' width='80' height='80'/><color=#F0DC82>轻功</color>按钮可施展轻功，进入疾跑段</font>", Level = 1}
g_tTotur.tOperator.Flying_Skill2 = {Text = "<font size='26'>点击<img src='UIAtlas2_MainCity_MainCitySkill1_icon_qinggong_main04' width='80' height='80'/><color=#F0DC82>轻功</color>按钮可进入纵跃段</font>", Level = 1}
g_tTotur.tOperator.Flying_Skill3 = {Text = "<font size='26'>继续点击<img src='UIAtlas2_MainCity_MainCitySkill1_icon_qinggong_main04' width='80' height='80'/><color=#F0DC82>轻功</color>按钮可跃起飞行</font>", Level = 1}
g_tTotur.tOperator.QuickUse = {Text = "<font size='24'>当前气力值低\n点击<color=#F0DC82>快捷使用风身散</color></font>", Level = 1}
g_tTotur.tComment.TEAM = {Text = "<font size='24'>点击头像可查看队友<color=#F0DC82>详细信息</color></font>", Level = 1}
g_tTotur.tOperator.QuickUse_ChooseItem = {Text = "<font size='24'>点击配置<color=#F0DC82>快捷使用</color>栏位</font>", Level = 1}
g_tTotur.tOperator.QuickUse_AddItem = {Text = "<font size='24'>点击选择道具添加到<color=#F0DC82>快捷使用</color></font>", Level = 1}
g_tTotur.tOperator.QuickUse_Item = {Text = "<font size='24'><color=#F0DC82>风身散</color>可瞬时回复<color=#F0DC82>气力值\n</color>点击<color=#F0DC82>快捷使用</color>该道具</font>", Level = 1}
g_tTotur.tFight.Attack_CastSkill_1 = {Text = "<font size='24'>点击释放<color=#F0DC82>傍身招式</color>进行<color=#F0DC82>攻击</color></font>", Level = 1}
g_tTotur.tMove.Slider_Screen_TYFM_Second = {Text = "<font size='24'>滑动屏幕可<color=#F0DC82>调整镜头视角</color></font>", Level = 1}
g_tTotur.tFight.Sprint_Skill = {Text = "<font size='24'>点击释放<color=#F0DC82>蹑云</color>可躲避攻击</font>", Level = 1}
g_tTotur.tCollect.Collect_SBBX = {Text = "<font size='24'>点击打开<color=#F0DC82>神兵宝匣</color></font>", Level = 1}
g_tTotur.tMove.Jump_Skill = {Text = "<font size='24'><color=#F0DC82>向前移动</color>同时点击<color=#F0DC82>跳跃</color>按钮可跃过平台</font>", Level = 1}
g_tTotur.tMove.Slider_Screen_TYFM_First = {Text = "<font size='24'>滑动屏幕可<color=#F0DC82>调整镜头视角</color></font>", Level = 1}
g_tTotur.tMove.Slider_Screen_TYFM_Third = {Text = "<font size='24'>滑动屏幕可<color=#F0DC82>调整镜头视角</color></font>", Level = 1}
g_tTotur.tShop.Npc_Buy2 = {Text = "<font size='24'><color=#F0DC82>选择</color>需要购买的商品</font>", Level = 1}
g_tTotur.tOperator.Open_Menu = {Text = "<font size='24'>点击打开<color=#F0DC82>菜单栏</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_Teach = {Text = "<font size='24'>点击查看游戏<color=#F0DC82>基础教学</color></font>", Level = 1}
g_tTotur.tMove.MOVE_NEAR = {Text = "<font size='24'>滑动摇杆<color=#F0DC82>移动</color>靠近<color=#F0DC82>李天玄</color></font>", Level = 1}
g_tTotur.tComment.CLICK_SUBMIT = {Text = "<font size='24'>与附近人物<color=#F0DC82>对话</color>完成任务</font>", Level = 1}
g_tTotur.tFight.Attack__Select = {Text = "<font size='24'>点击按钮可<color=#F0DC82>锁定</color>敌人</font>", Level = 1}
g_tTotur.tFight.Attack__Tips = {Text = "<font size='26'>点击<img src='UIAtlas2_MainCity_MainCitySkill1_img_skill_lock' width='48' height='48'/><color=#F0DC82>锁定</color>后，使用<color=#F0DC82>技能</color>攻击敌人</font>", Level = 1}
g_tTotur.tShop.CLICK_ShopClose = {Text = "<font size='24'>点击按钮<color=#F0DC82>关闭</color>商店</font>", Level = 1}
g_tTotur.tOperator.Flying_Sprint = {Text = "<font size='26'>点击<img src='UIAtlas2_MainCity_MainCitySkill1_icon_qinggong_01' width='80' height='80'/><color=#F0DC82>轻功</color>按钮可施展轻功，进入疾跑状态</font>", Level = 1}
g_tTotur.tOperator.CLICK_Service = {Text = "<font size='24'>查看游戏操作及玩法等指引</font>", Level = 1}
g_tTotur.tMove.Slider_Screen_TYFM_Fourth = {Text = "<font size='24'>滑动屏幕可<color=#F0DC82>调整镜头视角</color></font>", Level = 1}
g_tTotur.tOperator.Open_HuaELou = {Text = "<font size='24'>点击打开<color=#F0DC82>花萼楼</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_JHXJ = {Text = "<font size='24'>点击打开<color=#F0DC82>江湖行记</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_Collect = {Text = "<font size='24'>领取所有江湖行记奖励</font>", Level = 1}
g_tTotur.tOperator.Open_BeiBao = {Text = "<font size='24'>点击打开<color=#F0DC82>背包</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_ItemYXLL_yifu1 = {Text = "<font size='24'>点击选中<color=#F0DC82>玉雪灵龙·衣</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_ItemYXLL_yifu2 = {Text = "<font size='24'>点击<color=#F0DC82>使用</color>获取玉雪灵龙·衣</font>", Level = 1}
g_tTotur.tOperator.CLICK_ItemYXLL_toufa1 = {Text = "<font size='24'>点击选中<color=#F0DC82>玉雪灵龙·白发</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_ItemYXLL_toufa2 = {Text = "<font size='24'>点击<color=#F0DC82>使用</color>获取玉雪灵龙·白发</font>", Level = 1}
g_tTotur.tOperator.CLICK_ItemAH_chongwu1 = {Text = "<font size='24'>点击选中<color=#F0DC82>宠物·阿黄</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_ItemAH_chongwu2 = {Text = "<font size='24'>点击<color=#F0DC82>使用</color>获取宠物·阿黄</font>", Level = 1}
g_tTotur.tOperator.CLICK_pet = {Text = "<font size='24'>点击查看<color=#F0DC82>宠物</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_pet_zhaohuan = {Text = "<font size='24'>点击召唤<color=#F0DC82>宠物</color></font>", Level = 1}
g_tTotur.tSkill.KungFu_XinFa = {Text = "<font size='24'>此处查看或更改<color=#F0DC82>心法</color></font>", Level = 1}
g_tTotur.tSkill.KungFu_QiXue = {Text = "<font size='24'>此处可<color=#F0DC82>选择装备奇穴</color></font>", Level = 1}
g_tTotur.tSkill.KungFu_ZhaoShi = {Text = "<font size='24'>当前正在使用的<color=#F0DC82>招式配置</color></font>", Level = 1}
g_tTotur.tSkill.KungFu_ZhaoShiPeiZhi = {Text = "<font size='24'>此处可自定义<color=#F0DC82>招式配置</color></font>", Level = 1}
g_tTotur.tSkill.KungFu_TuiJianPeizhi = {Text = "<font size='24'>点击打开配置列表</font>", Level = 1}
g_tTotur.tSkill.KungFu_WuXueXiangQing = {Text = "<font size='24'>点击可查看<color=#F0DC82>武学详情</color></font>", Level = 1}
g_tTotur.tSkill.KungFu_WXXQ_zhaoshi = {Text = "<font size='24'>点击可查看<color=#F0DC82>招式说明</color></font>", Level = 1}
g_tTotur.tOperator.WaiGuan = {Text = "<font size='24'>点击<color=#F0DC82>外观</color>可查看新获得的外观</font>", Level = 1}
g_tTotur.tOperator.WaiGuan_xiazai = {Text = "<font size='24'><color=#F0DC82>预览</color>外观须下载该外观资源</font>", Level = 1}
g_tTotur.tOperator.WorldMap_xiazai = {Text = "<font size='24'>点击可下载该地图资源</font>", Level = 1}
g_tTotur.tOperator.CLICK_WuXueZhuShou = {Text = "<font size='24'>进入<color=#F0DC82>武学助手</color>状态，\n可在战斗中自动释放技能</font>", Level = 1}
g_tTotur.tOperator.CLICK_WuXueZhuShou_closed = {Text = "<font size='24'>关闭<color=#F0DC82>武学助手</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_MiJing = {Text = "<font size='24'>点击打开<color=#F0DC82>秘境</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_MiJing_TeShu = {Text = "<font size='24'>点击打开<color=#F0DC82>特殊玩法</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_BaiZhan = {Text = "<font size='24'>点击<color=#F0DC82>百战异闻录</color>玩法</font>", Level = 1}
g_tTotur.tOperator.CLICK_BaiZhanWuXue = {Text = "<font size='24'>点击打开<color=#F0DC82>百战武学面板</color></font>", Level = 1}
g_tTotur.tMove.RunToLiTianXuan = {Text = "<font size='26'>按住 <img src='UIAtlas2_Teach_Teach_Img_KeyW' width='32' height='32'/> 向前移动，靠近<color=#F0DC82>李天玄</color></font>", Level = 1}
g_tTotur.tFight.FirstAttack__Tips = {Text = "<font size='26'>点击释放<color=#F0DC82>傍身招式</color>进行<color=#F0DC82>攻击</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_OtherPlayer = {Text = "<font size='24'>点击可与该玩家进行<color=#F0DC82>交互</color></font>", Level = 1}
g_tTotur.tOperator.TEAM_Voice_Group = {Text = "<font size='24'><color=#F0DC82>麦克风</color>设置</font>", Level = 1}
g_tTotur.tOperator.TEAM_Voice_Open = {Text = "<font size='24'>可设置<color=#F0DC82>麦克风</color>开启或关闭</font>", Level = 1}
g_tTotur.tOperator.Chat_Page = {Text = "<font size='24'>点击切换到<color=#F0DC82>聊天页</color></font>", Level = 1}
g_tTotur.tOperator.Chat_Page_Team = {Text = "<font size='24'>点击切换到<color=#F0DC82>队伍聊天频道</color></font>", Level = 1}
g_tTotur.tOperator.Chat_Page_Channel = {Text = "<font size='24'>可切换<color=#F0DC82>队伍或团队聊天</color></font>", Level = 1}
g_tTotur.tOperator.Home_Unlock = {Text = "<font size='24'>点击解锁<color=#F0DC82>地块</color></font>", Level = 1}
g_tTotur.tOperator.Home_Building = {Text = "<font size='24'>点击打开<color=#F0DC82>建造</color>界面</font>", Level = 1}
g_tTotur.tOperator.Home_Subarea = {Text = "<font size='24'>点击打开<color=#F0DC82>分区管理</color></font>", Level = 1}
g_tTotur.tOperator.Home_Spading = {Text = "<font size='24'>点击确认<color=#F0DC82>铲平地块</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_YouMingZhi = {Text = "<font size='24'>点击《幽冥指》招式要诀·一重</font>", Level = 1}
g_tTotur.tOperator.CLICK_YouMingZhi_ShiYong = {Text = "<font size='24'>使用《幽冥指》招式要诀·一重</font>", Level = 1}
g_tTotur.tOperator.CLICK_YouMingZhi_XueXi = {Text = "<font size='24'>学习《幽冥指》招式要诀·一重</font>", Level = 1}
g_tTotur.tOperator.Home_BuildingList = {Text = "<font size='24'>点击打开<color=#F0DC82>建造</color>选项</font>", Level = 1}
g_tTotur.tOperator.Home_BuildingList_furniture = {Text = "<font size='24'>点击切换到<color=#F0DC82>家具</color>选项</font>", Level = 1}
g_tTotur.tOperator.Home_furniture_tongmuta = {Text = "<font size='24'>选中并摆放<color=#F0DC82>桐木榻</color></font>", Level = 1}
g_tTotur.tOperator.Home_furniture_done = {Text = "<font size='24'>确定位置，完成摆放</font>", Level = 1}
g_tTotur.tOperator.Home_furniture_save = {Text = "<font size='24'>点击<color=#F0DC82>保存</color>改动</font>", Level = 1}
g_tTotur.tOperator.Home_furniture_close = {Text = "<font size='24'>点击<color=#F0DC82>退出</color>建造</font>", Level = 1}
g_tTotur.tOperator.Swim_UnderWater = {Text = "<font size='26'><color=#F0DC82>镜头面向水下</color>游动可潜入水中</font>", Level = 1}
g_tTotur.tOperator.Swim_Float = {Text = "<font size='26'><color=#F0DC82>镜头面向水面</color>游动或点击跳跃<img src='UIAtlas2_MainCity_MainCitySkill1_img_skill_jump' width='60' height='60'/>可浮出水面</font>", Level = 1}
g_tTotur.tComment.CLICK_INTERACTIVE_furniture_1 = {Text = "<font size='24'>点击在床榻上小憩</font>", Level = 1}
g_tTotur.tOperator.Home_AcceptQuest = {Text = "<font size='26'>与私宅奉引<color=#F0DC82>何千千</color>交谈，开启<color=#F0DC82>私邸宅院引导</color></font>", Level = 1}
g_tTotur.tOperator.Home_SkinSwap = {Text = "<font size='24'>点击打开<color=#F0DC82>换肤</color>界面</font>", Level = 1}
g_tTotur.tOperator.Home_SkinSwap_visit = {Text = "<font size='24'>点击参观，体验<color=#F0DC82>换肤</color>效果</font>", Level = 1}
g_tTotur.tOperator.Home_Visit_Back = {Text = "<font size='26'>参观完毕后与<color=#F0DC82>家园车夫</color>交谈，可返回私邸</font>", Level = 1}
g_tTotur.tMove.AutoRun = {Text = "<font size='24'>点击开启<color=#F0DC82>自动寻路</color></font>", Level = 1}
g_tTotur.tOperator.Home_UpGrade = {Text = "<font size='24'>点击打开<color=#F0DC82>宅邸升级</color></font>", Level = 1}
g_tTotur.tOperator.Home_BuildingList_collect = {Text = "<font size='24'>点击切换到<color=#F0DC82>收藏</color>选项</font>", Level = 1}
g_tTotur.tOperator.Home_collect_budiaoming = {Text = "<font size='24'>选中并摆放<color=#F0DC82>不钓名</color></font>", Level = 1}
g_tTotur.tOperator.Home_collect_furniture = {Text = "<font size='24'>点击切换到<color=#F0DC82>居家</color>页面</font>", Level = 1}
g_tTotur.tComment.CLICK_INTERACTIVE_furniture_2 = {Text = "<font size='24'>点击打开<color=#F0DC82>鱼池</color>管理</font>", Level = 1}
g_tTotur.tComment.Home_Interactive_AddFish = {Text = "<font size='24'>点击添加<color=#F0DC82>鱼苗</color></font>", Level = 1}
g_tTotur.tComment.Home_Interactive_ChooseFish = {Text = "<font size='24'>点击选择一种<color=#F0DC82>鱼苗</color></font>", Level = 1}
g_tTotur.tOperator.Home_collect_plant = {Text = "<font size='24'>点击切换到<color=#F0DC82>种植</color>页面</font>", Level = 1}
g_tTotur.tComment.Home_collect_huagang = {Text = "<font size='24'>选中并摆放<color=#F0DC82>粗陶花缸</color></font>", Level = 1}
g_tTotur.tComment.CLICK_INTERACTIVE_furniture_3 = {Text = "<font size='24'>点击打开<color=#F0DC82>种植</color>管理</font>", Level = 1}
g_tTotur.tComment.Home_Interactive_AddSeed = {Text = "<font size='24'>点击添加<color=#F0DC82>种子</color>(必选)</font>", Level = 1}
g_tTotur.tComment.Home_Interactive_ChooseSeed = {Text = "<font size='24'>点击选择<color=#F0DC82>种子</color></font>", Level = 1}
g_tTotur.tComment.Home_Interactive_AddSoil = {Text = "<font size='24'>点击添加<color=#F0DC82>土壤</color>(必选)</font>", Level = 1}
g_tTotur.tComment.Home_Interactive_ChooseSoil = {Text = "<font size='24'>点击选择<color=#F0DC82>土壤</color></font>", Level = 1}
g_tTotur.tComment.Home_collect_pet = {Text = "<font size='24'>点击切换到<color=#F0DC82>宠物窝</color>页面</font>", Level = 1}
g_tTotur.tComment.Home_collect_ChongZuo = {Text = "<font size='24'>选中并摆放<color=#F0DC82>葵草宠座</color></font>", Level = 1}
g_tTotur.tComment.CLICK_INTERACTIVE_furniture_4 = {Text = "<font size='24'>点击打开<color=#F0DC82>宠物窝</color>管理</font>", Level = 1}
g_tTotur.tComment.Home_Interactive_AddPet = {Text = "<font size='24'>点击添加<color=#F0DC82>宠物</color></font>", Level = 1}
g_tTotur.tComment.Home_Interactive_ChoosePet = {Text = "<font size='24'>点击选择<color=#F0DC82>宠物</color></font>", Level = 1}
g_tTotur.tComment.Home_Interactive_AddFeed = {Text = "<font size='24'>点击添加<color=#F0DC82>饲料</color>(必选)</font>", Level = 1}
g_tTotur.tComment.Home_Interactive_ChooseFeed = {Text = "<font size='24'>点击选择<color=#F0DC82>饲料</color></font>", Level = 1}
g_tTotur.tComment.Home_TalkToCheFu = {Text = "<font size='24'>点击与<color=#F0DC82>车夫</color>交谈</font>", Level = 1}
g_tTotur.tComment.Home_Get_Pet = {Text = "<font size='26'>与<color=#F0DC82>何千千</color>交谈，获取宠物</font>", Level = 1}
g_tTotur.tOperator.CLICK_ItemXX_chongwu1 = {Text = "<font size='24'>点击选中<color=#F0DC82>宠物·香香</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_ItemXX_chongwu2 = {Text = "<font size='24'>点击<color=#F0DC82>使用</color>获取宠物·香香</font>", Level = 1}
g_tTotur.tFight.Skill_Teach_Btn1 = {Text = "<font size='26'>使用<color=#F0DC82>傍身招式</color>，进入战斗</font>", Level = 1}
g_tTotur.tFight.Skill_Teach9_Btn2 = {Text = "<font size='24'>使用<color=#F0DC82>对阵招式</color>，提高伤害</font>", Level = 1}
g_tTotur.tFight.Skill_Teach9_Btn3 = {Text = "<font size='26'>使用<color=#F0DC82>对阵招式</color>，输出伤害</font>", Level = 1}
g_tTotur.tOperator.Home_Overview_huoyuedu = {Text = "<font size='24'>完成家园活动可以增加<color=#F0DC82>活跃度</color></font>", Level = 1}
g_tTotur.tOperator.Home_Overview_ = {Text = "<font size='24'>家园各项<color=#F0DC82>积分</color>和<color=#F0DC82>货币</color>总览</font>", Level = 1}
g_tTotur.tOperator.Home_Overview_huodong = {Text = "<font size='24'>可参与的<color=#F0DC82>家园活动</color></font>", Level = 1}
g_tTotur.tOperator.Trading_fenlei = {Text = "<font size='24'>交易行<color=#F0DC82>商品分类</color></font>", Level = 1}
g_tTotur.tOperator.Trading_shangpin = {Text = "<font size='24'>当前分类<color=#F0DC82>所有商品</color></font>", Level = 1}
g_tTotur.tOperator.Trading_fenye = {Text = "<font size='24'>交易种类分页</font>", Level = 1}
g_tTotur.tOperator.Trading_jishou = {Text = "<font size='24'><color=#F0DC82>寄售</color>和<color=#F0DC82>寄售</color>物品入口</font>", Level = 1}
g_tTotur.tOperator.Trading_chaxun = {Text = "<font size='24'><color=#F0DC82>查询</color>物品入口</font>", Level = 1}
g_tTotur.tSkill.KungFu_Skill_1 = {Text = "<font size='24'>点击查看<color=#F0DC82>技能详情</color></font>", Level = 1}
g_tTotur.tSkill.KungFu_SkillTips = {Text = "<font size='24'>点击进入<color=#F0DC82>秘籍选择</color></font>", Level = 1}
g_tTotur.tSkill.KungFu_MiJi_select = {Text = "<font size='24'><color=#F0DC82>选择并装备</color>一本秘籍</font>", Level = 1}
g_tTotur.tSkill.Menu_Click_Skill = {Text = "<font size='24'>点击打开<color=#F0DC82>武学</color>界面</font>", Level = 1}
g_tTotur.tOperator.KungFu_Close = {Text = "<font size='24'><color=#F0DC82>配置完成</color>后关闭武学界面</font>", Level = 1}
g_tTotur.tOperator.Fish_ShopWarn = {Text = "<font size='24'>可在商店<color=#F0DC82>购买</color>鱼饵</font>", Level = 1}
g_tTotur.tMap.WorldMap_Scala_M = {Text = "<font size='24'>双指捏合或张开可<color=#F0DC82>缩放地图</color>大小</font>", Level = 1}
g_tTotur.tFight.Skill_Teach8_Btn2 = {Text = "<font size='24'>使用<color=#F0DC82>对阵招式</color>，输出伤害</font>", Level = 1}
g_tTotur.tFight.Skill_Teach8_Btn3 = {Text = "<font size='24'>使用<color=#F0DC82>对阵招式</color>，输出伤害</font>", Level = 1}
g_tTotur.tFight.Skill_TeachMJ_Btn2 = {Text = "<font size='24'>使用<color=#F0DC82>对阵招式</color>，积攒能量</font>", Level = 1}
g_tTotur.tFight.Skill_TeachMJ_Btn3 = {Text = "<font size='24'>使用<color=#F0DC82>对阵招式</color>，积攒能量</font>", Level = 1}
g_tTotur.tFight.Skill_TeachMJ_Btn1 = {Text = "<font size='24'>使用<color=#F0DC82>傍身招式</color>，释放能量</font>", Level = 1}
g_tTotur.tOperator.Home_CatchFish = {Text = "<font size='26'>等待鱼苗长大，从<color=#F0DC82>鱼池</color>中打捞鱼获</font>", Level = 1}
g_tTotur.tOperator.Home_Pet_bag = {Text = "<font size='26'>在背包中找到<color=#F0DC82>宠物：香香</color>并使用</font>", Level = 1}
g_tTotur.tQuest.Quest_QuickUse = {Text = "<font size='24'>点击此处可<color=#F0DC82>快捷使用</color>任务道具</font>", Level = 1}
g_tTotur.tMap.MiddleMap_WorldMap_Btn = {Text = "<font size='24'>此处可查看<color=#F0DC82>世界地图</color></font>", Level = 1}
g_tTotur.tMap.MiddleMap_CaijiBiaoji_Btn = {Text = "<font size='24'>此处可设置<color=#F0DC82>采集标识</color>开关</font>", Level = 1}
g_tTotur.tShop.Shop_SellPage = {Text = "<font size='24'>点击切换到<color=#F0DC82>出售</color>页面</font>", Level = 1}
g_tTotur.tShop.Shop_Sell_Select = {Text = "<font size='24'>选中要<color=#F0DC82>出售</color>要物品</font>", Level = 1}
g_tTotur.tShop.Shop_Sell = {Text = "<font size='24'>点击完成物品<color=#F0DC82>出售</color></font>", Level = 1}
g_tTotur.tFight.Enter_Battle = {Text = "<font size='24'><color=#F0DC82>战斗状态</color>标记</font>", Level = 1}
g_tTotur.tOperator.Team_Search = {Text = "<font size='24'>此处可<color=#F0DC82>搜索</color>或<color=#F0DC82>筛选</color>目标队伍</font>", Level = 1}
g_tTotur.tOperator.Team_Release = {Text = "", Level = 0}
g_tTotur.tOperator.Teach_Tips_1_3 = {Text = "<font size='22'><color=#C0C0C0>点击任意区域继续(1/3)</color></font>", Level = 1}
g_tTotur.tOperator.Teach_Tips_2_3 = {Text = "<font size='22'><color=#C0C0C0>点击任意区域继续(2/3)</color></font>", Level = 1}
g_tTotur.tOperator.Teach_Tips_3_3 = {Text = "<font size='22'><color=#C0C0C0>点击任意区域继续(3/3)</color></font>", Level = 1}
g_tTotur.tOperator.Teach_Tips_1_1 = {Text = "<font size='22'><color=#C0C0C0>点击任意区域继续</color></font>", Level = 1}
g_tTotur.tOperator.Teach_Tips_1_4 = {Text = "<font size='22'><color=#C0C0C0>点击任意区域继续(1/4)</color></font>", Level = 1}
g_tTotur.tOperator.Teach_Tips_2_4 = {Text = "<font size='22'><color=#C0C0C0>点击任意区域继续(2/4)</color></font>", Level = 1}
g_tTotur.tOperator.Teach_Tips_3_4 = {Text = "<font size='22'><color=#C0C0C0>点击任意区域继续(3/4)</color></font>", Level = 1}
g_tTotur.tOperator.Teach_Tips_4_4 = {Text = "<font size='22'><color=#C0C0C0>点击任意区域继续(4/4)</color></font>", Level = 1}
g_tTotur.tOperator.Teach_Tips_1_2 = {Text = "<font size='22'><color=#C0C0C0>点击任意区域继续(1/2)</color></font>", Level = 1}
g_tTotur.tOperator.Teach_Tips_2_2 = {Text = "<font size='22'><color=#C0C0C0>点击任意区域继续(2/2)</color></font>", Level = 1}
g_tTotur.tSkill.KungFu_Select_QiXue = {Text = "<font size='24'>查看并装备<color=#F0DC82>奇穴</color></font>", Level = 1}
g_tTotur.tMap.WorldMap_Scala_VK = {Text = "<font size='24'>滑动滚轮可<color=#F0DC82>缩放地图</color>大小</font>", Level = 1}
g_tTotur.tMap.MiddleMap_MenPai_Transport = {Text = "<font size='24'>乘坐<color=#F0DC82>场景交通</color>前往此处</font>", Level = 1}
g_tTotur.tFight.Attack_CastSkill_2 = {Text = "<font size='24'>点击释放<color=#F0DC82>对阵招式</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_ItemDX_MaPi1 = {Text = "<font size='24'>点击选中<color=#F0DC82>马匹·点星</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_ItemDX_MaPi2 = {Text = "<font size='24'>点击<color=#F0DC82>装备</color>获取马匹</font>", Level = 1}
g_tTotur.tOperator.CLICK_ItemShuJi1 = {Text = "<font size='24'>点击选中<color=#F0DC82>书籍</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_ItemShuJi2 = {Text = "<font size='24'>点击<color=#F0DC82>阅读</color>书籍</font>", Level = 1}
g_tTotur.tOperator.QuickOperation = {Text = "<font size='24'>打开<color=#F0DC82>快捷操作</color>面板</font>", Level = 1}
g_tTotur.tSkill.QuickOperation_wangling_FSWT = {Text = "<font size='24'>点击<color=#F0DC82>搭建个人营地</color></font>", Level = 1}
g_tTotur.tOperator.SandTable_TradeRoute = {Text = "<font size='24'>此处展示推荐的<color=#F0DC82>跑商路线</color></font>", Level = 1}
g_tTotur.tOperator.TEAM_Settings = {Text = "<font size='24'>队伍常用<color=#F0DC82>设置</color></font>", Level = 1}
g_tTotur.tOperator.TEAM_Voice = {Text = "<font size='24'><color=#F0DC82>麦克风</color>设置</font>", Level = 1}
g_tTotur.tComment.CLICK_pet_Select = {Text = "<font size='24'>选择一个<color=#F0DC82>宠物</color></font>", Level = 1}
g_tTotur.tOperator.Revive_luyingdian = {Text = "<font size='24'>有<color=#F0DC82>露营点</color>时，可以选择<color=#F0DC82>露营点疗伤</color></font>", Level = 1}
g_tTotur.tOperator.CPanle_Teach_1 = {Text = "<font size='24'>此处可以设置<color=#F0DC82>屏蔽</color>选项</font>", Level = 1}
g_tTotur.tOperator.CLICK_BagItem = {Text = "<font size='24'>点击选中<color=#F0DC82>目标道具</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_BagItem_use = {Text = "<font size='24'>点击<color=#F0DC82>使用</color>该道具</font>", Level = 1}
g_tTotur.tOperator.Home_ClickBluePMP = {Text = "<font size='24'>点击打开<color=#F0DC82>蓝图面板</color></font>", Level = 1}
g_tTotur.tOperator.Home_BulePMP_Choose1 = {Text = "<font size='24'>点击<color=#F0DC82>目标设计图</color></font>", Level = 1}
g_tTotur.tOperato.Home_Interactive_harvest = {Text = "<font size='24'>收获<color=#F0DC82>种植物</color></font>", Level = 1}
g_tTotur.tMove.Home_FollowGuide_bed = {Text = "<font size='26'>前往目标家具<color=#F0DC82>单人床</color>附近进行互动</font>", Level = 1}
g_tTotur.tMove.Home_FollowGuide_foundation = {Text = "<font size='26'>进入家园地基范围内开始<color=#F0DC82>建造</color></font>", Level = 1}
g_tTotur.tMove.Home_FollowGuide_flowerpot = {Text = "<font size='26'>前往目标家具<color=#F0DC82>粗陶花盆</color>附近进行互动</font>", Level = 1}
g_tTotur.tOperator.Home_Open_Order = {Text = "<font size='24'>点击打开<color=#F0DC82>订单</color>面板</font>", Level = 1}
g_tTotur.tOperator.Home_Open_Overview = {Text = "<font size='24'>点击打开<color=#F0DC82>总览</color>面板</font>", Level = 1}
g_tTotur.tOperator.CLICK_INTERACTIVE_cookingbench = {Text = "<font size='24'>点击打开<color=#F0DC82>炊事</color>管理</font>", Level = 1}
g_tTotur.tComment.Home_Interactive_AddWater = {Text = "<font size='24'>煮制热水需要消耗<color=#F0DC82>泉水</color></font>", Level = 1}
g_tTotur.tComment.Home_Interactive_cooking = {Text = "<font size='24'>点击开始煮制<color=#F0DC82>热水</color></font>", Level = 1}
g_tTotur.tComment.CLICK_INTERACTIVE_XuYuan = {Text = "<font size='24'>点击开始许愿</font>", Level = 1}
g_tTotur.tShop.Shop_Select_Lasso = {Text = "<font size='24'>点击选中<color=#F0DC82>套马索</color></font>", Level = 1}
g_tTotur.tShop.Shop_Buy_Lasso = {Text = "<font size='24'>点击购买<color=#F0DC82>套马索</color></font>", Level = 1}
g_tTotur.tOperator.Teach_Tips_1_5 = {Text = "<font size='22'><color=#C0C0C0>点击任意区域继续(1/5)</color></font>", Level = 1}
g_tTotur.tOperator.Teach_Tips_2_5 = {Text = "<font size='22'><color=#C0C0C0>点击任意区域继续(2/5)</color></font>", Level = 1}
g_tTotur.tOperator.Teach_Tips_3_5 = {Text = "<font size='22'><color=#C0C0C0>点击任意区域继续(3/5)</color></font>", Level = 1}
g_tTotur.tOperator.Teach_Tips_4_5 = {Text = "<font size='22'><color=#C0C0C0>点击任意区域继续(4/5)</color></font>", Level = 1}
g_tTotur.tOperator.Teach_Tips_5_5 = {Text = "<font size='22'><color=#C0C0C0>点击任意区域继续(5/5)</color></font>", Level = 1}
g_tTotur.tOperator.Home_Orderlist = {Text = "<font size='24'>此处可查看<color=#F0DC82>家园订单</color>类型</font>", Level = 1}
g_tTotur.tOperator.Home_Order_goods = {Text = "<font size='24'>当前订单所需商品，\n<color=#F0DC82>身份等级</color>提升可解锁更多商品</font>", Level = 1}
g_tTotur.tOperator.Home_Order_RefreshAndhelp = {Text = "<font size='24'><color=#F0DC82>刷新</color>订单和<color=#F0DC82>请求</color>协助</font>", Level = 1}
g_tTotur.tOperator.Home_Order_price = {Text = "<font size='24'>明日订单<color=#F0DC82>行情预测</color></font>", Level = 1}
g_tTotur.tOperator.Home_Order_times = {Text = "<font size='24'>可发布<color=#F0DC82>协助</color>次数和<color=#F0DC82>刷新</color>订单次数</font>", Level = 1}
g_tTotur.tOperator.Home_furniture_DoubleBed = {Text = "<font size='24'>点击切换到<color=#F0DC82>双人床</color>页面</font>", Level = 1}
g_tTotur.tOperator.Home_furniture_HYM = {Text = "<font size='24'>点击<color=#F0DC82>查看</color>黄杨木坐床</font>", Level = 1}
g_tTotur.tOperator.Home_furniture_BuyHYM = {Text = "<font size='24'>点击<color=#F0DC82>购买</color>黄杨木坐床</font>", Level = 1}
g_tTotur.tOperator.Home_FollowGuide_pet = {Text = "<font size='26'>前往目标家具<color=#F0DC82>宠物窝</color>附近进行互动</font>", Level = 1}
g_tTotur.tOperator.Home_Interactive_hotWater = {Text = "<font size='24'>点击选择<color=#F0DC82>热水</color></font>", Level = 1}
g_tTotur.tOperator.Home_Overview_Flowerpage = {Text = "<font size='24'>点击查看可<color=#F0DC82>前往</color>目标点</font>", Level = 1}
g_tTotur.tOperator.Home_Overview_Flower = {Text = "<font size='24'>点击前往<color=#F0DC82>目标点</color></font>", Level = 1}
g_tTotur.tOperator.Home_Order_sell = {Text = "<font size='24'>上交收获的种植物，\n完成一个<color=#F0DC82>订单</color></font>", Level = 1}
g_tTotur.tOperator.Tong_FenLei = {Text = "<font size='24'>可在此处切换<color=#F0DC82>帮会列表</color></font>", Level = 1}
g_tTotur.tOperator.Tong_LieBiao = {Text = "<font size='24'>可在列表中选择帮会<color=#F0DC82>申请入帮</color></font>", Level = 1}
g_tTotur.tOperator.Tong_SouSuo = {Text = "<font size='24'>可搜索并申请加入<color=#F0DC82>帮会</color></font>", Level = 1}
g_tTotur.tOperator.Tong_ChuanJian = {Text = "<font size='24'>快速追踪<color=#F0DC82>帮会登记人</color></font>", Level = 1}
g_tTotur.tComment.CLICK_Home = {Text = "<font size='24'>点击查看<color=#F0DC82>家园</color></font>", Level = 1}
g_tTotur.tComment.CLICK_Tong = {Text = "<font size='24'>点击查看<color=#F0DC82>帮会</color></font>", Level = 1}
g_tTotur.tComment.CLICK_Buy_PriviteHome = {Text = "<font size='24'>点击购买可获得<color=#F0DC82>私邸宅园</color></font>", Level = 1}
g_tTotur.tComment.CLICK_DaXiaZhiLu = {Text = "<font size='24'>点击开启<color=#F0DC82>大侠之路</color></font>", Level = 1}
g_tTotur.tComment.CLICK_ShiJianZhanChang = {Text = "<font size='24'>点击进入<color=#F0DC82>试剑战场</color></font>", Level = 1}
g_tTotur.tComment.CLICK_Apprentice = {Text = "<font size='24'>点击查看<color=#F0DC82>师徒</color></font>", Level = 1}
g_tTotur.tComment.CLICK_Apprentice_teach = {Text = "<font size='24'>点击选择<color=#F0DC82>我要拜师</color></font>", Level = 1}
g_tTotur.tComment.CLICK_Apprentice_send = {Text = "<font size='24'>点击开始编辑<color=#F0DC82>拜师信息</color></font>", Level = 1}
g_tTotur.tComment.CLICK_Apprentice_ok = {Text = "<font size='24'>编辑完成后点击<color=#F0DC82>确认</color>发布<color=#F0DC82>拜师信息</color></font>", Level = 1}
g_tTotur.tComment.CLICK_FengYunLu = {Text = "<font size='24'>点击查看<color=#F0DC82>风云录</color></font>", Level = 1}
g_tTotur.tComment.FengYunLu_lieBiao = {Text = "<font size='24'>可在列表中选择<color=#F0DC82>切换</color>排行分类</font>", Level = 1}
g_tTotur.tComment.FengYunLu_fanye = {Text = "<font size='24'>此处可翻页查看</font>", Level = 1}
g_tTotur.tComment.CLICK_Mail = {Text = "<font size='24'>点击查看<color=#F0DC82>邮件</color></font>", Level = 1}
g_tTotur.tComment.CLICK_ChengHao = {Text = "<font size='24'>点击查看<color=#F0DC82>称号</color></font>", Level = 1}
g_tTotur.tComment.ChengHao_All = {Text = "<font size='24'>展示当前分类下<color=#F0DC82>全部</color>称号\n高亮的为<color=#F0DC82>已获得</color>的称号</font>", Level = 1}
g_tTotur.tComment.ChengHao_ShaiXuan = {Text = "<font size='24'>此处可<color=#F0DC82>搜索</color>或<color=#F0DC82>筛选</color>指定称号</font>", Level = 1}
g_tTotur.tComment.ChengHao_FenLei = {Text = "<font size='24'>可切换显示<color=#F0DC82>不同分类</color>下的称号</font>", Level = 1}
g_tTotur.tComment.CLICK_Horse = {Text = "<font size='24'>点击查看<color=#F0DC82>坐骑</color></font>", Level = 1}
g_tTotur.tComment.Horse_LieBiao = {Text = "<font size='24'>所有<color=#F0DC82>已获得</color>坐骑</font>", Level = 1}
g_tTotur.tComment.Horse_MaJu = {Text = "<font size='24'>装备马具可<color=#F0DC82>提升</color>马匹移动速度</font>", Level = 1}
g_tTotur.tComment.Horse_FenLei = {Text = "<font size='24'>可切换显示奇趣坐骑</font>", Level = 1}
g_tTotur.tSkill.CastSkill_Dazuo = {Text = "<font size='24'>打坐可快速恢复\n<color=#F0DC82>气血值</color>与<color=#F0DC82>气力值</color></font>", Level = 1}
g_tTotur.tComment.CLICK_Hero = {Text = "<font size='24'>点击查看<color=#F0DC82>江湖侠客</color></font>", Level = 1}
g_tTotur.tComment.CLICK_WorldMap_Search = {Text = "<font size='24'>可快速<color=#F0DC82>搜索</color>目标场景</font>", Level = 1}
g_tTotur.tComment.CLICK_WareHose_BagUpgrade = {Text = "<font size='24'>点击此处可<color=#F0DC82>扩展仓库</color>栏位</font>", Level = 1}
g_tTotur.tOperator.CPanle_Teach_2 = {Text = "<font size='24'>设置个人<color=#F0DC82>名片形象</color></font>", Level = 1}
g_tTotur.tOperator.CPanle_Teach_3 = {Text = "<font size='24'>查看所有<color=#F0DC82>挂饰</color></font>", Level = 1}
g_tTotur.tComment.Open_Character = {Text = "<font size='24'>点击查看<color=#F0DC82>角色</color></font>", Level = 1}
g_tTotur.tComment.Mail_liebiao = {Text = "<font size='24'>注意分辨<color=#F0DC82>官方</color>和<color=#F0DC82>私人</color>邮件</font>", Level = 1}
g_tTotur.tComment.CLICK_Item_TaoMasuo = {Text = "<font size='24'>使用该道具学会<color=#F0DC82>套马</color>技能</font>", Level = 1}
g_tTotur.tComment.CLICK_Item_WXS1 = {Text = "<font size='24'>点击选择<color=#F0DC82>五行石</color></font>", Level = 1}
g_tTotur.tComment.CLICK_Item_WXS2 = {Text = "<font size='24'>使用五行石进行<color=#F0DC82>装备强化</color></font>", Level = 1}
g_tTotur.tComment.CLICK_PowerUp_Equip1 = {Text = "<font size='24'>选择一个<color=#F0DC82>装备栏位</color></font>", Level = 1}
g_tTotur.tComment.CLICK_PowerUp_AutoPlacement = {Text = "<font size='24'>快速填充用于精炼的<color=#F0DC82>五行石</color></font>", Level = 1}
g_tTotur.tComment.CLICK_PowerUp_btnRefine = {Text = "<font size='24'><color=#F0DC82>消耗</color>五行石提升<color=#F0DC82>精炼等级</color></font>", Level = 1}
g_tTotur.tComment.CLICK_PowerUp_FusionInsert = {Text = "<font size='24'>选择<color=#F0DC82>装备栏熔嵌</color>页面</font>", Level = 1}
g_tTotur.tComment.CLICK_PowerUp_FusionInsert_WXS1 = {Text = "<font size='24'>可<color=#F0DC82>熔嵌</color>新的或<color=#F0DC82>更换\n</color>已熔嵌的五行石</font>", Level = 1}
g_tTotur.tComment.ChengHao_ChenHao1 = {Text = "<font size='24'>点击选择一个<color=#F0DC82>称号</color></font>", Level = 1}
g_tTotur.tComment.ChengHao_YingYongChengHao = {Text = "<font size='24'>点击应用称号<color=#F0DC82>装备</color>选中的称号</font>", Level = 1}
g_tTotur.tComment.ChengHao_Close = {Text = "<font size='24'>应用完毕后退出称号面板</font>", Level = 1}
g_tTotur.tComment.Enter_Battle_LockTargets = {Text = "<font size='24'>点击可<color=#F0DC82>选中</color>或<color=#F0DC82>切换</color>目标\n点击<img src='UIAtlas2_Public_PublicButton_PublicButton1_Btn_suoOpen' width='40' height='40'/>可<color=#F0DC82>锁定</color>目标</font>", Level = 1}
g_tTotur.tComment.QuestPanle_track = {Text = "<font size='24'>点击可<color=#F0DC82>追踪</color>当前任务</font>", Level = 1}
g_tTotur.tComment.CLICK_BtnSwitch = {Text = "<font size='24'>点击可<color=#F0DC82>切换</color>菜单列表</font>", Level = 1}
g_tTotur.tComment.CLICK_BthCompass1 = {Text = "<font size='24'>点击<color=#F0DC82>罗盘</color>开始寻宝</font>", Level = 1}
g_tTotur.tComment.QuickOperation_Compass1 = {Text = "<font size='24'>可在<color=#F0DC82>快捷操作</color>中再次<color=#F0DC82>开启寻宝</color></font>", Level = 1}
g_tTotur.tComment.CLICK_GotoCompass = {Text = "<font size='24'>点击选择寻宝地点</font>", Level = 1}
g_tTotur.tComment.CLICK_ChooseLocation = {Text = "<font size='24'>选择任意寻宝区域</font>", Level = 1}
g_tTotur.tComment.QuickOperation_Compass2 = {Text = "<font size='24'>点击<color=#F0DC82>寻宝</color>可再次<color=#F0DC82>开启寻宝</color></font>", Level = 1}
g_tTotur.tComment.Tips_BthCompass = {Text = "<font size='26'>可跟随<color=#F0DC82>罗盘<img src='UIAtlas2_Public_PublicIcon_PublicIcon1_btn_xunbao' width='48' height='48'/>指引</color>前往目标点寻宝</font>", Level = 1}
g_tTotur.tComment.CLICK_BthCompass2 = {Text = "<font size='24'>点击<color=#F0DC82>罗盘</color>寻获宝物</font>", Level = 1}
g_tTotur.tComment.QuickOperation_DongZuo = {Text = "<font size='24'>查看<color=#F0DC82>挂件动作</color></font>", Level = 1}
g_tTotur.tComment.QuickOperation_guajiandongzuo = {Text = "<font size='24'>在此处配置使用<color=#F0DC82>挂件动作</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_ItemZF_MaPi1 = {Text = "<font size='24'>点击选中<color=#F0DC82>马匹·追风</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_ItemZF_MaPi2 = {Text = "<font size='24'>点击<color=#F0DC82>装备</color>获取马匹</font>", Level = 1}
g_tTotur.tOperator.CLICK_BAIZHANZHAOSHI = {Text = "<font size='24'>点击<color=#F0DC82>招式</color>打开百战武学界面</font>", Level = 1}
g_tTotur.tOperator.CLICK_TogDay_Refresh = {Text = "<font size='24'>不易完成的目标\n可以点击<color=#F0DC82>更换</color></font>", Level = 1}
g_tTotur.tOperator.Home_Overview_Activation = {Text = "<font size='24'>参与<color=#F0DC82>家园活动</color>可获得<color=#F0DC82>家园活跃度</color></font>", Level = 1}
g_tTotur.tComment.CLICK_Hero_ShenJianXin = {Text = "<font size='24'>点击查看侠客详情</font>", Level = 1}
g_tTotur.tComment.CLICK_Hero_QWXF = {Text = "<font size='24'>前往寻访<color=#F0DC82>结识</color>侠客<color=#F0DC82>沈剑心</color></font>", Level = 1}
g_tTotur.tComment.CLICK_Hero_ChaBing = {Text = "<font size='24'>点击<color=#F0DC82>领取每日一次</color>的<color=#F0DC82>上品茶饼\n</color>茶饼可用于<color=#F0DC82>翻阅</color>侠客传记</font>", Level = 1}
g_tTotur.tComment.CLICK_Hero_FanYue = {Text = "<font size='24'>消耗茶饼<color=#F0DC82>开始翻阅</color>侠客传记，\n有几率结识侠客。</font>", Level = 1}
g_tTotur.tComment.CLICK_Hero_Quest = {Text = "<font size='24'>前往完成<color=#F0DC82>侠缘任务</color>，结交侠客</font>", Level = 1}
g_tTotur.tComment.Main_QuickOperation = {Text = "<font size='24'>此处按钮可<color=#F0DC82>快捷操作侠客</color>\n（<img src='UIAtlas2_MainCity_MainCity1_icon_Switch' width='48' height='48'/>可调整快捷键预设）</font>", Level = 1}
g_tTotur.tComment.Main_QuickOperation_KaiZhan = {Text = "<font size='24'><img src='UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mxiake7' width='48' height='48'/>可操作侠客<color=#F0DC82>攻击目标</color></font>", Level = 1}
g_tTotur.tComment.Main_QuickOperation_GenSui = {Text = "<font size='24'><img src='UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mxiake4' width='48' height='48'/>可操作侠客<color=#F0DC82>跟随</color></font>", Level = 1}
g_tTotur.tComment.Main_QuickOperation_XiaKe = {Text = "<font size='24'><img src='UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mxiake' width='48' height='48'/>可<color=#F0DC82>召请/召回</color>侠客</font>", Level = 1}
g_tTotur.tComment.Home_Interactive_ChooseSeed_baihe = {Text = "<font size='24'>点击选择<color=#F0DC82>百合花种子·一级</color></font>", Level = 1}
g_tTotur.tComment.Home_AcceptQuest_HQQ = {Text = "<font size='24'>与何千千对话，开启<color=#F0DC82>私邸宅院引导</color></font>", Level = 1}
g_tTotur.tComment.TianCe_Horse = {Text = "<font size='24'>点击<color=#F0DC82>骑御</color>按钮即可骑上战马</font>", Level = 1}
g_tTotur.tComment.WaiZhuang_Open_BeiBao = {Text = "<font size='24'>获得<color=#F0DC82>宗门裳衣</color>，打开背包使用</font>", Level = 1}
g_tTotur.tOperator.CLICK_Item_ZMSY1 = {Text = "<font size='24'>点击选中<color=#F0DC82>宗门裳衣</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_Item_ZMSY2 = {Text = "<font size='24'>点击<color=#F0DC82>使用</color>获取宗门外装</font>", Level = 1}
g_tTotur.tOperator.PanleMain_settings_help = {Text = "<font size='24'>点击可获取使用<color=#F0DC82>指引</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_BHHJ_Setting = {Text = "<font size='24'>查看玩法内<color=#F0DC82>秘术技能</color>配置</font>", Level = 1}
g_tTotur.tOperator.CLICK_BHHJ_MiShu1 = {Text = "<font size='24'>点击查看秘术详情，空槽位时将自动装备，可<color=#F0DC82>卸下或丢弃</color>替换技能</font>", Level = 1}
g_tTotur.tOperator.CLICK_BHHJ_JiNeng = {Text = "<font size='24'>点击切换到<color=#F0DC82>技能配置</color>分页</font>", Level = 1}
g_tTotur.tOperator.CLICK_BHHJ_JiNeng1 = {Text = "<font size='24'>点击查看武学详情，空槽位时将自动装备，<color=#F0DC82>拖拽</color>换位置，可点击右上角<color=#F0DC82>丢弃</color>技能</font>", Level = 1}
g_tTotur.tOperator.ShareToChat = {Text = "<font size='24'>等待<color=#F0DC82>分享</color>的内容\n点击<color=#F0DC82>发送</color>按钮即可分享</font>", Level = 1}
g_tTotur.tOperator.CLICK_TogChangeMap = {Text = "<font size='24'>在阵营场景可切换\n<color=#F0DC82>主界面小地图</color>显示</font>", Level = 1}
g_tTotur.tOperator.LieXingDao_QuickBuyEuip = {Text = "<font size='24'>点击快速购买<color=#F0DC82>预设装备</color></font>", Level = 1}
g_tTotur.tOperator.LieXingDao_EuipShop = {Text = "<font size='24'>商店可以查看所有装备</font>", Level = 1}
g_tTotur.tOperator.LieXingDao_Skill = {Text = "<font size='24'>气血值低时可使用<color=#F0DC82>回城或恢复</color>技能</font>", Level = 1}
g_tTotur.tOperator.Tong_batte_tips = {Text = "<font size='24'>点击此处可<color=#F0DC82>查看</color>战场详情</font>", Level = 1}
g_tTotur.tOperator.KungFu_Presets = {Text = "<font size='24'><color=#F0DC82>查看或更改</color>武学分页预设</font>", Level = 1}
g_tTotur.tOperator.KungFu_Presets_bind = {Text = "<font size='24'><color=#F0DC82>查看或更改</color>武学分页绑定设置</font>", Level = 1}
g_tTotur.tComment.RunToLiTianXuan_Handle = {Text = "<font size='26'>前推摇杆向前移动，靠近<color=#F0DC82>李天玄</color></font>", Level = 1}
g_tTotur.tComment.WorldMap_Scala_Handle = {Text = "<font size='26'>按<img src='UIAtlas2_GameSetting_JoyStick_XBOX_1' width='35' height='35'/>切换到<color=#F0DC82>光标模式</color>，\n使用<color=#F0DC82>十字键</color><img src='UIAtlas2_GameSetting_JoyStick_XBOX_3' width='35' height='35'/>/<img src='UIAtlas2_GameSetting_JoyStick_XBOX_4' width='35' height='35'/>缩放地图</font>", Level = 1}
g_tTotur.tComment.Slider_Screen_TYFM_Second_handle = {Text = "<font size='24'>滑动右摇杆可<color=#F0DC82>调整镜头视角</color></font>", Level = 1}
g_tTotur.tFight.Skill_TeachDS_Btn2 = {Text = "<font size='24'>使用<color=#F0DC82>对阵招式</color>，输出伤害</font>", Level = 1}
g_tTotur.tFight.Skill_TeachDS_Btn3 = {Text = "<font size='24'>使用<color=#F0DC82>对阵招式</color>，输出伤害</font>", Level = 1}
g_tTotur.tComment.CLICK_STORY = {Text = "<font size='24'>点击打开<color=#F0DC82>剑侠录</color></font>", Level = 1}
g_tTotur.tComment.CLICK_Story_SLFY = {Text = "<font size='24'>开启</font><font size='28'><color=#F0DC82>丝路风语</color></font><font size='24'>章节故事</font>", Level = 1}
g_tTotur.tMap.MiddleMap_CaijiBiaoji_Btn1 = {Text = "<font size='24'>中小地图采集物显示开关</font>", Level = 1}
g_tTotur.tCollect.Collect_QSMY_FeiMingJu = {Text = "<font size='24'>点击<color=#F0DC82>非命居</color>进行<color=#F0DC82>升级</color></font>", Level = 1}
g_tTotur.tCollect.Collect_QSMY_JieYongGe = {Text = "<font size='24'>点击<color=#F0DC82>节用阁</color>进行<color=#F0DC82>升级</color></font>", Level = 1}
g_tTotur.tCollect.Collect_QSMY_BianDui = {Text = "<font size='24'>可将<color=#F0DC82>选中</color>的木偶<color=#F0DC82>加入</color>编队</font>", Level = 1}
g_tTotur.tCollect.Collect_QSMY_QingChu = {Text = "<font size='24'>可将<color=#F0DC82>选中</color>的木偶<color=#F0DC82>清出</color>编队</font>", Level = 0}
g_tTotur.tCollect.Collect_QSMY_KaiShi = {Text = "<font size='24'>编队完成后可<color=#F0DC82>开启挑战</color>随机关卡</font>", Level = 1}
g_tTotur.tOperator.StrikeTheJar_Settins = {Text = "<font size='24'><color=#F0DC82>自动砸罐</color>相关设置</font>", Level = 1}
g_tTotur.tOperator.StrikeTheJar_Item = {Text = "<font size='24'><color=#F0DC82>提高砸罐积分</color>道具的详细设置</font>", Level = 1}
g_tTotur.tOperator.StrikeTheJar_Switch = {Text = "<font size='24'><color=#F0DC82>开始</color>/<color=#F0DC82>停止</color>自动砸罐的开关</font>", Level = 1}
g_tTotur.tOperator.StrikeTheJar_Points = {Text = "<font size='24'>砸罐的<color=#F0DC82>积分</color>情况</font>", Level = 1}
g_tTotur.tOperator.CLICK_Item_XiaoYinChui = {Text = "<font size='24'>点击选中物品<color=#F0DC82>小银锤</color></font>", Level = 1}
g_tTotur.tOperator.CLICK_Item_XiaoYinChu2 = {Text = "<font size='24'>点击<color=#F0DC82>自动砸罐</color>打开相关设置</font>", Level = 1}
g_tTotur.tOperator.CLICK_POP_WareHouse = {Text = "<font size='24'>点击查看已调制好的香膏</font>", Level = 1}
g_tTotur.tOperator.CLICK_FlowerOintment = {Text = "<font size='24'>点击打开<color=#F0DC82>识香匣</color>使用香膏</font>", Level = 1}
g_tTotur.tComment.View_FlowerOintment = {Text = "<font size='24'>点击此处查看<color=#F0DC82>已拥有的香露</color></font>", Level = 1}
g_tTotur.tComment.Add_FlowerOintment = {Text = "<font size='24'>点击选择<color=#F0DC82>已拥有的香露</color>并放入,\n放入<color=#F0DC82>三个</color>香露后，放入<color=#F0DC82>蜂蜡</color>。</font>", Level = 1}
g_tTotur.tComment.CLICK_STORY_LBTJG = {Text = "<font size='24'>点击切换到<color=#F0DC82>龙变太极宫</color>章节</font>", Level = 1}
g_tTotur.tComment.CLICK_Story_LBTJG_start = {Text = "<font size='24'>开启</font><font size='28'><color=#F0DC82>龙变太极宫</color></font><font size='24'>章节故事</font>", Level = 1}
g_tTotur.tComment.CLICK_QiYuanTai = {Text = "<font size='24'>点击打开<color=#F0DC82>祈愿台</color></font>", Level = 1}
g_tTotur.tComment.CLICK_QiYuanTai_Add = {Text = "<font size='24'>点击查看<color=#F0DC82>祈愿物品</color></font>", Level = 1}
g_tTotur.tComment.CLICK_XunBao_Cangku = {Text = "<font size='24'>可进入预设界面配置本局进场携带的<color=#F0DC82>装备</color>以及<color=#F0DC82>道具</color></font>", Level = 1}
g_tTotur.tComment.CLICK_XunBao_Hat = {Text = "<font size='24'>点击<color=#F0DC82>装备栏位</color>打开装备选择界面</font>", Level = 1}
g_tTotur.tComment.CLICK_XunBao_Hat_1 = {Text = "<font size='24'>选择一件装备</font>", Level = 1}
g_tTotur.tComment.CLICK_XunBao_Buy = {Text = "<font size='24'>点击<color=#F0DC82>购买并穿戴</color>完成装备预设</font>", Level = 1}
g_tTotur.tComment.CLICK_XunBao_Weapon = {Text = "<font size='24'>点击<color=#F0DC82>武器栏位</color></font>", Level = 1}
g_tTotur.tComment.CLICK_XunBao_WeaponSkill = {Text = "<font size='24'>点击查看<color=#F0DC82>武器技能</color></font>", Level = 1}
g_tTotur.tComment.View_XunBao_WeaponSkill = {Text = "<font size='24'>武器技能列表里可查看\n<color=#F0DC82>武器的对应技能</color></font>", Level = 1}
g_tTotur.tComment.CLICK_XunBao_Shop = {Text = "<font size='24'>点击打开<color=#F0DC82>商店</color>可购买对局中\n使用的装备和物资</font>", Level = 1}
g_tTotur.tComment.CLICK_PictureMove = {Text = "<font size='24'>拖动图片到正确位置</font>", Level = 1}
g_tTotur.tComment.CLICK_SJZ_btn = {Text = "<font size='24'>点击进入设计站</font>", Level = 1}
g_tTotur.tComment.CLICK_SJZ_Zuopin = {Text = "<font size='24'>点击查看设计作品</font>", Level = 1}
g_tTotur.tComment.CLICK_KuaiJieAnNiu = {Text = "<font size='24'>可在此处对作品进行\n<color=#F0DC82>收藏</color>、<color=#F0DC82>打赏</color>和<color=#F0DC82>分享</color></font>", Level = 1}
g_tTotur.tComment.CLICK_Menu_More = {Text = "<font size='24'>点击展开更多入口</font>", Level = 1}
g_tTotur.tComment.CLICK_Menu_More_dashang = {Text = "<font size='24'>点击查看创作者提现</font>", Level = 1}
g_tTotur.tComment.CLICK_STORY_SXYLC = {Text = "<font size='24'>点击切换到<color=#F0DC82>使行伊丽川</color>章节</font>", Level = 1}
g_tTotur.tComment.CLICK_Story_SXYLC_start = {Text = "<font size='24'>开启</font><font size='28'><color=#F0DC82>使行伊丽川</color></font><font size='24'>章节故事</font>", Level = 1}
g_tTotur.tComment.CLICK_JiangHuKuaiBao = {Text = "<font size='24'>点击开启<color=#F0DC82>花萼楼</color></font>", Level = 1}
g_tTotur.tComment.CLICK_JHKB_LFXC_JQ = {Text = "<font size='24'>点击探寻秘境剧情</font>", Level = 1}
g_tTotur.tComment.CLICK_STORY_XYPQJ = {Text = "<font size='24'>点击切换到<color=#F0DC82>侠影破千机</color>章节</font>", Level = 1}
g_tTotur.tComment.CLICK_STORY_XYPQJ_start = {Text = "<font size='24'>开启</font><font size='28'><color=#F0DC82>侠影破千机</color></font><font size='24'>章节故事</font>", Level = 1}
g_tTotur.tComment.CLICK_ShangCheng_ChuanDa = {Text = "<font size='24'>点击可切换窗口\n<color=#F0DC82>展开</color>/<color=#F0DC82>收起</color>状态</font>", Level = 1}
g_tTotur.tComment.CLICK_YuYin_GuanzhanLieBiao = {Text = "<font size='24'>此处展示所有可进入频道</font>", Level = 1}
g_tTotur.tComment.CLICK_YuYin_ZhiBo = {Text = "<font size='24'>点击选择直播分页</font>", Level = 1}
