---------------------------------------------------------------------->
-- 脚本名称:	scripts/MiniGame/DouDiZhu/for3players/IdentityCustomValueName.lua
-- 更新时间:	2021/5/31 17:09:10
-- 更新用户:	caoqing-PC
-- 脚本说明:	
----------------------------------------------------------------------<

--********************************************
--*******************斗地主*******************
--********************************************

DDZ_WRITE_LOG = false
DEBUG_DOUDIZHU = false  --TODO：上线时需要关闭
DDZ_AUTO_TEST = false --TODO：自动出牌逻辑，上线时需要关闭

-----------------------CARD CONST---------------------------
DDZ_CONST_PLAYER_MAX = 3 --最大玩家数
DDZ_CONST_CARDS_INHAND_MAX = 20 --最大手牌数
DDZ_CONST_CARDS_NUM = 54  --全牌数组长度
DDZ_CONST_CARDS_VALUE_SUM = 1641 --斗地主所有牌值编码加总值
DDZ_CONST_LAIZI_TYPE = 2 --修改斗地主赖子数量
DDZ_CONST_TAX_RATE = 0.9 --结算税率
DDZ_CONST_HOMELAND_RATE = 0.01 --主人结算加成
DDZ_CONST_MAX_TIMES = 1000000 --斗地主INT倍率保护
DDZ_CONST_SOUND_LEN = 67

DDZ_CONST_TABLE_CARDS_LAST = {4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 1, 1} --记牌器剩余牌数初始值
DDZ_CONST_BOTTOM_SCORE = {10, 20, 50} --斗地主的底分，配置项

DDZ_CONST_DATAS_REMOTE_ID = 1074 --斗地主角色远程数据
DDZ_CONST_YEZILING_LITTLE_ID = 35995 --原本叶子令的ID，5w上限，每个算一个

-----------------------CONST_TIMES---------------------------
--重要，如果要增加DDZ_CONST_TIMES枚举类型，需同步UI客户端一起添加，并修改DDZ_PUBLIC_DATA_BYTE_TABLE_SETTING_TYPE后的枚举
DDZ_CONST_TIMES_INITIAL_CARDS = 1 --斗地主初始番数(初始化用，默认为1)
DDZ_CONST_TIMES_BOTTOM_CARDS = DDZ_CONST_TIMES_INITIAL_CARDS + 1  --斗地主基础番数
DDZ_CONST_TIMES_BOTTOM_CARDS_LINE = DDZ_CONST_TIMES_BOTTOM_CARDS + 1 --底牌3顺番数，如底牌为 3 4 5
DDZ_CONST_TIMES_BOTTOM_CARDS_DOUBLE = DDZ_CONST_TIMES_BOTTOM_CARDS_LINE + 1 --底牌对子番数，如底牌为 3 3 4
DDZ_CONST_TIMES_BOTTOM_CARDS_TRIPLE = DDZ_CONST_TIMES_BOTTOM_CARDS_DOUBLE + 1 --底牌3连番数，如底牌为 3 3 3
DDZ_CONST_TIMES_BOTTOM_CARDS_ROCKET = DDZ_CONST_TIMES_BOTTOM_CARDS_TRIPLE + 1 --底牌王炸番数
DDZ_CONST_TIMES_BOTTOM_CARDS_SJOKER = DDZ_CONST_TIMES_BOTTOM_CARDS_ROCKET + 1 --底牌小王番数
DDZ_CONST_TIMES_BOTTOM_CARDS_BJOKER = DDZ_CONST_TIMES_BOTTOM_CARDS_SJOKER + 1 --底牌大王番数
DDZ_CONST_TIMES_BOTTOM_CARDS_FLUSH = DDZ_CONST_TIMES_BOTTOM_CARDS_BJOKER + 1 --底牌同花番数
DDZ_CONST_TIMES_MINGPAI_STATE_INIT = DDZ_CONST_TIMES_BOTTOM_CARDS_FLUSH + 1 --开始前明牌番数
DDZ_CONST_TIMES_MINGPAI_STATE_SHUFFLE = DDZ_CONST_TIMES_MINGPAI_STATE_INIT + 1 --发牌前段明牌番数
DDZ_CONST_TIMES_CHAIRMAN_CALL = DDZ_CONST_TIMES_MINGPAI_STATE_SHUFFLE + 1 --叫地主番数
DDZ_CONST_TIMES_CHAIRMAN_ROB = DDZ_CONST_TIMES_CHAIRMAN_CALL + 1 --抢地主番数
DDZ_CONST_TIMES_DOUBLE_TYPE_NORMAL = DDZ_CONST_TIMES_CHAIRMAN_ROB + 1 --普通加倍
DDZ_CONST_TIMES_DOUBLE_TYPE_SUPER = DDZ_CONST_TIMES_DOUBLE_TYPE_NORMAL + 1 --超级加倍
DDZ_CONST_TIMES_DOUBLE_BOMB_BIG = DDZ_CONST_TIMES_DOUBLE_TYPE_SUPER + 1 --硬炸弹，非癞子炸弹
DDZ_CONST_TIMES_DOUBLE_BOMB_LAIZI = DDZ_CONST_TIMES_DOUBLE_BOMB_BIG + 1 --赖子炸弹
DDZ_CONST_TIMES_DOUBLE_BOMB_ROCKET = DDZ_CONST_TIMES_DOUBLE_BOMB_LAIZI + 1 --王炸
DDZ_CONST_TIMES_ENDINNG_SPRING = DDZ_CONST_TIMES_DOUBLE_BOMB_ROCKET + 1 --春天  19个数据

DDZ_CONST_CAERDS_TIMES = {		--每次都是乘法关系，除了底番默认都是 >2 的整数
	[DDZ_CONST_TIMES_INITIAL_CARDS] = 1, --斗地主初始番数 
	[DDZ_CONST_TIMES_BOTTOM_CARDS] = 1, --斗地主基础番数(调整为1倍)
	[DDZ_CONST_TIMES_BOTTOM_CARDS_LINE] = 2, --底牌3顺番数
	[DDZ_CONST_TIMES_BOTTOM_CARDS_DOUBLE] = 2, --底牌对子番数
	[DDZ_CONST_TIMES_BOTTOM_CARDS_TRIPLE] = 3, --底牌3连番数
	[DDZ_CONST_TIMES_BOTTOM_CARDS_ROCKET] = 8,      --底牌王炸番数
	[DDZ_CONST_TIMES_BOTTOM_CARDS_SJOKER] = 2,      --底牌小王番数
	[DDZ_CONST_TIMES_BOTTOM_CARDS_BJOKER] = 3,      --底牌大王番数
	[DDZ_CONST_TIMES_BOTTOM_CARDS_FLUSH] = 2,      --底牌同花番数
	[DDZ_CONST_TIMES_MINGPAI_STATE_INIT] = 4,    --开始前明牌番数
	[DDZ_CONST_TIMES_MINGPAI_STATE_SHUFFLE] = 2, --发牌前段明牌番数
	[DDZ_CONST_TIMES_CHAIRMAN_CALL] = 2,         --叫地主番数
	[DDZ_CONST_TIMES_CHAIRMAN_ROB] = 2,          --抢地主番数
	[DDZ_CONST_TIMES_DOUBLE_TYPE_NORMAL] = 2,    --普通加倍
	[DDZ_CONST_TIMES_DOUBLE_TYPE_SUPER] = 4,      --超级加倍
	[DDZ_CONST_TIMES_DOUBLE_BOMB_BIG] = 2,      --硬炸弹，不带癞子的炸弹
	[DDZ_CONST_TIMES_DOUBLE_BOMB_LAIZI] = 2,      --赖子炸弹，每1星增加值
	[DDZ_CONST_TIMES_DOUBLE_BOMB_ROCKET] = 4,      --王炸
	[DDZ_CONST_TIMES_ENDINNG_SPRING] = 4      --春天，结束时玩家没有出牌
}

-----------------------PRIVATE DATA---------------------------
DDZ_PRIVATE_DATA_BOOL_NEED_SETTLE_ACCOUNTS = 0 --是否需要结算流水(需要的时候置为1，结算完置为0，防止重复调用结算)

DDZ_PRIVATE_DATA_BYTE_BOTTOMCARDS = 0 --底牌3张
DDZ_PRIVATE_DATA_BYTE_LAIZI = DDZ_PRIVATE_DATA_BYTE_BOTTOMCARDS + 3 --癞子牌2张 
DDZ_PRIVATE_DATA_BYTE_CARDS_PILE = DDZ_PRIVATE_DATA_BYTE_LAIZI + 2 --牌堆54，用于不洗牌模式中牌值的记录 
DDZ_PRIVATE_DATA_BYTE_PLAYER_OVERTIME_COUNT = DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 54 --三个玩家的超时次数（超过2次判定为挂机）--当前数据总量：62

-----------------------PLAYER DATA---------------------------
DDZ_PLAYER_DATA_BYTE_HANDCARDS = 0 --玩家手牌数组20张
DDZ_PLAYER_DATA_BYTE_CARDS_TIPS = DDZ_PLAYER_DATA_BYTE_HANDCARDS + 20  --玩家出牌的提示牌值
DDZ_PLAYER_DATA_BYTE_MINGPAI_STATE = DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 20  --玩家明牌时当前牌桌状态
DDZ_PLAYER_DATA_BYTE_CHAIRMAN_TYPE = DDZ_PLAYER_DATA_BYTE_MINGPAI_STATE + 1 --玩家本身的叫地主状态(初始状态0、叫地主1、抢地主2、地主3、抢地主4、不叫5)
DDZ_PLAYER_DATA_BYTE_CARDS_NUM = DDZ_PLAYER_DATA_BYTE_CHAIRMAN_TYPE + 1 --玩家剩余手牌数量（0-20） 
DDZ_PLAYER_DATA_BYTE_CARDS_FIRST = DDZ_PLAYER_DATA_BYTE_CARDS_NUM + 1 --玩家首次出牌张数，用来判定地主春天 
DDZ_PLAYER_DATA_BYTE_CAERDS_TIMES = DDZ_PLAYER_DATA_BYTE_CARDS_FIRST + 1 --玩家加倍状态
DDZ_PLAYER_DATA_BYTE_CHAIRMAN_COMPARE = DDZ_PLAYER_DATA_BYTE_CAERDS_TIMES + 1 --玩家底牌分数，用于判断地主归属（1个数据） 
DDZ_PLAYER_DATA_BYTE_ACHIEVEMENT_BOMB = DDZ_PLAYER_DATA_BYTE_CHAIRMAN_COMPARE + 1 --玩家成就数据，炸弹数量
DDZ_PLAYER_DATA_BYTE_ACHIEVEMENT_SPRING = DDZ_PLAYER_DATA_BYTE_ACHIEVEMENT_BOMB + 1 --玩家成就数据，春天轮次
DDZ_PLAYER_DATA_BYTE_ACHIEVEMENT_LAIZI_NUM = DDZ_PLAYER_DATA_BYTE_ACHIEVEMENT_SPRING + 1 --玩家成就数据，癞子数量 --当前数据总量：49

-----------------------PUBLIC DATA---------------------------
DDZ_PUBLIC_DATA_BOOL_PLAYER_IS_AGENT = 0 --玩家挂机托管 --当前数量3
DDZ_PUBLIC_DATA_BOOL_PLAYER_OPERATE_JUMP = DDZ_PUBLIC_DATA_BOOL_PLAYER_IS_AGENT + 3 --玩家跳过状态 
DDZ_PUBLIC_DATA_BOOL_PLAYER_DEBUG = DDZ_PUBLIC_DATA_BOOL_PLAYER_OPERATE_JUMP + 3 --当前数量7
DDZ_PUBLIC_DATA_BOOL_PLAYER_WINNER = DDZ_PUBLIC_DATA_BOOL_PLAYER_DEBUG + 1 --当前数量10

DDZ_PUBLIC_DATA_BYTE_LAIZI = 0 --癞子牌2张
DDZ_PUBLIC_DATA_BYTE_LAIZI_NUM = DDZ_PUBLIC_DATA_BYTE_LAIZI + 2  --癞子牌数量(1，没有癞子，2有1个癞子，3有2个癞子）
DDZ_PUBLIC_DATA_BYTE_SHUFFLE_TYPE = DDZ_PUBLIC_DATA_BYTE_LAIZI_NUM + 1 --是否洗牌（1洗牌，2不洗牌）
DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD = DDZ_PUBLIC_DATA_BYTE_SHUFFLE_TYPE + 1 --当前出牌20张
DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_PLAYER = DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 20 --当前轮到谁出牌
DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD_OWNER = DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_PLAYER + 1 --当前的牌是谁出的
DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD_TYPE = DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD_OWNER + 1 --当前的牌是什么牌型（3个byte，用于判断大小）
DDZ_PUBLIC_DATA_BYTE_CHAIRMAN = DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD_TYPE + 3 --地主,playerID，没人叫地主=4
DDZ_PUBLIC_DATA_BYTE_RESTART = DDZ_PUBLIC_DATA_BYTE_CHAIRMAN + 1 --重新开始
DDZ_PUBLIC_DATA_BYTE_TABLE_MGR_STATE = DDZ_PUBLIC_DATA_BYTE_RESTART + 1 --牌桌状态
DDZ_PUBLIC_DATA_BYTE_COUNT_DOWN_PLAYER_AND_TYPE = DDZ_PUBLIC_DATA_BYTE_TABLE_MGR_STATE + 1 --倒计时玩家及倒计时类型
DDZ_PUBLIC_DATA_BYTE_PLAYER_WINNER = DDZ_PUBLIC_DATA_BYTE_COUNT_DOWN_PLAYER_AND_TYPE + 1 --胜利玩家记录  
DDZ_PUBLIC_DATA_BYTE_BOTTOMCARDS = DDZ_PUBLIC_DATA_BYTE_PLAYER_WINNER + 1 --3张底牌公开数据 
DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 = DDZ_PUBLIC_DATA_BYTE_BOTTOMCARDS + 3 --第1个玩家手牌明牌之后的数据
DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 = DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 20 --第2个玩家手牌明牌之后的数据（一次性记录20张，逻辑好写）
DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 = DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 20 --第3个玩家手牌明牌之后的数据 
DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_NUM = DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 20 --3个玩家的剩余手牌数量（0-20） 
DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST = DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_NUM + 3 --记牌器功能15张牌（3-k-2 + 小王 + 大王） 
DDZ_PUBLIC_DATA_BYTE_CHAIRMAN_TYPE_PLAYER = DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 15 --同步玩家1-3叫地主状态(3个数据)--当前数量：119
DDZ_PUBLIC_DATA_BYTE_PLAYER_DOUBLE_TYPE = DDZ_PUBLIC_DATA_BYTE_CHAIRMAN_TYPE_PLAYER + 3 --同步玩家1-3的加倍状态(3个数据)--当前数量：122
DDZ_PUBLIC_DATA_BYTE_PLAYER_MINGPAI_STATE = DDZ_PUBLIC_DATA_BYTE_PLAYER_DOUBLE_TYPE + 3 --同步玩家1-3的明牌状态(3个数据)--当前数量：125
DDZ_PUBLIC_DATA_BYTE_TIMES_TABLE_STATE = DDZ_PUBLIC_DATA_BYTE_PLAYER_MINGPAI_STATE + 3 --同步玩家加倍的状态(19个数据)，与DDZ_CONST_CAERDS_TIMES的枚举相同，注意使用时枚举值-1
DDZ_PUBLIC_DATA_BYTE_TABLE_SETTING_TYPE = DDZ_PUBLIC_DATA_BYTE_TIMES_TABLE_STATE + 19 --同步牌桌设置状态类型 
DDZ_PUBLIC_DATA_BYTE_ENDINNG_SPRING = DDZ_PUBLIC_DATA_BYTE_TABLE_SETTING_TYPE + 1 --春天状态的playerIndex ----当前数量：146

DDZ_PUBLIC_DATA_INT_CASH_BASE = 0  --底分（麻将桌传入）
DDZ_PUBLIC_DATA_INT_COUNT_DOWN_TIME = DDZ_PUBLIC_DATA_INT_CASH_BASE + 1		--倒计时
DDZ_PUBLIC_DATA_INT_CAERDS_TIMES = DDZ_PUBLIC_DATA_INT_COUNT_DOWN_TIME + 1 --牌桌翻倍数
DDZ_PUBLIC_DATA_INT_PLAYER_CASH_ORIGIN = DDZ_PUBLIC_DATA_INT_CAERDS_TIMES + 1 --玩家原始欢乐豆（用来算本场输赢，记录战绩）
DDZ_PUBLIC_DATA_INT_PLAYER_CASH = DDZ_PUBLIC_DATA_INT_PLAYER_CASH_ORIGIN + 3 --玩家欢乐豆
DDZ_PUBLIC_DATA_INT_PLAYER_CASH_HONOR = DDZ_PUBLIC_DATA_INT_PLAYER_CASH + 3 --玩家雀神点数 
DDZ_PUBLIC_DATA_INT_CUR_CONTINUE_WIN = DDZ_PUBLIC_DATA_INT_PLAYER_CASH_HONOR + 3 --当前连胜记录 
DDZ_PUBLIC_DATA_INT_HISTORY_CONTINUE_WIN = DDZ_PUBLIC_DATA_INT_CUR_CONTINUE_WIN + 3 --历史连胜记录 
DDZ_PUBLIC_DATA_INT_HISTORY_MATCH_COUNT = DDZ_PUBLIC_DATA_INT_HISTORY_CONTINUE_WIN + 3 --历史总场次 
DDZ_PUBLIC_DATA_INT_HISTORY_WIN_COUNT = DDZ_PUBLIC_DATA_INT_HISTORY_MATCH_COUNT + 3 --历史总场次 
DDZ_PUBLIC_DATA_INT_HISTORY_MAX_CASH = DDZ_PUBLIC_DATA_INT_HISTORY_WIN_COUNT + 3 --历史最大胡牌番 ----当前数量：27

-----------------------MSG---------------------------
DDZ_PLAYER_OPERATE_LAIZI_TIAN = 0 --天癞子
DDZ_PLAYER_OPERATE_LAIZI_DI = DDZ_PLAYER_OPERATE_LAIZI_TIAN + 1 --地癞子
DDZ_PLAYER_OPERATE_PLAYERHAND = DDZ_PLAYER_OPERATE_LAIZI_DI + 1 --玩家初始手牌
DDZ_PLAYER_OPERATE_SYN_CASH = DDZ_PLAYER_OPERATE_PLAYERHAND + 1 --同步钱数（playerID，之前的钱、结算后的钱）
DDZ_PLAYER_OPERATE_JUMP = DDZ_PLAYER_OPERATE_SYN_CASH + 1 --过牌
DDZ_PLAYER_OPERATE_JUMP_OPERATE = DDZ_PLAYER_OPERATE_JUMP + 1 --过牌标记消息，收到消息同步过牌
DDZ_PLAYER_OPERATE_CS_SEND = DDZ_PLAYER_OPERATE_JUMP_OPERATE + 1 --出牌，跟牌值
DDZ_PLAYER_OPERATE_CUR_CARD = DDZ_PLAYER_OPERATE_CS_SEND + 1 --同步出牌值，服务器下发消息
DDZ_PLAYER_OPERATE_SET_CUR_PLAYER = DDZ_PLAYER_OPERATE_CUR_CARD + 1 --设置下一个操作者，playerID
DDZ_PLAYER_OPERATE_TABLE_END_ROUND = DDZ_PLAYER_OPERATE_SET_CUR_PLAYER + 1 --本轮出牌结束，下家可以自由打牌（1，下个出牌的玩家)
DDZ_PLAYER_OPERATE_TIME = DDZ_PLAYER_OPERATE_TABLE_END_ROUND + 1 --操作倒计时，跟时间
DDZ_PLAYER_OPERATE_ERROR = DDZ_PLAYER_OPERATE_TIME + 1 --发送错误操作的操作码
DDZ_PLAYER_OPERATE_CHAIRMAN_TYPE = DDZ_PLAYER_OPERATE_ERROR + 1 --玩家叫地主(1叫，2抢，5不叫，6不抢)，客户端上行消息
DDZ_PLAYER_OPERATE_SET_CHAIRMAN = DDZ_PLAYER_OPERATE_CHAIRMAN_TYPE + 1 --同步地主（playerID，地主类型：1叫、2抢、3叫地主结束、4抢地主结束、5不叫、6不抢），服务器下发消息
DDZ_PLAYER_OPERATE_DOUBLE_TYPE = DDZ_PLAYER_OPERATE_SET_CHAIRMAN + 1 --玩家加倍类型上传消息（1普通加倍，2超级加倍，3不加倍），客户端上行消息
DDZ_PLAYER_OPERATE_BOTTOM_CARD = DDZ_PLAYER_OPERATE_DOUBLE_TYPE + 1  --广播底牌
DDZ_PLAYER_OPERATE_DOUBLE_PLAYER = DDZ_PLAYER_OPERATE_BOTTOM_CARD + 1 --玩家加倍广播（playerID，加倍类型），服务器下发消息
DDZ_PLAYER_OPERATE_CAERDS_TIMES = DDZ_PLAYER_OPERATE_DOUBLE_PLAYER + 1 --牌局番数消息（番数类型、番数增加值、总番数值）
DDZ_PLAYER_OPERATE_TABLE_STATE_BEGIN = DDZ_PLAYER_OPERATE_CAERDS_TIMES + 1 --同步牌桌开启状态
DDZ_PLAYER_OPERATE_TABLE_STATE_END = DDZ_PLAYER_OPERATE_TABLE_STATE_BEGIN + 1 --同步牌桌结束状态
DDZ_PLAYER_OPERATE_SET_AGENT = DDZ_PLAYER_OPERATE_TABLE_STATE_END + 1 --设置挂机
DDZ_PLAYER_OPERATE_GET_READY = DDZ_PLAYER_OPERATE_SET_AGENT + 1 --玩家点准备（DDZ_CONST_TABLE_STATE_END_GAME状态才生效）
DDZ_PLAYER_OPERATE_MINGPAI = DDZ_PLAYER_OPERATE_GET_READY + 1 --玩家明牌，客户端上行消息
DDZ_PLAYER_OPERATE_MINGPAI_END = DDZ_PLAYER_OPERATE_MINGPAI + 1 --玩家明牌广播，服务器下发消息 
DDZ_PLAYER_OPERATE_WAIT = DDZ_PLAYER_OPERATE_MINGPAI_END + 1 --第一轮等待出牌读秒读完
DDZ_PLAYER_OPERATE_DEBUG_SET_PLAYER_DATA = DDZ_PLAYER_OPERATE_WAIT + 1 --设置玩家数据
DDZ_PLAYER_OPERATE_SET_ACCENT = DDZ_PLAYER_OPERATE_DEBUG_SET_PLAYER_DATA + 1 --设置玩家口音
DDZ_PLAYER_OPERATE_OUT_OF_MONEY = DDZ_PLAYER_OPERATE_SET_ACCENT + 1 --认输
DDZ_PLAYER_OPERATE_WINNER = DDZ_PLAYER_OPERATE_OUT_OF_MONEY + 1  --获胜
DDZ_PLAYER_OPERATE_CLOSE_UI = DDZ_PLAYER_OPERATE_WINNER + 1 --关闭斗地主UI
DDZ_PLAYER_OPERATE_REQUEST_CARDS_TIPS = DDZ_PLAYER_OPERATE_CLOSE_UI + 1 --斗地主出牌提示请求
DDZ_PLAYER_OPERATE_SERVER_CARDS_TIPS = DDZ_PLAYER_OPERATE_REQUEST_CARDS_TIPS + 1 --斗地主出牌提示同步
DDZ_PLAYER_OPERATE_DEBUG_BEGIN = DDZ_PLAYER_OPERATE_SERVER_CARDS_TIPS + 1 --debug消息，允许换牌操作
DDZ_PLAYER_OPERATE_DEBUG_END = DDZ_PLAYER_OPERATE_DEBUG_BEGIN + 1 --debug消息，允许换牌操作
DDZ_PLAYER_OPERATE_CHANGE_CARDS = DDZ_PLAYER_OPERATE_DEBUG_END + 1 --换牌消息，设定第一个参数为交换双方顺序，2-3 为第一个玩家手牌，4-5为第二个玩家手牌
DDZ_PLAYER_OPERATE_CHANGE_END = DDZ_PLAYER_OPERATE_CHANGE_CARDS + 1 --换牌消息同步
DDZ_PLAYER_OPERATE_RESTART = DDZ_PLAYER_OPERATE_CHANGE_END + 1 --下一局游戏开启消息上传
DDZ_PLAYER_OPERATE_ENDINNG_SPRING = DDZ_PLAYER_OPERATE_RESTART + 1 --结算春天同步

-----------------------TABLE MGR STATE---------------------------
DDZ_CONST_TABLE_STATE_INIT = 1 --牌桌初始化(下一状态：等待玩家换牌)
DDZ_CONST_TABLE_STATE_SHOW_LAIZI_TIAN = DDZ_CONST_TABLE_STATE_INIT + 1 --发牌阶段
DDZ_CONST_TABLE_STATE_SEND_CARD = DDZ_CONST_TABLE_STATE_SHOW_LAIZI_TIAN + 1 --发牌阶段
DDZ_CONST_TABLE_STATE_CALL_CHAIRMAN = DDZ_CONST_TABLE_STATE_SEND_CARD + 1 --等待玩家叫地主
DDZ_CONST_TABLE_STATE_SET_CHAIRMAN = DDZ_CONST_TABLE_STATE_CALL_CHAIRMAN + 1 --等待玩家抢地主
DDZ_CONST_TABLE_STATE_SHOW_CHAIRMAN = DDZ_CONST_TABLE_STATE_SET_CHAIRMAN + 1 --同步底牌阶段
DDZ_CONST_TABLE_STATE_SHOW_LAIZI_DI = DDZ_CONST_TABLE_STATE_SHOW_CHAIRMAN + 1 --等待玩家抢地主
DDZ_CONST_TABLE_STATE_DOUBLE = DDZ_CONST_TABLE_STATE_SHOW_LAIZI_DI + 1 --加倍阶段（开始出牌、最后一次明牌）
DDZ_CONST_TABLE_STATE_SHUFFLE_MINGPAI = DDZ_CONST_TABLE_STATE_DOUBLE + 1 --客户端发牌阶段，玩家可以选择明牌
DDZ_CONST_TABLE_STATE_WAIT_CS_SEND = DDZ_CONST_TABLE_STATE_SHUFFLE_MINGPAI + 1 --等待玩家出牌
DDZ_CONST_TABLE_STATE_SETTLEMENT = DDZ_CONST_TABLE_STATE_WAIT_CS_SEND + 1 --春天结算
DDZ_CONST_TABLE_STATE_END_GAME = DDZ_CONST_TABLE_STATE_SETTLEMENT + 1 --结算界面
DDZ_CONST_TABLE_STATE_KILL_DOUDIZHU = DDZ_CONST_TABLE_STATE_END_GAME + 1 --关闭小游戏
DDZ_CONST_TABLE_STATE_WAIT_CS_SEND_AGENT = DDZ_CONST_TABLE_STATE_KILL_DOUDIZHU +1 --托管出牌

-----------------------COUNT DOWN---------------------------
DDZ_CONST_COUNT_DOWN_TIME = {
	[DDZ_CONST_TABLE_STATE_INIT] = 1,
	[DDZ_CONST_TABLE_STATE_SHOW_LAIZI_TIAN] = 5,
	[DDZ_CONST_TABLE_STATE_SEND_CARD] = 6,
	[DDZ_CONST_TABLE_STATE_CALL_CHAIRMAN] = 10,
	[DDZ_CONST_TABLE_STATE_SET_CHAIRMAN] = 10,
	[DDZ_CONST_TABLE_STATE_SHOW_CHAIRMAN] = 3,
	[DDZ_CONST_TABLE_STATE_SHOW_LAIZI_DI] = 5,
	[DDZ_CONST_TABLE_STATE_DOUBLE] = 8,
	[DDZ_CONST_TABLE_STATE_SHUFFLE_MINGPAI] = 8,
	[DDZ_CONST_TABLE_STATE_WAIT_CS_SEND] = 21,
	[DDZ_CONST_TABLE_STATE_SETTLEMENT] = 3,
	[DDZ_CONST_TABLE_STATE_END_GAME] = 300,
	[DDZ_CONST_TABLE_STATE_KILL_DOUDIZHU] = 1,
	[DDZ_CONST_TABLE_STATE_WAIT_CS_SEND_AGENT] = 3 --托管出牌时间
}--倒计时时间,从一状态到下一个状态的时间

-----------------------SOUNDID---------------------------

DDZ_SOUND_TABLE = {
	[DDZ_PLAYER_OPERATE_MINGPAI_END] = {[1] = {23539}},
	[DDZ_PLAYER_OPERATE_SET_CHAIRMAN] = {[3] = {23536}, [4] = {23542}, [5] = {23507}, [6] = {23508}, [7] = {23553}},
	[DDZ_PLAYER_OPERATE_DOUBLE_PLAYER] = {[1] = {23535, 23544}, [2] = {23510, 23543}, [3] = {23506}},
	[DDZ_PLAYER_OPERATE_JUMP_OPERATE] = {[1] = {23556, 23509, 23528, 23504}},
	[DDZ_PLAYER_OPERATE_ENDINNG_SPRING] = {[1] = {23537, 23505}},
}

DDZ_SOUND_CARD = {
	--DDZ_CONST_CARD 不能引用至本脚本，注意首层枚举为类型，二层枚举为牌值。与DDZ_GetCardType一致
	[1] = {[0x01] = 23492, [0x02] = 23493, [0x03] = 23494, [0x04] = 23495, [0x05] = 23496, [0x06] = 23497, [0x07] = 23498, [0x08] = 23499, [0x09] = 23500, [0x0a] = 23501, [0x0b] = 23502, [0x0c] = 23503, [0x0d] = 23491, [0x0e] = 23555, [0x0f] = 23512},
	[2] = {23549},
	[3] = {[0x01] = 23514, [0x02] = 23515, [0x03] = 23516, [0x04] = 23517, [0x05] = 23518, [0x06] = 23519, [0x07] = 23520, [0x08] = 23521, [0x09] = 23523, [0x0a] = 23524, [0x0b] = 23525, [0x0c] = 23522, [0x0d] = 23513},
	[4] = {23538},
	[5] = {23548},
	[6] = {23547},
	[7] = {[0x01] = 23546, [0x02] = 23526, [0x03] = 23554}, ---0x02、0x03 为飞机语音，需要做随机处理
	[8] = {[0x01] = 23545, [0x02] = 23526, [0x03] = 23554}, ---0x02、0x03 为飞机语音，需要做随机处理
	[9] = {23550},
	[10] = {23551},
	[11] = {23557, 23533},
	[12] = {23557, 23533},
	[13] = {23557, 23533},
	[14] = {23557, 23533},
	[15] = {23557, 23533},
	[16] = {23557, 23533},
	[17] = {23557, 23533},
	[18] = {23557, 23533},
	[19] = {23557, 23533},
	[20] = {23557, 23533},
	[21] = {23552, 23534},
}

DDZ_SOUND_RANDOM = {
	[1] = 100, --基础随机数
	[2] = 30, --对应DDZ_SOUND_SEND[1]
	[3] = 30, --对应DDZ_SOUND_SEND[2]
	[4] = 20, --对应DDZ_SOUND_SEND[3]
}

DDZ_SOUND_SEND = {
	[1] = {23511}, --普通出牌，第一个值为概率
	[2] = {23530}, --单张最大值，第一个值为概率
	[3] = {23527, 23532, 23531, 23540}, --单张刚好压过,第一个值为概率
	[4] = {23529}, --还剩两张牌
}

-----------------------REMOTE_LIST---------------------------

REMOTE_DOUDIZHU_DATAS = {
	CUR_CONTINUE_WIN_COUNT = {0, 2}, --当前连胜场次
	HISTORY_CONTINUE_WIN_COUNT = {2, 2}, --历史连胜记录
	HISTORY_MATCH_COUNT = {4, 4}, --历史总场次
	HISTORY_WIN_COUNT = {8, 4}, --历史总胜场数
	HISTORY_MAX_CASH = {12, 4}, --历史最大胡牌番数（番数是应收值）
}--角色远程数据块

-----------------------FUNCTION---------------------------
local miniGameMgr = GetMiniGameMgr()
function DDZ_INIT()
	miniGameMgr = GetMiniGameMgr()
end

function DDZ_SetNeedSettleAccounts(need)
	miniGameMgr.SetPrivateData(MINI_GAME_DATA_SIZE.BOOL, DDZ_PRIVATE_DATA_BOOL_NEED_SETTLE_ACCOUNTS, need)
end

function DDZ_GetNeedSettleAccounts()
	local temp = miniGameMgr.GetPrivateData(MINI_GAME_DATA_SIZE.BOOL, DDZ_PRIVATE_DATA_BOOL_NEED_SETTLE_ACCOUNTS)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPrivateBottomCards(data, offset)
	miniGameMgr.SetPrivateData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PRIVATE_DATA_BYTE_BOTTOMCARDS, data[offset],
		DDZ_PRIVATE_DATA_BYTE_BOTTOMCARDS + 1, data[offset + 1],
		DDZ_PRIVATE_DATA_BYTE_BOTTOMCARDS + 2, data[offset + 2]
	)
end

function DDZ_GetPrivateBottomCards()
	return miniGameMgr.GetPrivateData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PRIVATE_DATA_BYTE_BOTTOMCARDS,
		DDZ_PRIVATE_DATA_BYTE_BOTTOMCARDS + 1,
		DDZ_PRIVATE_DATA_BYTE_BOTTOMCARDS + 2
	)
end

function DDZ_SetPrivateCardsPile(tCardsPile, nIndexBegin)
	--服务器数据错位，nIndexBegin 从0开始，逻辑是用总牌数-记牌器的牌数得到nIndexBegin，故从0开始
	if type(tCardsPile) ~= "table" then
		return
	end
	for i = 1, #tCardsPile do
		miniGameMgr.SetPrivateData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + nIndexBegin + i - 1, tCardsPile[i])
	end
end

function DDZ_GetPrivateCardsPile()
	local temp = {}
	local temp1 = {}
	local temp2 = {}
	local temp3 = {}
	local tReturn = {}
	temp = miniGameMgr.GetPrivateData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x01,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x02,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x03,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x04,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x05,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x06,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x07,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x08,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x09,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x0A,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x0B,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x0C,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x0D,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x0E,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x0F
	)
	temp1 = miniGameMgr.GetPrivateData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x10,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x11,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x12,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x13,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x14,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x15,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x16,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x17,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x18,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x19,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x1A,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x1B,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x1C,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x1D,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x1E,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x1F
	)
	temp2 = miniGameMgr.GetPrivateData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x20,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x21,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x22,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x23,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x24,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x25,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x26,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x27,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x28,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x29,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x2A,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x2B,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x2C,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x2D,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x2E,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x2F
	)
	temp3 = miniGameMgr.GetPrivateData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x30,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x31,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x32,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x33,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x34,
		DDZ_PRIVATE_DATA_BYTE_CARDS_PILE + 0x35
	)
	for i = 1, 16 do
		tReturn[i] = temp[i]
	end
	for i = 1, 16 do
		tReturn[i + 16] = temp1[i]
	end
	for i = 1, 16 do
		tReturn[i + 32] = temp2[i]
	end
	for i = 1, 6 do
		tReturn[i + 48] = temp3[i]
	end
	return tReturn
end

function DDZ_SetPublicBottomCards(data, offset)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PUBLIC_DATA_BYTE_BOTTOMCARDS, data[offset],
		DDZ_PUBLIC_DATA_BYTE_BOTTOMCARDS + 1, data[offset + 1],
		DDZ_PUBLIC_DATA_BYTE_BOTTOMCARDS + 2, data[offset + 2]
	)
end

function DDZ_GetPublicBottomCards()
	return miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PUBLIC_DATA_BYTE_BOTTOMCARDS,
		DDZ_PUBLIC_DATA_BYTE_BOTTOMCARDS + 1,
		DDZ_PUBLIC_DATA_BYTE_BOTTOMCARDS + 2
	)
end

function DDZ_SetBottom2PlayerHand(nPlayerIndex, bottomCard)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x11, bottomCard[0x01],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x12, bottomCard[0x02],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x13, bottomCard[0x03]
	)
end

function DDZ_SetPlayerHand(nPlayerIndex, handCard)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS, handCard[0x01],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x01, handCard[0x02],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x02, handCard[0x03],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x03, handCard[0x04],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x04, handCard[0x05],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x05, handCard[0x06],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x06, handCard[0x07],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x07, handCard[0x08],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x08, handCard[0x09],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x09, handCard[0x0A],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x0A, handCard[0x0B],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x0B, handCard[0x0C],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x0C, handCard[0x0D],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x0D, handCard[0x0E],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x0E, handCard[0x0F],
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x0F, handCard[0x10]
	)
	for i = 0x11, #handCard do
		miniGameMgr.SetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_HANDCARDS + i - 1, handCard[i])
	end
end

function DDZ_GetPlayerHand(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = {}
	temp = miniGameMgr.GetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x01,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x02,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x03,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x04,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x05,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x06,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x07,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x08,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x09,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x0A,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x0B,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x0C,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x0D,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x0E,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x0F
	)
	local temp1 = {}
	temp1 = miniGameMgr.GetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x10,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x11,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x12,
		DDZ_PLAYER_DATA_BYTE_HANDCARDS + 0x13
	)
	for i = 1, 4 do
		temp[16 + i] = temp1[i]
	end
	return temp
end

function DDZ_SetPlayerCardsTips(nPlayerIndex, handCard)
	nPlayerIndex = nPlayerIndex - 1
	for i = 1, #handCard do
		miniGameMgr.SetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + i - 1, handCard[i])
	end
end

function DDZ_GetPlayerCardsTips(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = {}
	temp = miniGameMgr.GetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x01,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x02,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x03,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x04,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x05,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x06,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x07,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x08,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x09,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x0A,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x0B,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x0C,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x0D,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x0E,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x0F
	)
	local temp1 = {}
	temp1 = miniGameMgr.GetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x10,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x11,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x12,
		DDZ_PLAYER_DATA_BYTE_CARDS_TIPS + 0x13
	)
	for i = 1, 4 do
		temp[16 + i] = temp1[i]
	end
	return temp
end

function DDZ_SetPublicPlayerHandCards(nPlayerIndex, handCard)
	--nPlayerIndex = 1,2,3 分别对应 DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1，2，3，明牌后写入publicdata
	if nPlayerIndex == 1  then
		miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1, handCard[0x01],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x01, handCard[0x02],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x02, handCard[0x03],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x03, handCard[0x04],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x04, handCard[0x05],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x05, handCard[0x06],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x06, handCard[0x07],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x07, handCard[0x08],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x08, handCard[0x09],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x09, handCard[0x0A],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x0A, handCard[0x0B],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x0B, handCard[0x0C],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x0C, handCard[0x0D],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x0D, handCard[0x0E],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x0E, handCard[0x0F],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x0F, handCard[0x10]
		)
		for i = 0x11, #handCard do
			miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + i - 1, handCard[i])
		end
	elseif nPlayerIndex == 2 then
		miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2, handCard[0x01],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x01, handCard[0x02],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x02, handCard[0x03],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x03, handCard[0x04],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x04, handCard[0x05],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x05, handCard[0x06],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x06, handCard[0x07],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x07, handCard[0x08],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x08, handCard[0x09],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x09, handCard[0x0A],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x0A, handCard[0x0B],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x0B, handCard[0x0C],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x0C, handCard[0x0D],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x0D, handCard[0x0E],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x0E, handCard[0x0F],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x0F, handCard[0x10]
		)
		for i = 0x11, #handCard do
			miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + i - 1, handCard[i])
		end
	elseif nPlayerIndex == 3 then
		miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3, handCard[0x01],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x01, handCard[0x02],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x02, handCard[0x03],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x03, handCard[0x04],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x04, handCard[0x05],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x05, handCard[0x06],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x06, handCard[0x07],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x07, handCard[0x08],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x08, handCard[0x09],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x09, handCard[0x0A],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x0A, handCard[0x0B],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x0B, handCard[0x0C],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x0C, handCard[0x0D],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x0D, handCard[0x0E],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x0E, handCard[0x0F],
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x0F, handCard[0x10]
		)
		for i = 0x11, #handCard do
			miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + i - 1, handCard[i])
		end
	end
end

function DDZ_GetPublicPlayerHandCards(nPlayerIndex)
	local temp = {}
	local temp1 = {}
	if nPlayerIndex == 1 then
		temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x01,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x02,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x03,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x04,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x05,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x06,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x07,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x08,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x09,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x0A,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x0B,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x0C,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x0D,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x0E,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x0F
		)
		temp1 = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x10,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x11,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x12,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_1 + 0x13
		)
	elseif nPlayerIndex == 2 then
		temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x01,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x02,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x03,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x04,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x05,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x06,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x07,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x08,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x09,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x0A,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x0B,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x0C,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x0D,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x0E,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x0F
		)
		temp1 = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x10,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x11,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x12,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_2 + 0x13
		)
	elseif nPlayerIndex == 3 then
		temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x01,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x02,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x03,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x04,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x05,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x06,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x07,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x08,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x09,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x0A,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x0B,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x0C,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x0D,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x0E,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x0F
		)
		temp1 = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x10,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x11,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x12,
			DDZ_PUBLIC_DATA_BYTE_PLAYER_HANDCARDS_3 + 0x13
		)
	end
	for i = 1, 4 do
		temp[16 + i] = temp1[i]
	end
	return temp
end

function DDZ_SetPlayerCashOrigin(nPlayerIndex, cashOri)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_PLAYER_CASH_ORIGIN + nPlayerIndex, cashOri)
end

function DDZ_GetPlayerCashOrigin(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_PLAYER_CASH_ORIGIN + nPlayerIndex)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetCurContinueWin(nPlayerIndex, cash)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_CUR_CONTINUE_WIN + nPlayerIndex, cash)
end

function DDZ_GetCurContinueWin(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_CUR_CONTINUE_WIN + nPlayerIndex)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetHisContinueWin(nPlayerIndex, cash)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_HISTORY_CONTINUE_WIN + nPlayerIndex, cash)
end

function DDZ_GetHisContinueWin(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_HISTORY_CONTINUE_WIN + nPlayerIndex)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetHisMatchCount(nPlayerIndex, cash)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_HISTORY_MATCH_COUNT + nPlayerIndex, cash)
end

function DDZ_GetHisMatchCount(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_HISTORY_MATCH_COUNT + nPlayerIndex)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetHisWinCount(nPlayerIndex, cash)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_HISTORY_WIN_COUNT + nPlayerIndex, cash)
end

function DDZ_GetHisWinCount(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_HISTORY_WIN_COUNT + nPlayerIndex)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetHisMaxCash(nPlayerIndex, cash)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_HISTORY_MAX_CASH + nPlayerIndex, cash)
end

function DDZ_GetHisMaxCash(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_HISTORY_MAX_CASH + nPlayerIndex)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPlayerCash(nPlayerIndex, cash)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_PLAYER_CASH + nPlayerIndex, cash)
end

function DDZ_GetPlayerCash(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_PLAYER_CASH + nPlayerIndex)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPlayerCashHonor(nPlayerIndex, cashHonor)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_PLAYER_CASH_HONOR + nPlayerIndex, cashHonor)
end

function DDZ_GetPlayerCashHonor(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_PLAYER_CASH_HONOR + nPlayerIndex)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPublicLaiZi(laizi1, laizi2)
	if laizi1 > 0 and laizi2 == 0 then
		miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_LAIZI, laizi1)
	elseif laizi1 == 0 and laizi2 > 0 then
		miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_LAIZI + 1, laizi2)
	else
		miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_LAIZI, laizi1, DDZ_PUBLIC_DATA_BYTE_LAIZI + 1, laizi2)
	end
end

function DDZ_GetPublicLaiZi()
	return miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_LAIZI, DDZ_PUBLIC_DATA_BYTE_LAIZI + 1)
end

function DDZ_SetLaiZiNum(Num)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_LAIZI_NUM, Num)
end

function DDZ_GetLaiZiNum()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_LAIZI_NUM)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPrivateLaiZi(laizi1, laizi2)
	if laizi1 > 0 and laizi2 == 0 then
		miniGameMgr.SetPrivateData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PRIVATE_DATA_BYTE_LAIZI, laizi1)
	elseif laizi1 == 0 and laizi2 > 0 then
		miniGameMgr.SetPrivateData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PRIVATE_DATA_BYTE_LAIZI + 1, laizi2)
	else
		miniGameMgr.SetPrivateData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PRIVATE_DATA_BYTE_LAIZI, laizi1, DDZ_PRIVATE_DATA_BYTE_LAIZI + 1, laizi2)
	end
end

function DDZ_GetPrivateLaiZi()
	return miniGameMgr.GetPrivateData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PRIVATE_DATA_BYTE_LAIZI, DDZ_PRIVATE_DATA_BYTE_LAIZI + 1)
end

function DDZ_GetPublicCardsTimes()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_CAERDS_TIMES)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPublicCardsTimes(nCardsTimes)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_CAERDS_TIMES, nCardsTimes)
end

function DDZ_SetPublicTimesTableState(nTableState, nCardsTimes)
	nTableState = nTableState - 1
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_TIMES_TABLE_STATE + nTableState, nCardsTimes)
end

function DDZ_GetPublicTimesTableState(nTableState)
	nTableState = nTableState - 1
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_TIMES_TABLE_STATE + nTableState)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_GetPlayerWinner()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_PLAYER_WINNER)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPlayerWinner(nPlayerIndex)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_PLAYER_WINNER, nPlayerIndex)
end

function DDZ_GetPlayerCardsTimes(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_CAERDS_TIMES)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPlayerCardsTimes(nPlayerIndex, nCardsTimes)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_CAERDS_TIMES, nCardsTimes)
end

function DDZ_GetAchievementBomb(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_ACHIEVEMENT_BOMB)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetAchievementBomb(nPlayerIndex, num)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_ACHIEVEMENT_BOMB, num)
end

function DDZ_GetAchievementLaiNum(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_ACHIEVEMENT_LAIZI_NUM)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetAchievementLaiNum(nPlayerIndex, num)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_ACHIEVEMENT_LAIZI_NUM, num)
end

function DDZ_GetAchievementSpring(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_ACHIEVEMENT_SPRING)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetAchievementSpring(nPlayerIndex, num)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_ACHIEVEMENT_SPRING, num)
end

function DDZ_GetPlayeChairmanCompare(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_CHAIRMAN_COMPARE)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPlayerChairmanCompare(nPlayerIndex, Chairman)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_CHAIRMAN_COMPARE, Chairman)
end

function DDZ_GetReStartNum()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_RESTART)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetReStartNum(ReStartNum)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_RESTART, ReStartNum)
end

function DDZ_GetPlayerMingPaiState(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_MINGPAI_STATE)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_GetPublicMingPaiState(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_PLAYER_MINGPAI_STATE + nPlayerIndex)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPlayerMingPaiState(nPlayerIndex, state)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_MINGPAI_STATE, state)
end

function DDZ_SetPublicMingPaiState(nPlayerIndex, state)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_PLAYER_MINGPAI_STATE + nPlayerIndex, state)
end

function DDZ_SetPlayerDoubleType(nPlayerIndex, state)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_PLAYER_DOUBLE_TYPE + nPlayerIndex, state)
end

function DDZ_GetPlayerDoubleType(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_PLAYER_DOUBLE_TYPE + nPlayerIndex)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPlayerCardsFirst(nPlayerIndex, num)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_CARDS_FIRST, num)
end

function DDZ_GetPlayerCardsFirst(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_CARDS_FIRST)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_GetPlayerCardsNum(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_CARDS_NUM)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPlayerCardsNum(nPlayerIndex, Num)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_CARDS_NUM, Num)
end

function DDZ_GetPublicCardsLast2UI()
	local temp = DDZ_GetPublicCardsLast()
	--UI用数组结构需要后移两位，再前两位插入0
	table.insert(temp, 1, 0)
	table.insert(temp, 1, 0)
	return temp
end

function DDZ_GetPublicCardsLast()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x01,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x02,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x03,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x04,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x05,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x06,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x07,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x08,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x09,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x0A,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x0B,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x0C,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x0D,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x0E
	)
	return temp
end

function DDZ_SetPublicCardsLast(handCard)
	--handCard为剩余手牌方法，并不是手牌数组，为了统一变量名写为handCard
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST, handCard[0x01],
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x01, handCard[0x02],
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x02, handCard[0x03],
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x03, handCard[0x04],
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x04, handCard[0x05],
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x05, handCard[0x06],
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x06, handCard[0x07],
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x07, handCard[0x08],
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x08, handCard[0x09],
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x09, handCard[0x0A],
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x0A, handCard[0x0B],
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x0B, handCard[0x0C],
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x0C, handCard[0x0D],
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x0D, handCard[0x0E],
		DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_LAST + 0x0E, handCard[0x0F]
	)
end

function DDZ_GetPublicCardsNum(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_NUM + nPlayerIndex)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPublicCardsNum(nPlayerIndex, Num)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_PLAYER_CARDS_NUM + nPlayerIndex, Num)
end

function DDZ_GetPlayerChairManType(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_CHAIRMAN_TYPE)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_GetPubicChairManType()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PUBLIC_DATA_BYTE_CHAIRMAN_TYPE_PLAYER,
		DDZ_PUBLIC_DATA_BYTE_CHAIRMAN_TYPE_PLAYER + 0x01,
	DDZ_PUBLIC_DATA_BYTE_CHAIRMAN_TYPE_PLAYER + 0x02)
	return temp
end

function DDZ_SetPlayerChairManType(nPlayerIndex, type)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPlayerData(nPlayerIndex, MINI_GAME_DATA_SIZE.BYTE, DDZ_PLAYER_DATA_BYTE_CHAIRMAN_TYPE, type)
	--同步数据给PUBLIC_DATA用于UI
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_CHAIRMAN_TYPE_PLAYER + nPlayerIndex, type)
end

function DDZ_SetCurOperateCard(cardData)
	local tempCardData = {
		0, 0, 0, 0, 0,
		0, 0, 0, 0, 0,
		0, 0, 0, 0, 0,
		0, 0, 0, 0, 0
	}
	local index = 1
	for k, v in pairs(cardData) do
		tempCardData[index] = v
		index = index + 1
	end
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD, tempCardData[1],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 1, tempCardData[2],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 2, tempCardData[3],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 3, tempCardData[4],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 4, tempCardData[5],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 5, tempCardData[6],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 6, tempCardData[7],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 7, tempCardData[8],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 8, tempCardData[9],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 9, tempCardData[10]
	)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 10, tempCardData[11],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 11, tempCardData[12],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 12, tempCardData[13],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 13, tempCardData[14],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 14, tempCardData[15],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 15, tempCardData[16],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 16, tempCardData[17],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 17, tempCardData[18],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 18, tempCardData[19],
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 19, tempCardData[20]
	)
end

function DDZ_GetCurOperateCard()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 1,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 2,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 3,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 4,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 5,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 6,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 7,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 8,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 9
	)

	local tempCardData = {}
	local index = 1

	for k, v in pairs(temp) do
		if v == 0 then
			return tempCardData
		else
			tempCardData[index] = v
			index = index + 1
		end
	end

	temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 10,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 11,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 12,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 13,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 14,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 15,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 16,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 17,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 18,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD + 19
	)

	for k, v in pairs(temp) do
		if v == 0 then
			return tempCardData
		else
			tempCardData[index] = v
			index = index + 1
		end
	end

	return tempCardData
end

function DDZ_SetCurOperatePlayer(nPlayerIndex)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_PLAYER, nPlayerIndex)
end

function DDZ_GetCurOperatePlayer()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_PLAYER)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetCardOwner(nPlayerIndex)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD_OWNER, nPlayerIndex)
end

function DDZ_GetCardOwner()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD_OWNER)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetCurOperateCardType(typeID, firstCard, lenth)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD_TYPE, typeID,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD_TYPE + 1, firstCard,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD_TYPE + 2, lenth
	)
end

function DDZ_GetCurOperateCardType()
	return miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD_TYPE,
		DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD_TYPE + 1,
	DDZ_PUBLIC_DATA_BYTE_CUR_OPERATE_CARD_TYPE + 2)
end

function DDZ_SetChairMan(nPlayerIndex)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_CHAIRMAN, nPlayerIndex)
end

function DDZ_GetChairMan()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_CHAIRMAN)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetTableMgrState(state)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_TABLE_MGR_STATE, state)
end

function DDZ_GetTableMgrState()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_TABLE_MGR_STATE)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetSpringPlayerIndex(nPlayerIndex)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_ENDINNG_SPRING, nPlayerIndex)
end

function DDZ_GetSpringPlayerIndex()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_ENDINNG_SPRING)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetTableSettingType(state)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_TABLE_SETTING_TYPE, state)
end

function DDZ_GetTableSettingType()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_TABLE_SETTING_TYPE)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetCashBase(cashBase)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_CASH_BASE, cashBase)
end

function DDZ_GetCashBase()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_CASH_BASE)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetShuffleType(nShuffle)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_SHUFFLE_TYPE, nShuffle)
end

function DDZ_GetShuffleType()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_SHUFFLE_TYPE)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPlayerIsAgent(nPlayerIndex, isAgent)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BOOL, DDZ_PUBLIC_DATA_BOOL_PLAYER_IS_AGENT + nPlayerIndex, isAgent)
	if WRITE_LOG then
		--	Log(tostring("SetPlayerIsAgent：" .. nPlayerIndex .. "|" .. isAgent))
		Log(string.format("DDZ_SetPlayerIsAgent: %d, isAgent: %d", nPlayerIndex + 1, isAgent))
	end
end

function DDZ_GetPlayerIsAgent(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BOOL, DDZ_PUBLIC_DATA_BOOL_PLAYER_IS_AGENT + nPlayerIndex)
	if temp == nil then
		return 0
	end
	if WRITE_LOG then
		Log(string.format("DDZ_GetPlayerIsAgent: nPlayerIndex: %d, isAgent: %d", nPlayerIndex + 1, temp[1]))
	end
	return temp[1]
end

function DDZ_SetPlayerWinnerBool(nPlayerIndex, isAgent)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BOOL, DDZ_PUBLIC_DATA_BOOL_PLAYER_WINNER + nPlayerIndex, isAgent)
end

function DDZ_GetPlayerWinnerBool(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BOOL, DDZ_PUBLIC_DATA_BOOL_PLAYER_WINNER + nPlayerIndex)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPlayerOperateJump(nPlayerIndex, isAgent)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BOOL, DDZ_PUBLIC_DATA_BOOL_PLAYER_OPERATE_JUMP + nPlayerIndex, isAgent)
end

function DDZ_GetPlayerOperateJump(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BOOL, DDZ_PUBLIC_DATA_BOOL_PLAYER_OPERATE_JUMP + nPlayerIndex)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetPublicDebug(isAgent)
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BOOL, DDZ_PUBLIC_DATA_BOOL_PLAYER_DEBUG, isAgent)
end

function DDZ_GetPublicDebug()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BOOL, DDZ_PUBLIC_DATA_BOOL_PLAYER_DEBUG)
	if temp == nil then
		return 0
	end
	return temp[1]
end

function DDZ_SetCountDownTime(time, nTimeID, nPlayerIndex)
	-- local mgr = miniGameMgr
	if nPlayerIndex == -1 then
		nPlayerIndex = 0
	end
	local temp = nPlayerIndex * 0x10 + nTimeID
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_COUNT_DOWN_PLAYER_AND_TYPE, temp)

	if time > 0 then
		time = miniGameMgr.GetGameTime() + time
	end
	miniGameMgr.SetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_COUNT_DOWN_TIME, time)

	return time
end

function DDZ_GetCountDownTime()
	local temp = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.INT, DDZ_PUBLIC_DATA_INT_COUNT_DOWN_TIME)
	if temp == nil then
		return {}
	end
	local temp1 = miniGameMgr.GetPublicData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PUBLIC_DATA_BYTE_COUNT_DOWN_PLAYER_AND_TYPE)
	if temp1 == nil then
		return {}
	end
	return {temp[1], math.floor(temp1[1] / 0x10), temp1[1] % 0x10}
end

function DDZ_SetPlayerOperateCount(nPlayerIndex, count)
	-- local mgr = miniGameMgr
	if nPlayerIndex == -1 then
		for i = 1, DDZ_CONST_PLAYER_MAX do
			miniGameMgr.ChangePlayerOperateCount(i - 1, count)
		end
	else
		miniGameMgr.ChangePlayerOperateCount(nPlayerIndex - 1, count)
	end
end

function DDZ_GetPlayerOperateCount(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	return miniGameMgr.GetPlayerOperateCount(nPlayerIndex)
end

function DDZ_GetPlayerDWID(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	return miniGameMgr.GetPlayerID(nPlayerIndex)
end

function DDZ_SetPlayerOverTimeCount(nPlayerIndex, count)
	nPlayerIndex = nPlayerIndex - 1
	miniGameMgr.SetPrivateData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PRIVATE_DATA_BYTE_PLAYER_OVERTIME_COUNT + nPlayerIndex, count)
end

function DDZ_GetPlayerOverTimeCount(nPlayerIndex)
	nPlayerIndex = nPlayerIndex - 1
	local temp = miniGameMgr.GetPrivateData(MINI_GAME_DATA_SIZE.BYTE, DDZ_PRIVATE_DATA_BYTE_PLAYER_OVERTIME_COUNT + nPlayerIndex, count)
	if temp == nil then
		return 0
	end
	return temp[1]
end