-- 引擎的游戏逻辑脚本

local tScripts = {
    -- "scripts/skill/include/SkillLearn.lh",
    -- "scripts/Include/SkillRecipe.lh",
    -- "scripts/achievement/ItemAcquire_Achievement.lua",
    -- "scripts/skill/经脉/VerationTable.lua",
    -- "scripts/Tong/include/TongTechTree.lh",
    -- "scripts/Tong/include/SeedData.lh",
    -- "scripts/Include/CastleCustomValueName.lh",
    "scripts/HorseSkill/include/HorseMagicInfoToHorseSkillIdLvForUI.lua",
    "scripts/Map/HorseSkill/include/特殊坐骑属性汇总.lh",
    "scripts/Include/IdentityVisibleType.lua",  -- 里世界
    -- "scripts/Map/天山碎冰谷/include/Match3V3Acount.lua",
    "scripts/Include/JJCCoinFunc.lua",
    -- "scripts/Include/UIscript/UIscript_FriendsInvite.lua",
    -- "scripts/Include/UIscript/UIscriptDanmu.lua",
    -- "scripts/Include/UIscript/UIscript_ChangeSever.lua",
    -- "scripts/Include/UIscript/UIscript_JoinCamp.lua",
    -- "scripts/Include/UIscript/UIscript_AutomaticSell.lua",
    "scripts/Include/UIscript/UIscript_ToyBoxLimit.lua",
    -- "scripts/Map/阵营首领/include/ClientCommanderFunc.lua",
    "scripts/Map/好友系统/include/HelpMapData.lua",
    "scripts/Map/世界通用/include/新版连续签到_data.lua",
    -- "scripts/Map/天山碎冰谷/include/竞技场开房间data.lua",
    -- "scripts/Include/UIscript/UIscript_DestroyItemCheck.lua",
    -- "scripts/Include/UIscript/UIscript_BattleField.lua",
    "scripts/Include/UIscript/UIscript_PhotoGame.lua",
    "scripts/Include/UIscript/UIscript_PhotoStudio.lua",
    -- "scripts/Include/UIscript/UIscript_BossMaxLife.lua",
    "scripts/Include/UIscript/UIscript_ResetRaid.lua",
    "scripts/Include/UIscript/UIscript_SurpriseFree.lua",
    -- "scripts/Map/NpcPet/RepuNpcList.lua",
    -- "scripts/player/include/Kungfu2ArenaType.lh",
    -- "scripts/Include/UIscript/UIscript_WulinShenghui.lua",
    -- "scripts/Include/UIscript/UIscript_BoxLimit.lua",
    -- "scripts/Map/列星岛/include/CommonFunction.lua",
    -- "scripts/Map/好友系统/include/ClientData.lua",
    -- "scripts/Include/UIscript/UIscript_NewTrialValley.lua",
    -- "scripts/Include/UIscript/UIscript_Lottery.lua",
    "scripts/Map/家园系统客户端/Include/HomelandCommon.lua",
    -- "scripts/Map/家园系统客户端/Include/Home_LandObjectInteraction.lua",
    -- "scripts/Map/家园系统客户端/Include/Home_BuildLandObjectModels.lua",
    "scripts/Map/家园系统客户端/Include/Home_MiniGameCommonFunction.lua",
    -- "scripts/Map/家园系统客户端/Include/Home_BuildReplaceableModels.lua",
    -- "scripts/MiniGame/Mahjong/xueliuchenghe/IdentityCustomValueName.lua",
    -- "scripts/MiniGame/Mahjong/xueliuchenghe/xueliuchenghePlayerMgr.lua",
    -- "scripts/Include/UIscript/UIscript_MeiRenTuData.lua",
    -- "scripts/Include/UIscript/UIscript_TongWar.lua",
    "scripts/Include/UIscript/UIscript_Camp.lua",
    -- "scripts/MiniGame/DouDiZhu/for3players/IdentityCustomValueName.lua",
    -- "scripts/MiniGame/DouDiZhu/for3players/doudizhu3playersPlayerMgr.lua",
    "scripts/Include/UIscript/UIscript_Arena.lua",
    -- "scripts/Include/UIscript/UIscript_Asura.lua",
    -- "scripts/Include/UIscript/UIscript_SpiritEndurance.lua",
    -- "scripts/Include/UIscript/UIscript_MonsterBuff.lua",
    -- "scripts/Include/UIscript/UIscript_MonsterSkill.lua",
    -- "scripts/Include/UIscript/UIscript_JueJing.lua",
    -- "scripts/Include/UIscript/UIscript_LZXC.lua",
    -- "scripts/Include/UIscript/UIscriptDrawCard.lua",
    "scripts/Include/UIscript/UIscript_DiamondCount.lua",
    -- "scripts/Include/UIscript/UIscript_MatchGuess.lua",
    -- "scripts/Include/UIscript/UIscript_Homeland.lua",
    -- "scripts/Include/UIscript/UIscript_Hero.lua",
    -- "scripts/Include/UIscript/UIscript_CombatPresets.lua",
    -- "scripts/Include/UIscript/UIscript_Drama.lua",
    -- "scripts/Include/UIscript/UIscript_ThePassFight.lua",
    "scripts/Include/UIscript/UIscript_SeasonDistance.lua",
    -- "scripts/Include/UIscript/UIscript_FameShop.lua",
    -- "scripts/Include/UIscript/UIscript_SeasonTag.lua",
    "scripts/Include/UIscript/UIscript_Qiyu.lua",
    "scripts/Include/UIscript/UIscript_CheckOperatAct.lua",
    "scripts/Include/UIscript/UIscript_Homeland.lua",
    "scripts/Include/UIscript/UIscript_TeachSkill.lua",
    "scripts/Include/UIscript/UIscript_MonsterSkill.lua",
    "scripts/Include/UIscript/UIscript_SpiritEndurance.lua",
    "scripts/Include/UIscript/UIscript_EightWastesUIRemoteData.lua",
    "scripts/Include/UIscript/Uiscript_ShowCard.lua",
    "scripts/Include/UIscript/UIscript_WulinShenghui.lua",
    "scripts/Include/UIscript/UIscript_MonsterSkillPreSet.lua",
    "scripts/Include/UIscript/UIscript_SpecialWish.lua",
    "scripts/Include/UIscript/UIscript_Map.lua",
    "scripts/Include/UIscript/UIscript_Common.lua",
}

--local strConv = Platform.IsWindows() and UTF8ToGBK or function (s) return s end
for _, s in ipairs(tScripts) do
    require(UTF8ToGBK(s))
end
