--*************************************** 工具生成 ***************************************
UIBuffCatalogInfoTab = 
{
    [0]=
    {
        ["nID"]=0,
        ["nType"]=0,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_BuffHuoDong.png",
        ["nPriority"]=99
    },
    [1]=
    {
        ["nID"]=1,
        ["nType"]=1,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffbaofa1.png",
        ["nPriority"]=1
    },
    [2]=
    {
        ["nID"]=2,
        ["nType"]=1,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffshengcun1.png",
        ["nPriority"]=2
    },
    [3]=
    {
        ["nID"]=3,
        ["nType"]=1,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffyisu1.png",
        ["nPriority"]=3
    },
    [4]=
    {
        ["nID"]=4,
        ["nType"]=1,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffhuifu1.png",
        ["nPriority"]=4
    },
    [5]=
    {
        ["nID"]=5,
        ["nType"]=1,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Bufffantan1.png",
        ["nPriority"]=5
    },
    [6]=
    {
        ["nID"]=6,
        ["nType"]=2,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffbaofa2.png",
        ["nPriority"]=1
    },
    [7]=
    {
        ["nID"]=7,
        ["nType"]=2,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffshengcun2.png",
        ["nPriority"]=2
    },
    [8]=
    {
        ["nID"]=8,
        ["nType"]=2,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffkongzhi2.png",
        ["nPriority"]=3
    },
    [9]=
    {
        ["nID"]=9,
        ["nType"]=2,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffchenmo3.png",
        ["nPriority"]=4
    },
    [10]=
    {
        ["nID"]=10,
        ["nType"]=2,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffjiaoxie2.png",
        ["nPriority"]=5
    },
    [11]=
    {
        ["nID"]=11,
        ["nType"]=2,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffhuifu2.png",
        ["nPriority"]=6
    },
    [12]=
    {
        ["nID"]=12,
        ["nType"]=2,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffyisu2.png",
        ["nPriority"]=7
    },
    [13]=
    {
        ["nID"]=13,
        ["nType"]=1,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffmiankong1.png",
        ["nPriority"]=6
    },
    [14]=
    {
        ["nID"]=14,
        ["nType"]=1,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffliuxue1.png",
        ["nPriority"]=7
    },
    [15]=
    {
        ["nID"]=15,
        ["nType"]=2,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffliuxue2.png",
        ["nPriority"]=8
    },
    [16]=
    {
        ["nID"]=16,
        ["nType"]=1,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffchengmo1.png",
        ["nPriority"]=8
    },
    [17]=
    {
        ["nID"]=17,
        ["nType"]=1,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffjiaoxie1.png",
        ["nPriority"]=9
    },
    [18]=
    {
        ["nID"]=18,
        ["nType"]=1,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffshouna1.png",
        ["nPriority"]=10
    },
    [19]=
    {
        ["nID"]=19,
        ["nType"]=1,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffweixiezhi1.png",
        ["nPriority"]=11
    },
    [20]=
    {
        ["nID"]=20,
        ["nType"]=1,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffweixiezhi2.png",
        ["nPriority"]=12
    },
    [21]=
    {
        ["nID"]=21,
        ["nType"]=1,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffweixiezhi3.png",
        ["nPriority"]=13
    },
    [22]=
    {
        ["nID"]=22,
        ["nType"]=2,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffchaofeng.png",
        ["nPriority"]=9
    },
    [23]=
    {
        ["nID"]=23,
        ["nType"]=2,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffdaodi.png",
        ["nPriority"]=10
    },
    [24]=
    {
        ["nID"]=24,
        ["nType"]=2,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffxuanyun.png",
        ["nPriority"]=11
    },
    [25]=
    {
        ["nID"]=25,
        ["nType"]=2,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffdingshen.png",
        ["nPriority"]=12
    },
    [26]=
    {
        ["nID"]=26,
        ["nType"]=2,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffhuifu3.png",
        ["nPriority"]=13
    },
    [27]=
    {
        ["nID"]=27,
        ["nType"]=2,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffchenmo4.png",
        ["nPriority"]=14
    },
    [28]=
    {
        ["nID"]=28,
        ["nType"]=2,
        ["szFrame"]="UIAtlas2_MainCity_MainCitySkill1_Buffchenmo5.png",
        ["nPriority"]=15
    }
}
