--*************************************** 工具生成 ***************************************
UIBubbleMsgTab = 
{
    ["guild"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="guild",
        ["szTitle"]="帮会领地",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=true,
        ["szBarTitle"]="%d秒后传送出帮会领地",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["YuanXiao"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="",
        ["szType"]="YuanXiao",
        ["szTitle"]="元宵主界面",
        ["bMultiMsg"]=false,
        ["nPriority"]=210,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn28.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["tong_dif"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="tong_dif",
        ["szTitle"]="帮会秘境",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=true,
        ["szBarTitle"]="%d秒后传送出副本",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["AddLikeTip"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04",
        ["szType"]="AddLikeTip",
        ["szTitle"]="点赞",
        ["bMultiMsg"]=false,
        ["nPriority"]=110,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn16.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["ArenaBonus"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="",
        ["szType"]="ArenaBonus",
        ["szTitle"]="群英赛",
        ["bMultiMsg"]=false,
        ["nPriority"]=210,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn29.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["RoomInvite"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="RoomInvite",
        ["szTitle"]="房间邀请",
        ["bMultiMsg"]=false,
        ["nPriority"]=110,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn17.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["TeamInvite"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="TeamInvite",
        ["szTitle"]="组队邀请",
        ["bMultiMsg"]=false,
        ["nPriority"]=110,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn15.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["party_copy"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="party_copy",
        ["szTitle"]="队伍副本",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=true,
        ["szBarTitle"]="%d秒后传送出副本",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["CameraTrace"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn1.png",
        ["szType"]="CameraTrace",
        ["szTitle"]="云图拍照追踪",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn1.png",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=true
    },
    ["DungeonLive"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="DungeonLive",
        ["szTitle"]="副本观战观众管理",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="点击管理观战列表",
        ["szShortTitle"]="观众管理",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn30.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["NewMailTips"]=
    {
        ["szDesc"]="代码特殊显示规则，更改文本需找程序",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_02.png",
        ["szType"]="NewMailTips",
        ["szTitle"]="你有(<D0>/<D1>)封未读书信。",
        ["bMultiMsg"]=false,
        ["nPriority"]=20,
        ["bCanRemove"]=true,
        ["szBarTitle"]="你有(<D0>/<D1>)封未读书信。",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["ReadMailBtn"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_14.png",
        ["szType"]="ReadMailBtn",
        ["szTitle"]="门内传信",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn22.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["TongWhisper"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="TongWhisper",
        ["szTitle"]="帮会通知发送中",
        ["bMultiMsg"]=false,
        ["nPriority"]=100,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["MapQueueTips"]=
    {
        ["szDesc"]="代码特殊显示规则，更改文本需找程序",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_11.png",
        ["szType"]="MapQueueTips",
        ["szTitle"]="地图排队中",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="地图排队中(%d)",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn18.png",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["refresh_copy"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="refresh_copy",
        ["szTitle"]="副本重置",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=true,
        ["szBarTitle"]="%d秒后传送出副本",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["AddFeudInvite"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_01.png",
        ["szType"]="AddFeudInvite",
        ["szTitle"]="宿敌模式申请",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["AdventureTips"]=
    {
        ["szDesc"]="代码特殊显示规则，更改文本需找程序",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="AdventureTips",
        ["szTitle"]="奇遇",
        ["bMultiMsg"]=false,
        ["nPriority"]=10,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn8.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo2",
        ["bShowMainCityIcon"]=true
    },
    ["NewAddFoeTips"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_01.png",
        ["szType"]="NewAddFoeTips",
        ["szTitle"]="你有待处理的敌对消息。",
        ["bMultiMsg"]=false,
        ["nPriority"]=20,
        ["bCanRemove"]=true,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["NewMentorTips"]=
    {
        ["szDesc"]="显示内容根据事件传来的文本决定",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="NewMentorTips",
        ["szTitle"]="师徒消息",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=true,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["QueryEvokeTip"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_01.png",
        ["szType"]="QueryEvokeTip",
        ["szTitle"]="召唤请求",
        ["bMultiMsg"]=true,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="召唤请求",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["TongDiplomacy"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="TongDiplomacy",
        ["szTitle"]="帮会外交",
        ["bMultiMsg"]=false,
        ["nPriority"]=110,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn5.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["TongVoiceRoom"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="",
        ["szType"]="TongVoiceRoom",
        ["szTitle"]="帮会语音频道有帮众小聚，是否前往参与？",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="是否前往参与",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["ArenaInviteTip"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_01.png",
        ["szType"]="ArenaInviteTip",
        ["szTitle"]="邀请加入名剑队申请",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["ArenaQueueTips"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="ArenaQueueTips",
        ["szTitle"]="名剑大会排队中",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn6.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["ArtistGiftTips"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="ArtistGiftTips",
        ["szTitle"]="礼物信息",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["AuctionOpening"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="AuctionOpening",
        ["szTitle"]="掉落分配",
        ["bMultiMsg"]=false,
        ["nPriority"]=100,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn13.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["ChargeTimeTips"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="ChargeTimeTips",
        ["szTitle"]="试玩结束",
        ["bMultiMsg"]=false,
        ["nPriority"]=120,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="试玩结束",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn19.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["InteractInvite"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04",
        ["szType"]="InteractInvite",
        ["szTitle"]="交互邀请",
        ["bMultiMsg"]=false,
        ["nPriority"]=110,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn14.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["OpenLiveNotify"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="OpenLiveNotify",
        ["szTitle"]="开启直播",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="点击开启直播",
        ["szShortTitle"]="开启直播",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn32.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["PartnerMessage"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="PartnerMessage",
        ["szTitle"]="侠客邀约",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["SpringFestival"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="",
        ["szType"]="SpringFestival",
        ["szTitle"]="春节主界面",
        ["bMultiMsg"]=false,
        ["nPriority"]=210,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn27.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["TongInviteTips"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="TongInviteTips",
        ["szTitle"]="邀请入帮",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="邀请入帮",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["TradeInviteTip"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_01.png",
        ["szType"]="TradeInviteTip",
        ["szTitle"]="交易邀请",
        ["bMultiMsg"]=false,
        ["nPriority"]=110,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn14.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["AppointmentTips"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn20.png",
        ["szType"]="AppointmentTips",
        ["szTitle"]="地图排队预约",
        ["bMultiMsg"]=false,
        ["nPriority"]=100,
        ["bCanRemove"]=false,
        ["szBarTitle"]="预约中",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn20.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["BiaoShiInfoTips"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="BiaoShiInfoTips",
        ["szTitle"]="护镖信息",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["BiaoShiListTips"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="BiaoShiListTips",
        ["szTitle"]="我的镖师",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["ChatMonitorTips"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_15.png",
        ["szType"]="ChatMonitorTips",
        ["szTitle"]="聊天监控",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn23.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["CommandBaseData"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn21.png",
        ["szType"]="CommandBaseData",
        ["szTitle"]="阵营管理",
        ["bMultiMsg"]=false,
        ["nPriority"]=100,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn21.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["ExtractTeachBox"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_safe.png",
        ["szType"]="ExtractTeachBox",
        ["szTitle"]="寻宝模式教学",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn25.png",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=true
    },
    ["MentorInviteTip"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_01.png",
        ["szType"]="MentorInviteTip",
        ["szTitle"]="拜师申请",
        ["bMultiMsg"]=true,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="拜师申请",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["PKDuelInviteTip"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_01.png",
        ["szType"]="PKDuelInviteTip",
        ["szTitle"]="切磋邀请",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["PakDownloadTips"]=
    {
        ["szDesc"]="代码特殊显示规则，更改文本需找程序",
        ["szIcon"]="UIAtlas2_Public_PublicButton_PublicButton1_BtnEdit.png",
        ["szType"]="PakDownloadTips",
        ["szTitle"]="扩展资源下载中 or 扩展资源下载暂停",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["AccountException"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn26.png",
        ["szType"]="AccountException",
        ["szTitle"]="角色异常行为解除",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn26.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["BiaoshiTradeTips"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_01.png",
        ["szType"]="BiaoshiTradeTips",
        ["szTitle"]="镖师邀请",
        ["bMultiMsg"]=true,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["CloseCampModeTip"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="CloseCampModeTip",
        ["szTitle"]="关闭阵营模式",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="关闭阵营模式",
        ["szMainCityIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mzhenying1.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["DungeonStoryMode"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_01.png",
        ["szType"]="DungeonStoryMode",
        ["szTitle"]="单人模式",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="已开启单人模式",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn12.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["HorseFullMeasure"]=
    {
        ["szDesc"]="代码特殊显示规则，更改文本需找程序",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_13.png",
        ["szType"]="HorseFullMeasure",
        ["szTitle"]="坐骑饥饿，移速降低",
        ["bMultiMsg"]=false,
        ["nPriority"]=200,
        ["bCanRemove"]=false,
        ["szBarTitle"]="坐骑饥饿，移速降低",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_13.png",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["BiaoshiInviteTips"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_01.png",
        ["szType"]="BiaoshiInviteTips",
        ["szTitle"]="镖师申请",
        ["bMultiMsg"]=true,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["PVPFieldMapButton"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_01.png",
        ["szType"]="PVPFieldMapButton",
        ["szTitle"]="千里伐逐",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn9.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["ApprenticeInviteTip"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_01.png",
        ["szType"]="ApprenticeInviteTip",
        ["szTitle"]="收徒申请",
        ["bMultiMsg"]=true,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="收徒申请",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["LockTransactionTips"]=
    {
        ["szDesc"]="代码特殊显示规则，更改文本需找程序",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_safe.png",
        ["szType"]="LockTransactionTips",
        ["szTitle"]="交易锁定",
        ["bMultiMsg"]=false,
        ["nPriority"]=9,
        ["bCanRemove"]=false,
        ["szBarTitle"]="交易已锁定，点击解除",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn24.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo3",
        ["bShowMainCityIcon"]=false
    },
    ["OnAdvancedActiveTip"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="OnAdvancedActiveTip",
        ["szTitle"]="活动即将开启",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=true,
        ["szBarTitle"]="活动即将开启",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["PVPMatchSuccessTips"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="PVPMatchSuccessTips",
        ["szTitle"]="PVP玩法匹配成功",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="匹配成功",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn6.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["SpecialDiscountTips"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="SpecialDiscountTips",
        ["szTitle"]="直升满级",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["BattleFieldQueueTips"]=
    {
        ["szDesc"]="代码特殊显示规则，更改文本需找程序",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="BattleFieldQueueTips",
        ["szTitle"]="szName .. \"排队中\"",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn6.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["NewAddFellowshipTips"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_01.png",
        ["szType"]="NewAddFellowshipTips",
        ["szTitle"]="你有待处理的好友消息。",
        ["bMultiMsg"]=false,
        ["nPriority"]=20,
        ["bCanRemove"]=true,
        ["szBarTitle"]="",
        ["szShortTitle"]="好友申请",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["PVPFieldMapQueueTips"]=
    {
        ["szDesc"]="代码特殊显示规则，更改文本需找程序",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_11.png",
        ["szType"]="PVPFieldMapQueueTips",
        ["szTitle"]="跨服排队中",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="跨服排队中(%d)",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn18.png",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["CommandAuctionOpening"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="CommandAuctionOpening",
        ["szTitle"]="阵营拍卖",
        ["bMultiMsg"]=false,
        ["nPriority"]=100,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn7.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["TeamBuildingApplyTips"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="TeamBuildingApplyTips",
        ["szTitle"]="招募入队申请",
        ["bMultiMsg"]=false,
        ["nPriority"]=60,
        ["bCanRemove"]=true,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["ActivityAuctionOpening"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="ActivityAuctionOpening",
        ["szTitle"]="活动拍卖",
        ["bMultiMsg"]=false,
        ["nPriority"]=100,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn7.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["EquipDurabilityWarning"]=
    {
        ["szDesc"]="代码特殊显示规则，更改文本需找程序",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_03.png",
        ["szType"]="EquipDurabilityWarning",
        ["szTitle"]="%s%s已损坏 or 即将损坏",
        ["bMultiMsg"]=false,
        ["nPriority"]=20,
        ["bCanRemove"]=true,
        ["szBarTitle"]="%s%s已损坏 or 即将损坏",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=false
    },
    ["AIBodyGenerateWatingTips"]=
    {
        ["szDesc"]="代码特殊显示规则，更改文本需找程序",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="AIBodyGenerateWatingTips",
        ["szTitle"]="动捕生成中",
        ["bMultiMsg"]=false,
        ["nPriority"]=100,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn31.png",
        ["szImgBubbleList"]="",
        ["bShowMainCityIcon"]=true
    },
    ["ShowDungeonExcellentCard"]=
    {
        ["szDesc"]="越小优先级越低",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04",
        ["szType"]="ShowDungeonExcellentCard",
        ["szTitle"]="本场优秀表现",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=true,
        ["szBarTitle"]="点击查看本场优秀表现",
        ["szShortTitle"]="优秀表现",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn16.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    },
    ["TongBattleFieldQueueTips"]=
    {
        ["szDesc"]="代码特殊显示规则，更改文本需找程序",
        ["szIcon"]="UIAtlas2_MainCity_BubbleInfomation_icon_04.png",
        ["szType"]="TongBattleFieldQueueTips",
        ["szTitle"]="szName .. \"排队中\"",
        ["bMultiMsg"]=false,
        ["nPriority"]=90,
        ["bCanRemove"]=false,
        ["szBarTitle"]="",
        ["szShortTitle"]="",
        ["szMainCityIcon"]="UIAtlas2_MainCity_MainCity1_icon_Btn6.png",
        ["szImgBubbleList"]="UIAtlas2_MainCity_MainCity1_Bginfo",
        ["bShowMainCityIcon"]=true
    }
}
