--*************************************** 工具生成 ***************************************
UIChatTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["szName"]="全部",
        ["bEmptyCheck"]=false,
        ["szEmptyDesc"]="",
        ["szUIChannel"]="UI_Channel_All",
        ["tbRedPoints"]=
        {

        },
        ["nContentType"]=1,
        ["nMaxCacheCount"]=200,
        ["szEmptyBtnText"]="",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_12.png"
    },
    [2]=
    {
        ["nID"]=2,
        ["szName"]="常用",
        ["bEmptyCheck"]=false,
        ["szEmptyDesc"]="",
        ["szUIChannel"]="UI_Channel_Common",
        ["tbRedPoints"]=
        {

        },
        ["nContentType"]=1,
        ["nMaxCacheCount"]=100,
        ["szEmptyBtnText"]="",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_08.png"
    },
    [3]=
    {
        ["nID"]=3,
        ["szName"]="密聊",
        ["bEmptyCheck"]=false,
        ["szEmptyDesc"]="",
        ["szUIChannel"]="UI_Channel_Whisper",
        ["tbRedPoints"]=
        {
            [1]=2,
            [2]=4
        },
        ["nContentType"]=2,
        ["nMaxCacheCount"]=100,
        ["szEmptyBtnText"]="",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_08.png"
    },
    [4]=
    {
        ["nID"]=4,
        ["szName"]="侠缘",
        ["bEmptyCheck"]=false,
        ["szEmptyDesc"]="",
        ["szUIChannel"]="UI_Channel_AINpc",
        ["tbRedPoints"]=
        {
            [1]=7
        },
        ["nContentType"]=2,
        ["nMaxCacheCount"]=100,
        ["szEmptyBtnText"]="",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_08.png"
    },
    [5]=
    {
        ["nID"]=5,
        ["szName"]="队伍",
        ["bEmptyCheck"]=true,
        ["szEmptyDesc"]="尚未加入队伍",
        ["szUIChannel"]="UI_Channel_Team",
        ["tbRedPoints"]=
        {
            [1]=5
        },
        ["nContentType"]=1,
        ["nMaxCacheCount"]=100,
        ["szEmptyBtnText"]="加入队伍",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_10.png"
    },
    [6]=
    {
        ["nID"]=6,
        ["szName"]="帮会",
        ["bEmptyCheck"]=true,
        ["szEmptyDesc"]="暂无帮会，请前往加入帮会",
        ["szUIChannel"]="UI_Channel_Tong",
        ["tbRedPoints"]=
        {
            [1]=6
        },
        ["nContentType"]=1,
        ["nMaxCacheCount"]=100,
        ["szEmptyBtnText"]="加入帮会",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_05.png"
    },
    [7]=
    {
        ["nID"]=7,
        ["szName"]="阵营",
        ["bEmptyCheck"]=true,
        ["szEmptyDesc"]="尚未加入阵营，请前往加入阵营",
        ["szUIChannel"]="UI_Channel_Camp",
        ["tbRedPoints"]=
        {

        },
        ["nContentType"]=1,
        ["nMaxCacheCount"]=100,
        ["szEmptyBtnText"]="加入阵营",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_04.png"
    },
    [8]=
    {
        ["nID"]=8,
        ["szName"]="萌新",
        ["bEmptyCheck"]=false,
        ["szEmptyDesc"]="",
        ["szUIChannel"]="UI_Channel_Identity",
        ["tbRedPoints"]=
        {

        },
        ["nContentType"]=1,
        ["nMaxCacheCount"]=100,
        ["szEmptyBtnText"]="",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_17.png"
    },
    [9]=
    {
        ["nID"]=9,
        ["szName"]="地图",
        ["bEmptyCheck"]=false,
        ["szEmptyDesc"]="",
        ["szUIChannel"]="UI_Channel_SENCE",
        ["tbRedPoints"]=
        {

        },
        ["nContentType"]=1,
        ["nMaxCacheCount"]=100,
        ["szEmptyBtnText"]="",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_17.png"
    },
    [10]=
    {
        ["nID"]=10,
        ["szName"]="门派",
        ["bEmptyCheck"]=false,
        ["szEmptyDesc"]="",
        ["szUIChannel"]="UI_Channel_Force",
        ["tbRedPoints"]=
        {

        },
        ["nContentType"]=1,
        ["nMaxCacheCount"]=100,
        ["szEmptyBtnText"]="",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_06.png"
    },
    [11]=
    {
        ["nID"]=11,
        ["szName"]="其他",
        ["bEmptyCheck"]=false,
        ["szEmptyDesc"]="",
        ["szUIChannel"]="UI_Channel_Other",
        ["tbRedPoints"]=
        {

        },
        ["nContentType"]=1,
        ["nMaxCacheCount"]=100,
        ["szEmptyBtnText"]="120",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_11.png"
    },
    [12]=
    {
        ["nID"]=12,
        ["szName"]="系统",
        ["bEmptyCheck"]=false,
        ["szEmptyDesc"]="",
        ["szUIChannel"]="UI_Channel_System",
        ["tbRedPoints"]=
        {

        },
        ["nContentType"]=3,
        ["nMaxCacheCount"]=100,
        ["szEmptyBtnText"]="",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_02.png"
    },
    [13]=
    {
        ["nID"]=13,
        ["szName"]="战斗",
        ["bEmptyCheck"]=false,
        ["szEmptyDesc"]="",
        ["szUIChannel"]="UI_Channel_Fight",
        ["tbRedPoints"]=
        {

        },
        ["nContentType"]=3,
        ["nMaxCacheCount"]=200,
        ["szEmptyBtnText"]="",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_20.png"
    }
}
