--*************************************** 工具生成 ***************************************
UIDialogueColorTab = 
{
    [1]=
    {
        ["Color"]="#E2F6FB",
        ["FontID"]=1
    },
    [7]=
    {
        ["Color"]="#E2F6FB",
        ["FontID"]=7
    },
    [12]=
    {
        ["Color"]="#FF7676",
        ["FontID"]=12
    },
    [15]=
    {
        ["Color"]="#E2F6FB",
        ["FontID"]=15
    },
    [18]=
    {
        ["Color"]="#E2F6FB",
        ["FontID"]=18
    },
    [27]=
    {
        ["Color"]="#FFE26E",
        ["FontID"]=27
    },
    [31]=
    {
        ["Color"]="#FFE26E",
        ["FontID"]=31
    },
    [32]=
    {
        ["Color"]="#FFE26E",
        ["FontID"]=32
    },
    [65]=
    {
        ["Color"]="#FFEA88",
        ["FontID"]=65
    },
    [67]=
    {
        ["Color"]="#FFE26E",
        ["FontID"]=67
    },
    [68]=
    {
        ["Color"]="#FFE26E",
        ["FontID"]=68
    },
    [74]=
    {
        ["Color"]="#F2B4FF",
        ["FontID"]=74
    },
    [75]=
    {
        ["Color"]="#F2B4FF",
        ["FontID"]=75
    },
    [77]=
    {
        ["Color"]="#89DFFF",
        ["FontID"]=77
    },
    [80]=
    {
        ["Color"]="#79EAB4",
        ["FontID"]=80
    },
    [81]=
    {
        ["Color"]="#79EAB4",
        ["FontID"]=81
    },
    [82]=
    {
        ["Color"]="#FFE26E",
        ["FontID"]=82
    },
    [100]=
    {
        ["Color"]="#FFE26E",
        ["FontID"]=100
    },
    [101]=
    {
        ["Color"]="#FFE26E",
        ["FontID"]=101
    },
    [102]=
    {
        ["Color"]="FF7676",
        ["FontID"]=102
    },
    [103]=
    {
        ["Color"]="BE85FF",
        ["FontID"]=103
    },
    [104]=
    {
        ["Color"]="5B99FF",
        ["FontID"]=104
    },
    [105]=
    {
        ["Color"]="#9DFFA6",
        ["FontID"]=105
    },
    [106]=
    {
        ["Color"]="#E2F6FB",
        ["FontID"]=106
    },
    [107]=
    {
        ["Color"]="6A8695",
        ["FontID"]=107
    },
    [108]=
    {
        ["Color"]="86AEB4",
        ["FontID"]=108
    },
    [109]=
    {
        ["Color"]="AED9E0",
        ["FontID"]=109
    },
    [110]=
    {
        ["Color"]="D7F6FF",
        ["FontID"]=110
    },
    [111]=
    {
        ["Color"]="FFC2C2",
        ["FontID"]=111
    },
    [112]=
    {
        ["Color"]="D3AFFF",
        ["FontID"]=112
    },
    [113]=
    {
        ["Color"]="97C1FF",
        ["FontID"]=113
    },
    [138]=
    {
        ["Color"]="#79EAB4",
        ["FontID"]=138
    },
    [158]=
    {
        ["Color"]="#FFE26E",
        ["FontID"]=158
    },
    [160]=
    {
        ["Color"]="#E2F6FB",
        ["FontID"]=160
    },
    [161]=
    {
        ["Color"]="#6C8D9B",
        ["FontID"]=161
    },
    [162]=
    {
        ["Color"]="#E2F6FB",
        ["FontID"]=162
    },
    [164]=
    {
        ["Color"]="#FFE26E",
        ["FontID"]=164
    },
    [166]=
    {
        ["Color"]="#FF7676",
        ["FontID"]=166
    },
    [167]=
    {
        ["Color"]="#79EAB4",
        ["FontID"]=167
    },
    [168]=
    {
        ["Color"]="#FFE26E",
        ["FontID"]=168
    },
    [171]=
    {
        ["Color"]="#89DFFF",
        ["FontID"]=171
    },
    [172]=
    {
        ["Color"]="#FF7676",
        ["FontID"]=172
    },
    [173]=
    {
        ["Color"]="#79EAB4",
        ["FontID"]=173
    },
    [174]=
    {
        ["Color"]="#B6D4DC",
        ["FontID"]=174
    },
    [181]=
    {
        ["Color"]="#F2B4FF",
        ["FontID"]=181
    },
    [186]=
    {
        ["Color"]="#79EAB4",
        ["FontID"]=186
    },
    [202]=
    {
        ["Color"]="#89DFFF",
        ["FontID"]=202
    },
    [226]=
    {
        ["Color"]="#79EAB4",
        ["FontID"]=226
    },
    [229]=
    {
        ["Color"]="#79EAB4",
        ["FontID"]=229
    },
    [284]=
    {
        ["Color"]="#E2F6FB",
        ["FontID"]=284
    },
    [286]=
    {
        ["Color"]="#F2B4FF",
        ["FontID"]=286
    },
    [295]=
    {
        ["Color"]="#FFE26E",
        ["FontID"]=295
    },
    [406]=
    {
        ["Color"]="#D7F6FF",
        ["FontID"]=406
    },
    [414]=
    {
        ["Color"]="#FFEA88",
        ["FontID"]=414
    },
    [415]=
    {
        ["Color"]="#FFEA88",
        ["FontID"]=415
    }
}
