--*************************************** 工具生成 ***************************************
UIGamepadInteractionTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["VKey"]="OPTIONS",
        ["szDef"]="EnterCursor",
        ["szName"]="进入光标模式",
        ["nMaxKeyLen"]=0,
        ["nModeState"]=1,
        ["szModeFunc"]="SwitchMoveMode"
    },
    [2]=
    {
        ["nID"]=2,
        ["VKey"]="OPTIONS",
        ["szDef"]="ExitCursor",
        ["szName"]="退出光标模式",
        ["nMaxKeyLen"]=0,
        ["nModeState"]=2,
        ["szModeFunc"]="SwitchMoveMode"
    },
    [3]=
    {
        ["nID"]=3,
        ["VKey"]="A",
        ["szDef"]="CursorClick",
        ["szName"]="光标模式·确认",
        ["nMaxKeyLen"]=0,
        ["nModeState"]=2,
        ["szModeFunc"]="CursorClick"
    },
    [4]=
    {
        ["nID"]=4,
        ["VKey"]="B",
        ["szDef"]="CursorEsc",
        ["szName"]="光标模式·返回",
        ["nMaxKeyLen"]=0,
        ["nModeState"]=2,
        ["szModeFunc"]="CursorEsc"
    },
    [5]=
    {
        ["nID"]=5,
        ["VKey"]="DPAD_UP",
        ["szDef"]="CursorWheelUp",
        ["szName"]="光标模式·上滚",
        ["nMaxKeyLen"]=0,
        ["nModeState"]=2,
        ["szModeFunc"]="MouseWheelUp"
    },
    [6]=
    {
        ["nID"]=6,
        ["VKey"]="DPAD_DOWN",
        ["szDef"]="CursorWheelDown",
        ["szName"]="光标模式·下滚",
        ["nMaxKeyLen"]=0,
        ["nModeState"]=2,
        ["szModeFunc"]="MouseWheelDown"
    },
    [7]=
    {
        ["nID"]=7,
        ["VKey"]="MENU",
        ["szDef"]="SwitchSkill",
        ["szName"]="切换技能栏",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="SwitchSkill"
    },
    [8]=
    {
        ["nID"]=8,
        ["VKey"]="A",
        ["szDef"]="FuncSlot1",
        ["szName"]="槽位1",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="FuncSlot_1"
    },
    [9]=
    {
        ["nID"]=9,
        ["VKey"]="L_TRIGGER+X",
        ["szDef"]="FuncSlot2",
        ["szName"]="槽位2",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="FuncSlot_2"
    },
    [10]=
    {
        ["nID"]=10,
        ["VKey"]="L_TRIGGER+Y",
        ["szDef"]="FuncSlot3",
        ["szName"]="槽位3",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="FuncSlot_3"
    },
    [11]=
    {
        ["nID"]=11,
        ["VKey"]="X",
        ["szDef"]="FuncSlot4",
        ["szName"]="槽位4",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="FuncSlot_4"
    },
    [12]=
    {
        ["nID"]=12,
        ["VKey"]="Y",
        ["szDef"]="FuncSlot5",
        ["szName"]="槽位5",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="FuncSlot_5"
    },
    [13]=
    {
        ["nID"]=13,
        ["VKey"]="L_TRIGGER+A",
        ["szDef"]="FuncSlot6",
        ["szName"]="槽位6",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="FuncSlot_6"
    },
    [14]=
    {
        ["nID"]=14,
        ["VKey"]="DPAD_LEFT",
        ["szDef"]="SkillQuick",
        ["szName"]="特殊道具/团队标记",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="SkillQuick"
    },
    [15]=
    {
        ["nID"]=15,
        ["VKey"]="B",
        ["szDef"]="Jump",
        ["szName"]="跳跃",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="Jump"
    },
    [16]=
    {
        ["nID"]=16,
        ["VKey"]="L_TRIGGER+B",
        ["szDef"]="FuYao",
        ["szName"]="扶摇",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="FuYao"
    },
    [17]=
    {
        ["nID"]=17,
        ["VKey"]="R_SHOULDER",
        ["szDef"]="NieYun",
        ["szName"]="蹑云逐月/前飘",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="NieYun"
    },
    [18]=
    {
        ["nID"]=18,
        ["VKey"]="L_TRIGGER+R_SHOULDER",
        ["szDef"]="SpecialSprint",
        ["szName"]="门派轻功",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="QingGong"
    },
    [19]=
    {
        ["nID"]=19,
        ["VKey"]="L_SHOULDER",
        ["szDef"]="SelectTarget",
        ["szName"]="选择目标",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="SelectTarget"
    },
    [20]=
    {
        ["nID"]=20,
        ["VKey"]="R_TRIGGER+L_SHOULDER",
        ["szDef"]="LockTarget",
        ["szName"]="目标锁定",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="Attention"
    },
    [21]=
    {
        ["nID"]=21,
        ["VKey"]="DPAD_UP",
        ["szDef"]="SkillAuto",
        ["szName"]="武学助手",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="SkillAuto"
    },
    [22]=
    {
        ["nID"]=22,
        ["VKey"]="DPAD_DOWN",
        ["szDef"]="Interaction",
        ["szName"]="功能互动键",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="FInteract"
    },
    [23]=
    {
        ["nID"]=23,
        ["VKey"]="DPAD_RIGHT",
        ["szDef"]="ALLPicker",
        ["szName"]="全部拾取",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="ALLPicker"
    },
    [24]=
    {
        ["nID"]=24,
        ["VKey"]="L_TRIGGER+L_SHOULDER",
        ["szDef"]="FuncSlot11",
        ["szName"]="动态快捷栏额外槽位",
        ["nMaxKeyLen"]=2,
        ["nModeState"]=1,
        ["szModeFunc"]="FuncSlot_11"
    }
}
