--*************************************** 工具生成 ***************************************
UIMainCityLeftBottomTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["szDesc"]="寻宝",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mxunbao",
        ["nVIewID"]=0,
        ["szAction"]="APIHelper.TreasureHunting(true)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="寻宝",
        ["szIcon_mutex"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mxunbao",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=true,
        ["szAction_mutex"]="APIHelper.TreasureHunting(false)",
        ["tbUpdateEvents"]=
        {
            [1]="OnTreasureHuntingDisplayChanged"
        },
        ["szMutexCheckFun"]="APIHelper.TreasureHuntingCheck()",
        ["szLabelName_mutex"]="寻宝"
    },
    [2]=
    {
        ["nID"]=2,
        ["szDesc"]="自绝经脉",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mjingmai",
        ["nVIewID"]=0,
        ["szAction"]="SkillData.CastSkill(g_pClientPlayer, 608, nil, 1)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="自绝",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [3]=
    {
        ["nID"]=3,
        ["szDesc"]="摆擂",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mbailei",
        ["nVIewID"]=0,
        ["szAction"]="APIHelper.OpenChallenge()",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="摆擂",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [4]=
    {
        ["nID"]=4,
        ["szDesc"]="阵营模式",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mzhenying",
        ["nVIewID"]=0,
        ["szAction"]="APIHelper.OpenCloseCamp()",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="阵营",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [5]=
    {
        ["nID"]=5,
        ["szDesc"]="召请侠客",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mxiake",
        ["nVIewID"]=0,
        ["szAction"]="Event.Dispatch(EventType.OpenPartnerSummonPanelForSummon)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="召请",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [6]=
    {
        ["nID"]=6,
        ["szDesc"]="显示共鸣",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mgongming",
        ["nVIewID"]=0,
        ["szAction"]="Event.Dispatch(EventType.ShowPartnerMorph)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="共鸣",
        ["szIcon_mutex"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mgongming1",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=true,
        ["szAction_mutex"]="Event.Dispatch(EventType.HidePartnerMorph)",
        ["tbUpdateEvents"]=
        {
            [1]="OnPartnerMorphChanged"
        },
        ["szMutexCheckFun"]="APIHelper.PartnerMorphCheck()",
        ["szLabelName_mutex"]="共鸣"
    },
    [7]=
    {
        ["nID"]=7,
        ["szDesc"]="战斗数据",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mzhandou",
        ["nVIewID"]=0,
        ["szAction"]="Event.Dispatch(EventType.SwitchStatistVisibility)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="数据",
        ["szIcon_mutex"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mzhandou",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=true,
        ["szAction_mutex"]="Event.Dispatch(EventType.SwitchStatistVisibility)",
        ["tbUpdateEvents"]=
        {
            [1]="OnStatistVisibilityChanged"
        },
        ["szMutexCheckFun"]="APIHelper.StatistVisibilityCheck()",
        ["szLabelName_mutex"]="数据"
    },
    [8]=
    {
        ["nID"]=8,
        ["szDesc"]="套马",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mxunbao",
        ["nVIewID"]=0,
        ["szAction"]="SkillData.CastSkill(g_pClientPlayer, 23312, nil, 1)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="套马",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [9]=
    {
        ["nID"]=9,
        ["szDesc"]="隐藏界面",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mjiemian",
        ["nVIewID"]=0,
        ["szAction"]="UIHelper.EnterHideAllUIMode()",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="隐藏",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [10]=
    {
        ["nID"]=10,
        ["szDesc"]="镜头重置",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mjingtou",
        ["nVIewID"]=0,
        ["szAction"]="CameraMgr.CamaraReset()",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="镜头",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [11]=
    {
        ["nID"]=11,
        ["szDesc"]="屏蔽NPC",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mnpc",
        ["nVIewID"]=0,
        ["szAction"]="APIHelper.SetNpcDisplay()",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="NPC",
        ["szIcon_mutex"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mnpc1",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=true,
        ["szAction_mutex"]="APIHelper.SetNpcDisplay()",
        ["tbUpdateEvents"]=
        {
            [1]="OnNpcDisplayChanged"
        },
        ["szMutexCheckFun"]="APIHelper.NpcDisplayCheck()",
        ["szLabelName_mutex"]="NPC"
    },
    [12]=
    {
        ["nID"]=12,
        ["szDesc"]="屏蔽玩家",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mwanjia",
        ["nVIewID"]=0,
        ["szAction"]="APIHelper.SetPlayDisplay(GameSettingType.PlayDisplay.HideAll, true)",
        ["szCondition"]="g_pClientPlayer.nLevel >= 103",
        ["szGlobalKey"]="",
        ["szLabelName"]="玩家",
        ["szIcon_mutex"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mwanjia1",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=true,
        ["szAction_mutex"]="APIHelper.SetPlayDisplay(GameSettingType.PlayDisplay.All, true)",
        ["tbUpdateEvents"]=
        {
            [1]="OnGameSettingPlayDisplayChanged"
        },
        ["szMutexCheckFun"]="APIHelper.MainCityLeftBottomPlayDisplayCheck()",
        ["szLabelName_mutex"]="玩家"
    },
    [13]=
    {
        ["nID"]=13,
        ["szDesc"]="召唤宠物",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mchongwu",
        ["nVIewID"]=0,
        ["szAction"]="APIHelper.FellowPet(true)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="宠物",
        ["szIcon_mutex"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mchongwu1",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=true,
        ["szAction_mutex"]="APIHelper.FellowPet(false)",
        ["tbUpdateEvents"]=
        {
            [1]="OnFellowPetChanged"
        },
        ["szMutexCheckFun"]="APIHelper.PetCheck()",
        ["szLabelName_mutex"]="宠物"
    },
    [14]=
    {
        ["nID"]=14,
        ["szDesc"]="切换走路",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mzoulu",
        ["nVIewID"]=0,
        ["szAction"]="APIHelper.SwitchWalk()",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="走路",
        ["szIcon_mutex"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mzoulu",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=true,
        ["szAction_mutex"]="APIHelper.SwitchWalk()",
        ["tbUpdateEvents"]=
        {
            [1]="OnWalkModeChanged"
        },
        ["szMutexCheckFun"]="APIHelper.WalkModeCheck()",
        ["szLabelName_mutex"]="跑步"
    },
    [15]=
    {
        ["nID"]=15,
        ["szDesc"]="拍照",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mpaizhao",
        ["nVIewID"]=0,
        ["szAction"]="Event.Dispatch(EventType.OpenCameraPanel)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="拍照",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [16]=
    {
        ["nID"]=16,
        ["szDesc"]="表情动作",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_MBiaoqing",
        ["nVIewID"]=0,
        ["szAction"]="UIMgr.OpenSingle(true, VIEW_ID.PanelQuickOperation, 2)",
        ["szCondition"]="g_pClientPlayer.nLevel >= 103",
        ["szGlobalKey"]="",
        ["szLabelName"]="表情",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [17]=
    {
        ["nID"]=17,
        ["szDesc"]="切换外装预设",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mwaiguan",
        ["nVIewID"]=0,
        ["szAction"]="APIHelper.ChangeOutfit()",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="外装",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [18]=
    {
        ["nID"]=18,
        ["szDesc"]="同模",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mtongmo1",
        ["nVIewID"]=0,
        ["szAction"]="ToggleUniform(true)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="同模",
        ["szIcon_mutex"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mtongmo",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=true,
        ["szAction_mutex"]="ToggleUniform(false)",
        ["tbUpdateEvents"]=
        {
            [1]="OnCampUniformChanged"
        },
        ["szMutexCheckFun"]="APIHelper.CampUniformCheck()",
        ["szLabelName_mutex"]="同模"
    },
    [19]=
    {
        ["nID"]=19,
        ["szDesc"]="轻功",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mqinggong1",
        ["nVIewID"]=0,
        ["szAction"]="APIHelper.SwitchQingGong()",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="轻功",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="OnLeftBottomSprintChange",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {
            [1]="OnQingGongModeChanged"
        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]="轻功"
    },
    [20]=
    {
        ["nID"]=20,
        ["szDesc"]="暗器",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Manqi",
        ["nVIewID"]=0,
        ["szAction"]="SkillData.CastSkill(g_pClientPlayer, 34, nil, 1)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="暗器",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]="轻功"
    },
    [21]=
    {
        ["nID"]=21,
        ["szDesc"]="焦点列表",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_MFocusList",
        ["nVIewID"]=0,
        ["szAction"]="Event.Dispatch(EventType.SwitchFocusVisibility)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="焦点",
        ["szIcon_mutex"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_MFocusList",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=true,
        ["szAction_mutex"]="Event.Dispatch(EventType.SwitchFocusVisibility)",
        ["tbUpdateEvents"]=
        {
            [1]="OnFocusVisibilityChanged"
        },
        ["szMutexCheckFun"]="APIHelper.FocusVisibilityCheck()",
        ["szLabelName_mutex"]="焦点"
    },
    [22]=
    {
        ["nID"]=22,
        ["szDesc"]="自动行走",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mzidongzou",
        ["nVIewID"]=0,
        ["szAction"]="FuncSlotMgr.ExecuteCommand(\"AutoForward\")",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="行走",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [23]=
    {
        ["nID"]=23,
        ["szDesc"]="侠客跟随",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mxiake4",
        ["nVIewID"]=0,
        ["szAction"]="SkillData.CastSkill(g_pClientPlayer, 31337, nil, 1)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="跟随",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [24]=
    {
        ["nID"]=24,
        ["szDesc"]="侠客攻击",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mxiake5",
        ["nVIewID"]=0,
        ["szAction"]="SkillData.CastSkill(g_pClientPlayer, 31336, nil, 1)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="攻击",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [25]=
    {
        ["nID"]=25,
        ["szDesc"]="侠客停留",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mxiake3",
        ["nVIewID"]=0,
        ["szAction"]="SkillData.CastSkill(g_pClientPlayer, 31338, nil, 1)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="停留",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [26]=
    {
        ["nID"]=26,
        ["szDesc"]="侠客开战",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mxiake7",
        ["nVIewID"]=0,
        ["szAction"]="Event.Dispatch(EventType.On_Partner_TankAttack)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="开战",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [27]=
    {
        ["nID"]=27,
        ["szDesc"]="垂钓",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mdiaoyu",
        ["nVIewID"]=0,
        ["szAction"]="SkillData.CastSkill(g_pClientPlayer, 36261, nil, 1)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="垂钓",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [28]=
    {
        ["nID"]=28,
        ["szDesc"]="风宿帷天",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mzhangpeng",
        ["nVIewID"]=0,
        ["szAction"]="SkillData.CastSkill(g_pClientPlayer, 36158, nil, 1)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="营地",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [29]=
    {
        ["nID"]=29,
        ["szDesc"]="地图成就",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mchengjiu",
        ["nVIewID"]=0,
        ["szAction"]="UIMgr.OpenSingle(true, VIEW_ID.PanelMapAchievement)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="成就",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [30]=
    {
        ["nID"]=30,
        ["szDesc"]="时光漫游",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_Mshiguang",
        ["nVIewID"]=0,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelAtmosphere)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="时光",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    },
    [31]=
    {
        ["nID"]=31,
        ["szDesc"]="五味诀",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_wuweijue",
        ["nVIewID"]=0,
        ["szAction"]="SkillData.CastSkill(g_pClientPlayer, 41154, nil, 1)",
        ["szCondition"]="",
        ["szGlobalKey"]="",
        ["szLabelName"]="五味",
        ["szIcon_mutex"]="",
        ["nVIewID_mutex"]=0,
        ["szActionEvent"]="",
        ["bHasMutexState"]=false,
        ["szAction_mutex"]="",
        ["tbUpdateEvents"]=
        {

        },
        ["szMutexCheckFun"]="",
        ["szLabelName_mutex"]=""
    }
}
