--*************************************** 工具生成 ***************************************
UIQuickMenuTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["szDesc"]="打开寻宝界面",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn8.png",
        ["szTitle"]="寻宝",
        ["nGroupID"]=3,
        ["szAction"]="PanelGM|11|22",
        ["nActionID"]=6,
        ["nOpenType"]=1,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=1,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=5,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="20",
        ["tbCheckFunc"]=
        {
            [1]="not CrossMgr.IsCrossing(nil, true)",
            [2]="not BattleFieldData.IsInTreasureBattleFieldMap(true)"
        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=25,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=true,
        ["bHavaMutexState"]=false
    },
    [2]=
    {
        ["nID"]=2,
        ["szDesc"]="自绝经脉",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn6.png",
        ["szTitle"]="自绝经脉",
        ["nGroupID"]=1,
        ["szAction"]="608",
        ["nActionID"]=2,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=2,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=6,
        ["szGroupDesc"]="常用功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [3]=
    {
        ["nID"]=3,
        ["szDesc"]="打开摆擂界面",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn14.png",
        ["szTitle"]="摆擂",
        ["nGroupID"]=3,
        ["szAction"]="PanelArenaPop",
        ["nActionID"]=3,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=3,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=11,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {
            [1]="not BattleFieldData.IsInTreasureBattleFieldMap(true)"
        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=38,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=true,
        ["bHavaMutexState"]=false
    },
    [4]=
    {
        ["nID"]=4,
        ["szDesc"]="打开勿扰界面",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn15.png",
        ["szTitle"]="勿扰选项",
        ["nGroupID"]=1,
        ["szAction"]="PanelShieldPop",
        ["nActionID"]=1,
        ["nOpenType"]=0,
        ["bIsDisplay"]=false,
        ["nLeftBtnID"]=0,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=0,
        ["szGroupDesc"]="常用功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=false,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [5]=
    {
        ["nID"]=5,
        ["szDesc"]="打开/关闭阵营模式",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn16.png",
        ["szTitle"]="阵营模式",
        ["nGroupID"]=1,
        ["szAction"]="PanelGM|11|22",
        ["nActionID"]=5,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=4,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=5,
        ["szGroupDesc"]="常用功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {
            [1]="not BattleFieldData.IsInTreasureBattleFieldMap(true)"
        },
        ["szMutexTitle"]="阵营模式",
        ["szsMutexIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn16_1.png",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=37,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=true,
        ["bHavaMutexState"]=true
    },
    [7]=
    {
        ["nID"]=7,
        ["szDesc"]="打开幻境云图",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn9.png",
        ["szTitle"]="幻境云图",
        ["nGroupID"]=1,
        ["szAction"]="OpenCameraPanel",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=false,
        ["nLeftBtnID"]=0,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=0,
        ["szGroupDesc"]="常用功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [8]=
    {
        ["nID"]=8,
        ["szDesc"]="触发事件，进而打开召请侠客界面",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_xiakeBtn1.png",
        ["szTitle"]="召请侠客",
        ["nGroupID"]=4,
        ["szAction"]="OpenPartnerSummonPanelForSummon",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=5,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=1,
        ["szGroupDesc"]="侠客功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {
            [1]="not BattleFieldData.IsInTreasureBattleFieldMap(true)"
        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=41,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [9]=
    {
        ["nID"]=9,
        ["szDesc"]="触发事件，进而打开召回侠客界面",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_xiakeBtn2.png",
        ["szTitle"]="召回侠客",
        ["nGroupID"]=4,
        ["szAction"]="OpenPartnerSummonPanelForRecall",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=0,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=2,
        ["szGroupDesc"]="侠客功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {
            [1]="not BattleFieldData.IsInTreasureBattleFieldMap(true)"
        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [10]=
    {
        ["nID"]=10,
        ["szDesc"]="施放技能，使侠客切换为跟随模式",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_xiakeBtn4.png",
        ["szTitle"]="侠客跟随",
        ["nGroupID"]=4,
        ["szAction"]="31337",
        ["nActionID"]=2,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=23,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=3,
        ["szGroupDesc"]="侠客功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [11]=
    {
        ["nID"]=11,
        ["szDesc"]="施放技能，使侠客切换为攻击模式",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_xiakeBtn5.png",
        ["szTitle"]="侠客攻击",
        ["nGroupID"]=4,
        ["szAction"]="31336",
        ["nActionID"]=2,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=24,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=5,
        ["szGroupDesc"]="侠客功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [12]=
    {
        ["nID"]=12,
        ["szDesc"]="施放技能，使侠客切换为停留模式",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_xiakeBtn3.png",
        ["szTitle"]="侠客停留",
        ["nGroupID"]=4,
        ["szAction"]="31338",
        ["nActionID"]=2,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=25,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=6,
        ["szGroupDesc"]="侠客功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [13]=
    {
        ["nID"]=13,
        ["szDesc"]="在主界面显示共鸣",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_xiakeBtn6.png",
        ["szTitle"]="显示共鸣",
        ["nGroupID"]=4,
        ["szAction"]="ShowPartnerMorph",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=6,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=7,
        ["szGroupDesc"]="侠客功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {
            [1]="not BattleFieldData.IsInTreasureBattleFieldMap(true)"
        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=42,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [14]=
    {
        ["nID"]=14,
        ["szDesc"]="在主界面隐藏共鸣",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_xiakeBtn6.png",
        ["szTitle"]="隐藏共鸣",
        ["nGroupID"]=4,
        ["szAction"]="HidePartnerMorph",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=6,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=7,
        ["szGroupDesc"]="侠客功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {
            [1]="not BattleFieldData.IsInTreasureBattleFieldMap(true)"
        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [15]=
    {
        ["nID"]=15,
        ["szDesc"]="显示/隐藏战斗统计",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn4.png",
        ["szTitle"]="战斗数据",
        ["nGroupID"]=1,
        ["szAction"]="SwitchStatistVisibility",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=7,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=9,
        ["szGroupDesc"]="常用功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=false,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=true,
        ["bHavaMutexState"]=false
    },
    [16]=
    {
        ["nID"]=16,
        ["szDesc"]="显示/隐藏焦点列表",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn34.png",
        ["szTitle"]="焦点列表",
        ["nGroupID"]=1,
        ["szAction"]="SwitchFocusVisibility",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=21,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=10,
        ["szGroupDesc"]="常用功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=false,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=true,
        ["bHavaMutexState"]=false
    },
    [17]=
    {
        ["nID"]=17,
        ["szDesc"]="显示/隐藏谁在看我",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_SeeMeBtn.png",
        ["szTitle"]="谁在看我",
        ["nGroupID"]=1,
        ["szAction"]="SwitchWhoSeeMeVisibility",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=0,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=11,
        ["szGroupDesc"]="常用功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=false,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=true,
        ["bHavaMutexState"]=false
    },
    [19]=
    {
        ["nID"]=19,
        ["szDesc"]="套马",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn13.png",
        ["szTitle"]="套马",
        ["nGroupID"]=3,
        ["szAction"]="23312",
        ["nActionID"]=2,
        ["nOpenType"]=1,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=8,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=6,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="20",
        ["tbCheckFunc"]=
        {
            [1]="not CrossMgr.IsCrossing(nil, true)",
            [2]="not BattleFieldData.IsInTreasureBattleFieldMap(true)"
        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=39,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [20]=
    {
        ["nID"]=20,
        ["szDesc"]="隐藏界面",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn7.png",
        ["szTitle"]="隐藏界面",
        ["nGroupID"]=1,
        ["szAction"]="UIHelper.EnterHideAllUIMode()",
        ["nActionID"]=8,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=9,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=1,
        ["szGroupDesc"]="常用功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [21]=
    {
        ["nID"]=21,
        ["szDesc"]="镜头重置",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn18.png",
        ["szTitle"]="镜头重置",
        ["nGroupID"]=1,
        ["szAction"]="CameraMgr.CamaraReset()",
        ["nActionID"]=8,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=10,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=2,
        ["szGroupDesc"]="常用功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [22]=
    {
        ["nID"]=22,
        ["szDesc"]="场景标记",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn21.png",
        ["szTitle"]="场景标记",
        ["nGroupID"]=2,
        ["szAction"]="StartEndWorldMark",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=0,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=2,
        ["szGroupDesc"]="队伍功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=true,
        ["bHavaMutexState"]=false
    },
    [23]=
    {
        ["nID"]=23,
        ["szDesc"]="标记管理",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn22.png",
        ["szTitle"]="标记管理",
        ["nGroupID"]=2,
        ["szAction"]="PanelSceneMark",
        ["nActionID"]=1,
        ["nOpenType"]=0,
        ["bIsDisplay"]=false,
        ["nLeftBtnID"]=0,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=3,
        ["szGroupDesc"]="队伍功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [24]=
    {
        ["nID"]=24,
        ["szDesc"]="玩家显示",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn19.png",
        ["szTitle"]="玩家显示",
        ["nGroupID"]=1,
        ["szAction"]="OpenPlayerDisplayModeList",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=12,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=7,
        ["szGroupDesc"]="常用功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=false,
        ["nSystemOpenID"]=50,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [25]=
    {
        ["nID"]=25,
        ["szDesc"]="打开召唤宠物界面/快捷召回宠物",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_petBtn1.png",
        ["szTitle"]="召唤宠物",
        ["nGroupID"]=3,
        ["szAction"]="PanelGM|11|22",
        ["nActionID"]=9,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=13,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=7,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {
            [1]="not BattleFieldData.IsInTreasureBattleFieldMap(true)"
        },
        ["szMutexTitle"]="召回宠物",
        ["szsMutexIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_petBtn1.png",
        ["bCloseOnClick"]=false,
        ["nSystemOpenID"]=40,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=true,
        ["bHavaMutexState"]=true
    },
    [26]=
    {
        ["nID"]=26,
        ["szDesc"]="教程盒子界面",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_TutorialBtn.png",
        ["szTitle"]="指引",
        ["nGroupID"]=1,
        ["szAction"]="PanelTutorialCollection",
        ["nActionID"]=1,
        ["nOpenType"]=0,
        ["bIsDisplay"]=false,
        ["nLeftBtnID"]=0,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=0,
        ["szGroupDesc"]="常用功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [27]=
    {
        ["nID"]=27,
        ["szDesc"]="切换走路",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn26.png",
        ["szTitle"]="切换走路",
        ["nGroupID"]=3,
        ["szAction"]="APIHelper.SwitchWalk()",
        ["nActionID"]=8,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=14,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=1,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="关闭走路",
        ["szsMutexIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn26.png",
        ["bCloseOnClick"]=false,
        ["nSystemOpenID"]=51,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=true,
        ["bHavaMutexState"]=true
    },
    [28]=
    {
        ["nID"]=28,
        ["szDesc"]="屏蔽NPC",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn24.png",
        ["szTitle"]="屏蔽NPC",
        ["nGroupID"]=1,
        ["szAction"]="ToggleNpc()",
        ["nActionID"]=8,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=11,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=8,
        ["szGroupDesc"]="常用功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="屏蔽NPC",
        ["szsMutexIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn24_1.png",
        ["bCloseOnClick"]=false,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=true,
        ["bHavaMutexState"]=true
    },
    [29]=
    {
        ["nID"]=29,
        ["szDesc"]="开启关闭语音",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn20.png",
        ["szTitle"]="语音管理",
        ["nGroupID"]=2,
        ["szAction"]="OpenVoiceDisplayModeList",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=0,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=4,
        ["szGroupDesc"]="队伍功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=false,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [30]=
    {
        ["nID"]=30,
        ["szDesc"]="队伍标记",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn25.png",
        ["szTitle"]="一键标记",
        ["nGroupID"]=2,
        ["szAction"]="TeamMarkData.AutoSetTeamMark()",
        ["nActionID"]=8,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=0,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=1,
        ["szGroupDesc"]="队伍功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [31]=
    {
        ["nID"]=31,
        ["szDesc"]="阵营同模",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn28.png",
        ["szTitle"]="阵营同模",
        ["nGroupID"]=1,
        ["szAction"]="ToggleUniform()",
        ["nActionID"]=8,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=18,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=3,
        ["szGroupDesc"]="常用功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="关闭同模",
        ["szsMutexIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn28_1.png",
        ["bCloseOnClick"]=false,
        ["nSystemOpenID"]=26,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=true,
        ["bHavaMutexState"]=true
    },
    [32]=
    {
        ["nID"]=32,
        ["szDesc"]="轻功模式",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn27_1.png",
        ["szTitle"]="轻功模式",
        ["nGroupID"]=1,
        ["szAction"]="OpenSprintModeList",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=19,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=4,
        ["szGroupDesc"]="常用功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=false,
        ["nSystemOpenID"]=27,
        ["szActionEvent"]="OnQuickMenuSprintChange",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [33]=
    {
        ["nID"]=33,
        ["szDesc"]="拍照",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn9.png",
        ["szTitle"]="拍照",
        ["nGroupID"]=3,
        ["szAction"]="OpenCameraPanel",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=15,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=3,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [34]=
    {
        ["nID"]=34,
        ["szDesc"]="表情动作",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn29.png",
        ["szTitle"]="表情动作",
        ["nGroupID"]=3,
        ["szAction"]="ON_OPEN_ACTIONOPERATION",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=16,
        ["tbRedPoint"]=
        {
            [1]=1602,
            [2]=1603
        },
        ["nGroupIndex"]=9,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=false,
        ["nSystemOpenID"]=35,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [35]=
    {
        ["nID"]=35,
        ["szDesc"]="外观预设",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn30.png",
        ["szTitle"]="外观预设",
        ["nGroupID"]=3,
        ["szAction"]="APIHelper.ChangeOutfit()",
        ["nActionID"]=8,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=17,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=10,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=false,
        ["nSystemOpenID"]=49,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [36]=
    {
        ["nID"]=36,
        ["szDesc"]="暗器",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn31.png",
        ["szTitle"]="暗器",
        ["nGroupID"]=3,
        ["szAction"]="34",
        ["nActionID"]=2,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=20,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=12,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [37]=
    {
        ["nID"]=37,
        ["szDesc"]="开始垂钓",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn32.png",
        ["szTitle"]="垂钓",
        ["nGroupID"]=3,
        ["szAction"]="36261",
        ["nActionID"]=2,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=27,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=4,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=53,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=true,
        ["bHavaMutexState"]=false
    },
    [38]=
    {
        ["nID"]=38,
        ["szDesc"]="万灵营地技能",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn33.png",
        ["szTitle"]="风宿帷天",
        ["nGroupID"]=3,
        ["szAction"]="36158",
        ["nActionID"]=2,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=28,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=13,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [39]=
    {
        ["nID"]=39,
        ["szDesc"]="自动行走",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn35.png",
        ["szTitle"]="自动行走",
        ["nGroupID"]=3,
        ["szAction"]="FuncSlotMgr.ExecuteCommand(\"AutoForward\")",
        ["nActionID"]=8,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=22,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=2,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [40]=
    {
        ["nID"]=40,
        ["szDesc"]="宠物交互",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn37.png",
        ["szTitle"]="宠物交互",
        ["nGroupID"]=3,
        ["szAction"]="PanelGM|11|22",
        ["nActionID"]=10,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=0,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=8,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="宠物交互",
        ["szsMutexIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn36.png",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=40,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=true,
        ["bHavaMutexState"]=true
    },
    [41]=
    {
        ["nID"]=41,
        ["szDesc"]="触发事件，调用侠客开战",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_xiakeBtn8.png",
        ["szTitle"]="侠客开战",
        ["nGroupID"]=4,
        ["szAction"]="On_Partner_TankAttack",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=26,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=4,
        ["szGroupDesc"]="侠客功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [42]=
    {
        ["nID"]=42,
        ["szDesc"]="侠客交互",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn39.png",
        ["szTitle"]="侠客交互",
        ["nGroupID"]=4,
        ["szAction"]="PanelGM|11|22",
        ["nActionID"]=11,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=0,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=8,
        ["szGroupDesc"]="侠客功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="侠客交互",
        ["szsMutexIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn38.png",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=75,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=true,
        ["bHavaMutexState"]=true
    },
    [43]=
    {
        ["nID"]=43,
        ["szDesc"]="打开GM界面",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn41.png",
        ["szTitle"]="重载按键",
        ["nGroupID"]=1,
        ["szAction"]="ResetSkillAndJoystick",
        ["nActionID"]=7,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=0,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=11,
        ["szGroupDesc"]="常用功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [44]=
    {
        ["nID"]=44,
        ["szDesc"]="查看当前场景的地图成就",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn42.png",
        ["szTitle"]="地图成就",
        ["nGroupID"]=3,
        ["szAction"]="PanelMapAchievement",
        ["nActionID"]=1,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=29,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=14,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=77,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [45]=
    {
        ["nID"]=45,
        ["szDesc"]="切花滤镜",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn43.png",
        ["szTitle"]="时光漫游",
        ["nGroupID"]=3,
        ["szAction"]="PanelAtmosphere",
        ["nActionID"]=1,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=30,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=15,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [46]=
    {
        ["nID"]=46,
        ["szDesc"]="打开春节活动砸年兽陶罐设置",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_QuickBtn44.png",
        ["szTitle"]="年兽陶罐",
        ["nGroupID"]=3,
        ["szAction"]="PanelNianShouTaobaoGuanSetting",
        ["nActionID"]=1,
        ["nOpenType"]=2,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=0,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=16,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="33",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=0,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    },
    [47]=
    {
        ["nID"]=47,
        ["szDesc"]="打开五味诀",
        ["szIcon"]="UIAtlas2_Public_PublicSystemButton_PublicSystemButton_wuweijueBtn.png",
        ["szTitle"]="五味诀",
        ["nGroupID"]=3,
        ["szAction"]="PanelWuWeiJuePop",
        ["nActionID"]=1,
        ["nOpenType"]=0,
        ["bIsDisplay"]=true,
        ["nLeftBtnID"]=31,
        ["tbRedPoint"]=
        {

        },
        ["nGroupIndex"]=17,
        ["szGroupDesc"]="玩法功能",
        ["szOpenParam"]="",
        ["tbCheckFunc"]=
        {

        },
        ["szMutexTitle"]="",
        ["szsMutexIcon"]="",
        ["bCloseOnClick"]=true,
        ["nSystemOpenID"]=80,
        ["szActionEvent"]="",
        ["bHavaCloseState"]=false,
        ["bHavaMutexState"]=false
    }
}
