--*************************************** 工具生成 ***************************************
UIRedpointTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["szDesc"]="红点测试",
        ["tbEvents"]=
        {
            [1]="OnViewClose",
            [2]="OnWindowsMouseWheel"
        }
    },
    [2]=
    {
        ["nID"]=2,
        ["szDesc"]="密聊红点",
        ["tbEvents"]=
        {
            [1]="OnChatRecentWhisperUnreadAdd",
            [2]="OnChatRecentWhisperUnreadRemove"
        }
    },
    [3]=
    {
        ["nID"]=3,
        ["szDesc"]="聊天表情红点",
        ["tbEvents"]=
        {
            [1]="OnChatEmojiAdd",
            [2]="OnChatEmojiRemove"
        }
    },
    [4]=
    {
        ["nID"]=4,
        ["szDesc"]="离线消息红点",
        ["tbEvents"]=
        {
            [1]="OnChatHintMsgUpdate"
        }
    },
    [5]=
    {
        ["nID"]=5,
        ["szDesc"]="队伍频道红点",
        ["tbEvents"]=
        {
            [1]="OnChatHintMsgUpdate"
        }
    },
    [6]=
    {
        ["nID"]=6,
        ["szDesc"]="帮会频道红点",
        ["tbEvents"]=
        {
            [1]="OnChatHintMsgUpdate"
        }
    },
    [7]=
    {
        ["nID"]=7,
        ["szDesc"]="侠缘频道红点",
        ["tbEvents"]=
        {
            [1]="OnChatAINpcUnReadChange"
        }
    },
    [1001]=
    {
        ["nID"]=1001,
        ["szDesc"]="花萼楼-总入口",
        ["tbEvents"]=
        {
            [1]="ON_DAILY_SIGN_REFRESH",
            [2]="ON_DAILY_SIGN_GET_AWARD",
            [3]="CHANGE_NEW_EXT_POINT_NOTIFY",
            [4]="OnUpdateHuaELouRedPoint",
            [5]="OnPlayerLevelUp",
            [6]="On_Recharge_CheckWelfare_CallBack",
            [7]="On_Recharge_GetWelfareRwd_CallBack",
            [8]="ON_RECVSEASON_REWARD",
            [9]="On_Recharge_CheckProgress_CallBack",
            [10]="On_Recharge_GetProgressReward_CallBack",
            [11]="On_Recharge_CheckOnSaleMonthly_CallBack",
            [12]="On_Recharge_GetOnSaleMonthlyRwd_CallBack",
            [13]="SYNC_REGRESSION_PLAYER_DATA",
            [14]="UPDATE_CONTINUOUS_LOGIN_REWARD_FLAG",
            [15]="On_Recharge_CheckOnSale",
            [16]="On_Recharge_GetOnSaleRwd",
            [17]="On_Recharge_CheckTongBaoGift_CallBack",
            [18]="On_Recharge_GetTongBaoGiftRwd_CallBack",
            [19]="REMOTE_NEWSIGNIN_DATA_EVENT",
            [20]="On_Recharge_GetFriInvReward_CallBack",
            [21]="On_Recharge_GetFriendsPoints_CallBack",
            [22]="EVENT_RECHARGE_CUSTOM_DATA_UPDATE",
            [23]="On_Check_Operation_CallBack",
            [24]="On_Get_Operation_Reward_CallBack"
        }
    },
    [1101]=
    {
        ["nID"]=1101,
        ["szDesc"]="挂饰秘鉴-挂件",
        ["tbEvents"]=
        {
            [1]="ON_ADD_PENDANT",
            [2]="ON_UPDATE_PENDANT_NEW"
        }
    },
    [1102]=
    {
        ["nID"]=1102,
        ["szDesc"]="挂饰秘鉴-特效",
        ["tbEvents"]=
        {
            [1]="ON_UPDATE_EFFECT_NEW"
        }
    },
    [1103]=
    {
        ["nID"]=1103,
        ["szDesc"]="挂饰秘鉴-小头像",
        ["tbEvents"]=
        {
            [1]="OnAvatarNewUpdate",
            [2]="ACQUIRE_MINI_AVATAR"
        }
    },
    [1104]=
    {
        ["nID"]=1104,
        ["szDesc"]="挂饰秘鉴-待机动作",
        ["tbEvents"]=
        {
            [1]="ON_CHANGE_PLAYER_IDLE_ACTION_NOTIFY",
            [2]="ON_UPDATE_IDLEACTION_NEW"
        }
    },
    [1105]=
    {
        ["nID"]=1105,
        ["szDesc"]="挂饰秘鉴-武技殊影",
        ["tbEvents"]=
        {
            [1]="ON_UPDATE_SKILL_SKIN",
            [2]="ON_UPDATE_SKILLSKIN_NEW"
        }
    },
    [1201]=
    {
        ["nID"]=1201,
        ["szDesc"]="公告-更新日志",
        ["tbEvents"]=
        {
            [1]="OnBulletinRedPointUpdate"
        }
    },
    [1202]=
    {
        ["nID"]=1202,
        ["szDesc"]="公告-游戏公告",
        ["tbEvents"]=
        {
            [1]="OnBulletinRedPointUpdate"
        }
    },
    [1203]=
    {
        ["nID"]=1203,
        ["szDesc"]="公告-系统公告",
        ["tbEvents"]=
        {
            [1]="OnBulletinRedPointUpdate"
        }
    },
    [1204]=
    {
        ["nID"]=1204,
        ["szDesc"]="公告-充值返还公告",
        ["tbEvents"]=
        {
            [1]="OnBulletinRedPointUpdate"
        }
    },
    [1205]=
    {
        ["nID"]=1205,
        ["szDesc"]="公告-技改公告",
        ["tbEvents"]=
        {
            [1]="OnBulletinRedPointUpdate"
        }
    },
    [1301]=
    {
        ["nID"]=1301,
        ["szDesc"]="称号-获得新称号",
        ["tbEvents"]=
        {
            [1]="DESIGNATION_ANNOUNCE",
            [2]="OnDesignationNewUpdate"
        }
    },
    [1401]=
    {
        ["nID"]=1401,
        ["szDesc"]="坐骑-普通坐骑",
        ["tbEvents"]=
        {
            [1]="HORSE_ITEM_UPDATE",
            [2]="OnHorseNewUpdate"
        }
    },
    [1402]=
    {
        ["nID"]=1402,
        ["szDesc"]="坐骑-奇趣坐骑",
        ["tbEvents"]=
        {
            [1]="HORSE_ITEM_UPDATE",
            [2]="OnHorseNewUpdate"
        }
    },
    [1501]=
    {
        ["nID"]=1501,
        ["szDesc"]="宠物-获得新宠物",
        ["tbEvents"]=
        {
            [1]="ACQUIRE_FELLOW_PET",
            [2]="OnPetNewUpdate"
        }
    },
    [1601]=
    {
        ["nID"]=1601,
        ["szDesc"]="快捷操作-玩具箱",
        ["tbEvents"]=
        {
            [1]="TOYBOX_ADD",
            [2]="OnToyBoxNewUpdate"
        }
    },
    [1602]=
    {
        ["nID"]=1602,
        ["szDesc"]="快捷操作-表情动作",
        ["tbEvents"]=
        {
            [1]="ON_ADD_EMOTION_ACTION_NOTIFY",
            [2]="OnEmotionActionNewUpdate"
        }
    },
    [1603]=
    {
        ["nID"]=1603,
        ["szDesc"]="快捷操作-头顶表情",
        ["tbEvents"]=
        {
            [1]="ON_OPERATE_BRIGHT_MARK_NOTIFY",
            [2]="OnBrightMarkNewUpdate"
        }
    },
    [1701]=
    {
        ["nID"]=1701,
        ["szDesc"]="主界面右上角-气泡消息",
        ["tbEvents"]=
        {
            [1]="BubbleMsg",
            [2]="BubbleRedPointUpdate"
        }
    },
    [1801]=
    {
        ["nID"]=1801,
        ["szDesc"]="行记-入口",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckRFirstCharge_CallBack",
            [2]="On_Recharge_GetRFirstChargeRwd_CallBack",
            [3]="REMOTE_BATTLEPASS",
            [4]="ON_SYNC_SET_COLLECTION"
        }
    },
    [1901]=
    {
        ["nID"]=1901,
        ["szDesc"]="武学面板-未装备秘籍",
        ["tbEvents"]=
        {
            [1]="MYSTIQUE_ACTIVE_UPDATE",
            [2]="UPDATE_TALENT_SET_SLOT_SKILL",
            [3]="SKILL_RED_POINT_UPDATE",
            [4]="ON_UPDATE_TALENT"
        }
    },
    [1902]=
    {
        ["nID"]=1902,
        ["szDesc"]="武学面板-武学推荐",
        ["tbEvents"]=
        {
            [1]="SKILL_RED_POINT_UPDATE",
            [2]="ON_UPDATE_TALENT"
        }
    },
    [1903]=
    {
        ["nID"]=1903,
        ["szDesc"]="武学面板-武学推荐-秘境推荐",
        ["tbEvents"]=
        {
            [1]="SKILL_RED_POINT_UPDATE",
            [2]="ON_UPDATE_TALENT"
        }
    },
    [1904]=
    {
        ["nID"]=1904,
        ["szDesc"]="武学面板-武学推荐-竞技推荐",
        ["tbEvents"]=
        {
            [1]="SKILL_RED_POINT_UPDATE",
            [2]="ON_UPDATE_TALENT"
        }
    },
    [1905]=
    {
        ["nID"]=1905,
        ["szDesc"]="武学面板-流派提示",
        ["tbEvents"]=
        {
            [1]="SKILL_RED_POINT_UPDATE",
            [2]="ON_UPDATE_TALENT"
        }
    },
    [2001]=
    {
        ["nID"]=2001,
        ["szDesc"]="商城-福袋",
        ["tbEvents"]=
        {
            [1]="OnCoinShopDrawStorageUpdate"
        }
    },
    [2002]=
    {
        ["nID"]=2002,
        ["szDesc"]="商城-优惠券",
        ["tbEvents"]=
        {
            [1]="COINSHOP_PUSHINFO_UPDATE"
        }
    },
    [2003]=
    {
        ["nID"]=2003,
        ["szDesc"]="商城-保管",
        ["tbEvents"]=
        {
            [1]="TRADE_CENTER_COUNT_UPDATE"
        }
    },
    [2004]=
    {
        ["nID"]=2004,
        ["szDesc"]="商城-福利返还",
        ["tbEvents"]=
        {
            [1]="ON_QUERY_AVAILABLE_INNER_CHARGE_RESPOND",
            [2]="ON_DO_INNER_CHARGE_RESPOND"
        }
    },
    [2005]=
    {
        ["nID"]=2005,
        ["szDesc"]="商城-外装使用",
        ["tbEvents"]=
        {
            [1]="ONGETFUDAI",
            [2]="XX",
            [3]="XXX"
        }
    },
    [2006]=
    {
        ["nID"]=2006,
        ["szDesc"]="商城-校服活动",
        ["tbEvents"]=
        {
            [1]="PLAYER_LEVEL_UP",
            [2]="CHANGE_NEW_EXT_POINT_NOTIFY",
            [3]="SchoolActivityRedUpdate"
        }
    },
    [2007]=
    {
        ["nID"]=2007,
        ["szDesc"]="商城-我的外观",
        ["tbEvents"]=
        {
            [1]="ON_ADD_PENDANT",
            [2]="ON_UPDATE_PENDANT_NEW",
            [3]="ON_UPDATE_EXTERIOR_NEW",
            [4]="ON_UPDATE_WEAPON_EXTERIOR_NEW",
            [5]="ON_UPDATE_PENDANT_PET_NEW",
            [6]="ON_UPDATE_HAIR_NEW",
            [7]="ON_UPDATE_FACE_NEW",
            [8]="ON_UPDATE_BODY_NEW",
            [9]="ON_UPDATE_IDLEACTION_NEW"
        }
    },
    [2008]=
    {
        ["nID"]=2008,
        ["szDesc"]="商城-零元购",
        ["tbEvents"]=
        {
            [1]="DIS_COUPON_CHANGED"
        }
    },
    [2101]=
    {
        ["nID"]=2101,
        ["szDesc"]="招募-申请",
        ["tbEvents"]=
        {
            [1]="OnRecruitApplyCountUpdate"
        }
    },
    [2201]=
    {
        ["nID"]=2201,
        ["szDesc"]="武林通鉴",
        ["tbEvents"]=
        {
            [1]="QUEST_FINISHED",
            [2]="SET_QUEST_STATE",
            [3]="OnUpdateWuLinTongJianRedpoint"
        }
    },
    [2301]=
    {
        ["nID"]=2301,
        ["szDesc"]="邮件-未读邮件",
        ["tbEvents"]=
        {
            [1]="UPDATE_MAIL_READ_FLAG",
            [2]="MAIL_LIST_UPDATE"
        }
    },
    [2401]=
    {
        ["nID"]=2401,
        ["szDesc"]="花萼楼每日签到",
        ["tbEvents"]=
        {
            [1]="ON_DAILY_SIGN_REFRESH",
            [2]="ON_DAILY_SIGN_GET_AWARD",
            [3]="UPDATE_CONTINUOUS_LOGIN_REWARD_FLAG"
        }
    },
    [2402]=
    {
        ["nID"]=2402,
        ["szDesc"]="花萼楼活动119",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2403]=
    {
        ["nID"]=2403,
        ["szDesc"]="花萼楼月度冲消",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckOnSaleMonthly_CallBack",
            [2]="On_Recharge_GetOnSaleMonthlyRwd_CallBack"
        }
    },
    [2404]=
    {
        ["nID"]=2404,
        ["szDesc"]="花萼楼赛季展望",
        ["tbEvents"]=
        {
            [1]="ON_RECVSEASON_REWARD"
        }
    },
    [2405]=
    {
        ["nID"]=2405,
        ["szDesc"]="花萼楼活动48",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckProgress_CallBack",
            [2]="On_Recharge_GetProgressReward_CallBack"
        }
    },
    [2406]=
    {
        ["nID"]=2406,
        ["szDesc"]="花萼楼回归活动",
        ["tbEvents"]=
        {
            [1]="SYNC_REGRESSION_PLAYER_DATA"
        }
    },
    [2407]=
    {
        ["nID"]=2407,
        ["szDesc"]="花萼楼活动154",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2408]=
    {
        ["nID"]=2408,
        ["szDesc"]="花萼楼活动86",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2409]=
    {
        ["nID"]=2409,
        ["szDesc"]="花萼楼活动72",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2410]=
    {
        ["nID"]=2410,
        ["szDesc"]="花萼楼活动157",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2411]=
    {
        ["nID"]=2411,
        ["szDesc"]="花萼楼活动160",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2412]=
    {
        ["nID"]=2412,
        ["szDesc"]="花萼楼活动155",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack",
            [3]="CHANGE_NEW_EXT_POINT_NOTIFY"
        }
    },
    [2413]=
    {
        ["nID"]=2413,
        ["szDesc"]="花萼楼活动165",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2414]=
    {
        ["nID"]=2414,
        ["szDesc"]="花萼楼活动168",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2415]=
    {
        ["nID"]=2415,
        ["szDesc"]="花萼楼活动2",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckOnSale_CallBack",
            [2]="On_Recharge_GetOnSaleRwd_CallBack"
        }
    },
    [2416]=
    {
        ["nID"]=2416,
        ["szDesc"]="花萼楼活动105",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack"
        }
    },
    [2417]=
    {
        ["nID"]=2417,
        ["szDesc"]="花萼楼活动169",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2418]=
    {
        ["nID"]=2418,
        ["szDesc"]="花萼楼活动120",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2419]=
    {
        ["nID"]=2419,
        ["szDesc"]="花萼楼活动4",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckTongBaoGift_CallBack",
            [2]="On_Recharge_GetTongBaoGiftRwd_CallBack"
        }
    },
    [2420]=
    {
        ["nID"]=2420,
        ["szDesc"]="花萼楼活动103",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2421]=
    {
        ["nID"]=2421,
        ["szDesc"]="花萼楼活动180",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2422]=
    {
        ["nID"]=2422,
        ["szDesc"]="花萼楼活动185",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2423]=
    {
        ["nID"]=2423,
        ["szDesc"]="花萼楼活动187",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2424]=
    {
        ["nID"]=2424,
        ["szDesc"]="花萼楼活动186",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2425]=
    {
        ["nID"]=2425,
        ["szDesc"]="花萼楼活动188",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2426]=
    {
        ["nID"]=2426,
        ["szDesc"]="花萼楼活动91",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2427]=
    {
        ["nID"]=2427,
        ["szDesc"]="花萼楼活动40",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2428]=
    {
        ["nID"]=2428,
        ["szDesc"]="花萼楼活动196",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2429]=
    {
        ["nID"]=2429,
        ["szDesc"]="花萼楼活动198",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2430]=
    {
        ["nID"]=2430,
        ["szDesc"]="花萼楼活动90",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2431]=
    {
        ["nID"]=2431,
        ["szDesc"]="花萼楼活动199",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2432]=
    {
        ["nID"]=2432,
        ["szDesc"]="花萼楼活动204",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2433]=
    {
        ["nID"]=2433,
        ["szDesc"]="花萼楼活动203",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2434]=
    {
        ["nID"]=2434,
        ["szDesc"]="花萼楼活动209",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2435]=
    {
        ["nID"]=2435,
        ["szDesc"]="花萼楼活动211",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2436]=
    {
        ["nID"]=2436,
        ["szDesc"]="花萼楼活动213",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2437]=
    {
        ["nID"]=2437,
        ["szDesc"]="花萼楼活动214",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2438]=
    {
        ["nID"]=2438,
        ["szDesc"]="花萼楼活动215",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2439]=
    {
        ["nID"]=2439,
        ["szDesc"]="花萼楼活动218",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2440]=
    {
        ["nID"]=2440,
        ["szDesc"]="花萼楼活动219",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2441]=
    {
        ["nID"]=2441,
        ["szDesc"]="花萼楼活动220",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2442]=
    {
        ["nID"]=2442,
        ["szDesc"]="花萼楼活动221",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckWelfare_CallBack",
            [2]="On_Recharge_GetWelfareRwd_CallBack"
        }
    },
    [2443]=
    {
        ["nID"]=2443,
        ["szDesc"]="花萼楼活动225",
        ["tbEvents"]=
        {
            [1]="REMOTE_NEWSIGNIN_DATA_EVENT"
        }
    },
    [2444]=
    {
        ["nID"]=2444,
        ["szDesc"]="花萼楼活动226",
        ["tbEvents"]=
        {
            [1]="REMOTE_NEWSIGNIN_DATA_EVENT"
        }
    },
    [2445]=
    {
        ["nID"]=2445,
        ["szDesc"]="花萼楼活动11-好友招募",
        ["tbEvents"]=
        {
            [1]="On_Recharge_GetFriInvReward_CallBack",
            [2]="On_Recharge_GetFriendsPoints_CallBack"
        }
    },
    [2446]=
    {
        ["nID"]=2446,
        ["szDesc"]="花萼楼活动234-萌新接引",
        ["tbEvents"]=
        {
            [1]="EVENT_RECHARGE_CUSTOM_DATA_UPDATE"
        }
    },
    [2447]=
    {
        ["nID"]=2447,
        ["szDesc"]="花萼楼活动250",
        ["tbEvents"]=
        {
            [1]="On_Check_Operation_CallBack",
            [2]="On_Get_Operation_Reward_CallBack"
        }
    },
    [2448]=
    {
        ["nID"]=2448,
        ["szDesc"]="花萼楼活动251",
        ["tbEvents"]=
        {
            [1]="On_Check_Operation_CallBack",
            [2]="On_Get_Operation_Reward_CallBack"
        }
    },
    [2501]=
    {
        ["nID"]=2501,
        ["szDesc"]="阵营排行奖励",
        ["tbEvents"]=
        {
            [1]="On_CAMP_GETTITLEPOINTRANKINFO",
            [2]="On_CAMP_GETTITLEPOINTRANKREWARD"
        }
    },
    [2502]=
    {
        ["nID"]=2502,
        ["szDesc"]="130级加入阵营提示",
        ["tbEvents"]=
        {
            [1]="PLAYER_LEVEL_UP",
            [2]="PLAYER_LEVEL_UPDATE"
        }
    },
    [2601]=
    {
        ["nID"]=2601,
        ["szDesc"]="竞技解锁",
        ["tbEvents"]=
        {
            [1]="OnUpdateArenaRedPoint"
        }
    },
    [2701]=
    {
        ["nID"]=2701,
        ["szDesc"]="日课奖励",
        ["tbEvents"]=
        {
            [1]="On_Get_Daily_Allinfo"
        }
    },
    [2702]=
    {
        ["nID"]=2702,
        ["szDesc"]="赛季荣誉",
        ["tbEvents"]=
        {
            [1]="CB_SH_TaskRewardGranted",
            [2]="OnSeasonTaskProgressMessage",
            [3]="CB_SH_SetPersonReward"
        }
    },
    [2703]=
    {
        ["nID"]=2703,
        ["szDesc"]="周课奖励",
        ["tbEvents"]=
        {
            [1]="On_GameGuide_UpdateWeeklyInfo"
        }
    },
    [2704]=
    {
        ["nID"]=2704,
        ["szDesc"]="赛季段位-每日",
        ["tbEvents"]=
        {
            [1]="CB_SA_SetPersonReward",
            [2]="CB_SA_TaskUpdate"
        }
    },
    [2705]=
    {
        ["nID"]=2705,
        ["szDesc"]="赛季段位-秘境",
        ["tbEvents"]=
        {
            [1]="CB_SA_SetPersonReward",
            [2]="CB_SA_TaskUpdate"
        }
    },
    [2706]=
    {
        ["nID"]=2706,
        ["szDesc"]="赛季段位-阵营",
        ["tbEvents"]=
        {
            [1]="CB_SA_SetPersonReward",
            [2]="CB_SA_TaskUpdate"
        }
    },
    [2707]=
    {
        ["nID"]=2707,
        ["szDesc"]="赛季段位-竞技",
        ["tbEvents"]=
        {
            [1]="CB_SA_SetPersonReward",
            [2]="CB_SA_TaskUpdate"
        }
    },
    [2708]=
    {
        ["nID"]=2708,
        ["szDesc"]="赛季段位-休闲",
        ["tbEvents"]=
        {
            [1]="CB_SA_SetPersonReward",
            [2]="CB_SA_TaskUpdate"
        }
    },
    [2709]=
    {
        ["nID"]=2709,
        ["szDesc"]="荣誉挑战-坐骑兑换",
        ["tbEvents"]=
        {
            [1]="CB_SH_TaskRewardGranted",
            [2]="CB_SH_SetPersonReward",
            [3]="CB_SH_ExchangeMount",
            [4]="ChallengeHorseRedDotChange"
        }
    },
    [2801]=
    {
        ["nID"]=2801,
        ["szDesc"]="行记-首充",
        ["tbEvents"]=
        {
            [1]="On_Recharge_CheckRFirstCharge_CallBack",
            [2]="On_Recharge_GetRFirstChargeRwd_CallBack"
        }
    },
    [2802]=
    {
        ["nID"]=2802,
        ["szDesc"]="行记-江湖行记",
        ["tbEvents"]=
        {
            [1]="REMOTE_BATTLEPASS",
            [2]="ON_SYNC_SET_COLLECTION"
        }
    },
    [2901]=
    {
        ["nID"]=2901,
        ["szDesc"]="神兵百炼-入口",
        ["tbEvents"]=
        {
            [1]="OnPlayerLevelUp",
            [2]="OrangeWeaponUpgRedPoint",
            [3]="ON_SYNC_SET_COLLECTION",
            [4]="REMOTE_BATTLEPASS",
            [5]="BAG_ITEM_UPDATE",
            [6]="On_Upgrade_OrangeWeapon"
        }
    },
    [3001]=
    {
        ["nID"]=3001,
        ["szDesc"]="帮会消息",
        ["tbEvents"]=
        {
            [1]="OnTongApplyListRedPointUpdate"
        }
    },
    [3101]=
    {
        ["nID"]=3101,
        ["szDesc"]="花萼楼赛季展望-战力篇",
        ["tbEvents"]=
        {
            [1]="ON_RECVSEASON_REWARD"
        }
    },
    [3102]=
    {
        ["nID"]=3102,
        ["szDesc"]="花萼楼赛季展望-家园篇",
        ["tbEvents"]=
        {
            [1]="ON_RECVSEASON_REWARD"
        }
    },
    [3201]=
    {
        ["nID"]=3201,
        ["szDesc"]="教程盒子",
        ["tbEvents"]=
        {
            [1]="OnUpdateTeachBoxRedPoint"
        }
    },
    [3301]=
    {
        ["nID"]=3301,
        ["szDesc"]="师徒-菜单入口",
        ["tbEvents"]=
        {
            [1]="OnUpdateMentorRedpoint"
        }
    },
    [3302]=
    {
        ["nID"]=3302,
        ["szDesc"]="师徒-拜师成功",
        ["tbEvents"]=
        {
            [1]="OnUpdateMentorRedpoint"
        }
    },
    [3303]=
    {
        ["nID"]=3303,
        ["szDesc"]="师徒-收徒成功",
        ["tbEvents"]=
        {
            [1]="OnUpdateMentorRedpoint"
        }
    },
    [3401]=
    {
        ["nID"]=3401,
        ["szDesc"]="界面自定义",
        ["tbEvents"]=
        {
            [1]="OnUpdateCustomRedPoint"
        }
    },
    [3501]=
    {
        ["nID"]=3501,
        ["szDesc"]="名剑-段位奖励可领取-2v2",
        ["tbEvents"]=
        {
            [1]="OnUpdateArenaRedPoint"
        }
    },
    [3502]=
    {
        ["nID"]=3502,
        ["szDesc"]="名剑-段位奖励可领取-3v3",
        ["tbEvents"]=
        {
            [1]="OnUpdateArenaRedPoint"
        }
    },
    [3503]=
    {
        ["nID"]=3503,
        ["szDesc"]="名剑-段位奖励可领取-5v5",
        ["tbEvents"]=
        {
            [1]="OnUpdateArenaRedPoint"
        }
    },
    [3504]=
    {
        ["nID"]=3504,
        ["szDesc"]="绝境战场-寻宝模式赛季奖励可领取",
        ["tbEvents"]=
        {
            [1]="OnUpdateExtractRewardRedPoint"
        }
    },
    [3601]=
    {
        ["nID"]=3601,
        ["szDesc"]="日历活动",
        ["tbEvents"]=
        {
            [1]="OnUpdateActivityRedPoint"
        }
    },
    [3602]=
    {
        ["nID"]=3602,
        ["szDesc"]="日历收藏活动",
        ["tbEvents"]=
        {
            [1]="OnUpdateActivityRedPoint"
        }
    },
    [3603]=
    {
        ["nID"]=3603,
        ["szDesc"]="日历休闲活动",
        ["tbEvents"]=
        {
            [1]="OnUpdateActivityRedPoint"
        }
    },
    [3604]=
    {
        ["nID"]=3604,
        ["szDesc"]="日历协作活动",
        ["tbEvents"]=
        {
            [1]="OnUpdateActivityRedPoint"
        }
    },
    [3605]=
    {
        ["nID"]=3605,
        ["szDesc"]="日历对抗活动",
        ["tbEvents"]=
        {
            [1]="OnUpdateActivityRedPoint"
        }
    },
    [3606]=
    {
        ["nID"]=3606,
        ["szDesc"]="日历家园活动",
        ["tbEvents"]=
        {
            [1]="OnUpdateActivityRedPoint"
        }
    },
    [3607]=
    {
        ["nID"]=3607,
        ["szDesc"]="日历往事活动",
        ["tbEvents"]=
        {
            [1]="OnUpdateActivityRedPoint"
        }
    },
    [3608]=
    {
        ["nID"]=3608,
        ["szDesc"]="八荒技能",
        ["tbEvents"]=
        {
            [1]="SetBaHuangSkillRedPoint",
            [2]="OnEnterBahuangDynamic"
        }
    },
    [3701]=
    {
        ["nID"]=3701,
        ["szDesc"]="侠客茶饼",
        ["tbEvents"]=
        {
            [1]="On_Partner_IsGetDailyTeaSuccess"
        }
    },
    [3702]=
    {
        ["nID"]=3702,
        ["szDesc"]="侠客出行完成提示",
        ["tbEvents"]=
        {
            [1]="PartnerTravelHasFinishedSlot",
            [2]="PartnerTravel_AfterTakeReward"
        }
    },
    [3801]=
    {
        ["nID"]=3801,
        ["szDesc"]="家园-可升级",
        ["tbEvents"]=
        {
            [1]="OnUpdateHomelandRedPoint"
        }
    },
    [3802]=
    {
        ["nID"]=3802,
        ["szDesc"]="家园-总览可领取活跃奖励",
        ["tbEvents"]=
        {
            [1]="OnUpdateHomelandRedPoint"
        }
    },
    [3803]=
    {
        ["nID"]=3803,
        ["szDesc"]="家园-庐园广记可领取套装奖励",
        ["tbEvents"]=
        {
            [1]="OnHomelandShowSetRedDot"
        }
    },
    [3804]=
    {
        ["nID"]=3804,
        ["szDesc"]="家园-结庐江湖可领奖",
        ["tbEvents"]=
        {
            [1]="HOME_GET_SEASON_POINTS",
            [2]="ON_SYNC_SET_COLLECTION"
        }
    },
    [3805]=
    {
        ["nID"]=3805,
        ["szDesc"]="家园-日志新消息",
        ["tbEvents"]=
        {
            [1]="OnUpdateHomelandRedPoint"
        }
    },
    [3901]=
    {
        ["nID"]=3901,
        ["szDesc"]="信息追踪",
        ["tbEvents"]=
        {
            [1]="OnUpdateTraceInfoRedPoint"
        }
    },
    [4001]=
    {
        ["nID"]=4001,
        ["szDesc"]="预约-逐鹿中原",
        ["tbEvents"]=
        {
            [1]="ON_SCHEDULE_MAP_APPOINTMENT_RESPOND",
            [2]="OnMapAppointmentNewUpdate"
        }
    },
    [4002]=
    {
        ["nID"]=4002,
        ["szDesc"]="预约-阵营攻防",
        ["tbEvents"]=
        {
            [1]="ON_SCHEDULE_MAP_APPOINTMENT_RESPOND",
            [2]="OnMapAppointmentNewUpdate"
        }
    },
    [4101]=
    {
        ["nID"]=4101,
        ["szDesc"]="商店-活动-分类-子商店",
        ["tbEvents"]=
        {
            [1]="OnShopRedPointChanged"
        }
    },
    [4201]=
    {
        ["nID"]=4201,
        ["szDesc"]="剑侠录-奖励红点",
        ["tbEvents"]=
        {
            [1]="OnRewardStateChanged"
        }
    },
    [4301]=
    {
        ["nID"]=4301,
        ["szDesc"]="客服中心微信小管家红点",
        ["tbEvents"]=
        {
            [1]="OnCheckVerifyWechatManager"
        }
    },
    [4399]=
    {
        ["nID"]=4399,
        ["szDesc"]="名片-生日设置",
        ["tbEvents"]=
        {
            [1]="OnUpdateBirthdaySetRedPoint"
        }
    },
    [4401]=
    {
        ["nID"]=4401,
        ["szDesc"]="花萼楼活动238-秘境任务",
        ["tbEvents"]=
        {
            [1]="OnClickLangFengXuanChengTask"
        }
    }
}
