--*************************************** 工具生成 ***************************************
UIRewardsCameraTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["fYaw"]=0.05,
        ["szDesc"]="默认",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=0,
        ["nRoleType"]=1,
        ["nCameraIndex"]=1,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [2]=
    {
        ["nID"]=2,
        ["fYaw"]=0.05,
        ["szDesc"]="默认",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=0,
        ["nRoleType"]=2,
        ["nCameraIndex"]=2,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [3]=
    {
        ["nID"]=3,
        ["fYaw"]=0.05,
        ["szDesc"]="默认",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=0,
        ["nRoleType"]=5,
        ["nCameraIndex"]=3,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [4]=
    {
        ["nID"]=4,
        ["fYaw"]=0.05,
        ["szDesc"]="默认",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=0,
        ["nRoleType"]=6,
        ["nCameraIndex"]=4,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [5]=
    {
        ["nID"]=5,
        ["fYaw"]=0.05,
        ["szDesc"]="面部挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=1,
        ["nRoleType"]=1,
        ["nCameraIndex"]=1,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [6]=
    {
        ["nID"]=6,
        ["fYaw"]=0.05,
        ["szDesc"]="面部挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=1,
        ["nRoleType"]=2,
        ["nCameraIndex"]=2,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [7]=
    {
        ["nID"]=7,
        ["fYaw"]=0.05,
        ["szDesc"]="面部挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=1,
        ["nRoleType"]=5,
        ["nCameraIndex"]=3,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [8]=
    {
        ["nID"]=8,
        ["fYaw"]=0.05,
        ["szDesc"]="面部挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=1,
        ["nRoleType"]=6,
        ["nCameraIndex"]=4,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [9]=
    {
        ["nID"]=9,
        ["fYaw"]=3.16,
        ["szDesc"]="背部挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=2,
        ["nRoleType"]=1,
        ["nCameraIndex"]=5,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [10]=
    {
        ["nID"]=10,
        ["fYaw"]=3.16,
        ["szDesc"]="背部挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=2,
        ["nRoleType"]=2,
        ["nCameraIndex"]=6,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [11]=
    {
        ["nID"]=11,
        ["fYaw"]=3.16,
        ["szDesc"]="背部挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=2,
        ["nRoleType"]=5,
        ["nCameraIndex"]=7,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [12]=
    {
        ["nID"]=12,
        ["fYaw"]=3.16,
        ["szDesc"]="背部挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=2,
        ["nRoleType"]=6,
        ["nCameraIndex"]=8,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [13]=
    {
        ["nID"]=13,
        ["fYaw"]=0.94,
        ["szDesc"]="腰部挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=3,
        ["nRoleType"]=1,
        ["nCameraIndex"]=17,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [14]=
    {
        ["nID"]=14,
        ["fYaw"]=0.94,
        ["szDesc"]="腰部挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=3,
        ["nRoleType"]=2,
        ["nCameraIndex"]=18,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [15]=
    {
        ["nID"]=15,
        ["fYaw"]=0.94,
        ["szDesc"]="腰部挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=3,
        ["nRoleType"]=5,
        ["nCameraIndex"]=19,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [16]=
    {
        ["nID"]=16,
        ["fYaw"]=0.94,
        ["szDesc"]="腰部挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=3,
        ["nRoleType"]=6,
        ["nCameraIndex"]=20,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [17]=
    {
        ["nID"]=17,
        ["fYaw"]=3.16,
        ["szDesc"]="翅膀",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=4,
        ["nRoleType"]=1,
        ["nCameraIndex"]=1,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [18]=
    {
        ["nID"]=18,
        ["fYaw"]=3.16,
        ["szDesc"]="翅膀",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=4,
        ["nRoleType"]=2,
        ["nCameraIndex"]=2,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [19]=
    {
        ["nID"]=19,
        ["fYaw"]=3.16,
        ["szDesc"]="翅膀",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=4,
        ["nRoleType"]=5,
        ["nCameraIndex"]=3,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [20]=
    {
        ["nID"]=20,
        ["fYaw"]=3.16,
        ["szDesc"]="翅膀",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=4,
        ["nRoleType"]=6,
        ["nCameraIndex"]=4,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [21]=
    {
        ["nID"]=21,
        ["fYaw"]=3.16,
        ["szDesc"]="后背挂件",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=5,
        ["nRoleType"]=1,
        ["nCameraIndex"]=1,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [22]=
    {
        ["nID"]=22,
        ["fYaw"]=3.16,
        ["szDesc"]="后背挂件",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=5,
        ["nRoleType"]=2,
        ["nCameraIndex"]=2,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [23]=
    {
        ["nID"]=23,
        ["fYaw"]=3.16,
        ["szDesc"]="后背挂件",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=5,
        ["nRoleType"]=5,
        ["nCameraIndex"]=3,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [24]=
    {
        ["nID"]=24,
        ["fYaw"]=3.16,
        ["szDesc"]="后背挂件",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=5,
        ["nRoleType"]=6,
        ["nCameraIndex"]=4,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [25]=
    {
        ["nID"]=25,
        ["fYaw"]=-0.94,
        ["szDesc"]="右肩挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=6,
        ["nRoleType"]=1,
        ["nCameraIndex"]=9,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [26]=
    {
        ["nID"]=26,
        ["fYaw"]=-0.94,
        ["szDesc"]="右肩挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=6,
        ["nRoleType"]=2,
        ["nCameraIndex"]=10,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [27]=
    {
        ["nID"]=27,
        ["fYaw"]=-0.94,
        ["szDesc"]="右肩挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=6,
        ["nRoleType"]=5,
        ["nCameraIndex"]=11,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [28]=
    {
        ["nID"]=28,
        ["fYaw"]=-0.94,
        ["szDesc"]="右肩挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=6,
        ["nRoleType"]=6,
        ["nCameraIndex"]=12,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [29]=
    {
        ["nID"]=29,
        ["fYaw"]=0.94,
        ["szDesc"]="左肩挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=7,
        ["nRoleType"]=1,
        ["nCameraIndex"]=13,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [30]=
    {
        ["nID"]=30,
        ["fYaw"]=0.94,
        ["szDesc"]="左肩挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=7,
        ["nRoleType"]=2,
        ["nCameraIndex"]=14,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [31]=
    {
        ["nID"]=31,
        ["fYaw"]=0.94,
        ["szDesc"]="左肩挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=7,
        ["nRoleType"]=5,
        ["nCameraIndex"]=15,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [32]=
    {
        ["nID"]=32,
        ["fYaw"]=0.94,
        ["szDesc"]="左肩挂件",
        ["szOffset"]="4.2;0;0",
        ["nCameraID"]=7,
        ["nRoleType"]=6,
        ["nCameraIndex"]=16,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [33]=
    {
        ["nID"]=33,
        ["fYaw"]=0.05,
        ["szDesc"]="面部挂件",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=8,
        ["nRoleType"]=1,
        ["nCameraIndex"]=21,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [34]=
    {
        ["nID"]=34,
        ["fYaw"]=0.05,
        ["szDesc"]="面部挂件",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=8,
        ["nRoleType"]=2,
        ["nCameraIndex"]=22,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [35]=
    {
        ["nID"]=35,
        ["fYaw"]=0.05,
        ["szDesc"]="面部挂件",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=8,
        ["nRoleType"]=5,
        ["nCameraIndex"]=23,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [36]=
    {
        ["nID"]=36,
        ["fYaw"]=0.05,
        ["szDesc"]="面部挂件",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=8,
        ["nRoleType"]=6,
        ["nCameraIndex"]=24,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Min"
    },
    [37]=
    {
        ["nID"]=37,
        ["fYaw"]=0.05,
        ["szDesc"]="环身特效",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=9,
        ["nRoleType"]=1,
        ["nCameraIndex"]=25,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [38]=
    {
        ["nID"]=38,
        ["fYaw"]=0.05,
        ["szDesc"]="环身特效",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=9,
        ["nRoleType"]=2,
        ["nCameraIndex"]=26,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [39]=
    {
        ["nID"]=39,
        ["fYaw"]=0.05,
        ["szDesc"]="环身特效",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=9,
        ["nRoleType"]=5,
        ["nCameraIndex"]=27,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    },
    [40]=
    {
        ["nID"]=40,
        ["fYaw"]=0.05,
        ["szDesc"]="环身特效",
        ["szOffset"]="3.2;0;0",
        ["nCameraID"]=9,
        ["nRoleType"]=6,
        ["nCameraIndex"]=28,
        ["szCameraType"]="ShopRewards",
        ["szInitPosition"]="Max"
    }
}
