--*************************************** 工具生成 ***************************************
UISeasonRewardTab = 
{
    [1]=
    {
        ["nCount"]=30,
        ["nIndex"]=1,
        ["nTabType"]=5,
        ["dwTabIndex"]=40385,
        ["nAwardType"]=1
    },
    [2]=
    {
        ["nCount"]=10,
        ["nIndex"]=2,
        ["nTabType"]=5,
        ["dwTabIndex"]=85486,
        ["nAwardType"]=1
    },
    [3]=
    {
        ["nCount"]=10,
        ["nIndex"]=3,
        ["nTabType"]=5,
        ["dwTabIndex"]=33492,
        ["nAwardType"]=1
    },
    [4]=
    {
        ["nCount"]=50,
        ["nIndex"]=4,
        ["nTabType"]=5,
        ["dwTabIndex"]=18448,
        ["nAwardType"]=1
    },
    [5]=
    {
        ["nCount"]=30,
        ["nIndex"]=5,
        ["nTabType"]=5,
        ["dwTabIndex"]=44429,
        ["nAwardType"]=1
    },
    [6]=
    {
        ["nCount"]=2,
        ["nIndex"]=6,
        ["nTabType"]=5,
        ["dwTabIndex"]=45838,
        ["nAwardType"]=1
    },
    [7]=
    {
        ["nCount"]=100,
        ["nIndex"]=7,
        ["nTabType"]=5,
        ["dwTabIndex"]=24444,
        ["nAwardType"]=1
    },
    [8]=
    {
        ["nCount"]=20,
        ["nIndex"]=8,
        ["nTabType"]=5,
        ["dwTabIndex"]=31734,
        ["nAwardType"]=1
    },
    [9]=
    {
        ["nCount"]=1,
        ["nIndex"]=9,
        ["nTabType"]=5,
        ["dwTabIndex"]=81925,
        ["nAwardType"]=1
    },
    [10]=
    {
        ["nCount"]=50,
        ["nIndex"]=10,
        ["nTabType"]=5,
        ["dwTabIndex"]=53907,
        ["nAwardType"]=2
    },
    [11]=
    {
        ["nCount"]=1,
        ["nIndex"]=11,
        ["nTabType"]=5,
        ["dwTabIndex"]=40373,
        ["nAwardType"]=2
    },
    [12]=
    {
        ["nCount"]=30,
        ["nIndex"]=12,
        ["nTabType"]=5,
        ["dwTabIndex"]=34998,
        ["nAwardType"]=2
    },
    [13]=
    {
        ["nCount"]=100,
        ["nIndex"]=13,
        ["nTabType"]=5,
        ["dwTabIndex"]=34995,
        ["nAwardType"]=2
    },
    [14]=
    {
        ["nCount"]=30,
        ["nIndex"]=14,
        ["nTabType"]=5,
        ["dwTabIndex"]=81561,
        ["nAwardType"]=2
    },
    [15]=
    {
        ["nCount"]=2,
        ["nIndex"]=15,
        ["nTabType"]=5,
        ["dwTabIndex"]=45838,
        ["nAwardType"]=2
    },
    [16]=
    {
        ["nCount"]=30,
        ["nIndex"]=16,
        ["nTabType"]=5,
        ["dwTabIndex"]=43751,
        ["nAwardType"]=2
    },
    [17]=
    {
        ["nCount"]=5000,
        ["nIndex"]=17,
        ["nTabType"]=5,
        ["dwTabIndex"]=84023,
        ["nAwardType"]=2
    },
    [18]=
    {
        ["nCount"]=1,
        ["nIndex"]=18,
        ["nTabType"]=5,
        ["dwTabIndex"]=81926,
        ["nAwardType"]=2
    }
}
