--*************************************** 工具生成 ***************************************
UISelfieFilterTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=0.671053,
            [3]=0.87319,
            [4]=1
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=0.407895,
            [2]=0.754634,
            [3]=1,
            [4]=1.75
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=0.989677,
            [2]=1,
            [3]=0.723684,
            [4]=1
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.7
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=0.763158,
            [2]=1,
            [3]=0.867013,
            [4]=1.5
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=0.552632,
            [2]=1,
            [3]=0.974899,
            [4]=1.6548
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=2
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.2024
        },
        ["Shadows.Contrast"]=
        {
            [1]=0.486842,
            [2]=0.898321,
            [3]=1,
            [4]=0.2976
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=0.928987,
            [2]=1,
            [3]=0.631579,
            [4]=1.2
        },
        ["Shadows.ShadowMax"]=0.1565,
        ["Shadows.Saturation"]=
        {
            [1]=0.289474,
            [2]=0.833781,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.1905
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.2
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6500,
        ["WhiteBalence.WhiteTint"]=0
    },
    [2]=
    {
        ["nID"]=2,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=0.863035,
            [3]=0.75,
            [4]=0.6
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0.007889,
            [2]=0.014191,
            [3]=0.020005,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=0.8095,
            [2]=0.8571,
            [3]=1,
            [4]=1.2619
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1.2857,
            [2]=1.3095,
            [3]=1.1071,
            [4]=1
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.2
        },
        ["Global.Saturation"]=
        {
            [1]=0.5357,
            [2]=1.4,
            [3]=0.7143,
            [4]=1.2
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=11625,
        ["WhiteBalence.WhiteTint"]=0.0162
    },
    [3]=
    {
        ["nID"]=3,
        ["Global.Gain"]=
        {
            [1]=0.95,
            [2]=1,
            [3]=1,
            [4]=1.8
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0.024735,
            [2]=0.031006,
            [3]=0.039994,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.7976
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=0.8452,
            [2]=0.8452,
            [3]=0.8333,
            [4]=1.0833
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.4
        },
        ["Global.Saturation"]=
        {
            [1]=1.0357,
            [2]=1.0119,
            [3]=0.9881,
            [4]=0.5952
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=0.9881,
            [2]=1,
            [3]=0.9762,
            [4]=1.3
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=0.7619,
            [2]=1,
            [3]=1,
            [4]=0.9048
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6500,
        ["WhiteBalence.WhiteTint"]=0
    },
    [4]=
    {
        ["nID"]=4,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.08
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.2
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.15
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.05
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.8
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.0238
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.8
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.8
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.5
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.8
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6500,
        ["WhiteBalence.WhiteTint"]=0
    },
    [5]=
    {
        ["nID"]=5,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=0.749615,
            [3]=0.460526,
            [4]=0.9881
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=0.878289,
            [3]=0.513158,
            [4]=0.9048
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=0.873431,
            [3]=0.565789,
            [4]=1.2
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=0.9286,
            [2]=0.693076,
            [3]=0.562047,
            [4]=0.881
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Saturation"]=
        {
            [1]=0,
            [2]=0.5,
            [3]=1,
            [4]=1
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=0.969385,
            [2]=0.95142,
            [3]=0.869,
            [4]=1.0714
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1.5,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6500,
        ["WhiteBalence.WhiteTint"]=0
    },
    [6]=
    {
        ["nID"]=6,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=0.779608,
            [3]=0.473684,
            [4]=2
        },
        ["Global.Gamma"]=
        {
            [1]=0.985997,
            [2]=0.947368,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=0.769211,
            [3]=0.473684,
            [4]=1.4405
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=0.815789,
            [2]=0.88939,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.05
        },
        ["Highlights.Min"]=-0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1,
            [2]=0.929588,
            [3]=0.539474,
            [4]=1
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.0952
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.1
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.5
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6500,
        ["WhiteBalence.WhiteTint"]=0.1
    },
    [7]=
    {
        ["nID"]=7,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=1.0476,
            [3]=1.0833,
            [4]=1.1
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=0.9,
            [2]=1,
            [3]=1,
            [4]=0.65
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6500,
        ["WhiteBalence.WhiteTint"]=0
    },
    [8]=
    {
        ["nID"]=8,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=1.05,
            [3]=1,
            [4]=1.2
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1,
            [2]=0.95,
            [3]=1,
            [4]=0.96
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1.2,
            [3]=1,
            [4]=0.9
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1.2,
            [3]=0.9,
            [4]=1.1
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=0.9,
            [2]=1.2,
            [3]=0.95,
            [4]=1.05
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1.3,
            [3]=0.8,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6100,
        ["WhiteBalence.WhiteTint"]=-0.15
    },
    [9]=
    {
        ["nID"]=9,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.55
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6500,
        ["WhiteBalence.WhiteTint"]=0
    },
    [10]=
    {
        ["nID"]=10,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.5
        },
        ["Global.Gamma"]=
        {
            [1]=0.973684,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=0.513158,
            [2]=0.834665,
            [3]=1,
            [4]=2
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=0.921053,
            [2]=0.975743,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.2024
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6700,
        ["WhiteBalence.WhiteTint"]=0
    },
    [11]=
    {
        ["nID"]=11,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=0.719611,
            [3]=0.486842,
            [4]=0.5
        },
        ["Global.Gamma"]=
        {
            [1]=0.574986,
            [2]=0.513158,
            [3]=1.0595,
            [4]=1.5
        },
        ["Shadows.Gain"]=
        {
            [1]=0.2,
            [2]=0.2,
            [3]=0.2,
            [4]=1.5
        },
        ["Global.Offset"]=
        {
            [1]=0.016907,
            [2]=0.015076,
            [3]=0.033707,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=0.832237,
            [3]=0.328947,
            [4]=1.5
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1,
            [2]=1.0119,
            [3]=1,
            [4]=1.1
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=0.83,
            [3]=0.6,
            [4]=1.2
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=2
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1.2024,
            [4]=1
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=0.852639,
            [3]=0.552632,
            [4]=1.3
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=0.907895,
            [3]=1,
            [4]=0.8095
        },
        ["WhiteBalence.WhiteTemp"]=5381,
        ["WhiteBalence.WhiteTint"]=0.2162
    },
    [12]=
    {
        ["nID"]=12,
        ["Global.Gain"]=
        {
            [1]=0.772057,
            [2]=1.1071,
            [3]=0.816031,
            [4]=1.15
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0.022019,
            [2]=0.039994,
            [3]=0.03772,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1.2738,
            [2]=1.1667,
            [3]=1.0357,
            [4]=1.1
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=0.68,
            [2]=1,
            [3]=0.789474,
            [4]=1.25
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1.0476,
            [3]=1.119,
            [4]=1.4524
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.2
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1.5952,
            [2]=0.4762,
            [3]=1.131,
            [4]=0.8214
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=7676,
        ["WhiteBalence.WhiteTint"]=0.2324
    },
    [13]=
    {
        ["nID"]=13,
        ["Global.Gain"]=
        {
            [1]=1.0238,
            [2]=0.956445,
            [3]=0.754379,
            [4]=0.97
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0.029999,
            [2]=0.026505,
            [3]=0.022492,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=0.98,
            [3]=0.9,
            [4]=1
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1,
            [2]=0.960526,
            [3]=0.990132,
            [4]=1.3
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=0.98,
            [3]=0.9,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=2383,
        ["WhiteBalence.WhiteTint"]=0.342
    },
    [14]=
    {
        ["nID"]=14,
        ["Global.Gain"]=
        {
            [1]=0.896457,
            [2]=0.852632,
            [3]=1.08,
            [4]=1.5952
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1.0595,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=0.660724,
            [2]=0.5,
            [3]=1,
            [4]=1.3452
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1.059397,
            [2]=1.13,
            [3]=0.877237,
            [4]=1.32
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=0.85,
            [2]=0.85,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=0.736842,
            [2]=0.784712,
            [3]=1,
            [4]=0.869
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=0.973444,
            [3]=0.789474,
            [4]=1.2
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=0.941976,
            [2]=1,
            [3]=0.7,
            [4]=1.1
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1.631,
            [3]=0.8,
            [4]=0.9
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1.02,
            [2]=1,
            [3]=1,
            [4]=0.8
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=0.328947,
            [2]=1,
            [3]=0.753821,
            [4]=1.1548
        },
        ["Highlights.Contrast"]=
        {
            [1]=0.946153,
            [2]=1,
            [3]=0.657895,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=0.7143,
            [2]=1,
            [3]=0.7619,
            [4]=1.1
        },
        ["WhiteBalence.WhiteTemp"]=9961,
        ["WhiteBalence.WhiteTint"]=-0.0064
    },
    [15]=
    {
        ["nID"]=15,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1.0714,
            [2]=1.0714,
            [3]=0.869,
            [4]=0.7381
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=0.996407,
            [3]=0.776316,
            [4]=1.2
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.1
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=7819,
        ["WhiteBalence.WhiteTint"]=0.2312
    },
    [16]=
    {
        ["nID"]=16,
        ["Global.Gain"]=
        {
            [1]=0.631579,
            [2]=0.688619,
            [3]=1,
            [4]=1.7976
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=0.8,
            [3]=0.8,
            [4]=1.7
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=0.644737,
            [3]=0.893345,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=0.640526,
            [3]=0.486842,
            [4]=2
        },
        ["Shadows.Gamma"]=
        {
            [1]=0.578947,
            [2]=0.710976,
            [3]=1,
            [4]=1.0238
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=0.893434,
            [3]=0.828947,
            [4]=1.1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.2
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.3
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.2024
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.7024
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6500,
        ["WhiteBalence.WhiteTint"]=0
    },
    [17]=
    {
        ["nID"]=17,
        ["Global.Gain"]=
        {
            [1]=0.99862,
            [2]=1.1071,
            [3]=0.611818,
            [4]=0.5119
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0.005539,
            [2]=0.005264,
            [3]=0.020005,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=0.9643,
            [4]=1.2
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1.000913,
            [2]=1.0714,
            [3]=1.0595,
            [4]=0.9286
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0.012116,
            [2]=0.020005,
            [3]=0.012665,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Saturation"]=
        {
            [1]=0.289474,
            [2]=1,
            [3]=0.758032,
            [4]=1.1667
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1.131,
            [2]=1.0476,
            [3]=1.0476,
            [4]=1.2143
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6596,
        ["WhiteBalence.WhiteTint"]=-0.2757
    },
    [18]=
    {
        ["nID"]=18,
        ["Global.Gain"]=
        {
            [1]=0.868421,
            [2]=0.947451,
            [3]=1,
            [4]=1.5
        },
        ["Global.Gamma"]=
        {
            [1]=0.973684,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=0.513158,
            [2]=0.834665,
            [3]=1,
            [4]=2
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.7
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=0.921053,
            [2]=0.975743,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=0.710526,
            [2]=1,
            [3]=0.950284,
            [4]=1.5
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.2024
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=0.776316,
            [2]=0.786513,
            [3]=1,
            [4]=1.2024
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6700,
        ["WhiteBalence.WhiteTint"]=0
    },
    [19]=
    {
        ["nID"]=19,
        ["Global.Gain"]=
        {
            [1]=0.644737,
            [2]=0.733553,
            [3]=1,
            [4]=1.2143
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0.013718,
            [2]=0.013687,
            [3]=0.020005,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=0.918718,
            [3]=0.710526,
            [4]=1.2
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1.2381,
            [2]=1.119,
            [3]=0.7976,
            [4]=0.85
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.5
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=7676,
        ["WhiteBalence.WhiteTint"]=0.1514
    },
    [20]=
    {
        ["nID"]=20,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1.2,
            [4]=0.3
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0.010269,
            [2]=0.015244,
            [3]=0.020005,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.8
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=0.75,
            [2]=0.838917,
            [3]=1,
            [4]=0.9405
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.8
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=5881,
        ["WhiteBalence.WhiteTint"]=0.0725
    },
    [21]=
    {
        ["nID"]=21,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1,
            [2]=0.95,
            [3]=0.9,
            [4]=0.9
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Saturation"]=
        {
            [1]=0.9,
            [2]=1.25,
            [3]=1.2,
            [4]=1.2
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1.8,
            [4]=1.3
        },
        ["WhiteBalence.WhiteTemp"]=5700,
        ["WhiteBalence.WhiteTint"]=0.01
    },
    [22]=
    {
        ["nID"]=22,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=0.95213,
            [3]=0.8095,
            [4]=1
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0.039994,
            [2]=0.022629,
            [3]=0.0392,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=0.8929,
            [2]=0.86274,
            [3]=0.552188,
            [4]=1.2
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=0.708883,
            [3]=0.447368,
            [4]=1.15
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=0.89,
            [4]=1.3
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=5145,
        ["WhiteBalence.WhiteTint"]=0.4432
    },
    [23]=
    {
        ["nID"]=23,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=0.923589,
            [3]=0.842105,
            [4]=1
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=0.781579,
            [2]=0.886676,
            [3]=0.99,
            [4]=1.1548
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1.03,
            [2]=0.72,
            [3]=0.43,
            [4]=1.08
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Saturation"]=
        {
            [1]=0.75,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.0476
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1.05,
            [2]=1.04,
            [3]=0.98,
            [4]=0.93
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6144,
        ["WhiteBalence.WhiteTint"]=0.114286
    },
    [24]=
    {
        ["nID"]=24,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=0.951667,
            [3]=0.842105,
            [4]=0.9
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=0.988605,
            [3]=0.921053,
            [4]=1.05
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=0.94,
            [3]=0.87,
            [4]=1.2024
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.95
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.98
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.85
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=0.949831,
            [3]=0.8452,
            [4]=1
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.9
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.95
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=7500,
        ["WhiteBalence.WhiteTint"]=0
    },
    [25]=
    {
        ["nID"]=25,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.85
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.05
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.9
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.8
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.9
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.05
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.8
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.8
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.05
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6500,
        ["WhiteBalence.WhiteTint"]=0
    },
    [26]=
    {
        ["nID"]=26,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.2
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.2
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.15
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.05
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.1
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6500,
        ["WhiteBalence.WhiteTint"]=0
    },
    [27]=
    {
        ["nID"]=27,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=0.959626,
            [3]=0.802632,
            [4]=1.05
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=0.963816,
            [3]=0.8929,
            [4]=1.2
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.85
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.95
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.15
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.95
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.05
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.95
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.08
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6611,
        ["WhiteBalence.WhiteTint"]=0.0718
    },
    [28]=
    {
        ["nID"]=28,
        ["Global.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Global.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Gain"]=
        {
            [1]=1,
            [2]=0.959626,
            [3]=0.802632,
            [4]=1.05
        },
        ["Global.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Gain"]=
        {
            [1]=1,
            [2]=0.963816,
            [3]=0.8929,
            [4]=1.2
        },
        ["Shadows.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Min"]=0.5,
        ["Midtones.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Global.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.85
        },
        ["Highlights.Gain"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Midtones.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Highlights.Gamma"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Shadows.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.95
        },
        ["Global.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.15
        },
        ["Highlights.Offset"]=
        {
            [1]=0,
            [2]=0,
            [3]=0,
            [4]=0
        },
        ["Midtones.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.95
        },
        ["Shadows.ShadowMax"]=0.09,
        ["Shadows.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.05
        },
        ["Highlights.Contrast"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=0.95
        },
        ["Midtones.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1.08
        },
        ["Global.SceneColorTint"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["Highlights.Saturation"]=
        {
            [1]=1,
            [2]=1,
            [3]=1,
            [4]=1
        },
        ["WhiteBalence.WhiteTemp"]=6611,
        ["WhiteBalence.WhiteTint"]=0.0718
    }
}
