--*************************************** 工具生成 ***************************************
UIShortcutInteractionTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["VKey"]="W",
        ["szDef"]="Forward",
        ["szName"]="前进",
        ["szType"]="OSBind",
        ["szTitle"]="移动操作",
        ["paramArgs"]="MoveUp",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [2]=
    {
        ["nID"]=2,
        ["VKey"]="S",
        ["szDef"]="Backward",
        ["szName"]="后退",
        ["szType"]="OSBind",
        ["szTitle"]="移动操作",
        ["paramArgs"]="MoveDown",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [3]=
    {
        ["nID"]=3,
        ["VKey"]="A",
        ["szDef"]="TurnLeft",
        ["szName"]="左平移",
        ["szType"]="OSBind",
        ["szTitle"]="移动操作",
        ["paramArgs"]="MoveLeft",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [4]=
    {
        ["nID"]=4,
        ["VKey"]="D",
        ["szDef"]="TurnRight",
        ["szName"]="右平移",
        ["szType"]="OSBind",
        ["szTitle"]="移动操作",
        ["paramArgs"]="MoveRight",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [5]=
    {
        ["nID"]=5,
        ["VKey"]="Space",
        ["szDef"]="Jump",
        ["szName"]="跳跃",
        ["szType"]="Action",
        ["szTitle"]="角色动作",
        ["paramArgs"]="Jump",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="VK",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [6]=
    {
        ["nID"]=6,
        ["VKey"]="T",
        ["szDef"]="RideHorse",
        ["szName"]="骑乘",
        ["szType"]="Action",
        ["szTitle"]="角色动作",
        ["paramArgs"]="Riding",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [7]=
    {
        ["nID"]=7,
        ["VKey"]="R",
        ["szDef"]="SwitchSkill",
        ["szName"]="切换技能栏",
        ["szType"]="Action",
        ["szTitle"]="角色动作",
        ["paramArgs"]="SwitchSkill",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [8]=
    {
        ["nID"]=8,
        ["VKey"]="V",
        ["szDef"]="Meditation",
        ["szName"]="打坐/起立",
        ["szType"]="Action",
        ["szTitle"]="角色动作",
        ["paramArgs"]="Meditation",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [9]=
    {
        ["nID"]=9,
        ["VKey"]="X",
        ["szDef"]="Transfer",
        ["szName"]="神行",
        ["szType"]="Action",
        ["szTitle"]="角色动作",
        ["paramArgs"]="Transfer",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [10]=
    {
        ["nID"]=10,
        ["VKey"]="OEM2",
        ["szDef"]="SwitchWalk",
        ["szName"]="切换走路/跑步",
        ["szType"]="Hotkey",
        ["szTitle"]="移动操作",
        ["paramArgs"]="1",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [11]=
    {
        ["nID"]=11,
        ["VKey"]="G",
        ["szDef"]="AutoForward",
        ["szName"]="自动前进/续飞/连冲",
        ["szType"]="Hotkey",
        ["szTitle"]="移动操作",
        ["paramArgs"]="17",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [12]=
    {
        ["nID"]=12,
        ["VKey"]="Ctrl+G",
        ["szDef"]="FollowTarget",
        ["szName"]="跟随目标",
        ["szType"]="Hotkey",
        ["szTitle"]="移动操作",
        ["paramArgs"]="2",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [13]=
    {
        ["nID"]=13,
        ["VKey"]="F",
        ["szDef"]="Interaction",
        ["szName"]="功能互动键",
        ["szType"]="Action",
        ["szTitle"]="移动操作",
        ["paramArgs"]="Picker",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [14]=
    {
        ["nID"]=14,
        ["VKey"]="Z",
        ["szDef"]="ALLPicker",
        ["szName"]="全部拾取",
        ["szType"]="Action",
        ["szTitle"]="移动操作",
        ["paramArgs"]="ALLPicker",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [15]=
    {
        ["nID"]=15,
        ["VKey"]="1",
        ["szDef"]="SkillSlot1",
        ["szName"]="技能槽位1",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="SkillSlot1",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="VK",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [16]=
    {
        ["nID"]=16,
        ["VKey"]="2",
        ["szDef"]="SkillSlot2",
        ["szName"]="技能槽位2",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="SkillSlot2",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="VK",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [17]=
    {
        ["nID"]=17,
        ["VKey"]="3",
        ["szDef"]="SkillSlot3",
        ["szName"]="技能槽位3",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="SkillSlot3",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="VK",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [18]=
    {
        ["nID"]=18,
        ["VKey"]="4",
        ["szDef"]="SkillSlot4",
        ["szName"]="技能槽位4",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="SkillSlot4",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="VK",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [19]=
    {
        ["nID"]=19,
        ["VKey"]="5",
        ["szDef"]="SkillSlot5",
        ["szName"]="技能槽位5",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="SkillSlot5",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="VK",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [20]=
    {
        ["nID"]=20,
        ["VKey"]="6",
        ["szDef"]="SkillSlot6",
        ["szName"]="技能槽位6",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="SkillSlot6",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="VK",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [21]=
    {
        ["nID"]=21,
        ["VKey"]="Q",
        ["szDef"]="SpecialSprint",
        ["szName"]="门派轻功",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="SpecialSprint",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="VK",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [22]=
    {
        ["nID"]=22,
        ["VKey"]="E",
        ["szDef"]="FuYao",
        ["szName"]="扶摇",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="FuYao",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="VK",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [23]=
    {
        ["nID"]=23,
        ["VKey"]="OEM3",
        ["szDef"]="NieYun",
        ["szName"]="蹑云逐月/前飘",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="Roll",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="VK",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [24]=
    {
        ["nID"]=24,
        ["VKey"]="7",
        ["szDef"]="SkillAuto",
        ["szName"]="助手",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="SkillAuto",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="VK",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [25]=
    {
        ["nID"]=25,
        ["VKey"]="8",
        ["szDef"]="SkillQuick",
        ["szName"]="特殊道具/团队标记",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="SkillQuick",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="VK",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [26]=
    {
        ["nID"]=26,
        ["VKey"]="Esc",
        ["szDef"]="PanelSystemMenu",
        ["szName"]="菜单界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="1",
        ["nMaxKeyLen"]=0,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [27]=
    {
        ["nID"]=27,
        ["VKey"]="",
        ["szDef"]="PanelGameSettings",
        ["szName"]="设置界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="38",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [28]=
    {
        ["nID"]=28,
        ["VKey"]="Enter",
        ["szDef"]="PanelChat",
        ["szName"]="聊天界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="39",
        ["nMaxKeyLen"]=0,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [29]=
    {
        ["nID"]=29,
        ["VKey"]="Shift+F1",
        ["szDef"]="WidgetQuickUsedTip",
        ["szName"]="快捷使用界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="40",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [30]=
    {
        ["nID"]=30,
        ["VKey"]="Shift+F2",
        ["szDef"]="PanelQuickOperation",
        ["szName"]="快捷操作界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="41",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [31]=
    {
        ["nID"]=31,
        ["VKey"]="Shift+M",
        ["szDef"]="PanelHome",
        ["szName"]="家园界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="13",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [32]=
    {
        ["nID"]=32,
        ["VKey"]="Shift+E",
        ["szDef"]="PanelExteriorMain_Wardrobe",
        ["szName"]="外观商城界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="2",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [33]=
    {
        ["nID"]=33,
        ["VKey"]="Shift+R",
        ["szDef"]="PanelTopUpMain",
        ["szName"]="充值界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="32",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [34]=
    {
        ["nID"]=34,
        ["VKey"]="L",
        ["szDef"]="PanelTask",
        ["szName"]="任务界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="5",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [35]=
    {
        ["nID"]=35,
        ["VKey"]="B",
        ["szDef"]="PanelHalfBag",
        ["szName"]="背包界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="3",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [36]=
    {
        ["nID"]=36,
        ["VKey"]="C",
        ["szDef"]="PanelCharacter",
        ["szName"]="角色界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="7",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [37]=
    {
        ["nID"]=37,
        ["VKey"]="Shift+F",
        ["szDef"]="PanelPowerUp",
        ["szName"]="强化界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="16",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [38]=
    {
        ["nID"]=38,
        ["VKey"]="P",
        ["szDef"]="PanelSkillNew",
        ["szName"]="武学界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="4",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [39]=
    {
        ["nID"]=39,
        ["VKey"]="I",
        ["szDef"]="PanelLifeMain",
        ["szName"]="技艺界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="23",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [40]=
    {
        ["nID"]=40,
        ["VKey"]="Shift+T",
        ["szDef"]="PanelSaddleHorse",
        ["szName"]="坐骑界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="15",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [41]=
    {
        ["nID"]=41,
        ["VKey"]="Ctrl+A",
        ["szDef"]="PanelPvPMatching",
        ["szName"]="名剑大会界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="44",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [42]=
    {
        ["nID"]=42,
        ["VKey"]="K",
        ["szDef"]="PanelFactionManagement",
        ["szName"]="帮会界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="14",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [43]=
    {
        ["nID"]=43,
        ["VKey"]="O",
        ["szDef"]="PanelChatSocial",
        ["szName"]="社交界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="12",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [44]=
    {
        ["nID"]=44,
        ["VKey"]="U",
        ["szDef"]="PanelApprenticeNew",
        ["szName"]="师徒界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="34",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [45]=
    {
        ["nID"]=45,
        ["VKey"]="M",
        ["szDef"]="PanelMiddleMap",
        ["szName"]="地图界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="30",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [46]=
    {
        ["nID"]=46,
        ["VKey"]="H",
        ["szDef"]="PanelCollection",
        ["szName"]="大侠之路",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="52",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [47]=
    {
        ["nID"]=47,
        ["VKey"]="N",
        ["szDef"]="PanelHuaELou",
        ["szName"]="花萼楼",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="31",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [48]=
    {
        ["nID"]=48,
        ["VKey"]="Shift+H",
        ["szDef"]="PanelTutorialCollection",
        ["szName"]="帮助与反馈",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="33",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [49]=
    {
        ["nID"]=49,
        ["VKey"]="Ctrl+C",
        ["szDef"]="PanelPartner",
        ["szName"]="红尘侠影界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="22",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [50]=
    {
        ["nID"]=50,
        ["VKey"]="J",
        ["szDef"]="PanelBattleFieldInformation",
        ["szName"]="阵营战场界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="59",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [51]=
    {
        ["nID"]=51,
        ["VKey"]="Ctrl+L",
        ["szDef"]="PanelImpasseMatching",
        ["szName"]="绝境战场界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="11",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [52]=
    {
        ["nID"]=52,
        ["VKey"]="Alt+J",
        ["szDef"]="PanelReadMain",
        ["szName"]="阅读界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="35",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [53]=
    {
        ["nID"]=53,
        ["VKey"]="Ctrl+T",
        ["szDef"]="PanelTeam",
        ["szName"]="队伍招募",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="42",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [54]=
    {
        ["nID"]=54,
        ["VKey"]="Ctrl+P",
        ["szDef"]="PanelPetMap",
        ["szName"]="宠物界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="19",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [55]=
    {
        ["nID"]=55,
        ["VKey"]="Y",
        ["szDef"]="PanelAchievementMian",
        ["szName"]="隐元秘鉴",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="18",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [56]=
    {
        ["nID"]=56,
        ["VKey"]="Ctrl+M",
        ["szDef"]="PanelCampMap",
        ["szName"]="战争沙盘",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="43",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [57]=
    {
        ["nID"]=57,
        ["VKey"]="Ctrl+U",
        ["szDef"]="ShowPanel",
        ["szName"]="显示/隐藏界面",
        ["szType"]="Hotkey",
        ["szTitle"]="界面相关",
        ["paramArgs"]="16",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [58]=
    {
        ["nID"]=58,
        ["VKey"]="Ctrl+J",
        ["szDef"]="PanelQiYu",
        ["szName"]="奇遇界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="20",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [59]=
    {
        ["nID"]=59,
        ["VKey"]="Ctrl+H",
        ["szDef"]="PanelCamera",
        ["szName"]="幻境云图界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="45",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [60]=
    {
        ["nID"]=60,
        ["VKey"]="Shift+C",
        ["szDef"]="PanelActivityCalendar",
        ["szName"]="活动界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="6",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [61]=
    {
        ["nID"]=61,
        ["VKey"]="Shift+B",
        ["szDef"]="PanelDungeonEntrance",
        ["szName"]="秘境界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="8",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [62]=
    {
        ["nID"]=62,
        ["VKey"]="Ctrl+V",
        ["szDef"]="PanelFengYunLu",
        ["szName"]="风云录",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="21",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [63]=
    {
        ["nID"]=63,
        ["VKey"]="Ctrl+R",
        ["szDef"]="PanelRenownList",
        ["szName"]="声望界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="24",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [64]=
    {
        ["nID"]=64,
        ["VKey"]="",
        ["szDef"]="PanelWuLinTongJian",
        ["szName"]="武林通鉴",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="27",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [65]=
    {
        ["nID"]=65,
        ["VKey"]="Shift+L",
        ["szDef"]="PanelSwordMemories",
        ["szName"]="剑侠录",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="54",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [66]=
    {
        ["nID"]=66,
        ["VKey"]="Shift+G",
        ["szDef"]="PanelWuDou",
        ["szName"]="武斗值界面",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="37",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [67]=
    {
        ["nID"]=67,
        ["VKey"]="Alt+H",
        ["szDef"]="TreasureHunting",
        ["szName"]="寻宝",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="46",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [68]=
    {
        ["nID"]=68,
        ["VKey"]="",
        ["szDef"]="WidgetDomesticate",
        ["szName"]="驯养",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="47",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [69]=
    {
        ["nID"]=69,
        ["VKey"]="Ctrl+E",
        ["szDef"]="PanelExteriorMain",
        ["szName"]="外观预设",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="48",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [70]=
    {
        ["nID"]=70,
        ["VKey"]="Ctrl+K",
        ["szDef"]="PanelJiangHuBaiTai",
        ["szName"]="江湖百态",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="28",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [71]=
    {
        ["nID"]=71,
        ["VKey"]="Ctrl+Z",
        ["szDef"]="PanelQianLiFaZhu",
        ["szName"]="千里伐逐",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="49",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [72]=
    {
        ["nID"]=72,
        ["VKey"]="Ctrl+B",
        ["szDef"]="PanelEquipStore",
        ["szName"]="装备物资",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="17",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [73]=
    {
        ["nID"]=73,
        ["VKey"]="",
        ["szDef"]="PanelPersonalTitle",
        ["szName"]="称号",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="26",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [74]=
    {
        ["nID"]=74,
        ["VKey"]="",
        ["szDef"]="PanelBenefits",
        ["szName"]="行记",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="50",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [75]=
    {
        ["nID"]=75,
        ["VKey"]="",
        ["szDef"]="PanelBubbleInformation",
        ["szName"]="消息提示",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="51",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [76]=
    {
        ["nID"]=76,
        ["VKey"]="",
        ["szDef"]="PanelEmail",
        ["szName"]="邮件",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="36",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [77]=
    {
        ["nID"]=77,
        ["VKey"]="",
        ["szDef"]="WidgetCamp",
        ["szName"]="阵营",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="10",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [78]=
    {
        ["nID"]=78,
        ["VKey"]="",
        ["szDef"]="WidgetAthletics",
        ["szName"]="竞技",
        ["szType"]="Menu",
        ["szTitle"]="界面相关",
        ["paramArgs"]="9",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [79]=
    {
        ["nID"]=79,
        ["VKey"]="F1",
        ["szDef"]="SelectSelf",
        ["szName"]="选择自己",
        ["szType"]="Hotkey",
        ["szTitle"]="目标选择",
        ["paramArgs"]="3",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [80]=
    {
        ["nID"]=80,
        ["VKey"]="F2",
        ["szDef"]="SelectTeammate1",
        ["szName"]="选择队友1",
        ["szType"]="Hotkey",
        ["szTitle"]="目标选择",
        ["paramArgs"]="4",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [81]=
    {
        ["nID"]=81,
        ["VKey"]="F3",
        ["szDef"]="SelectTeammate2",
        ["szName"]="选择队友2",
        ["szType"]="Hotkey",
        ["szTitle"]="目标选择",
        ["paramArgs"]="5",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [82]=
    {
        ["nID"]=82,
        ["VKey"]="F4",
        ["szDef"]="SelectTeammate3",
        ["szName"]="选择队友3",
        ["szType"]="Hotkey",
        ["szTitle"]="目标选择",
        ["paramArgs"]="6",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [83]=
    {
        ["nID"]=83,
        ["VKey"]="F5",
        ["szDef"]="SelectTeammate4",
        ["szName"]="选择队友4",
        ["szType"]="Hotkey",
        ["szTitle"]="目标选择",
        ["paramArgs"]="7",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [84]=
    {
        ["nID"]=84,
        ["VKey"]="",
        ["szDef"]="SearchAllies",
        ["szName"]="选择盟友",
        ["szType"]="Hotkey",
        ["szTitle"]="目标选择",
        ["paramArgs"]="8",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [85]=
    {
        ["nID"]=85,
        ["VKey"]="Tab",
        ["szDef"]="SelectEnemy",
        ["szName"]="选择敌人",
        ["szType"]="Action",
        ["szTitle"]="目标选择",
        ["paramArgs"]="Target",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [86]=
    {
        ["nID"]=86,
        ["VKey"]="Ctrl+1",
        ["szDef"]="LockTarget",
        ["szName"]="目标锁定",
        ["szType"]="Action",
        ["szTitle"]="目标选择",
        ["paramArgs"]="LockTarget",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [87]=
    {
        ["nID"]=87,
        ["VKey"]="MouseWheelUp",
        ["szDef"]="CameraZoomIn",
        ["szName"]="推进镜头",
        ["szType"]="Hotkey",
        ["szTitle"]="其它设置",
        ["paramArgs"]="20",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [88]=
    {
        ["nID"]=88,
        ["VKey"]="MouseWheelDown",
        ["szDef"]="CameraZoomOut",
        ["szName"]="拉远镜头",
        ["szType"]="Hotkey",
        ["szTitle"]="其它设置",
        ["paramArgs"]="21",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [89]=
    {
        ["nID"]=89,
        ["VKey"]="F11",
        ["szDef"]="CamaraReset",
        ["szName"]="重置镜头",
        ["szType"]="Hotkey",
        ["szTitle"]="其它设置",
        ["paramArgs"]="9",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [90]=
    {
        ["nID"]=90,
        ["VKey"]="",
        ["szDef"]="CameraUp",
        ["szName"]="抬起镜头",
        ["szType"]="Hotkey",
        ["szTitle"]="其它设置",
        ["paramArgs"]="22",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [91]=
    {
        ["nID"]=91,
        ["VKey"]="",
        ["szDef"]="CameraDown",
        ["szName"]="低下镜头",
        ["szType"]="Hotkey",
        ["szTitle"]="其它设置",
        ["paramArgs"]="23",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [92]=
    {
        ["nID"]=92,
        ["VKey"]="Ctrl+Shift+N",
        ["szDef"]="ShowNPC",
        ["szName"]="显示/隐藏NPC",
        ["szType"]="Hotkey",
        ["szTitle"]="其它设置",
        ["paramArgs"]="10",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [93]=
    {
        ["nID"]=93,
        ["VKey"]="Ctrl+Shift+P",
        ["szDef"]="SwitchPlayerDisplay",
        ["szName"]="切换玩家显示模式",
        ["szType"]="Hotkey",
        ["szTitle"]="其它设置",
        ["paramArgs"]="11",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [94]=
    {
        ["nID"]=94,
        ["VKey"]="Ctrl+Shift+OEMComma",
        ["szDef"]="ClipCursor",
        ["szName"]="控制鼠标不可离开游戏窗口",
        ["szType"]="Hotkey",
        ["szTitle"]="其它设置",
        ["paramArgs"]="18",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {
            [1]="Platform.IsWindows()"
        }
    },
    [95]=
    {
        ["nID"]=95,
        ["VKey"]="",
        ["szDef"]="PartnerAttack",
        ["szName"]="攻击",
        ["szType"]="Hotkey",
        ["szTitle"]="助战侠客",
        ["paramArgs"]="13",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [96]=
    {
        ["nID"]=96,
        ["VKey"]="",
        ["szDef"]="PartnerFollow",
        ["szName"]="跟随",
        ["szType"]="Hotkey",
        ["szTitle"]="助战侠客",
        ["paramArgs"]="14",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [97]=
    {
        ["nID"]=97,
        ["VKey"]="",
        ["szDef"]="PartnerStop",
        ["szName"]="停留",
        ["szType"]="Hotkey",
        ["szTitle"]="助战侠客",
        ["paramArgs"]="15",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [98]=
    {
        ["nID"]=98,
        ["VKey"]="",
        ["szDef"]="PartnerTankAttack",
        ["szName"]="开战",
        ["szType"]="Hotkey",
        ["szTitle"]="助战侠客",
        ["paramArgs"]="19",
        ["nMaxKeyLen"]=3,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [99]=
    {
        ["nID"]=99,
        ["VKey"]="Alt+1",
        ["szDef"]="ActionBar1",
        ["szName"]="槽位1",
        ["szType"]="Action",
        ["szTitle"]="动态快捷栏相关",
        ["paramArgs"]="ActionBar1",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [100]=
    {
        ["nID"]=100,
        ["VKey"]="Alt+2",
        ["szDef"]="ActionBar2",
        ["szName"]="槽位2",
        ["szType"]="Action",
        ["szTitle"]="动态快捷栏相关",
        ["paramArgs"]="ActionBar2",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [101]=
    {
        ["nID"]=101,
        ["VKey"]="Alt+3",
        ["szDef"]="ActionBar3",
        ["szName"]="槽位3",
        ["szType"]="Action",
        ["szTitle"]="动态快捷栏相关",
        ["paramArgs"]="ActionBar3",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [102]=
    {
        ["nID"]=102,
        ["VKey"]="Alt+4",
        ["szDef"]="ActionBar4",
        ["szName"]="槽位4",
        ["szType"]="Action",
        ["szTitle"]="动态快捷栏相关",
        ["paramArgs"]="ActionBar4",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [103]=
    {
        ["nID"]=103,
        ["VKey"]="Alt+5",
        ["szDef"]="ActionBar5",
        ["szName"]="槽位5",
        ["szType"]="Action",
        ["szTitle"]="动态快捷栏相关",
        ["paramArgs"]="ActionBar5",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [104]=
    {
        ["nID"]=104,
        ["VKey"]="Alt+6",
        ["szDef"]="ActionBar6",
        ["szName"]="槽位6",
        ["szType"]="Action",
        ["szTitle"]="动态快捷栏相关",
        ["paramArgs"]="ActionBar6",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [105]=
    {
        ["nID"]=105,
        ["VKey"]="Alt+7",
        ["szDef"]="ActionBar7",
        ["szName"]="槽位7",
        ["szType"]="Action",
        ["szTitle"]="动态快捷栏相关",
        ["paramArgs"]="ActionBar7",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [106]=
    {
        ["nID"]=106,
        ["VKey"]="Alt+8",
        ["szDef"]="ActionBar8",
        ["szName"]="槽位8",
        ["szType"]="Action",
        ["szTitle"]="动态快捷栏相关",
        ["paramArgs"]="ActionBar8",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [107]=
    {
        ["nID"]=107,
        ["VKey"]="Alt+9",
        ["szDef"]="ActionBar9",
        ["szName"]="槽位9",
        ["szType"]="Action",
        ["szTitle"]="动态快捷栏相关",
        ["paramArgs"]="ActionBar9",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [108]=
    {
        ["nID"]=108,
        ["VKey"]="Alt+0",
        ["szDef"]="ActionBar10",
        ["szName"]="槽位10",
        ["szType"]="Action",
        ["szTitle"]="动态快捷栏相关",
        ["paramArgs"]="ActionBar10",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [109]=
    {
        ["nID"]=109,
        ["VKey"]="Alt+OEM3",
        ["szDef"]="ActionBarSwitch",
        ["szName"]="动态快捷栏切页",
        ["szType"]="Action",
        ["szTitle"]="动态快捷栏相关",
        ["paramArgs"]="ActionBarSwitch",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [110]=
    {
        ["nID"]=110,
        ["VKey"]="9",
        ["szDef"]="SkillSlot11",
        ["szName"]="动态技能栏额外槽位",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="SkillSlot11",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="VK",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [111]=
    {
        ["nID"]=111,
        ["VKey"]="1",
        ["szDef"]="DXSkillSlot1",
        ["szName"]="旗舰技能槽位1",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot1",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [112]=
    {
        ["nID"]=112,
        ["VKey"]="2",
        ["szDef"]="DXSkillSlot2",
        ["szName"]="旗舰技能槽位2",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot2",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [113]=
    {
        ["nID"]=113,
        ["VKey"]="3",
        ["szDef"]="DXSkillSlot3",
        ["szName"]="旗舰技能槽位3",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot3",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [114]=
    {
        ["nID"]=114,
        ["VKey"]="4",
        ["szDef"]="DXSkillSlot4",
        ["szName"]="旗舰技能槽位4",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot4",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [115]=
    {
        ["nID"]=115,
        ["VKey"]="5",
        ["szDef"]="DXSkillSlot5",
        ["szName"]="旗舰技能槽位5",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot5",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [116]=
    {
        ["nID"]=116,
        ["VKey"]="6",
        ["szDef"]="DXSkillSlot6",
        ["szName"]="旗舰技能槽位6",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot6",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [117]=
    {
        ["nID"]=117,
        ["VKey"]="7",
        ["szDef"]="DXSkillSlot7",
        ["szName"]="旗舰技能槽位7",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot7",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [118]=
    {
        ["nID"]=118,
        ["VKey"]="8",
        ["szDef"]="DXSkillSlot8",
        ["szName"]="旗舰技能槽位8",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot8",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [119]=
    {
        ["nID"]=119,
        ["VKey"]="9",
        ["szDef"]="DXSkillSlot9",
        ["szName"]="旗舰技能槽位9",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot9",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [120]=
    {
        ["nID"]=120,
        ["VKey"]="0",
        ["szDef"]="DXSkillSlot10",
        ["szName"]="旗舰技能槽位10",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot10",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [121]=
    {
        ["nID"]=121,
        ["VKey"]="OEMMinus",
        ["szDef"]="DXSkillSlot11",
        ["szName"]="旗舰技能槽位11",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot11",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [122]=
    {
        ["nID"]=122,
        ["VKey"]="Shift+1",
        ["szDef"]="DXSkillSlot12",
        ["szName"]="旗舰技能槽位12",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot12",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [123]=
    {
        ["nID"]=123,
        ["VKey"]="Shift+2",
        ["szDef"]="DXSkillSlot13",
        ["szName"]="旗舰技能槽位13",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot13",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [124]=
    {
        ["nID"]=124,
        ["VKey"]="Shift+3",
        ["szDef"]="DXSkillSlot14",
        ["szName"]="旗舰技能槽位14",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot14",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [125]=
    {
        ["nID"]=125,
        ["VKey"]="Shift+4",
        ["szDef"]="DXSkillSlot15",
        ["szName"]="旗舰技能槽位15",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot15",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [126]=
    {
        ["nID"]=126,
        ["VKey"]="Shift+5",
        ["szDef"]="DXSkillSlot16",
        ["szName"]="旗舰技能槽位16",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot16",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [127]=
    {
        ["nID"]=127,
        ["VKey"]="Shift+6",
        ["szDef"]="DXSkillSlot17",
        ["szName"]="旗舰技能槽位17",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot17",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [128]=
    {
        ["nID"]=128,
        ["VKey"]="Shift+7",
        ["szDef"]="DXSkillSlot18",
        ["szName"]="旗舰技能槽位18",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot18",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [129]=
    {
        ["nID"]=129,
        ["VKey"]="Shift+8",
        ["szDef"]="DXSkillSlot19",
        ["szName"]="旗舰技能槽位19",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot19",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [130]=
    {
        ["nID"]=130,
        ["VKey"]="Shift+9",
        ["szDef"]="DXSkillSlot20",
        ["szName"]="旗舰技能槽位20",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot20",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [131]=
    {
        ["nID"]=131,
        ["VKey"]="Shift+0",
        ["szDef"]="DXSkillSlot21",
        ["szName"]="旗舰技能槽位21",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot21",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [132]=
    {
        ["nID"]=132,
        ["VKey"]="Shift+OEMMinus",
        ["szDef"]="DXSkillSlot22",
        ["szName"]="旗舰技能槽位22",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot22",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [133]=
    {
        ["nID"]=133,
        ["VKey"]="Alt+Z",
        ["szDef"]="DXSkillSlot23",
        ["szName"]="旗舰技能槽位23",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot23",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [134]=
    {
        ["nID"]=134,
        ["VKey"]="Alt+X",
        ["szDef"]="DXSkillSlot24",
        ["szName"]="旗舰技能槽位24",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot24",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [135]=
    {
        ["nID"]=135,
        ["VKey"]="Alt+C",
        ["szDef"]="DXSkillSlot25",
        ["szName"]="旗舰技能槽位25",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlot25",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [136]=
    {
        ["nID"]=136,
        ["VKey"]="Alt+B",
        ["szDef"]="DXSkillHouChe",
        ["szName"]="旗舰后撤",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillHouChe",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [137]=
    {
        ["nID"]=137,
        ["VKey"]="Space",
        ["szDef"]="DXSkillJump",
        ["szName"]="旗舰跳跃",
        ["szType"]="Action",
        ["szTitle"]="角色动作",
        ["paramArgs"]="DXSkillJump",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [138]=
    {
        ["nID"]=138,
        ["VKey"]="Shift+J",
        ["szDef"]="DXSkillAuto",
        ["szName"]="旗舰武学助手",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXWidgetSkillAuto",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [139]=
    {
        ["nID"]=139,
        ["VKey"]="Alt+R",
        ["szDef"]="DXSkillSwitchPage",
        ["szName"]="旗舰切换技能页",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXWidgetSwitchPage",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [140]=
    {
        ["nID"]=140,
        ["VKey"]="OEM3",
        ["szDef"]="DXSkillSlotNieYun",
        ["szName"]="旗舰蹑云",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSlotNieYun",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [141]=
    {
        ["nID"]=141,
        ["VKey"]="Alt+V",
        ["szDef"]="DXSkillLingXiao",
        ["szName"]="旗舰凌霄揽胜",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillLingXiao",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [142]=
    {
        ["nID"]=142,
        ["VKey"]="Alt+N",
        ["szDef"]="DXSkillYaoTai",
        ["szName"]="旗舰瑶台枕鹤",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillYaoTai",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [143]=
    {
        ["nID"]=143,
        ["VKey"]="Alt+M",
        ["szDef"]="DXSkillYingFeng",
        ["szName"]="旗舰迎风回浪",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillYingFeng",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [144]=
    {
        ["nID"]=144,
        ["VKey"]="E",
        ["szDef"]="DXSkillFuYao",
        ["szName"]="旗舰扶摇",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillFuYao",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [145]=
    {
        ["nID"]=145,
        ["VKey"]="Ctrl+2",
        ["szDef"]="DXSkillSpecial1",
        ["szName"]="旗舰特殊技能槽位1",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial1",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [146]=
    {
        ["nID"]=146,
        ["VKey"]="Ctrl+3",
        ["szDef"]="DXSkillSpecial2",
        ["szName"]="旗舰特殊技能槽位2",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial2",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [147]=
    {
        ["nID"]=147,
        ["VKey"]="Ctrl+4",
        ["szDef"]="DXSkillSpecial3",
        ["szName"]="旗舰特殊技能槽位3",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial3",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [148]=
    {
        ["nID"]=148,
        ["VKey"]="Ctrl+5",
        ["szDef"]="DXSkillSpecial4",
        ["szName"]="旗舰特殊技能槽位4",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial4",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [149]=
    {
        ["nID"]=149,
        ["VKey"]="Ctrl+6",
        ["szDef"]="DXSkillSpecial5",
        ["szName"]="旗舰特殊技能槽位5",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial5",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [150]=
    {
        ["nID"]=150,
        ["VKey"]="Ctrl+7",
        ["szDef"]="DXSkillSpecial6",
        ["szName"]="旗舰特殊技能槽位6",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial6",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [151]=
    {
        ["nID"]=151,
        ["VKey"]="Ctrl+8",
        ["szDef"]="DXSkillSpecial7",
        ["szName"]="旗舰特殊技能槽位7",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial7",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [152]=
    {
        ["nID"]=152,
        ["VKey"]="Ctrl+9",
        ["szDef"]="DXSkillSpecial8",
        ["szName"]="旗舰特殊技能槽位8",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial8",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [153]=
    {
        ["nID"]=153,
        ["VKey"]="Ctrl+0",
        ["szDef"]="DXSkillSpecial9",
        ["szName"]="旗舰特殊技能槽位9",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial9",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [154]=
    {
        ["nID"]=154,
        ["VKey"]="Ctrl+F1",
        ["szDef"]="DXSkillSpecial10",
        ["szName"]="旗舰特殊技能槽位10",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial10",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [155]=
    {
        ["nID"]=155,
        ["VKey"]="Ctrl+F2",
        ["szDef"]="DXSkillSpecial11",
        ["szName"]="旗舰特殊技能槽位11",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial11",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [156]=
    {
        ["nID"]=156,
        ["VKey"]="Ctrl+F3",
        ["szDef"]="DXSkillSpecial12",
        ["szName"]="旗舰特殊技能槽位12",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial12",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [157]=
    {
        ["nID"]=157,
        ["VKey"]="Ctrl+F4",
        ["szDef"]="DXSkillSpecial13",
        ["szName"]="旗舰特殊技能槽位13",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial13",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [158]=
    {
        ["nID"]=158,
        ["VKey"]="Ctrl+F5",
        ["szDef"]="DXSkillSpecial14",
        ["szName"]="旗舰特殊技能槽位14",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial14",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [159]=
    {
        ["nID"]=159,
        ["VKey"]="Ctrl+F6",
        ["szDef"]="DXSkillSpecial15",
        ["szName"]="旗舰特殊技能槽位15",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial15",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [160]=
    {
        ["nID"]=160,
        ["VKey"]="Ctrl+F7",
        ["szDef"]="DXSkillSpecial16",
        ["szName"]="旗舰特殊技能槽位16",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillSpecial16",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    },
    [161]=
    {
        ["nID"]=161,
        ["VKey"]="Alt+Q",
        ["szDef"]="DXSkillQuickUse",
        ["szName"]="旗舰快捷使用",
        ["szType"]="Action",
        ["szTitle"]="技能相关",
        ["paramArgs"]="DXSkillQuickUse",
        ["nMaxKeyLen"]=2,
        ["szPlatform"]="DX",
        ["tbDisplayCheckFunc"]=
        {

        }
    }
}
