--*************************************** 工具生成 ***************************************
UISkillSkinTab = 
{
    [17]=
    {
        [30]=
        {
            ["nIndex"]=1,
            ["nSkinID"]=30,
            ["nSkillID"]=17,
            ["szImgPath"]="mui/Resource/SkillSkinPic/Img_DaZuo_GuGuang.png",
            ["nItemIndex"]=48778,
            ["szSkinName"]="孤光",
            ["szSkillName"]="打坐"
        },
        [32]=
        {
            ["nIndex"]=2,
            ["nSkinID"]=32,
            ["nSkillID"]=17,
            ["szImgPath"]="mui/Resource/SkillSkinPic/Img_DaZuo_NingYu.png",
            ["nItemIndex"]=51945,
            ["szSkinName"]="凝玉",
            ["szSkillName"]="打坐"
        },
        [81]=
        {
            ["nIndex"]=3,
            ["nSkinID"]=81,
            ["nSkillID"]=17,
            ["szImgPath"]="mui/Resource/SkillSkinPic/Img_DaZuo_JingLong.png",
            ["nItemIndex"]=71472,
            ["szSkinName"]="龙烛",
            ["szSkillName"]="打坐"
        }
    },
    [34]=
    {
        [43]=
        {
            ["nIndex"]=4,
            ["nSkinID"]=43,
            ["nSkillID"]=34,
            ["szImgPath"]="mui/Resource/SkillSkinPic/Img_HongQi_BingLing.png",
            ["nItemIndex"]=54039,
            ["szSkinName"]="冰凌",
            ["szSkillName"]="虹气长空"
        }
    },
    [35]=
    {
        [45]=
        {
            ["nIndex"]=5,
            ["nSkinID"]=45,
            ["nSkillID"]=35,
            ["szImgPath"]="mui/Resource/SkillSkinPic/Img_ChuanGong_QiHai.png",
            ["nItemIndex"]=54199,
            ["szSkinName"]="绮海",
            ["szSkillName"]="传功"
        },
        [83]=
        {
            ["nIndex"]=6,
            ["nSkinID"]=83,
            ["nSkillID"]=35,
            ["szImgPath"]="mui/Resource/SkillSkinPic/Img_ChuanGong_QinXin.png",
            ["nItemIndex"]=71474,
            ["szSkinName"]="雨霖",
            ["szSkillName"]="传功"
        }
    },
    [81]=
    {
        [31]=
        {
            ["nIndex"]=7,
            ["nSkinID"]=31,
            ["nSkillID"]=81,
            ["szImgPath"]="mui/Resource/SkillSkinPic/Img_ShenXing_FeiGuang.png",
            ["nItemIndex"]=48843,
            ["szSkinName"]="飞光",
            ["szSkillName"]="神行千里"
        },
        [82]=
        {
            ["nIndex"]=8,
            ["nSkinID"]=82,
            ["nSkillID"]=81,
            ["szImgPath"]="mui/Resource/SkillSkinPic/Img_ShenXing_XueZhan.png",
            ["nItemIndex"]=71473,
            ["szSkinName"]="行焰",
            ["szSkillName"]="神行千里"
        },
        [85]=
        {
            ["nIndex"]=9,
            ["nSkinID"]=85,
            ["nSkillID"]=81,
            ["szImgPath"]="mui/Resource/SkillSkinPic/Img_ShenXing_FengTian.png",
            ["nItemIndex"]=71476,
            ["szSkinName"]="迷云",
            ["szSkillName"]="神行千里"
        },
        [102]=
        {
            ["nIndex"]=10,
            ["nSkinID"]=102,
            ["nSkillID"]=81,
            ["szImgPath"]="mui/Resource/SkillSkinPic/Img_ShenXing_HuanSha.png",
            ["nItemIndex"]=78481,
            ["szSkinName"]="唤沙",
            ["szSkillName"]="神行千里"
        }
    },
    [608]=
    {
        [44]=
        {
            ["nIndex"]=11,
            ["nSkinID"]=44,
            ["nSkillID"]=608,
            ["szImgPath"]="mui/Resource/SkillSkinPic/Img_ZiJue_CiGu.png",
            ["nItemIndex"]=54091,
            ["szSkinName"]="刺骨",
            ["szSkillName"]="自绝经脉"
        },
        [84]=
        {
            ["nIndex"]=12,
            ["nSkinID"]=84,
            ["nSkillID"]=608,
            ["szImgPath"]="mui/Resource/SkillSkinPic/Img_ZiJue_ZhengFeng.png",
            ["nItemIndex"]=71475,
            ["szSkinName"]="激夜",
            ["szSkillName"]="自绝经脉"
        }
    },
    [100004]=
    {
        [86]=
        {
            ["nIndex"]=13,
            ["nSkinID"]=86,
            ["nSkillID"]=100004,
            ["szImgPath"]="mui/Resource/SkillSkinPic/Img_FuYao_DaoXiang.png",
            ["nItemIndex"]=71477,
            ["szSkinName"]="稷黍",
            ["szSkillName"]="扶摇直上"
        },
        [87]=
        {
            ["nIndex"]=14,
            ["nSkinID"]=87,
            ["nSkillID"]=100004,
            ["szImgPath"]="mui/Resource/SkillSkinPic/Img_FuYao_HengDao.png",
            ["nItemIndex"]=71478,
            ["szSkinName"]="飘摇",
            ["szSkillName"]="扶摇直上"
        }
    }
}
