--*************************************** 工具生成 ***************************************
UIStoreCameraTab = 
{
    ["Pet"]=
    {
        ["8-36046"]=
        {
            ["nIndex"]=1,
            ["szDesc"]="宠物-剪梅",
            ["szType"]="Pet",
            ["nItemType"]=8,
            ["nModelYaw"]=0,
            ["nItemIndex"]=36046,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=120,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=60,
                [3]=-45
            },
            ["tbModelTranslation"]=
            {
                [1]=-270,
                [2]=12,
                [3]=-80
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        ["default"]=
        {
            ["nIndex"]=-5,
            ["szDesc"]="宠物 - 默认值",
            ["szType"]="Pet",
            ["nItemType"]=0,
            ["nModelYaw"]=0.8,
            ["nItemIndex"]=0,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=120,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=60,
                [3]=-45
            },
            ["tbModelTranslation"]=
            {
                [1]=-70,
                [2]=12,
                [3]=-80
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        }
    },
    ["Ride"]=
    {
        ["default"]=
        {
            ["nIndex"]=-4,
            ["szDesc"]="坐骑 - 默认值",
            ["szType"]="Ride",
            ["nItemType"]=0,
            ["nModelYaw"]=1.9,
            ["nItemIndex"]=0,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=120,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=114,
                [3]=-45
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-130,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        }
    },
    ["Player"]=
    {
        ["default"]=
        {
            ["nIndex"]=-2,
            ["szDesc"]="人物模型 - 默认值",
            ["szType"]="Player",
            ["nItemType"]=0,
            ["nModelYaw"]=1.9,
            ["nItemIndex"]=0,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=120,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-45
            },
            ["tbModelTranslation"]=
            {
                [1]=-70,
                [2]=12,
                [3]=-80
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        }
    },
    ["Pendant"]=
    {
        ["default"]=
        {
            ["nIndex"]=-1,
            ["szDesc"]="纯挂件 - 默认值",
            ["szType"]="Pendant",
            ["nItemType"]=0,
            ["nModelYaw"]=72,
            ["nItemIndex"]=0,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=120,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-45
            },
            ["tbModelTranslation"]=
            {
                [1]=-120,
                [2]=100,
                [3]=-80
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        }
    },
    ["Furniture"]=
    {
        ["default"]=
        {
            ["nIndex"]=-3,
            ["szDesc"]="家具 - 默认值",
            ["szType"]="Furniture",
            ["nItemType"]=0,
            ["nModelYaw"]=2,
            ["nItemIndex"]=0,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=120,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=60,
                [3]=-45
            },
            ["tbModelTranslation"]=
            {
                [1]=-70,
                [2]=12,
                [3]=-80
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        }
    }
}
