--*************************************** 工具生成 ***************************************
UISystemOpenTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["szDef"]="ActivityCalendar",
        ["szDesc"]="侠士达到120级后方可开启日历",
        ["szName"]="活动",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=901
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [2]=
    {
        ["nID"]=2,
        ["szDef"]="DungeonEntrance",
        ["szDesc"]="侠士达到120级后方可开启秘境",
        ["szName"]="秘境",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=1252
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [3]=
    {
        ["nID"]=3,
        ["szDef"]="Task",
        ["szDesc"]="",
        ["szName"]="任务",
        ["szTitle"]="",
        ["tbViewIDs"]=
        {
            [1]=172
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=1,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [4]=
    {
        ["nID"]=4,
        ["szDef"]="Bag",
        ["szDesc"]="",
        ["szName"]="背包",
        ["szTitle"]="",
        ["tbViewIDs"]=
        {
            [1]=111,
            [2]=117
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=1,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [5]=
    {
        ["nID"]=5,
        ["szDef"]="Character",
        ["szDesc"]="",
        ["szName"]="角色",
        ["szTitle"]="",
        ["tbViewIDs"]=
        {
            [1]=51
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=1,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [6]=
    {
        ["nID"]=6,
        ["szDef"]="PowerUp",
        ["szDesc"]="侠士达到20级后方可开启强化",
        ["szName"]="强化",
        ["szTitle"]="20级开启",
        ["tbViewIDs"]=
        {
            [1]=65
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=20,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [7]=
    {
        ["nID"]=7,
        ["szDef"]="Skill",
        ["szDesc"]="侠士达到102级且加入门派后方可查看武学",
        ["szName"]="武学",
        ["szTitle"]="102级并\n加入门派开启",
        ["tbViewIDs"]=
        {
            [1]=651,
            [2]=699
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=102,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [8]=
    {
        ["nID"]=8,
        ["szDef"]="Life",
        ["szDesc"]="侠士达到120级后方可开启技艺",
        ["szName"]="技艺",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=731
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [9]=
    {
        ["nID"]=9,
        ["szDef"]="Horse",
        ["szDesc"]="侠士获得坐骑方可开启",
        ["szName"]="坐骑",
        ["szTitle"]="获得坐骑开启",
        ["tbViewIDs"]=
        {
            [1]=1401
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=106,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=10
    },
    [10]=
    {
        ["nID"]=10,
        ["szDef"]="PvPArena",
        ["szDesc"]="侠士达到130级方可开启竞技",
        ["szName"]="竞技",
        ["szTitle"]="130级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=130,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [11]=
    {
        ["nID"]=11,
        ["szDef"]="Tong",
        ["szDesc"]="侠士达到108级后方可开启帮会",
        ["szName"]="帮会",
        ["szTitle"]="108级开启",
        ["tbViewIDs"]=
        {
            [1]=2001,
            [2]=2003
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=108,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [12]=
    {
        ["nID"]=12,
        ["szDef"]="Social",
        ["szDesc"]="侠士达到106级后方可查看师徒",
        ["szName"]="社交",
        ["szTitle"]="106级开启",
        ["tbViewIDs"]=
        {
            [1]=703
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=106,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [13]=
    {
        ["nID"]=13,
        ["szDef"]="EquipStore",
        ["szDesc"]="侠士达到108级后方可开启商店",
        ["szName"]="商店",
        ["szTitle"]="108级开启",
        ["tbViewIDs"]=
        {
            [1]=603
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=108,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [14]=
    {
        ["nID"]=14,
        ["szDef"]="Partner",
        ["szDesc"]="侠士达到120级后方可结识江湖侠客",
        ["szName"]="红尘侠影",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=3201
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [15]=
    {
        ["nID"]=15,
        ["szDef"]="Homeland",
        ["szDesc"]="侠士达到120级后方可开启家园",
        ["szName"]="家园",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=2801
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=27076,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [16]=
    {
        ["nID"]=16,
        ["szDef"]="Camp",
        ["szDesc"]="侠士达到120级后方可加入阵营",
        ["szName"]="阵营",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=1523
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [17]=
    {
        ["nID"]=17,
        ["szDef"]="RoadChivalrous",
        ["szDesc"]="侠士满级后方可开启大侠之路",
        ["szName"]="大侠之路",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=281
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [18]=
    {
        ["nID"]=18,
        ["szDef"]="Recruit",
        ["szDesc"]="侠士达到110级后方可发布招募",
        ["szName"]="发布招募",
        ["szTitle"]="110级开启",
        ["tbViewIDs"]=
        {
            [1]=858
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=110,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [19]=
    {
        ["nID"]=19,
        ["szDef"]="Reward",
        ["szDesc"]="非试玩帐号、且角色等级大于20级才可参与决斗挑战",
        ["szName"]="发布悬赏",
        ["szTitle"]="20级开启",
        ["tbViewIDs"]=
        {
            [1]=63
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=20,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [20]=
    {
        ["nID"]=20,
        ["szDef"]="Keju",
        ["szDesc"]="侠士达到110级后方参与科举考试",
        ["szName"]="科举考试",
        ["szTitle"]="",
        ["tbViewIDs"]=
        {
            [1]=2601
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=110,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [21]=
    {
        ["nID"]=21,
        ["szDef"]="PowerUp",
        ["szDesc"]="侠士达到110级后方可强化装备",
        ["szName"]="装备强化",
        ["szTitle"]="",
        ["tbViewIDs"]=
        {
            [1]=65
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=110,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [22]=
    {
        ["nID"]=22,
        ["szDef"]="WuLinTongJian ",
        ["szDesc"]="侠士达到120级后方可开启武林通鉴",
        ["szName"]="武林通鉴",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=4151
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [23]=
    {
        ["nID"]=23,
        ["szDef"]="JiangHuBaiTai",
        ["szDesc"]="侠士达到120级后方可开启江湖百态",
        ["szName"]="江湖百态",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=4381
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [24]=
    {
        ["nID"]=24,
        ["szDef"]="Domesticate",
        ["szDesc"]="侠士达到110级后方可开启驯养",
        ["szName"]="驯养",
        ["szTitle"]="110级开启",
        ["tbViewIDs"]=
        {
            [1]=1403
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=110,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [25]=
    {
        ["nID"]=25,
        ["szDef"]="Compass",
        ["szDesc"]="侠士达到109级后方可开启寻宝",
        ["szName"]="寻宝",
        ["szTitle"]="109级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=109,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [26]=
    {
        ["nID"]=26,
        ["szDef"]="PVPTM",
        ["szDesc"]="侠士达到106级后方可开启阵营同模",
        ["szName"]="阵营同模",
        ["szTitle"]="106级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=106,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [27]=
    {
        ["nID"]=27,
        ["szDef"]="QingGong",
        ["szDesc"]="侠士达到102级后方可开启轻功切换",
        ["szName"]="轻功模式",
        ["szTitle"]="102级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=102,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [28]=
    {
        ["nID"]=28,
        ["szDef"]="PetMap",
        ["szDesc"]="侠士达到106级后方可开启宠物",
        ["szName"]="宠物",
        ["szTitle"]="106级开启",
        ["tbViewIDs"]=
        {
            [1]=3051
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=106,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [29]=
    {
        ["nID"]=29,
        ["szDef"]="QiYu",
        ["szDesc"]="侠士获得奇遇方可开启",
        ["szName"]="奇遇",
        ["szTitle"]="获得奇遇开启",
        ["tbViewIDs"]=
        {
            [1]=751,
            [2]=752
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=27078,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [30]=
    {
        ["nID"]=30,
        ["szDef"]="FengYunLu",
        ["szDesc"]="侠士达到120级后方可开启风云录",
        ["szName"]="风云录",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=2501,
            [2]=2502,
            [3]=2503
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [31]=
    {
        ["nID"]=31,
        ["szDef"]="FengYunLu",
        ["szDesc"]="侠士达到106级后方可查看阅读",
        ["szName"]="阅读",
        ["szTitle"]="106级开启",
        ["tbViewIDs"]=
        {
            [1]=735,
            [2]=734
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=106,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [32]=
    {
        ["nID"]=32,
        ["szDef"]="PersonalTitle",
        ["szDesc"]="侠士获得称号方可开启",
        ["szName"]="称号",
        ["szTitle"]="获得称号开启",
        ["tbViewIDs"]=
        {
            [1]=64
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=713
    },
    [33]=
    {
        ["nID"]=33,
        ["szDef"]="HomeWarehouse",
        ["szDesc"]="侠士达到108级后方可开启仓库",
        ["szName"]="仓库",
        ["szTitle"]="108级开启",
        ["tbViewIDs"]=
        {
            [1]=114,
            [2]=116
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=108,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [34]=
    {
        ["nID"]=34,
        ["szDef"]="TradingHouse",
        ["szDesc"]="侠士达到106级后方可开启交易行",
        ["szName"]="交易行",
        ["szTitle"]="106级开启",
        ["tbViewIDs"]=
        {
            [1]=2401
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=106,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [35]=
    {
        ["nID"]=35,
        ["szDef"]="BiaoQing",
        ["szDesc"]="侠士达到103级后方可开启表情动作",
        ["szName"]="表情动作",
        ["szTitle"]="103级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=103,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [36]=
    {
        ["nID"]=36,
        ["szDef"]="RenownList",
        ["szDesc"]="侠士达到120级后方可开启声望",
        ["szName"]="声望",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=3151,
            [2]=3153
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [37]=
    {
        ["nID"]=37,
        ["szDef"]="CampMode",
        ["szDesc"]="侠士达到120级后方可开启阵营模式",
        ["szName"]="阵营模式",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [38]=
    {
        ["nID"]=38,
        ["szDef"]="Arena",
        ["szDesc"]="侠士达到120级后方可开启摆擂",
        ["szName"]="摆擂",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [39]=
    {
        ["nID"]=39,
        ["szDef"]="Matchmaking",
        ["szDesc"]="侠士达到109级后方可开启套马",
        ["szName"]="套马",
        ["szTitle"]="109级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=109,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [40]=
    {
        ["nID"]=40,
        ["szDef"]="Pet",
        ["szDesc"]="侠士达到106级后方可开启召唤宠物",
        ["szName"]="召唤宠物",
        ["szTitle"]="106级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=106,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [41]=
    {
        ["nID"]=41,
        ["szDef"]="Role",
        ["szDesc"]="侠士达到110级后方可开启召请侠客",
        ["szName"]="召请侠客",
        ["szTitle"]="110级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=110,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [42]=
    {
        ["nID"]=42,
        ["szDef"]="Resonance",
        ["szDesc"]="侠士达到110级后方可开启显示共鸣",
        ["szName"]="显示共鸣",
        ["szTitle"]="110级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=110,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [44]=
    {
        ["nID"]=44,
        ["szDef"]="PvPMatching",
        ["szDesc"]="侠士达到130级方可开启竞技",
        ["szName"]="竞技",
        ["szTitle"]="130级开启",
        ["tbViewIDs"]=
        {
            [1]=1501
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=130,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [45]=
    {
        ["nID"]=45,
        ["szDef"]="MingWang",
        ["szDesc"]="侠士达到120级后方可开启名望",
        ["szName"]="名望",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=4266
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [46]=
    {
        ["nID"]=46,
        ["szDef"]="WuDou",
        ["szDesc"]="侠士达到120级后方可开启决斗",
        ["szName"]="决斗",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=62
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [47]=
    {
        ["nID"]=47,
        ["szDef"]="ReleaseRewardPop",
        ["szDesc"]="侠士达到120级后方可查看武力值",
        ["szName"]="武力值",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=63
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [49]=
    {
        ["nID"]=49,
        ["szDef"]="WaiShe",
        ["szDesc"]="侠士达到106级后方可开启外观预设切换",
        ["szName"]="外观预设",
        ["szTitle"]="106级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=106,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [50]=
    {
        ["nID"]=50,
        ["szDef"]="WanJia",
        ["szDesc"]="侠士达到103级后方可开启玩家显示",
        ["szName"]="玩家显示",
        ["szTitle"]="103级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=103,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [51]=
    {
        ["nID"]=51,
        ["szDef"]="Walk",
        ["szDesc"]="侠士达到100级后方可开启走路",
        ["szName"]="切换走路",
        ["szTitle"]="100级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=100,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [52]=
    {
        ["nID"]=52,
        ["szDef"]="RiKe",
        ["szDesc"]="侠士达到120级后方可查看每日",
        ["szName"]="日课",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [53]=
    {
        ["nID"]=53,
        ["szDef"]="CuiDiao",
        ["szDesc"]="侠士达到108级后方可开启垂钓",
        ["szName"]="垂钓",
        ["szTitle"]="108级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=108,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [54]=
    {
        ["nID"]=54,
        ["szDef"]="ImpasseMatching",
        ["szDesc"]="侠士达到120级后方可参与绝境战场",
        ["szName"]="绝境战场",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=1528
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [55]=
    {
        ["nID"]=55,
        ["szDef"]="BaizhanMain",
        ["szDesc"]="侠士达到120级后方可参与百战异闻录",
        ["szName"]="百战",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=4491
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [56]=
    {
        ["nID"]=56,
        ["szDef"]="BattleFieldInformation",
        ["szDesc"]="侠士达到130级后方可参与阵营战场",
        ["szName"]="阵营战场",
        ["szTitle"]="130级开启",
        ["tbViewIDs"]=
        {
            [1]=1509
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=130,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [57]=
    {
        ["nID"]=57,
        ["szDef"]="JiangHuXingJi",
        ["szDesc"]="",
        ["szName"]="江湖行记主按钮",
        ["szTitle"]="",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=104,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [58]=
    {
        ["nID"]=58,
        ["szDef"]="JiangHuXingJiBP",
        ["szDesc"]="侠士达到104级后方可开启江湖行记",
        ["szName"]="江湖行记BP",
        ["szTitle"]="104级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=104,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [59]=
    {
        ["nID"]=59,
        ["szDef"]="MJShop",
        ["szDesc"]="侠士达到120级后方可开启名剑商店",
        ["szName"]="名剑商店",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [60]=
    {
        ["nID"]=60,
        ["szDef"]="ZYShop",
        ["szDesc"]="侠士达到120级后方可开启阵营商店",
        ["szName"]="阵营商店",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [61]=
    {
        ["nID"]=61,
        ["szDef"]="XXShop",
        ["szDesc"]="侠士达到120级后方可开启侠行商店",
        ["szName"]="侠行商店",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [62]=
    {
        ["nID"]=62,
        ["szDef"]="XXDShop",
        ["szDesc"]="侠士达到120级后方可开启休闲点商店",
        ["szName"]="休闲点商店",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [63]=
    {
        ["nID"]=63,
        ["szDef"]="FSLShop",
        ["szDesc"]="侠士达到120级后方可开启飞沙令商店",
        ["szName"]="飞沙令商店",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [64]=
    {
        ["nID"]=64,
        ["szDef"]="LKXShop",
        ["szDesc"]="侠士达到120级后方可开启浪客行商店",
        ["szName"]="浪客行商店",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [65]=
    {
        ["nID"]=65,
        ["szDef"]="JSZBShop",
        ["szDesc"]="侠士达到120级后方可开启绝世装备",
        ["szName"]="绝世装备商店",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [66]=
    {
        ["nID"]=66,
        ["szDef"]="CLShop",
        ["szDesc"]="侠士达到120级后方可开启材料",
        ["szName"]="材料商店",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [67]=
    {
        ["nID"]=67,
        ["szDef"]="ShenBing",
        ["szDesc"]="侠士达到120级且加入门派后方可开启神兵百炼",
        ["szName"]="神兵百炼",
        ["szTitle"]="120级并\n加入门派开启",
        ["tbViewIDs"]=
        {
            [1]=4901
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {
            [1]="not UI_PlayerForceIDIsZero()",
            [2]="not CheckPlayerKungfuID()"
        },
        ["nOpenAchievementID"]=0
    },
    [68]=
    {
        ["nID"]=68,
        ["szDef"]="PersonalCard",
        ["szDesc"]="侠士达到112级后方可开启个人名片",
        ["szName"]="个人名片",
        ["szTitle"]="112级开启",
        ["tbViewIDs"]=
        {
            [1]=4801
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=112,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [69]=
    {
        ["nID"]=69,
        ["szDef"]="Accessory",
        ["szDesc"]="侠士装备一个挂件方可查看",
        ["szName"]="挂件秘鉴",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {
            [1]=61
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=730
    },
    [70]=
    {
        ["nID"]=70,
        ["szDef"]="WorldMap",
        ["szDesc"]="侠士达到102级后方可查看世界地图",
        ["szName"]="世界地图",
        ["szTitle"]="",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=102,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [71]=
    {
        ["nID"]=71,
        ["szDef"]="SwitchEquip",
        ["szDesc"]="侠士达到120级后方可开启速切功能",
        ["szName"]="速切装备",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [72]=
    {
        ["nID"]=72,
        ["szDef"]="MainCityCustom",
        ["szDesc"]="侠士达到102级后方可开启调整界面大小",
        ["szName"]="主界面自定义",
        ["szTitle"]="",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=102,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [73]=
    {
        ["nID"]=73,
        ["szDef"]="TeachBox",
        ["szDesc"]="侠士达到106级后方可查看",
        ["szName"]="教学指引",
        ["szTitle"]="106级开启",
        ["tbViewIDs"]=
        {
            [1]=4551
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=106,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [74]=
    {
        ["nID"]=74,
        ["szDef"]="SwordMemories",
        ["szDesc"]="侠士达到106级后方可查看剑侠录",
        ["szName"]="剑侠录",
        ["szTitle"]="106级开启",
        ["tbViewIDs"]=
        {
            [1]=283
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=106,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [75]=
    {
        ["nID"]=75,
        ["szDef"]="XiaKeJiaoHu",
        ["szDesc"]="侠士达到110级后方可开启侠客交互",
        ["szName"]="侠客交互",
        ["szTitle"]="110级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=110,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [76]=
    {
        ["nID"]=76,
        ["szDef"]="WanBaoLou",
        ["szDesc"]="侠士达到120级后方可开启万宝楼",
        ["szName"]="万宝楼 ",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [77]=
    {
        ["nID"]=77,
        ["szDef"]="DiTuChengJiu",
        ["szDesc"]="侠士达到120级后方可查看",
        ["szName"]="地图成就",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [78]=
    {
        ["nID"]=78,
        ["szDef"]="JiaoDianLieBiao",
        ["szDesc"]="侠士达到120级后方可开启",
        ["szName"]="焦点列表",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [79]=
    {
        ["nID"]=79,
        ["szDef"]="XiuXian",
        ["szDesc"]="侠士达到120级后方可开启单人休闲",
        ["szName"]="单人休闲",
        ["szTitle"]="120级开启",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=120,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [80]=
    {
        ["nID"]=80,
        ["szDef"]="WuWeiJue",
        ["szDesc"]="侠士达到108级后方可开启五味诀",
        ["szName"]="五味诀",
        ["szTitle"]="108级开启",
        ["tbViewIDs"]=
        {
            [1]=5261
        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=108,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {

        },
        ["nOpenAchievementID"]=0
    },
    [81]=
    {
        ["nID"]=81,
        ["szDef"]="ShareStation",
        ["szDesc"]="部分功能升级维护中，商城设计站暂未开放",
        ["szName"]="设计站",
        ["szTitle"]="",
        ["tbViewIDs"]=
        {

        },
        ["bIsDisplay"]=true,
        ["nOpenLevel"]=100,
        ["nOpenQuestID"]=0,
        ["szSystemOpen"]="",
        ["tbOtherCheckFunc"]=
        {
            [1]="ShareStationData.GetOpenState()"
        },
        ["nOpenAchievementID"]=0
    }
}
