--*************************************** 工具生成 ***************************************
UITipsSizeTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["nScale"]=0.82,
        ["szPrefabName"]="WidgetPlayerPop",
        ["szPanelParentName"]=""
    },
    [2]=
    {
        ["nID"]=2,
        ["nScale"]=0.82,
        ["szPrefabName"]="WidgetQuickUsedTip",
        ["szPanelParentName"]=""
    },
    [3]=
    {
        ["nID"]=3,
        ["nScale"]=0.82,
        ["szPrefabName"]="WidgetMainCityBuffContentTip",
        ["szPanelParentName"]=""
    },
    [4]=
    {
        ["nID"]=4,
        ["nScale"]=0.82,
        ["szPrefabName"]="WidgetInteractionMorePop",
        ["szPanelParentName"]=""
    },
    [5]=
    {
        ["nID"]=5,
        ["nScale"]=0.82,
        ["szPrefabName"]="AniAll/WidgetAniRight/WidgetMoneyList",
        ["szPanelParentName"]="PanelHalfBag"
    },
    [6]=
    {
        ["nID"]=6,
        ["nScale"]=0.82,
        ["szPrefabName"]="WidgetChatSwitchTip",
        ["szPanelParentName"]=""
    },
    [7]=
    {
        ["nID"]=7,
        ["nScale"]=0.82,
        ["szPrefabName"]="WidgetTeach_RichText",
        ["szPanelParentName"]=""
    },
    [8]=
    {
        ["nID"]=8,
        ["nScale"]=0.82,
        ["szPrefabName"]="WidgetFiltrateTip",
        ["szPanelParentName"]=""
    },
    [9]=
    {
        ["nID"]=9,
        ["nScale"]=0.82,
        ["szPrefabName"]="__bgMainCityInteractive/WidgetAnchor",
        ["szPanelParentName"]="PanelMainCityInteractive"
    },
    [10]=
    {
        ["nID"]=10,
        ["nScale"]=0.82,
        ["szPrefabName"]="WidgetCompassTips",
        ["szPanelParentName"]=""
    },
    [11]=
    {
        ["nID"]=11,
        ["nScale"]=0.82,
        ["szPrefabName"]="WidgetQuickUsedTip",
        ["szPanelParentName"]=""
    },
    [12]=
    {
        ["nID"]=12,
        ["nScale"]=0.82,
        ["szPrefabName"]="WidgetPublicLabelTips",
        ["szPanelParentName"]=""
    }
}
