--*************************************** 工具生成 ***************************************
UIBtnCtrlTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["szBtnDes"]="打开背包",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIMgr.Open(VIEW_ID.PanelHalfBag)"
        }
    },
    [2]=
    {
        ["nID"]=2,
        ["szBtnDes"]="打开帮会",
        ["szFuncTip"]="",
        ["szShowTip"]="条件不允许打开帮会聊天",
        ["tbCheckFunc"]=
        {
            [1]="TongData.HavePlayerJoinedTong()"
        },
        ["tbActionFunc"]=
        {
            [1]="ChatHelper.Chat(UI_Chat_Channel.Tong)"
        }
    },
    [3]=
    {
        ["nID"]=3,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="CoinShopData.Open()"
        }
    },
    [4]=
    {
        ["nID"]=4,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('CoinShopTitle/0/0')"
        }
    },
    [5]=
    {
        ["nID"]=5,
        ["szBtnDes"]="查看详情",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('CreativePlan', false)"
        }
    },
    [6]=
    {
        ["nID"]=6,
        ["szBtnDes"]="查看详情",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('GroupPromotion', false)"
        }
    },
    [7]=
    {
        ["nID"]=7,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('Exterior/4/3140')"
        }
    },
    [8]=
    {
        ["nID"]=8,
        ["szBtnDes"]="查看活动",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/818')"
        }
    },
    [9]=
    {
        ["nID"]=9,
        ["szBtnDes"]="勋章兑换商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('NPCGuide/2044')"
        }
    },
    [10]=
    {
        ["nID"]=10,
        ["szBtnDes"]="前往师徒册",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIMgr.Open(VIEW_ID.PanelApprenticeNew)"
        }
    },
    [11]=
    {
        ["nID"]=11,
        ["szBtnDes"]="师徒值兑换商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('NPCGuide/2433')"
        }
    },
    [12]=
    {
        ["nID"]=12,
        ["szBtnDes"]="立即添加",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://kf-qw.xoyo.com/sy/jump?page=gNj')"
        }
    },
    [13]=
    {
        ["nID"]=13,
        ["szBtnDes"]="立即添加",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://kf-qw.xoyo.com/sy/jump?page=PBk')"
        }
    },
    [14]=
    {
        ["nID"]=14,
        ["szBtnDes"]="立即添加",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://kf-qw.xoyo.com/sy/jump?page=2J0')"
        }
    },
    [15]=
    {
        ["nID"]=15,
        ["szBtnDes"]="查看详情",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://jx3.xoyo.com/index/#/article-details?catid=2466&id=6197')"
        }
    },
    [16]=
    {
        ["nID"]=16,
        ["szBtnDes"]="查看活动",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/908')"
        }
    },
    [17]=
    {
        ["nID"]=17,
        ["szBtnDes"]="我要建议",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://www.diaochapai.com/survey/f708b16a-c2de-4082-9a35-0bc29c4049fb')"
        }
    },
    [18]=
    {
        ["nID"]=18,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'CoinShopTitle/6/20')"
        }
    },
    [19]=
    {
        ["nID"]=19,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1482')"
        }
    },
    [20]=
    {
        ["nID"]=20,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'CoinShopTitle/6/19')"
        }
    },
    [21]=
    {
        ["nID"]=21,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'CoinShopTitle/3/5')"
        }
    },
    [22]=
    {
        ["nID"]=22,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'CoinShopTitle/3/1')"
        }
    },
    [23]=
    {
        ["nID"]=23,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'BuildFace')"
        }
    },
    [24]=
    {
        ["nID"]=24,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'CoinShopHair')"
        }
    },
    [25]=
    {
        ["nID"]=25,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'SchoolSplit/3/6')"
        }
    },
    [26]=
    {
        ["nID"]=26,
        ["szBtnDes"]="积分兑换",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://jx3.xoyo.com/chuangzuo.html?utm_source=tongrenxiu#/')"
        }
    },
    [27]=
    {
        ["nID"]=27,
        ["szBtnDes"]="抖音激励站",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://jx3.xoyo.com/jilizhan.html#/')"
        }
    },
    [28]=
    {
        ["nID"]=28,
        ["szBtnDes"]="添加小管家",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://kf-qw.xoyo.com/sy/jump?page=K3G')"
        }
    },
    [29]=
    {
        ["nID"]=29,
        ["szBtnDes"]="前往获取",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.Teleport(2294, 455)"
        }
    },
    [30]=
    {
        ["nID"]=30,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1415/1')"
        }
    },
    [31]=
    {
        ["nID"]=31,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/901')"
        }
    },
    [32]=
    {
        ["nID"]=32,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/933')"
        }
    },
    [33]=
    {
        ["nID"]=33,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="CoinShopData.Open()"
        }
    },
    [34]=
    {
        ["nID"]=34,
        ["szBtnDes"]="前往秘境",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIMgr.Open(VIEW_ID.PanelDungeonEntrance)"
        }
    },
    [35]=
    {
        ["nID"]=35,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/858')"
        }
    },
    [36]=
    {
        ["nID"]=36,
        ["szBtnDes"]="外观商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="CoinShopData.Open()"
        }
    },
    [37]=
    {
        ["nID"]=37,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1488/25')"
        }
    },
    [38]=
    {
        ["nID"]=38,
        ["szBtnDes"]="前往活动",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('GuideTeleport/2482/652')"
        }
    },
    [39]=
    {
        ["nID"]=39,
        ["szBtnDes"]="查看详情",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/365')"
        }
    },
    [40]=
    {
        ["nID"]=40,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1321/7')"
        }
    },
    [41]=
    {
        ["nID"]=41,
        ["szBtnDes"]="购买",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleBuy('OABUY-6|5185')"
        }
    },
    [42]=
    {
        ["nID"]=42,
        ["szBtnDes"]="购买",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleBuy('OABUY-6|5186')"
        }
    },
    [43]=
    {
        ["nID"]=43,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'CoinShopTitle/6/17')"
        }
    },
    [44]=
    {
        ["nID"]=44,
        ["szBtnDes"]="查看详情",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/1025')"
        }
    },
    [45]=
    {
        ["nID"]=45,
        ["szBtnDes"]="查看详情",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/957')"
        }
    },
    [46]=
    {
        ["nID"]=46,
        ["szBtnDes"]="前往活动",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('GuideTeleport/2687/11')"
        }
    },
    [47]=
    {
        ["nID"]=47,
        ["szBtnDes"]="48元",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {
            [1]="PayData.CanBuyRMBProduct('com.jx3wj.ios.20240830gift_48', 156) and GetClientPlayer().GetCoinShopPreOrderCount(143)>0"
        },
        ["tbActionFunc"]=
        {
            [1]="PayData.BuyRMBProduct('com.jx3wj.ios.20240830gift_48')"
        }
    },
    [48]=
    {
        ["nID"]=48,
        ["szBtnDes"]="购买",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleBuy('OABUY-6|5339')"
        }
    },
    [49]=
    {
        ["nID"]=49,
        ["szBtnDes"]="购买",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleBuy('OABUY-6|5340')"
        }
    },
    [50]=
    {
        ["nID"]=50,
        ["szBtnDes"]="预览",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('Exterior/4/5339')"
        }
    },
    [51]=
    {
        ["nID"]=51,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [52]=
    {
        ["nID"]=52,
        ["szBtnDes"]="购买四乡风物",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('Exterior/4/6006')"
        }
    },
    [53]=
    {
        ["nID"]=53,
        ["szBtnDes"]="查看活动",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/855')"
        }
    },
    [54]=
    {
        ["nID"]=54,
        ["szBtnDes"]="活动详情",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/964')"
        }
    },
    [55]=
    {
        ["nID"]=55,
        ["szBtnDes"]="立即前往",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/966')"
        }
    },
    [56]=
    {
        ["nID"]=56,
        ["szBtnDes"]="邮件",
        ["szFuncTip"]="MailMgr.GetMailTip()",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {
            [1]="not GetClientScene().GetMapOperationState(MAP_OPERATION_TYPE.DISABLE_MAIL_BOX)",
            [2]="not g_pClientPlayer.bFightState",
            [3]="g_pClientPlayer.nMoveState ~= MOVE_STATE.ON_DEATH"
        },
        ["tbActionFunc"]=
        {
            [1]="UIMgr.Open(VIEW_ID.PanelEmail)"
        }
    },
    [57]=
    {
        ["nID"]=57,
        ["szBtnDes"]="查看活动",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/819')"
        }
    },
    [58]=
    {
        ["nID"]=58,
        ["szBtnDes"]="前往投票",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="WebUrl.OpenByID(WEBURL_ID.TONG_REN_EXTERIOR)"
        }
    },
    [59]=
    {
        ["nID"]=59,
        ["szBtnDes"]="前往投票",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="WebUrl.OpenByID(WEBURL_ID.TONG_REN_WEAPON)"
        }
    },
    [60]=
    {
        ["nID"]=60,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('Exterior/4/4677')"
        }
    },
    [61]=
    {
        ["nID"]=61,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('Exterior/4/4678')"
        }
    },
    [62]=
    {
        ["nID"]=62,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('Exterior/4/5468')"
        }
    },
    [63]=
    {
        ["nID"]=63,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('Exterior/4/5467')"
        }
    },
    [64]=
    {
        ["nID"]=64,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1515')"
        }
    },
    [65]=
    {
        ["nID"]=65,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/972')"
        }
    },
    [66]=
    {
        ["nID"]=66,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('PanelLink/ArenaQueue.Open')"
        }
    },
    [67]=
    {
        ["nID"]=67,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/501/15')"
        }
    },
    [68]=
    {
        ["nID"]=68,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/114')"
        }
    },
    [69]=
    {
        ["nID"]=69,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1140/16')"
        }
    },
    [70]=
    {
        ["nID"]=70,
        ["szBtnDes"]="查看详情",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/451')"
        }
    },
    [71]=
    {
        ["nID"]=71,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJumpYunTu()"
        }
    },
    [72]=
    {
        ["nID"]=72,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/87/17')"
        }
    },
    [73]=
    {
        ["nID"]=73,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [74]=
    {
        ["nID"]=74,
        ["szBtnDes"]="前往吃宴",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [75]=
    {
        ["nID"]=75,
        ["szBtnDes"]="888通宝购买",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleBuy('OABUY-6|6208')"
        }
    },
    [76]=
    {
        ["nID"]=76,
        ["szBtnDes"]="2026通宝购买",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleBuy('OABUY-6|6209')"
        }
    },
    [77]=
    {
        ["nID"]=77,
        ["szBtnDes"]="4800通宝购买",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleBuy('OABUY-6|6210')"
        }
    },
    [78]=
    {
        ["nID"]=78,
        ["szBtnDes"]="前往拜年",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [79]=
    {
        ["nID"]=79,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [80]=
    {
        ["nID"]=80,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1106/18')"
        }
    },
    [81]=
    {
        ["nID"]=81,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('FBlist/688')"
        }
    },
    [82]=
    {
        ["nID"]=82,
        ["szBtnDes"]="前往比赛",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIMgr.Open(VIEW_ID.PanelPvPMatching,nil,5, true)"
        }
    },
    [83]=
    {
        ["nID"]=83,
        ["szBtnDes"]="前往报名",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('WebURL/5')"
        }
    },
    [84]=
    {
        ["nID"]=84,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1474/19')"
        }
    },
    [85]=
    {
        ["nID"]=85,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1015/20')"
        }
    },
    [86]=
    {
        ["nID"]=86,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/860')"
        }
    },
    [87]=
    {
        ["nID"]=87,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1521/1')"
        }
    },
    [88]=
    {
        ["nID"]=88,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/977')"
        }
    },
    [89]=
    {
        ["nID"]=89,
        ["szBtnDes"]="活动详情",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/1040')"
        }
    },
    [90]=
    {
        ["nID"]=90,
        ["szBtnDes"]="立即前往",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIMgr.Open(VIEW_ID.PanelPvPMatching,nil,6, true)"
        }
    },
    [91]=
    {
        ["nID"]=91,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [92]=
    {
        ["nID"]=92,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/102/22')"
        }
    },
    [93]=
    {
        ["nID"]=93,
        ["szBtnDes"]="初次参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [94]=
    {
        ["nID"]=94,
        ["szBtnDes"]="前往仙灵岛",
        ["szFuncTip"]="",
        ["szShowTip"]="需要完成联动任务“海外仙岛”",
        ["tbCheckFunc"]=
        {
            [1]="QuestData.IsCompleted(28001)"
        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '2742')"
        }
    },
    [95]=
    {
        ["nID"]=95,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'CoinShopTitle/3/6')"
        }
    },
    [96]=
    {
        ["nID"]=96,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://jx3.xoyo.com/p/m/2025/04/11/new-version/index.html?utm_source=game')"
        }
    },
    [97]=
    {
        ["nID"]=97,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'Exterior/4/5636')"
        }
    },
    [98]=
    {
        ["nID"]=98,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [99]=
    {
        ["nID"]=99,
        ["szBtnDes"]="登录奖励",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="ActivityData.OpenFestivalRewardPop(43)"
        }
    },
    [100]=
    {
        ["nID"]=100,
        ["szBtnDes"]="奖励查询",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="ActivityData.OpenFestivalStampPop(43)"
        }
    },
    [101]=
    {
        ["nID"]=101,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1019/2')"
        }
    },
    [102]=
    {
        ["nID"]=102,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/95/4')"
        }
    },
    [103]=
    {
        ["nID"]=103,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'CoinShopTitle/6/7')"
        }
    },
    [104]=
    {
        ["nID"]=104,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [105]=
    {
        ["nID"]=105,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIMgr.Open(VIEW_ID.PanelImpasseMatching, nil, 8)"
        }
    },
    [106]=
    {
        ["nID"]=106,
        ["szBtnDes"]="前往主城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '2756')"
        }
    },
    [107]=
    {
        ["nID"]=107,
        ["szBtnDes"]="前往百溪",
        ["szFuncTip"]="",
        ["szShowTip"]="需要完成活动任务“遥闻南音”",
        ["tbCheckFunc"]=
        {
            [1]="QuestData.IsCompleted(28257)"
        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '2758')"
        }
    },
    [108]=
    {
        ["nID"]=108,
        ["szBtnDes"]="往期商店",
        ["szFuncTip"]="",
        ["szShowTip"]="需要完成活动任务“弦歌不辍”",
        ["tbCheckFunc"]=
        {
            [1]="QuestData.IsCompleted(28261)"
        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1441/5')"
        }
    },
    [109]=
    {
        ["nID"]=109,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'BattleFieldQueue/676')"
        }
    },
    [110]=
    {
        ["nID"]=110,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1539/27')"
        }
    },
    [111]=
    {
        ["nID"]=111,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://jx3.xoyo.com/p/m/2025/10/30/douyin-binding/index.html')"
        }
    },
    [112]=
    {
        ["nID"]=112,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://jx3.xoyo.com/p/zt/2025/10/30/douyin-binding/index.html')"
        }
    },
    [113]=
    {
        ["nID"]=113,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [114]=
    {
        ["nID"]=114,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/103/6')"
        }
    },
    [115]=
    {
        ["nID"]=115,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'CoinShopHair')"
        }
    },
    [116]=
    {
        ["nID"]=116,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [117]=
    {
        ["nID"]=117,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [118]=
    {
        ["nID"]=118,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1117/8')"
        }
    },
    [119]=
    {
        ["nID"]=119,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1323/13')"
        }
    },
    [120]=
    {
        ["nID"]=120,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/1542/1')"
        }
    },
    [121]=
    {
        ["nID"]=121,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('LinkActivity/1024')"
        }
    },
    [122]=
    {
        ["nID"]=122,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [123]=
    {
        ["nID"]=123,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/104/9')"
        }
    },
    [124]=
    {
        ["nID"]=124,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [125]=
    {
        ["nID"]=125,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/906/11')"
        }
    },
    [126]=
    {
        ["nID"]=126,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://www.bilibili.com/blackboard/era/CW66zg1KuKKtzprR.html')"
        }
    },
    [127]=
    {
        ["nID"]=127,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://www.bilibili.com/blackboard/era/NWxG0IhlKGSNBJMY.html')"
        }
    },
    [128]=
    {
        ["nID"]=128,
        ["szBtnDes"]="立即前往",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIMgr.Open(VIEW_ID.PanelSkillNew, 102393)"
        }
    },
    [129]=
    {
        ["nID"]=129,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'CoinShopTitle/3/4')"
        }
    },
    [130]=
    {
        ["nID"]=130,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'Exterior/4/6000')"
        }
    },
    [131]=
    {
        ["nID"]=131,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [132]=
    {
        ["nID"]=132,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('Update_Target_List', '')"
        }
    },
    [133]=
    {
        ["nID"]=133,
        ["szBtnDes"]="打开商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('ShopPanel/412/14')"
        }
    },
    [134]=
    {
        ["nID"]=134,
        ["szBtnDes"]="内容前瞻",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://weibo.com/ttarticle/p/show?id=2309405244781512229269')"
        }
    },
    [135]=
    {
        ["nID"]=135,
        ["szBtnDes"]="前往投票",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="WebUrl.OpenByID(WEBURL_ID.WEB_EFFECT)"
        }
    },
    [136]=
    {
        ["nID"]=136,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="Event.Dispatch('EVENT_LINK_NOTIFY', 'OrangeWeaponUpg/130')"
        }
    },
    [137]=
    {
        ["nID"]=137,
        ["szBtnDes"]="前往商城",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="CoinShopData.Open()"
        }
    },
    [138]=
    {
        ["nID"]=138,
        ["szBtnDes"]="查看春节活动",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIMgr.Open(VIEW_ID.PanelSpringFestival)"
        }
    },
    [139]=
    {
        ["nID"]=139,
        ["szBtnDes"]="前往参与",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('WebURL/64')"
        }
    },
    [140]=
    {
        ["nID"]=140,
        ["szBtnDes"]="前往微信添加",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://kf-qw.xoyo.com/sy/guide?page=wmq')"
        }
    },
    [141]=
    {
        ["nID"]=141,
        ["szBtnDes"]="前往微信添加",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://kf-qw.xoyo.com/sy/guide?page=jRB')"
        }
    },
    [142]=
    {
        ["nID"]=142,
        ["szBtnDes"]="前往任务",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.TangJianZhuanTeleport()"
        }
    },
    [143]=
    {
        ["nID"]=143,
        ["szBtnDes"]="前往观战",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="RoomVoiceData.JumpToRoomVoice(true,true)"
        }
    },
    [144]=
    {
        ["nID"]=144,
        ["szBtnDes"]="前往微信添加",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://kf-qw.xoyo.com/sy/jump?page=2J0')"
        }
    },
    [145]=
    {
        ["nID"]=145,
        ["szBtnDes"]="前往微信报名",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIHelper.OpenWebWithDefaultBrowser('https://kf-qw.xoyo.com/sy/jump?page=PBk')"
        }
    },
    [146]=
    {
        ["nID"]=146,
        ["szBtnDes"]="",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {

        }
    },
    [147]=
    {
        ["nID"]=147,
        ["szBtnDes"]="前往商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="ShopData.OpenSystemShopGroup(1, 1478)"
        }
    },
    [148]=
    {
        ["nID"]=148,
        ["szBtnDes"]="前往商店",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="ShopData.OpenSystemShopGroup(1, 1184)"
        }
    },
    [149]=
    {
        ["nID"]=149,
        ["szBtnDes"]="前往浪客行",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="CollectionFuncList.Excute('GoToLKX')"
        }
    },
    [150]=
    {
        ["nID"]=150,
        ["szBtnDes"]="竞技场",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIMgr.Open(VIEW_ID.PanelPvPMatching, nil, 2)"
        }
    },
    [151]=
    {
        ["nID"]=151,
        ["szBtnDes"]="战场",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIMgr.OpenSingle(true, VIEW_ID.PanelBattleFieldInformation)"
        }
    },
    [152]=
    {
        ["nID"]=152,
        ["szBtnDes"]="绝境战场",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="UIMgr.OpenSingle(true, VIEW_ID.PanelFactionChampionship)"
        }
    },
    [153]=
    {
        ["nID"]=153,
        ["szBtnDes"]="前往秘境",
        ["szFuncTip"]="",
        ["szShowTip"]="",
        ["tbCheckFunc"]=
        {

        },
        ["tbActionFunc"]=
        {
            [1]="HuaELouData.HandleJump('FBlist/793')"
        }
    }
}
