--*************************************** 工具生成 ***************************************
UICameraTab = 
{
    ["Pet"]=
    {
        [18]=
        {
            ["nID"]=18,
            ["nIndex"]=128,
            ["szDesc"]="宠物-祥兔阿甘",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=85,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=16,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [19]=
        {
            ["nID"]=19,
            ["nIndex"]=129,
            ["szDesc"]="宠物-瑞兔阿甘",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=85,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=16,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [20]=
        {
            ["nID"]=20,
            ["nIndex"]=7,
            ["szDesc"]="宠物-比翼",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-40,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [22]=
        {
            ["nID"]=22,
            ["nIndex"]=37,
            ["szDesc"]="宠物-孔明灯·碧",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=0,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [23]=
        {
            ["nID"]=23,
            ["nIndex"]=38,
            ["szDesc"]="宠物-孔明灯·苍",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=0,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [24]=
        {
            ["nID"]=24,
            ["nIndex"]=39,
            ["szDesc"]="宠物-孔明灯·朱",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=0,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [25]=
        {
            ["nID"]=25,
            ["nIndex"]=40,
            ["szDesc"]="宠物-执子之手",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=0,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [52]=
        {
            ["nID"]=52,
            ["nIndex"]=22,
            ["szDesc"]="宠物-飞鸿",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=90,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [53]=
        {
            ["nID"]=53,
            ["nIndex"]=23,
            ["szDesc"]="宠物-白凤",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=90,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [54]=
        {
            ["nID"]=54,
            ["nIndex"]=21,
            ["szDesc"]="宠物-紫翎",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=90,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [55]=
        {
            ["nID"]=55,
            ["nIndex"]=19,
            ["szDesc"]="宠物-赤箭",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=90,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [56]=
        {
            ["nID"]=56,
            ["nIndex"]=20,
            ["szDesc"]="宠物-栖夜",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=90,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [75]=
        {
            ["nID"]=75,
            ["nIndex"]=2,
            ["szDesc"]="宠物-咕咕",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-40,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [83]=
        {
            ["nID"]=83,
            ["nIndex"]=123,
            ["szDesc"]="宠物-冰蓝花客",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-500,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=90,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=16,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [125]=
        {
            ["nID"]=125,
            ["nIndex"]=43,
            ["szDesc"]="宠物-胜鹭",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-130,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [155]=
        {
            ["nID"]=155,
            ["nIndex"]=125,
            ["szDesc"]="宠物-昊苍",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-500,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=16,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [159]=
        {
            ["nID"]=159,
            ["nIndex"]=124,
            ["szDesc"]="宠物-疾幽",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-500,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=16,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [199]=
        {
            ["nID"]=199,
            ["nIndex"]=126,
            ["szDesc"]="宠物-凌岳",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-500,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=16,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [207]=
        {
            ["nID"]=207,
            ["nIndex"]=11,
            ["szDesc"]="宠物-苍翼",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=90,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [208]=
        {
            ["nID"]=208,
            ["nIndex"]=36,
            ["szDesc"]="宠物-戏参北斗",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=0,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [255]=
        {
            ["nID"]=255,
            ["nIndex"]=33,
            ["szDesc"]="宠物-吉瑞",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-170,
                [2]=96,
                [3]=-100
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=24,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [276]=
        {
            ["nID"]=276,
            ["nIndex"]=6,
            ["szDesc"]="宠物-白小奇",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=40,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [293]=
        {
            ["nID"]=293,
            ["nIndex"]=127,
            ["szDesc"]="宠物-昊苍·急景",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-500,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=16,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [309]=
        {
            ["nID"]=309,
            ["nIndex"]=5,
            ["szDesc"]="宠物-霄霄",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-130,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [319]=
        {
            ["nID"]=319,
            ["nIndex"]=12,
            ["szDesc"]="宠物-小羽",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-130,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [336]=
        {
            ["nID"]=336,
            ["nIndex"]=24,
            ["szDesc"]="宠物-幽明录",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-80,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [374]=
        {
            ["nID"]=374,
            ["nIndex"]=3,
            ["szDesc"]="宠物-夭夭",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-170,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [380]=
        {
            ["nID"]=380,
            ["nIndex"]=4,
            ["szDesc"]="宠物-琼琼",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-120,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [383]=
        {
            ["nID"]=383,
            ["nIndex"]=8,
            ["szDesc"]="宠物-雀食",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-120,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [409]=
        {
            ["nID"]=409,
            ["nIndex"]=1,
            ["szDesc"]="宠物-小鸮",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-130,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [414]=
        {
            ["nID"]=414,
            ["nIndex"]=31,
            ["szDesc"]="宠物-喳喳",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-70,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [426]=
        {
            ["nID"]=426,
            ["nIndex"]=27,
            ["szDesc"]="宠物-静子",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-160,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [427]=
        {
            ["nID"]=427,
            ["nIndex"]=34,
            ["szDesc"]="宠物-霜繁枝",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-80,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [429]=
        {
            ["nID"]=429,
            ["nIndex"]=9,
            ["szDesc"]="宠物-岁岁",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-130,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [430]=
        {
            ["nID"]=430,
            ["nIndex"]=10,
            ["szDesc"]="宠物-冥冥",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-80,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [431]=
        {
            ["nID"]=431,
            ["nIndex"]=13,
            ["szDesc"]="宠物-江南沧浪子",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-120,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [432]=
        {
            ["nID"]=432,
            ["nIndex"]=15,
            ["szDesc"]="宠物-九州百人语",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-120,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [433]=
        {
            ["nID"]=433,
            ["nIndex"]=16,
            ["szDesc"]="宠物-岚峰小二爷",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-120,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [434]=
        {
            ["nID"]=434,
            ["nIndex"]=14,
            ["szDesc"]="宠物-瀚海小旋风",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-120,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [435]=
        {
            ["nID"]=435,
            ["nIndex"]=18,
            ["szDesc"]="宠物-翁洲青蓑衣",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-120,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [436]=
        {
            ["nID"]=436,
            ["nIndex"]=17,
            ["szDesc"]="宠物-滩涂背刀客",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-120,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [439]=
        {
            ["nID"]=439,
            ["nIndex"]=41,
            ["szDesc"]="宠物-青云客",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-130,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [446]=
        {
            ["nID"]=446,
            ["nIndex"]=32,
            ["szDesc"]="宠物-小肥啾",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-70,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [452]=
        {
            ["nID"]=452,
            ["nIndex"]=25,
            ["szDesc"]="宠物-灵鸽·小七",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-120,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [455]=
        {
            ["nID"]=455,
            ["nIndex"]=26,
            ["szDesc"]="宠物-念念归",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-90,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [457]=
        {
            ["nID"]=457,
            ["nIndex"]=35,
            ["szDesc"]="宠物-小钻风",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=-40,
                [2]=16,
                [3]=20
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [466]=
        {
            ["nID"]=466,
            ["nIndex"]=30,
            ["szDesc"]="宠物-蛋黄",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-70,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [485]=
        {
            ["nID"]=485,
            ["nIndex"]=28,
            ["szDesc"]="宠物-鸷",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-150,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [486]=
        {
            ["nID"]=486,
            ["nIndex"]=29,
            ["szDesc"]="宠物-盈盈",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-340,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [499]=
        {
            ["nID"]=499,
            ["nIndex"]=42,
            ["szDesc"]="宠物-絮絮",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-130,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [518]=
        {
            ["nID"]=518,
            ["nIndex"]=121,
            ["szDesc"]="宠物-小红一百",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-70,
                [2]=60,
                [3]=-60
            },
            ["tbCameraLookPos"]=
            {
                [1]=102,
                [2]=12,
                [3]=42
            },
            ["tbModelTranslation"]=
            {
                [1]=20,
                [2]=20,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [519]=
        {
            ["nID"]=519,
            ["nIndex"]=122,
            ["szDesc"]="宠物-苍穹",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-360,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=78,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=0,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [522]=
        {
            ["nID"]=522,
            ["nIndex"]=131,
            ["szDesc"]="宠物-天禄",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=-290,
                [2]=78,
                [3]=-80
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [523]=
        {
            ["nID"]=523,
            ["nIndex"]=132,
            ["szDesc"]="宠物-吐宝神鼬",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=-250,
                [2]=60,
                [3]=-60
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [524]=
        {
            ["nID"]=524,
            ["nIndex"]=133,
            ["szDesc"]="宠物-金角",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=-260,
                [2]=66,
                [3]=-70
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [525]=
        {
            ["nID"]=525,
            ["nIndex"]=134,
            ["szDesc"]="宠物-八斤",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=-140,
                [2]=36,
                [3]=-40
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [526]=
        {
            ["nID"]=526,
            ["nIndex"]=135,
            ["szDesc"]="宠物-银角",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=-280,
                [2]=72,
                [3]=-70
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [527]=
        {
            ["nID"]=527,
            ["nIndex"]=136,
            ["szDesc"]="宠物-长镰",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=120,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=500,
                [2]=18,
                [3]=140
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [546]=
        {
            ["nID"]=546,
            ["nIndex"]=137,
            ["szDesc"]="宠物-花楹",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-54,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        ["default"]=
        {
            ["nID"]=0,
            ["nIndex"]=-2,
            ["szDesc"]="宠物 - 默认值",
            ["szType"]="Pet",
            ["nModelYaw"]=1.9,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=55,
                [3]=-15
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=16,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.45,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        }
    },
    ["Ride"]=
    {
        [1604]=
        {
            ["nID"]=1604,
            ["nIndex"]=101,
            ["szDesc"]="坐骑 - 成就奖励",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=116,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=106,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=12,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [3152]=
        {
            ["nID"]=3152,
            ["nIndex"]=100,
            ["szDesc"]="坐骑 - 声望奖励",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=126,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=116,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=12,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [60358]=
        {
            ["nID"]=60358,
            ["nIndex"]=103,
            ["szDesc"]="坐骑-渡情",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=50,
                [2]=20,
                [3]=-40
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [63440]=
        {
            ["nID"]=63440,
            ["nIndex"]=104,
            ["szDesc"]="坐骑-鸾",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=40,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [90153]=
        {
            ["nID"]=90153,
            ["nIndex"]=105,
            ["szDesc"]="坐骑-月伴晨星",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=42,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [97910]=
        {
            ["nID"]=97910,
            ["nIndex"]=106,
            ["szDesc"]="坐骑-星河清梦",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=24,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [115525]=
        {
            ["nID"]=115525,
            ["nIndex"]=107,
            ["szDesc"]="坐骑-红罗舸",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=24,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [119772]=
        {
            ["nID"]=119772,
            ["nIndex"]=108,
            ["szDesc"]="坐骑-兰芷风烟",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=36,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [125802]=
        {
            ["nID"]=125802,
            ["nIndex"]=109,
            ["szDesc"]="坐骑-乘雀揽星",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=24,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [129859]=
        {
            ["nID"]=129859,
            ["nIndex"]=110,
            ["szDesc"]="坐骑-画境仙游",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=22,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [136213]=
        {
            ["nID"]=136213,
            ["nIndex"]=111,
            ["szDesc"]="坐骑-玉鸾临渊·千灯",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=40,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [136247]=
        {
            ["nID"]=136247,
            ["nIndex"]=102,
            ["szDesc"]="坐骑-八卦龟",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=35,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [136254]=
        {
            ["nID"]=136254,
            ["nIndex"]=112,
            ["szDesc"]="坐骑-骁齿",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=36,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [136270]=
        {
            ["nID"]=136270,
            ["nIndex"]=113,
            ["szDesc"]="坐骑-锦鳞戏辰",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=64,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [136282]=
        {
            ["nID"]=136282,
            ["nIndex"]=114,
            ["szDesc"]="坐骑-共潮生·海小一",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=24,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [176644]=
        {
            ["nID"]=176644,
            ["nIndex"]=116,
            ["szDesc"]="坐骑-烟波流光",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=34,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [176647]=
        {
            ["nID"]=176647,
            ["nIndex"]=115,
            ["szDesc"]="坐骑-奔腾不休盆盆船",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=20,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [211385]=
        {
            ["nID"]=211385,
            ["nIndex"]=119,
            ["szDesc"]="坐骑-麒麟·幻影",
            ["szType"]="Ride",
            ["nModelYaw"]=1.6,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=12,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [211392]=
        {
            ["nID"]=211392,
            ["nIndex"]=117,
            ["szDesc"]="坐骑-鳄霸",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=18,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [211401]=
        {
            ["nID"]=211401,
            ["nIndex"]=118,
            ["szDesc"]="坐骑-万顷波",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=34,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [211446]=
        {
            ["nID"]=211446,
            ["nIndex"]=120,
            ["szDesc"]="坐骑-松枝悦",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=30,
                [2]=40,
                [3]=-90
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        [211453]=
        {
            ["nID"]=211453,
            ["nIndex"]=130,
            ["szDesc"]="坐骑-七星剑",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-230,
                [2]=150,
                [3]=-200
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=30,
                [3]=-156
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=-48,
                [3]=-140
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        },
        ["default"]=
        {
            ["nID"]=0,
            ["nIndex"]=-3,
            ["szDesc"]="坐骑 - 默认值",
            ["szType"]="Ride",
            ["nModelYaw"]=2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=106,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=100,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=0,
                [2]=12,
                [3]=0
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        }
    },
    ["PartnerNpc"]=
    {
        ["default"]=
        {
            ["nID"]=0,
            ["nIndex"]=-1,
            ["szDesc"]="红尘侠影 - 默认值",
            ["szType"]="PartnerNpc",
            ["nModelYaw"]=1.2,
            ["tbCameraPos"]=
            {
                [1]=-400,
                [2]=120,
                [3]=-110
            },
            ["tbCameraLookPos"]=
            {
                [1]=0,
                [2]=114,
                [3]=-30
            },
            ["tbModelTranslation"]=
            {
                [1]=-80,
                [2]=12,
                [3]=50
            },
            ["tbCameraPerspective"]=
            {
                [1]=0.79,
                [2]=1.78,
                [3]=20,
                [4]=40000
            }
        }
    }
}
