--*************************************** 工具生成 ***************************************
UIChatDisplayFlagTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["szName"]="全部",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {

        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_05",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_12.png"
    },
    [2]=
    {
        ["nID"]=2,
        ["szName"]="世界",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=32
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_12",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_11.png"
    },
    [3]=
    {
        ["nID"]=3,
        ["szName"]="近聊",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=1
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_10",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_01.png"
    },
    [4]=
    {
        ["nID"]=4,
        ["szName"]="地图",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=5
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_02",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_09.png"
    },
    [5]=
    {
        ["nID"]=5,
        ["szName"]="队伍",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=2
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_01",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_10.png"
    },
    [6]=
    {
        ["nID"]=6,
        ["szName"]="帮会",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=29,
            [2]=31
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_07",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_05.png"
    },
    [7]=
    {
        ["nID"]=7,
        ["szName"]="门派",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=33
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_06",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_06.png"
    },
    [8]=
    {
        ["nID"]=8,
        ["szName"]="阵营",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=34
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_08",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_04.png"
    },
    [9]=
    {
        ["nID"]=9,
        ["szName"]="密聊",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=6
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_03",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_08.png"
    },
    [10]=
    {
        ["nID"]=10,
        ["szName"]="侠缘",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=-2
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_22",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_08.png"
    },
    [11]=
    {
        ["nID"]=11,
        ["szName"]="好友",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=36
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_04",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_07.png"
    },
    [12]=
    {
        ["nID"]=12,
        ["szName"]="全服",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=49
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_14",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_13.png"
    },
    [13]=
    {
        ["nID"]=13,
        ["szName"]="战场",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=4
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_09",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_03.png"
    },
    [14]=
    {
        ["nID"]=14,
        ["szName"]="李渡鬼域",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=47
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_19",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_03.png"
    },
    [15]=
    {
        ["nID"]=15,
        ["szName"]="系统",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=7,
            [2]=9,
            [3]=35,
            [4]=37,
            [5]=48
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_11",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_02.png"
    },
    [16]=
    {
        ["nID"]=16,
        ["szName"]="剧情",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {

        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_15",
        ["szUIChannelIcon"]=""
    },
    [17]=
    {
        ["nID"]=17,
        ["szName"]="团队",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=3
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_13",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_18.png"
    },
    [18]=
    {
        ["nID"]=18,
        ["szName"]="同盟",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=30
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_16",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_17.png"
    },
    [19]=
    {
        ["nID"]=19,
        ["szName"]="GM",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=8,
            [2]=10,
            [3]=11,
            [4]=12,
            [5]=13
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_GM",
        ["szUIChannelIcon"]=""
    },
    [20]=
    {
        ["nID"]=20,
        ["szName"]="NPC",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=14,
            [2]=15,
            [3]=16,
            [4]=17,
            [5]=18,
            [6]=19,
            [7]=20,
            [8]=21,
            [9]=22,
            [10]=23,
            [11]=24,
            [12]=25,
            [13]=26,
            [14]=27,
            [15]=28
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_NPC",
        ["szUIChannelIcon"]=""
    },
    [21]=
    {
        ["nID"]=21,
        ["szName"]="萌新",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=40
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_17",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_15.png"
    },
    [22]=
    {
        ["nID"]=22,
        ["szName"]="房间",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=50
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_18",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_16.png"
    },
    [23]=
    {
        ["nID"]=23,
        ["szName"]="战斗",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=-1
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_20",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_16.png"
    },
    [24]=
    {
        ["nID"]=24,
        ["szName"]="语音",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=51
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_21",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_19.png"
    },
    [25]=
    {
        ["nID"]=25,
        ["szName"]="弹幕",
        ["nOpenAcv"]=0,
        ["nOpenLvl"]=0,
        ["tbChannelIDs"]=
        {
            [1]=52
        },
        ["szChannelIcon"]="UIAtlas2_Chat_Chat1_img_sort_23",
        ["szUIChannelIcon"]="UIAtlas2_Chat_Chat1_icon_sort_19.png"
    }
}
