--*************************************** 工具生成 ***************************************
--@see trunk/tools/CocosCreator/project/Tools/ToLuaTool/special_tab/generateOtherTab.lua

UIChatEmojiGroupTab = 
{
    [0] = {nGroupID = 0, szGroupName = "默认表情", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face"},
    [1] = {nGroupID = 1, szGroupName = "萌鸡", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_kaixin_0002"},
    [2] = {nGroupID = 2, szGroupName = "企鹅", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face1"},
    [3] = {nGroupID = 3, szGroupName = "萌虎", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face2"},
    [4] = {nGroupID = 4, szGroupName = "明教萌猫", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face3"},
    [5] = {nGroupID = 5, szGroupName = "万花松鼠", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face8"},
    [6] = {nGroupID = 6, szGroupName = "少林灵猴", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face5"},
    [7] = {nGroupID = 7, szGroupName = "唐门小猪", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face7"},
    [8] = {nGroupID = 8, szGroupName = "七秀萌兔", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face6"},
    [9] = {nGroupID = 9, szGroupName = "五毒孔雀", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face11"},
    [10] = {nGroupID = 10, szGroupName = "长歌小鹿", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face10"},
    [11] = {nGroupID = 11, szGroupName = "藏剑猞猁", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face12"},
    [12] = {nGroupID = 12, szGroupName = "苍云幼狮", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face9"},
    [13] = {nGroupID = 13, szGroupName = "纯阳仙鹤", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face14"},
    [14] = {nGroupID = 14, szGroupName = "丐帮鹰隼", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face13"},
    [15] = {nGroupID = 15, szGroupName = "天策小狼", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face4"},
    [16] = {nGroupID = 16, szGroupName = "霸刀雪貂", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face15"},
    [17] = {nGroupID = 17, szGroupName = "弹幕", szGroupIcon = "Resource_ChatEmotion_Danmaku_face_哎嘿嘿"},
    [18] = {nGroupID = 18, szGroupName = "蓬莱海獭", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face16"},
    [19] = {nGroupID = 19, szGroupName = "沈剑心", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face17"},
    [20] = {nGroupID = 20, szGroupName = "凌雪阁黑豹", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face18"},
    [21] = {nGroupID = 21, szGroupName = "衍天宗幻狐", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face19"},
    [22] = {nGroupID = 22, szGroupName = "鹰嘤", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face20"},
    [23] = {nGroupID = 23, szGroupName = "鹿呦呦", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face21"},
    [24] = {nGroupID = 24, szGroupName = "药宗狍子", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face23"},
    [25] = {nGroupID = 25, szGroupName = "鸭吖", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face24"},
    [26] = {nGroupID = 26, szGroupName = "团团子", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face25"},
    [27] = {nGroupID = 27, szGroupName = "虎崽", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face29"},
    [28] = {nGroupID = 28, szGroupName = "妙喵", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face32"},
    [29] = {nGroupID = 29, szGroupName = "冲鸭", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face30"},
    [30] = {nGroupID = 30, szGroupName = "羊羊出击", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face33"},
    [31] = {nGroupID = 31, szGroupName = "狼狼冲呀", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face34"},
    [32] = {nGroupID = 32, szGroupName = "熊宝", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face38"},
    [33] = {nGroupID = 33, szGroupName = "啾啾", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face40"},
    [34] = {nGroupID = 34, szGroupName = "刀宗鹦鹉", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face39"},
    [35] = {nGroupID = 35, szGroupName = "甜兔", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face41"},
    [36] = {nGroupID = 36, szGroupName = "阿寨", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face42"},
    [37] = {nGroupID = 37, szGroupName = "猫猫突击", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face43"},
    [38] = {nGroupID = 38, szGroupName = "兔兔探头", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face44"},
    [39] = {nGroupID = 39, szGroupName = "豹抱", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face46"},
    [40] = {nGroupID = 40, szGroupName = "", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face49"},
    [41] = {nGroupID = 41, szGroupName = "小黑喵喵", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face50"},
    [42] = {nGroupID = 42, szGroupName = "小黑少侠", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face51"},
    [43] = {nGroupID = 43, szGroupName = "龙宝", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face52"},
    [44] = {nGroupID = 44, szGroupName = "神龙大侠", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face55"},
    [45] = {nGroupID = 45, szGroupName = "非人哉", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face56"},
    [46] = {nGroupID = 46, szGroupName = "小企", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face57"},
    [47] = {nGroupID = 47, szGroupName = "哎鸭", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face59"},
    [48] = {nGroupID = 48, szGroupName = "段氏小熊猫", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face61"},
    [49] = {nGroupID = 49, szGroupName = "考考", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face62"},
    [50] = {nGroupID = 50, szGroupName = "咪咿", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face63"},
    [51] = {nGroupID = 51, szGroupName = "有兽焉", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face65"},
    [52] = {nGroupID = 52, szGroupName = "美汪", szGroupIcon = "UIAtlas2_Chat_Talk_firstframe_Talk_face66"},
}
