--*************************************** 工具生成 ***************************************
UIDynamicSkillInfoTab = 
{
    [4265]=
    {
        ["ID"]=4265,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [4267]=
    {
        ["ID"]=4267,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [7876]=
    {
        ["ID"]=7876,
        ["szDetail"]="",
        ["szFuncName"]="斩"
    },
    [7877]=
    {
        ["ID"]=7877,
        ["szDetail"]="",
        ["szFuncName"]="赦"
    },
    [8815]=
    {
        ["ID"]=8815,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [8818]=
    {
        ["ID"]=8818,
        ["szDetail"]="",
        ["szFuncName"]="冲锋"
    },
    [8819]=
    {
        ["ID"]=8819,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [8820]=
    {
        ["ID"]=8820,
        ["szDetail"]="",
        ["szFuncName"]="解控"
    },
    [8821]=
    {
        ["ID"]=8821,
        ["szDetail"]="",
        ["szFuncName"]="减伤"
    },
    [8829]=
    {
        ["ID"]=8829,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [8830]=
    {
        ["ID"]=8830,
        ["szDetail"]="",
        ["szFuncName"]="易伤"
    },
    [8831]=
    {
        ["ID"]=8831,
        ["szDetail"]="",
        ["szFuncName"]="增伤"
    },
    [8832]=
    {
        ["ID"]=8832,
        ["szDetail"]="",
        ["szFuncName"]="减伤"
    },
    [8833]=
    {
        ["ID"]=8833,
        ["szDetail"]="",
        ["szFuncName"]="免控"
    },
    [8955]=
    {
        ["ID"]=8955,
        ["szDetail"]="",
        ["szFuncName"]="燃火箭"
    },
    [8962]=
    {
        ["ID"]=8962,
        ["szDetail"]="",
        ["szFuncName"]="自爆"
    },
    [8968]=
    {
        ["ID"]=8968,
        ["szDetail"]="",
        ["szFuncName"]="连射"
    },
    [8972]=
    {
        ["ID"]=8972,
        ["szDetail"]="",
        ["szFuncName"]="战斗"
    },
    [8973]=
    {
        ["ID"]=8973,
        ["szDetail"]="",
        ["szFuncName"]="移动"
    },
    [9020]=
    {
        ["ID"]=9020,
        ["szDetail"]="",
        ["szFuncName"]="离开坐骑"
    },
    [9042]=
    {
        ["ID"]=9042,
        ["szDetail"]="",
        ["szFuncName"]="自爆"
    },
    [9071]=
    {
        ["ID"]=9071,
        ["szDetail"]="",
        ["szFuncName"]="扫射"
    },
    [9079]=
    {
        ["ID"]=9079,
        ["szDetail"]="",
        ["szFuncName"]="扫射"
    },
    [9085]=
    {
        ["ID"]=9085,
        ["szDetail"]="",
        ["szFuncName"]="点火"
    },
    [9086]=
    {
        ["ID"]=9086,
        ["szDetail"]="",
        ["szFuncName"]="爆发"
    },
    [9091]=
    {
        ["ID"]=9091,
        ["szDetail"]="",
        ["szFuncName"]="穿心弩"
    },
    [9100]=
    {
        ["ID"]=9100,
        ["szDetail"]="",
        ["szFuncName"]="照明弹"
    },
    [9267]=
    {
        ["ID"]=9267,
        ["szDetail"]="",
        ["szFuncName"]="战斗"
    },
    [9294]=
    {
        ["ID"]=9294,
        ["szDetail"]="",
        ["szFuncName"]="移动"
    },
    [9301]=
    {
        ["ID"]=9301,
        ["szDetail"]="",
        ["szFuncName"]="碎山石"
    },
    [9302]=
    {
        ["ID"]=9302,
        ["szDetail"]="",
        ["szFuncName"]="裂火石"
    },
    [9307]=
    {
        ["ID"]=9307,
        ["szDetail"]="",
        ["szFuncName"]="撞击"
    },
    [13952]=
    {
        ["ID"]=13952,
        ["szDetail"]="",
        ["szFuncName"]="泥鳅"
    },
    [13953]=
    {
        ["ID"]=13953,
        ["szDetail"]="",
        ["szFuncName"]="狗尾巴草"
    },
    [13954]=
    {
        ["ID"]=13954,
        ["szDetail"]="",
        ["szFuncName"]="蚯蚓"
    },
    [13955]=
    {
        ["ID"]=13955,
        ["szDetail"]="",
        ["szFuncName"]="收竿"
    },
    [14374]=
    {
        ["ID"]=14374,
        ["szDetail"]="",
        ["szFuncName"]="战斗"
    },
    [14375]=
    {
        ["ID"]=14375,
        ["szDetail"]="",
        ["szFuncName"]="移动"
    },
    [14376]=
    {
        ["ID"]=14376,
        ["szDetail"]="",
        ["szFuncName"]="连射"
    },
    [14378]=
    {
        ["ID"]=14378,
        ["szDetail"]="",
        ["szFuncName"]="燃火箭"
    },
    [14380]=
    {
        ["ID"]=14380,
        ["szDetail"]="",
        ["szFuncName"]="自爆"
    },
    [14382]=
    {
        ["ID"]=14382,
        ["szDetail"]="",
        ["szFuncName"]="穿心弩"
    },
    [14387]=
    {
        ["ID"]=14387,
        ["szDetail"]="",
        ["szFuncName"]="扫射"
    },
    [14564]=
    {
        ["ID"]=14564,
        ["szDetail"]="",
        ["szFuncName"]="投掷"
    },
    [14682]=
    {
        ["ID"]=14682,
        ["szDetail"]="",
        ["szFuncName"]="战斗"
    },
    [14683]=
    {
        ["ID"]=14683,
        ["szDetail"]="",
        ["szFuncName"]="移动"
    },
    [14684]=
    {
        ["ID"]=14684,
        ["szDetail"]="",
        ["szFuncName"]="碎山石"
    },
    [14685]=
    {
        ["ID"]=14685,
        ["szDetail"]="",
        ["szFuncName"]="裂火石"
    },
    [14686]=
    {
        ["ID"]=14686,
        ["szDetail"]="",
        ["szFuncName"]="撞击"
    },
    [14786]=
    {
        ["ID"]=14786,
        ["szDetail"]="",
        ["szFuncName"]="齐射"
    },
    [14978]=
    {
        ["ID"]=14978,
        ["szDetail"]="",
        ["szFuncName"]="火油箭"
    },
    [14982]=
    {
        ["ID"]=14982,
        ["szDetail"]="",
        ["szFuncName"]="石爆"
    },
    [15003]=
    {
        ["ID"]=15003,
        ["szDetail"]="",
        ["szFuncName"]="战斗"
    },
    [15004]=
    {
        ["ID"]=15004,
        ["szDetail"]="",
        ["szFuncName"]="移动"
    },
    [15005]=
    {
        ["ID"]=15005,
        ["szDetail"]="",
        ["szFuncName"]="连射"
    },
    [15009]=
    {
        ["ID"]=15009,
        ["szDetail"]="",
        ["szFuncName"]="燃火箭"
    },
    [15012]=
    {
        ["ID"]=15012,
        ["szDetail"]="",
        ["szFuncName"]="自爆"
    },
    [15015]=
    {
        ["ID"]=15015,
        ["szDetail"]="",
        ["szFuncName"]="穿心弩"
    },
    [15021]=
    {
        ["ID"]=15021,
        ["szDetail"]="",
        ["szFuncName"]="扫射"
    },
    [15106]=
    {
        ["ID"]=15106,
        ["szDetail"]="",
        ["szFuncName"]="投掷"
    },
    [15111]=
    {
        ["ID"]=15111,
        ["szDetail"]="",
        ["szFuncName"]="骑乘"
    },
    [17272]=
    {
        ["ID"]=17272,
        ["szDetail"]="",
        ["szFuncName"]="焰火红绯"
    },
    [17273]=
    {
        ["ID"]=17273,
        ["szDetail"]="",
        ["szFuncName"]="焰火月白"
    },
    [17667]=
    {
        ["ID"]=17667,
        ["szDetail"]="",
        ["szFuncName"]="星彩绽击"
    },
    [17672]=
    {
        ["ID"]=17672,
        ["szDetail"]="",
        ["szFuncName"]="破浪冲锋"
    },
    [17674]=
    {
        ["ID"]=17674,
        ["szDetail"]="",
        ["szFuncName"]="网罗后船"
    },
    [17676]=
    {
        ["ID"]=17676,
        ["szDetail"]="",
        ["szFuncName"]="抛竿"
    },
    [17677]=
    {
        ["ID"]=17677,
        ["szDetail"]="",
        ["szFuncName"]="收竿"
    },
    [17678]=
    {
        ["ID"]=17678,
        ["szDetail"]="",
        ["szFuncName"]="对饮游侠"
    },
    [17692]=
    {
        ["ID"]=17692,
        ["szDetail"]="",
        ["szFuncName"]="火龙击"
    },
    [18876]=
    {
        ["ID"]=18876,
        ["szDetail"]="",
        ["szFuncName"]="降落"
    },
    [19356]=
    {
        ["ID"]=19356,
        ["szDetail"]="",
        ["szFuncName"]="迅影凌波"
    },
    [19357]=
    {
        ["ID"]=19357,
        ["szDetail"]="",
        ["szFuncName"]="无畏冲锋"
    },
    [19360]=
    {
        ["ID"]=19360,
        ["szDetail"]="",
        ["szFuncName"]="临时加固"
    },
    [19361]=
    {
        ["ID"]=19361,
        ["szDetail"]="",
        ["szFuncName"]="坠星震击"
    },
    [19387]=
    {
        ["ID"]=19387,
        ["szDetail"]="",
        ["szFuncName"]="排浪击"
    },
    [19389]=
    {
        ["ID"]=19389,
        ["szDetail"]="",
        ["szFuncName"]="雷音震爆"
    },
    [19411]=
    {
        ["ID"]=19411,
        ["szDetail"]="",
        ["szFuncName"]="加速"
    },
    [19448]=
    {
        ["ID"]=19448,
        ["szDetail"]="",
        ["szFuncName"]="回复"
    },
    [20441]=
    {
        ["ID"]=20441,
        ["szDetail"]="",
        ["szFuncName"]="燃火箭"
    },
    [20442]=
    {
        ["ID"]=20442,
        ["szDetail"]="",
        ["szFuncName"]="增益"
    },
    [20455]=
    {
        ["ID"]=20455,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [20456]=
    {
        ["ID"]=20456,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [20791]=
    {
        ["ID"]=20791,
        ["szDetail"]="",
        ["szFuncName"]="月弄痕"
    },
    [20792]=
    {
        ["ID"]=20792,
        ["szDetail"]="",
        ["szFuncName"]="张桎辕"
    },
    [20794]=
    {
        ["ID"]=20794,
        ["szDetail"]="",
        ["szFuncName"]="司空仲平"
    },
    [20797]=
    {
        ["ID"]=20797,
        ["szDetail"]="",
        ["szFuncName"]="肖药儿"
    },
    [20798]=
    {
        ["ID"]=20798,
        ["szDetail"]="",
        ["szFuncName"]="米丽古丽"
    },
    [20799]=
    {
        ["ID"]=20799,
        ["szDetail"]="",
        ["szFuncName"]="陶寒亭"
    },
    [20864]=
    {
        ["ID"]=20864,
        ["szDetail"]="",
        ["szFuncName"]="减伤"
    },
    [21039]=
    {
        ["ID"]=21039,
        ["szDetail"]="",
        ["szFuncName"]="下马"
    },
    [21040]=
    {
        ["ID"]=21040,
        ["szDetail"]="",
        ["szFuncName"]="同骑"
    },
    [21254]=
    {
        ["ID"]=21254,
        ["szDetail"]="",
        ["szFuncName"]="焰火若竹"
    },
    [22842]=
    {
        ["ID"]=22842,
        ["szDetail"]="",
        ["szFuncName"]="追星"
    },
    [22846]=
    {
        ["ID"]=22846,
        ["szDetail"]="",
        ["szFuncName"]="箭雨"
    },
    [22861]=
    {
        ["ID"]=22861,
        ["szDetail"]="",
        ["szFuncName"]="扫射"
    },
    [22908]=
    {
        ["ID"]=22908,
        ["szDetail"]="",
        ["szFuncName"]="免控"
    },
    [23769]=
    {
        ["ID"]=23769,
        ["szDetail"]="",
        ["szFuncName"]="向左"
    },
    [23770]=
    {
        ["ID"]=23770,
        ["szDetail"]="",
        ["szFuncName"]="向右"
    },
    [23772]=
    {
        ["ID"]=23772,
        ["szDetail"]="",
        ["szFuncName"]="躺下"
    },
    [23773]=
    {
        ["ID"]=23773,
        ["szDetail"]="",
        ["szFuncName"]="坐起"
    },
    [23781]=
    {
        ["ID"]=23781,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [23782]=
    {
        ["ID"]=23782,
        ["szDetail"]="",
        ["szFuncName"]="交互"
    },
    [23828]=
    {
        ["ID"]=23828,
        ["szDetail"]="",
        ["szFuncName"]="扶摇"
    },
    [23830]=
    {
        ["ID"]=23830,
        ["szDetail"]="",
        ["szFuncName"]="倚靠"
    },
    [23831]=
    {
        ["ID"]=23831,
        ["szDetail"]="",
        ["szFuncName"]="向内"
    },
    [23832]=
    {
        ["ID"]=23832,
        ["szDetail"]="",
        ["szFuncName"]="侧坐"
    },
    [23833]=
    {
        ["ID"]=23833,
        ["szDetail"]="",
        ["szFuncName"]="向外"
    },
    [23834]=
    {
        ["ID"]=23834,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [23852]=
    {
        ["ID"]=23852,
        ["szDetail"]="",
        ["szFuncName"]="侧坐"
    },
    [23853]=
    {
        ["ID"]=23853,
        ["szDetail"]="",
        ["szFuncName"]="向外"
    },
    [23854]=
    {
        ["ID"]=23854,
        ["szDetail"]="",
        ["szFuncName"]="倚靠"
    },
    [23855]=
    {
        ["ID"]=23855,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [23857]=
    {
        ["ID"]=23857,
        ["szDetail"]="",
        ["szFuncName"]="侧坐"
    },
    [23858]=
    {
        ["ID"]=23858,
        ["szDetail"]="",
        ["szFuncName"]="向内"
    },
    [23859]=
    {
        ["ID"]=23859,
        ["szDetail"]="",
        ["szFuncName"]="向外"
    },
    [23860]=
    {
        ["ID"]=23860,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [23888]=
    {
        ["ID"]=23888,
        ["szDetail"]="",
        ["szFuncName"]="向左"
    },
    [23889]=
    {
        ["ID"]=23889,
        ["szDetail"]="",
        ["szFuncName"]="向右"
    },
    [23890]=
    {
        ["ID"]=23890,
        ["szDetail"]="",
        ["szFuncName"]="躺下"
    },
    [23891]=
    {
        ["ID"]=23891,
        ["szDetail"]="",
        ["szFuncName"]="坐起"
    },
    [23892]=
    {
        ["ID"]=23892,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [23895]=
    {
        ["ID"]=23895,
        ["szDetail"]="",
        ["szFuncName"]="写字"
    },
    [23896]=
    {
        ["ID"]=23896,
        ["szDetail"]="",
        ["szFuncName"]="读书"
    },
    [23897]=
    {
        ["ID"]=23897,
        ["szDetail"]="",
        ["szFuncName"]="画画"
    },
    [23899]=
    {
        ["ID"]=23899,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [23916]=
    {
        ["ID"]=23916,
        ["szDetail"]="",
        ["szFuncName"]="描眉"
    },
    [23917]=
    {
        ["ID"]=23917,
        ["szDetail"]="",
        ["szFuncName"]="唇纸"
    },
    [23918]=
    {
        ["ID"]=23918,
        ["szDetail"]="",
        ["szFuncName"]="腮红"
    },
    [23919]=
    {
        ["ID"]=23919,
        ["szDetail"]="",
        ["szFuncName"]="梳头"
    },
    [23920]=
    {
        ["ID"]=23920,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [23963]=
    {
        ["ID"]=23963,
        ["szDetail"]="",
        ["szFuncName"]="戏水"
    },
    [23964]=
    {
        ["ID"]=23964,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [24007]=
    {
        ["ID"]=24007,
        ["szDetail"]="",
        ["szFuncName"]="捶背"
    },
    [24008]=
    {
        ["ID"]=24008,
        ["szDetail"]="",
        ["szFuncName"]="静看"
    },
    [24013]=
    {
        ["ID"]=24013,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [24065]=
    {
        ["ID"]=24065,
        ["szDetail"]="",
        ["szFuncName"]="如厕"
    },
    [24066]=
    {
        ["ID"]=24066,
        ["szDetail"]="",
        ["szFuncName"]="清洁"
    },
    [24068]=
    {
        ["ID"]=24068,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [24069]=
    {
        ["ID"]=24069,
        ["szDetail"]="",
        ["szFuncName"]="加水"
    },
    [24070]=
    {
        ["ID"]=24070,
        ["szDetail"]="",
        ["szFuncName"]="盥洗"
    },
    [24071]=
    {
        ["ID"]=24071,
        ["szDetail"]="",
        ["szFuncName"]="擦干"
    },
    [24072]=
    {
        ["ID"]=24072,
        ["szDetail"]="",
        ["szFuncName"]="倒水"
    },
    [24073]=
    {
        ["ID"]=24073,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [24076]=
    {
        ["ID"]=24076,
        ["szDetail"]="",
        ["szFuncName"]="打水"
    },
    [24077]=
    {
        ["ID"]=24077,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [24081]=
    {
        ["ID"]=24081,
        ["szDetail"]="",
        ["szFuncName"]="落花"
    },
    [24160]=
    {
        ["ID"]=24160,
        ["szDetail"]="",
        ["szFuncName"]="管家"
    },
    [24567]=
    {
        ["ID"]=24567,
        ["szDetail"]="150",
        ["szFuncName"]="少林"
    },
    [24568]=
    {
        ["ID"]=24568,
        ["szDetail"]="150",
        ["szFuncName"]="万花"
    },
    [24569]=
    {
        ["ID"]=24569,
        ["szDetail"]="200",
        ["szFuncName"]="天策"
    },
    [24570]=
    {
        ["ID"]=24570,
        ["szDetail"]="150",
        ["szFuncName"]="纯阳"
    },
    [24571]=
    {
        ["ID"]=24571,
        ["szDetail"]="240",
        ["szFuncName"]="七秀"
    },
    [24572]=
    {
        ["ID"]=24572,
        ["szDetail"]="180",
        ["szFuncName"]="唐门"
    },
    [24573]=
    {
        ["ID"]=24573,
        ["szDetail"]="150",
        ["szFuncName"]="五毒"
    },
    [24574]=
    {
        ["ID"]=24574,
        ["szDetail"]="220",
        ["szFuncName"]="藏剑"
    },
    [24575]=
    {
        ["ID"]=24575,
        ["szDetail"]="200",
        ["szFuncName"]="丐帮"
    },
    [24576]=
    {
        ["ID"]=24576,
        ["szDetail"]="200",
        ["szFuncName"]="明教"
    },
    [24577]=
    {
        ["ID"]=24577,
        ["szDetail"]="240",
        ["szFuncName"]="苍云"
    },
    [24578]=
    {
        ["ID"]=24578,
        ["szDetail"]="200",
        ["szFuncName"]="长歌"
    },
    [24579]=
    {
        ["ID"]=24579,
        ["szDetail"]="200",
        ["szFuncName"]="霸刀"
    },
    [24580]=
    {
        ["ID"]=24580,
        ["szDetail"]="180",
        ["szFuncName"]="蓬莱"
    },
    [24581]=
    {
        ["ID"]=24581,
        ["szDetail"]="220",
        ["szFuncName"]="凌雪"
    },
    [24582]=
    {
        ["ID"]=24582,
        ["szDetail"]="50",
        ["szFuncName"]="心影"
    },
    [24661]=
    {
        ["ID"]=24661,
        ["szDetail"]="",
        ["szFuncName"]="演武"
    },
    [24662]=
    {
        ["ID"]=24662,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [25811]=
    {
        ["ID"]=25811,
        ["szDetail"]="",
        ["szFuncName"]="摇摆"
    },
    [25812]=
    {
        ["ID"]=25812,
        ["szDetail"]="",
        ["szFuncName"]="停止"
    },
    [25813]=
    {
        ["ID"]=25813,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [25832]=
    {
        ["ID"]=25832,
        ["szDetail"]="",
        ["szFuncName"]="选茶"
    },
    [25833]=
    {
        ["ID"]=25833,
        ["szDetail"]="",
        ["szFuncName"]="沏茶"
    },
    [25834]=
    {
        ["ID"]=25834,
        ["szDetail"]="",
        ["szFuncName"]="品茗"
    },
    [25835]=
    {
        ["ID"]=25835,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [25842]=
    {
        ["ID"]=25842,
        ["szDetail"]="",
        ["szFuncName"]="躺下"
    },
    [25843]=
    {
        ["ID"]=25843,
        ["szDetail"]="",
        ["szFuncName"]="坐起"
    },
    [25845]=
    {
        ["ID"]=25845,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [25875]=
    {
        ["ID"]=25875,
        ["szDetail"]="",
        ["szFuncName"]="摇摆"
    },
    [25876]=
    {
        ["ID"]=25876,
        ["szDetail"]="",
        ["szFuncName"]="停止"
    },
    [25877]=
    {
        ["ID"]=25877,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [25878]=
    {
        ["ID"]=25878,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [26117]=
    {
        ["ID"]=26117,
        ["szDetail"]="",
        ["szFuncName"]="饮酒"
    },
    [26118]=
    {
        ["ID"]=26118,
        ["szDetail"]="",
        ["szFuncName"]="戏水"
    },
    [26119]=
    {
        ["ID"]=26119,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [26360]=
    {
        ["ID"]=26360,
        ["szDetail"]="",
        ["szFuncName"]="夹菜·右"
    },
    [26361]=
    {
        ["ID"]=26361,
        ["szDetail"]="",
        ["szFuncName"]="夹菜·左"
    },
    [26362]=
    {
        ["ID"]=26362,
        ["szDetail"]="",
        ["szFuncName"]="聊天·右"
    },
    [26363]=
    {
        ["ID"]=26363,
        ["szDetail"]="",
        ["szFuncName"]="聊天·左"
    },
    [26364]=
    {
        ["ID"]=26364,
        ["szDetail"]="",
        ["szFuncName"]="大笑"
    },
    [26365]=
    {
        ["ID"]=26365,
        ["szDetail"]="",
        ["szFuncName"]="畅饮"
    },
    [26366]=
    {
        ["ID"]=26366,
        ["szDetail"]="",
        ["szFuncName"]="邀杯"
    },
    [26367]=
    {
        ["ID"]=26367,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [26397]=
    {
        ["ID"]=26397,
        ["szDetail"]="",
        ["szFuncName"]="移动"
    },
    [26398]=
    {
        ["ID"]=26398,
        ["szDetail"]="",
        ["szFuncName"]="战斗"
    },
    [26407]=
    {
        ["ID"]=26407,
        ["szDetail"]="",
        ["szFuncName"]="移动"
    },
    [26408]=
    {
        ["ID"]=26408,
        ["szDetail"]="",
        ["szFuncName"]="移动"
    },
    [26409]=
    {
        ["ID"]=26409,
        ["szDetail"]="",
        ["szFuncName"]="投掷"
    },
    [26542]=
    {
        ["ID"]=26542,
        ["szDetail"]="",
        ["szFuncName"]="涮肉"
    },
    [26543]=
    {
        ["ID"]=26543,
        ["szDetail"]="",
        ["szFuncName"]="涮菜"
    },
    [26544]=
    {
        ["ID"]=26544,
        ["szDetail"]="",
        ["szFuncName"]="敬茶"
    },
    [26545]=
    {
        ["ID"]=26545,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [26584]=
    {
        ["ID"]=26584,
        ["szDetail"]="",
        ["szFuncName"]="红灯"
    },
    [26585]=
    {
        ["ID"]=26585,
        ["szDetail"]="",
        ["szFuncName"]="黄灯"
    },
    [26586]=
    {
        ["ID"]=26586,
        ["szDetail"]="",
        ["szFuncName"]="绿灯"
    },
    [26587]=
    {
        ["ID"]=26587,
        ["szDetail"]="",
        ["szFuncName"]="警告"
    },
    [26588]=
    {
        ["ID"]=26588,
        ["szDetail"]="",
        ["szFuncName"]="下车"
    },
    [26590]=
    {
        ["ID"]=26590,
        ["szDetail"]="",
        ["szFuncName"]="发射"
    },
    [26591]=
    {
        ["ID"]=26591,
        ["szDetail"]="",
        ["szFuncName"]="下车"
    },
    [27093]=
    {
        ["ID"]=27093,
        ["szDetail"]="",
        ["szFuncName"]="近程"
    },
    [27094]=
    {
        ["ID"]=27094,
        ["szDetail"]="",
        ["szFuncName"]="远程"
    },
    [27171]=
    {
        ["ID"]=27171,
        ["szDetail"]="",
        ["szFuncName"]="摇摆"
    },
    [27172]=
    {
        ["ID"]=27172,
        ["szDetail"]="",
        ["szFuncName"]="停止"
    },
    [27173]=
    {
        ["ID"]=27173,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [28167]=
    {
        ["ID"]=28167,
        ["szDetail"]="220",
        ["szFuncName"]="衍天"
    },
    [28169]=
    {
        ["ID"]=28169,
        ["szDetail"]="",
        ["szFuncName"]="滚石"
    },
    [28203]=
    {
        ["ID"]=28203,
        ["szDetail"]="",
        ["szFuncName"]="火石"
    },
    [29332]=
    {
        ["ID"]=29332,
        ["szDetail"]="",
        ["szFuncName"]="小七"
    },
    [29333]=
    {
        ["ID"]=29333,
        ["szDetail"]="",
        ["szFuncName"]="游驹"
    },
    [29334]=
    {
        ["ID"]=29334,
        ["szDetail"]="",
        ["szFuncName"]="司徒一一"
    },
    [29335]=
    {
        ["ID"]=29335,
        ["szDetail"]="",
        ["szFuncName"]="白某"
    },
    [31019]=
    {
        ["ID"]=31019,
        ["szDetail"]="",
        ["szFuncName"]="擦汗"
    },
    [31022]=
    {
        ["ID"]=31022,
        ["szDetail"]="",
        ["szFuncName"]="扇风"
    },
    [31023]=
    {
        ["ID"]=31023,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [31103]=
    {
        ["ID"]=31103,
        ["szDetail"]="",
        ["szFuncName"]="摇摆"
    },
    [31104]=
    {
        ["ID"]=31104,
        ["szDetail"]="",
        ["szFuncName"]="停止"
    },
    [31105]=
    {
        ["ID"]=31105,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [32069]=
    {
        ["ID"]=32069,
        ["szDetail"]="",
        ["szFuncName"]="攻击"
    },
    [32072]=
    {
        ["ID"]=32072,
        ["szDetail"]="",
        ["szFuncName"]="召唤"
    },
    [32073]=
    {
        ["ID"]=32073,
        ["szDetail"]="",
        ["szFuncName"]="站位"
    },
    [32121]=
    {
        ["ID"]=32121,
        ["szDetail"]="",
        ["szFuncName"]="追人"
    },
    [32137]=
    {
        ["ID"]=32137,
        ["szDetail"]="",
        ["szFuncName"]="群攻"
    },
    [32295]=
    {
        ["ID"]=32295,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [32326]=
    {
        ["ID"]=32326,
        ["szDetail"]="",
        ["szFuncName"]="无敌"
    },
    [32342]=
    {
        ["ID"]=32342,
        ["szDetail"]="",
        ["szFuncName"]="击退"
    },
    [35235]=
    {
        ["ID"]=35235,
        ["szDetail"]="",
        ["szFuncName"]="开车"
    },
    [35236]=
    {
        ["ID"]=35236,
        ["szDetail"]="",
        ["szFuncName"]="停车"
    },
    [35237]=
    {
        ["ID"]=35237,
        ["szDetail"]="",
        ["szFuncName"]="下车"
    },
    [35239]=
    {
        ["ID"]=35239,
        ["szDetail"]="",
        ["szFuncName"]="招手"
    },
    [35240]=
    {
        ["ID"]=35240,
        ["szDetail"]="",
        ["szFuncName"]="下车"
    },
    [35885]=
    {
        ["ID"]=35885,
        ["szDetail"]="",
        ["szFuncName"]="集结"
    },
    [36546]=
    {
        ["ID"]=36546,
        ["szDetail"]="",
        ["szFuncName"]="碎空石"
    },
    [36614]=
    {
        ["ID"]=36614,
        ["szDetail"]="",
        ["szFuncName"]="开船"
    },
    [36615]=
    {
        ["ID"]=36615,
        ["szDetail"]="",
        ["szFuncName"]="停船"
    },
    [36616]=
    {
        ["ID"]=36616,
        ["szDetail"]="",
        ["szFuncName"]="下船"
    },
    [36617]=
    {
        ["ID"]=36617,
        ["szDetail"]="",
        ["szFuncName"]="下船"
    },
    [36618]=
    {
        ["ID"]=36618,
        ["szDetail"]="",
        ["szFuncName"]="挥手"
    },
    [37026]=
    {
        ["ID"]=37026,
        ["szDetail"]="",
        ["szFuncName"]="喜"
    },
    [37027]=
    {
        ["ID"]=37027,
        ["szDetail"]="",
        ["szFuncName"]="怒"
    },
    [37028]=
    {
        ["ID"]=37028,
        ["szDetail"]="",
        ["szFuncName"]="醉"
    },
    [37029]=
    {
        ["ID"]=37029,
        ["szDetail"]="",
        ["szFuncName"]="醒"
    },
    [37030]=
    {
        ["ID"]=37030,
        ["szDetail"]="",
        ["szFuncName"]="惊"
    },
    [37031]=
    {
        ["ID"]=37031,
        ["szDetail"]="",
        ["szFuncName"]="疑"
    },
    [37032]=
    {
        ["ID"]=37032,
        ["szDetail"]="",
        ["szFuncName"]="寻"
    },
    [37033]=
    {
        ["ID"]=37033,
        ["szDetail"]="",
        ["szFuncName"]="盼"
    },
    [37081]=
    {
        ["ID"]=37081,
        ["szDetail"]="",
        ["szFuncName"]="喜"
    },
    [37082]=
    {
        ["ID"]=37082,
        ["szDetail"]="",
        ["szFuncName"]="怒"
    },
    [37083]=
    {
        ["ID"]=37083,
        ["szDetail"]="",
        ["szFuncName"]="醉"
    },
    [37084]=
    {
        ["ID"]=37084,
        ["szDetail"]="",
        ["szFuncName"]="醒"
    },
    [37085]=
    {
        ["ID"]=37085,
        ["szDetail"]="",
        ["szFuncName"]="惊"
    },
    [37086]=
    {
        ["ID"]=37086,
        ["szDetail"]="",
        ["szFuncName"]="疑"
    },
    [37087]=
    {
        ["ID"]=37087,
        ["szDetail"]="",
        ["szFuncName"]="寻"
    },
    [37088]=
    {
        ["ID"]=37088,
        ["szDetail"]="",
        ["szFuncName"]="盼"
    },
    [37183]=
    {
        ["ID"]=37183,
        ["szDetail"]="",
        ["szFuncName"]="墨染飞龙"
    },
    [37262]=
    {
        ["ID"]=37262,
        ["szDetail"]="",
        ["szFuncName"]="比心"
    },
    [37263]=
    {
        ["ID"]=37263,
        ["szDetail"]="",
        ["szFuncName"]="画心"
    },
    [37264]=
    {
        ["ID"]=37264,
        ["szDetail"]="",
        ["szFuncName"]="比心"
    },
    [37265]=
    {
        ["ID"]=37265,
        ["szDetail"]="",
        ["szFuncName"]="画心"
    },
    [37266]=
    {
        ["ID"]=37266,
        ["szDetail"]="",
        ["szFuncName"]="下车"
    },
    [37721]=
    {
        ["ID"]=37721,
        ["szDetail"]="",
        ["szFuncName"]="启动"
    },
    [37722]=
    {
        ["ID"]=37722,
        ["szDetail"]="",
        ["szFuncName"]="停止"
    },
    [37723]=
    {
        ["ID"]=37723,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [37724]=
    {
        ["ID"]=37724,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [37725]=
    {
        ["ID"]=37725,
        ["szDetail"]="",
        ["szFuncName"]="挥手"
    },
    [37726]=
    {
        ["ID"]=37726,
        ["szDetail"]="",
        ["szFuncName"]="启动"
    },
    [37727]=
    {
        ["ID"]=37727,
        ["szDetail"]="",
        ["szFuncName"]="停止"
    },
    [37728]=
    {
        ["ID"]=37728,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [37729]=
    {
        ["ID"]=37729,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [37730]=
    {
        ["ID"]=37730,
        ["szDetail"]="",
        ["szFuncName"]="张望"
    },
    [37760]=
    {
        ["ID"]=37760,
        ["szDetail"]="",
        ["szFuncName"]="开箱"
    },
    [37761]=
    {
        ["ID"]=37761,
        ["szDetail"]="",
        ["szFuncName"]="驱蜂"
    },
    [37762]=
    {
        ["ID"]=37762,
        ["szDetail"]="",
        ["szFuncName"]="割蜜"
    },
    [37763]=
    {
        ["ID"]=37763,
        ["szDetail"]="",
        ["szFuncName"]="归箱"
    },
    [37764]=
    {
        ["ID"]=37764,
        ["szDetail"]="",
        ["szFuncName"]="尝味"
    },
    [37788]=
    {
        ["ID"]=37788,
        ["szDetail"]="",
        ["szFuncName"]="连续垂钓"
    },
    [38024]=
    {
        ["ID"]=38024,
        ["szDetail"]="",
        ["szFuncName"]="杀青"
    },
    [38025]=
    {
        ["ID"]=38025,
        ["szDetail"]="",
        ["szFuncName"]="揉捻"
    },
    [38026]=
    {
        ["ID"]=38026,
        ["szDetail"]="",
        ["szFuncName"]="抖散"
    },
    [38027]=
    {
        ["ID"]=38027,
        ["szDetail"]="",
        ["szFuncName"]="出锅"
    },
    [38092]=
    {
        ["ID"]=38092,
        ["szDetail"]="",
        ["szFuncName"]="倒酒"
    },
    [38146]=
    {
        ["ID"]=38146,
        ["szDetail"]="",
        ["szFuncName"]="锤"
    },
    [38147]=
    {
        ["ID"]=38147,
        ["szDetail"]="",
        ["szFuncName"]="锤"
    },
    [38148]=
    {
        ["ID"]=38148,
        ["szDetail"]="",
        ["szFuncName"]="锤"
    },
    [38154]=
    {
        ["ID"]=38154,
        ["szDetail"]="",
        ["szFuncName"]="砸"
    },
    [38157]=
    {
        ["ID"]=38157,
        ["szDetail"]="",
        ["szFuncName"]="拉"
    },
    [38177]=
    {
        ["ID"]=38177,
        ["szDetail"]="",
        ["szFuncName"]="冲"
    },
    [38267]=
    {
        ["ID"]=38267,
        ["szDetail"]="240",
        ["szFuncName"]="药宗"
    },
    [38269]=
    {
        ["ID"]=38269,
        ["szDetail"]="220",
        ["szFuncName"]="刀宗"
    },
    [38271]=
    {
        ["ID"]=38271,
        ["szDetail"]="180",
        ["szFuncName"]="万灵"
    },
    [38386]=
    {
        ["ID"]=38386,
        ["szDetail"]="",
        ["szFuncName"]="梧桐霜月"
    },
    [38387]=
    {
        ["ID"]=38387,
        ["szDetail"]="",
        ["szFuncName"]="昆山玉碎"
    },
    [38388]=
    {
        ["ID"]=38388,
        ["szDetail"]="",
        ["szFuncName"]="一段"
    },
    [38389]=
    {
        ["ID"]=38389,
        ["szDetail"]="",
        ["szFuncName"]="二段"
    },
    [38390]=
    {
        ["ID"]=38390,
        ["szDetail"]="",
        ["szFuncName"]="三段"
    },
    [38391]=
    {
        ["ID"]=38391,
        ["szDetail"]="",
        ["szFuncName"]="四段"
    },
    [38392]=
    {
        ["ID"]=38392,
        ["szDetail"]="",
        ["szFuncName"]="五段"
    },
    [38393]=
    {
        ["ID"]=38393,
        ["szDetail"]="",
        ["szFuncName"]="六段"
    },
    [38401]=
    {
        ["ID"]=38401,
        ["szDetail"]="",
        ["szFuncName"]="镜头开关"
    },
    [38543]=
    {
        ["ID"]=38543,
        ["szDetail"]="",
        ["szFuncName"]="摸脖子"
    },
    [38544]=
    {
        ["ID"]=38544,
        ["szDetail"]="",
        ["szFuncName"]="摸脊背"
    },
    [38545]=
    {
        ["ID"]=38545,
        ["szDetail"]="",
        ["szFuncName"]="摸肋岔"
    },
    [39524]=
    {
        ["ID"]=39524,
        ["szDetail"]="",
        ["szFuncName"]="演奏"
    },
    [39525]=
    {
        ["ID"]=39525,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [39591]=
    {
        ["ID"]=39591,
        ["szDetail"]="",
        ["szFuncName"]="跳舞"
    },
    [39592]=
    {
        ["ID"]=39592,
        ["szDetail"]="",
        ["szFuncName"]="停止"
    },
    [39593]=
    {
        ["ID"]=39593,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [39602]=
    {
        ["ID"]=39602,
        ["szDetail"]="",
        ["szFuncName"]="轻轻推"
    },
    [39603]=
    {
        ["ID"]=39603,
        ["szDetail"]="",
        ["szFuncName"]="停止"
    },
    [39604]=
    {
        ["ID"]=39604,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [39605]=
    {
        ["ID"]=39605,
        ["szDetail"]="",
        ["szFuncName"]="用力推"
    },
    [39606]=
    {
        ["ID"]=39606,
        ["szDetail"]="",
        ["szFuncName"]="离开"
    },
    [39909]=
    {
        ["ID"]=39909,
        ["szDetail"]="",
        ["szFuncName"]="聚怪"
    },
    [39910]=
    {
        ["ID"]=39910,
        ["szDetail"]="",
        ["szFuncName"]="爆发"
    },
    [39911]=
    {
        ["ID"]=39911,
        ["szDetail"]="",
        ["szFuncName"]="群攻"
    },
    [39912]=
    {
        ["ID"]=39912,
        ["szDetail"]="",
        ["szFuncName"]="打断"
    },
    [39913]=
    {
        ["ID"]=39913,
        ["szDetail"]="",
        ["szFuncName"]="重置"
    },
    [39914]=
    {
        ["ID"]=39914,
        ["szDetail"]="",
        ["szFuncName"]="增伤"
    },
    [39915]=
    {
        ["ID"]=39915,
        ["szDetail"]="",
        ["szFuncName"]="单点"
    },
    [39916]=
    {
        ["ID"]=39916,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [39917]=
    {
        ["ID"]=39917,
        ["szDetail"]="",
        ["szFuncName"]="移速"
    },
    [41190]=
    {
        ["ID"]=41190,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41191]=
    {
        ["ID"]=41191,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41192]=
    {
        ["ID"]=41192,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41193]=
    {
        ["ID"]=41193,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41194]=
    {
        ["ID"]=41194,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41195]=
    {
        ["ID"]=41195,
        ["szDetail"]="",
        ["szFuncName"]="爆发"
    },
    [41196]=
    {
        ["ID"]=41196,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41197]=
    {
        ["ID"]=41197,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41198]=
    {
        ["ID"]=41198,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41199]=
    {
        ["ID"]=41199,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41200]=
    {
        ["ID"]=41200,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41202]=
    {
        ["ID"]=41202,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41203]=
    {
        ["ID"]=41203,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41204]=
    {
        ["ID"]=41204,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41205]=
    {
        ["ID"]=41205,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41206]=
    {
        ["ID"]=41206,
        ["szDetail"]="",
        ["szFuncName"]="爆发"
    },
    [41208]=
    {
        ["ID"]=41208,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41209]=
    {
        ["ID"]=41209,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41210]=
    {
        ["ID"]=41210,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41211]=
    {
        ["ID"]=41211,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41212]=
    {
        ["ID"]=41212,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41213]=
    {
        ["ID"]=41213,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41214]=
    {
        ["ID"]=41214,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41215]=
    {
        ["ID"]=41215,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41216]=
    {
        ["ID"]=41216,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41217]=
    {
        ["ID"]=41217,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41218]=
    {
        ["ID"]=41218,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41220]=
    {
        ["ID"]=41220,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41221]=
    {
        ["ID"]=41221,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41222]=
    {
        ["ID"]=41222,
        ["szDetail"]="",
        ["szFuncName"]="沉默"
    },
    [41223]=
    {
        ["ID"]=41223,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41224]=
    {
        ["ID"]=41224,
        ["szDetail"]="",
        ["szFuncName"]="爆发"
    },
    [41225]=
    {
        ["ID"]=41225,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41226]=
    {
        ["ID"]=41226,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41227]=
    {
        ["ID"]=41227,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41228]=
    {
        ["ID"]=41228,
        ["szDetail"]="",
        ["szFuncName"]="增益"
    },
    [41240]=
    {
        ["ID"]=41240,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41259]=
    {
        ["ID"]=41259,
        ["szDetail"]="",
        ["szFuncName"]="位移"
    },
    [41260]=
    {
        ["ID"]=41260,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41265]=
    {
        ["ID"]=41265,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41267]=
    {
        ["ID"]=41267,
        ["szDetail"]="",
        ["szFuncName"]="爆发"
    },
    [41268]=
    {
        ["ID"]=41268,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41272]=
    {
        ["ID"]=41272,
        ["szDetail"]="",
        ["szFuncName"]="爆发"
    },
    [41281]=
    {
        ["ID"]=41281,
        ["szDetail"]="",
        ["szFuncName"]="扶摇"
    },
    [41282]=
    {
        ["ID"]=41282,
        ["szDetail"]="",
        ["szFuncName"]="位移"
    },
    [41283]=
    {
        ["ID"]=41283,
        ["szDetail"]="",
        ["szFuncName"]="扶摇"
    },
    [41284]=
    {
        ["ID"]=41284,
        ["szDetail"]="",
        ["szFuncName"]="位移"
    },
    [41337]=
    {
        ["ID"]=41337,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41338]=
    {
        ["ID"]=41338,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41339]=
    {
        ["ID"]=41339,
        ["szDetail"]="",
        ["szFuncName"]="位移"
    },
    [41340]=
    {
        ["ID"]=41340,
        ["szDetail"]="",
        ["szFuncName"]="爆发"
    },
    [41341]=
    {
        ["ID"]=41341,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41345]=
    {
        ["ID"]=41345,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41347]=
    {
        ["ID"]=41347,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41348]=
    {
        ["ID"]=41348,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41349]=
    {
        ["ID"]=41349,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41351]=
    {
        ["ID"]=41351,
        ["szDetail"]="",
        ["szFuncName"]="增益"
    },
    [41352]=
    {
        ["ID"]=41352,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41353]=
    {
        ["ID"]=41353,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41354]=
    {
        ["ID"]=41354,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41357]=
    {
        ["ID"]=41357,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41358]=
    {
        ["ID"]=41358,
        ["szDetail"]="",
        ["szFuncName"]="位移"
    },
    [41359]=
    {
        ["ID"]=41359,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41360]=
    {
        ["ID"]=41360,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41361]=
    {
        ["ID"]=41361,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41366]=
    {
        ["ID"]=41366,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41375]=
    {
        ["ID"]=41375,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41379]=
    {
        ["ID"]=41379,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41380]=
    {
        ["ID"]=41380,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41381]=
    {
        ["ID"]=41381,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41382]=
    {
        ["ID"]=41382,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41383]=
    {
        ["ID"]=41383,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41384]=
    {
        ["ID"]=41384,
        ["szDetail"]="",
        ["szFuncName"]="爆发"
    },
    [41385]=
    {
        ["ID"]=41385,
        ["szDetail"]="",
        ["szFuncName"]="爆发"
    },
    [41386]=
    {
        ["ID"]=41386,
        ["szDetail"]="",
        ["szFuncName"]="爆发"
    },
    [41387]=
    {
        ["ID"]=41387,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41388]=
    {
        ["ID"]=41388,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41389]=
    {
        ["ID"]=41389,
        ["szDetail"]="",
        ["szFuncName"]="位移"
    },
    [41390]=
    {
        ["ID"]=41390,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41391]=
    {
        ["ID"]=41391,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41405]=
    {
        ["ID"]=41405,
        ["szDetail"]="",
        ["szFuncName"]="爆发"
    },
    [41413]=
    {
        ["ID"]=41413,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41414]=
    {
        ["ID"]=41414,
        ["szDetail"]="",
        ["szFuncName"]="位移"
    },
    [41415]=
    {
        ["ID"]=41415,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41416]=
    {
        ["ID"]=41416,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41417]=
    {
        ["ID"]=41417,
        ["szDetail"]="",
        ["szFuncName"]="爆发"
    },
    [41428]=
    {
        ["ID"]=41428,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41429]=
    {
        ["ID"]=41429,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41430]=
    {
        ["ID"]=41430,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41431]=
    {
        ["ID"]=41431,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41432]=
    {
        ["ID"]=41432,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41467]=
    {
        ["ID"]=41467,
        ["szDetail"]="",
        ["szFuncName"]="位移"
    },
    [41477]=
    {
        ["ID"]=41477,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41478]=
    {
        ["ID"]=41478,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41479]=
    {
        ["ID"]=41479,
        ["szDetail"]="",
        ["szFuncName"]="位移"
    },
    [41481]=
    {
        ["ID"]=41481,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41482]=
    {
        ["ID"]=41482,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41500]=
    {
        ["ID"]=41500,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41501]=
    {
        ["ID"]=41501,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41502]=
    {
        ["ID"]=41502,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41503]=
    {
        ["ID"]=41503,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41504]=
    {
        ["ID"]=41504,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41505]=
    {
        ["ID"]=41505,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41522]=
    {
        ["ID"]=41522,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41526]=
    {
        ["ID"]=41526,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41553]=
    {
        ["ID"]=41553,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    },
    [41558]=
    {
        ["ID"]=41558,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [41559]=
    {
        ["ID"]=41559,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [43227]=
    {
        ["ID"]=43227,
        ["szDetail"]="",
        ["szFuncName"]="伤害"
    },
    [43293]=
    {
        ["ID"]=43293,
        ["szDetail"]="",
        ["szFuncName"]="控制"
    }
}
