--*************************************** 工具生成 ***************************************
UIDynamicSkillGroupType = 
{
    [1]=
    {
        ["nID"]=1,
        ["nGroup"]=45,
        ["szGamePlay"]="Horse"
    },
    [2]=
    {
        ["nID"]=2,
        ["nGroup"]=46,
        ["szGamePlay"]="Horse"
    },
    [3]=
    {
        ["nID"]=3,
        ["nGroup"]=141,
        ["szGamePlay"]="Horse"
    },
    [4]=
    {
        ["nID"]=4,
        ["nGroup"]=172,
        ["szGamePlay"]="Horse"
    },
    [5]=
    {
        ["nID"]=5,
        ["nGroup"]=195,
        ["szGamePlay"]="Horse"
    },
    [6]=
    {
        ["nID"]=6,
        ["nGroup"]=307,
        ["szGamePlay"]="Horse"
    },
    [7]=
    {
        ["nID"]=7,
        ["nGroup"]=330,
        ["szGamePlay"]="Horse"
    },
    [8]=
    {
        ["nID"]=8,
        ["nGroup"]=345,
        ["szGamePlay"]="Horse"
    },
    [9]=
    {
        ["nID"]=9,
        ["nGroup"]=359,
        ["szGamePlay"]="Horse"
    },
    [10]=
    {
        ["nID"]=10,
        ["nGroup"]=360,
        ["szGamePlay"]="Horse"
    },
    [11]=
    {
        ["nID"]=11,
        ["nGroup"]=439,
        ["szGamePlay"]="Horse"
    },
    [12]=
    {
        ["nID"]=12,
        ["nGroup"]=482,
        ["szGamePlay"]="Horse"
    },
    [13]=
    {
        ["nID"]=13,
        ["nGroup"]=526,
        ["szGamePlay"]="Horse"
    },
    [14]=
    {
        ["nID"]=14,
        ["nGroup"]=572,
        ["szGamePlay"]="Horse"
    },
    [15]=
    {
        ["nID"]=15,
        ["nGroup"]=573,
        ["szGamePlay"]="Horse"
    },
    [16]=
    {
        ["nID"]=16,
        ["nGroup"]=574,
        ["szGamePlay"]="Horse"
    },
    [17]=
    {
        ["nID"]=17,
        ["nGroup"]=581,
        ["szGamePlay"]="Horse"
    },
    [18]=
    {
        ["nID"]=18,
        ["nGroup"]=582,
        ["szGamePlay"]="Horse"
    },
    [19]=
    {
        ["nID"]=19,
        ["nGroup"]=583,
        ["szGamePlay"]="Horse"
    },
    [20]=
    {
        ["nID"]=20,
        ["nGroup"]=588,
        ["szGamePlay"]="Horse"
    },
    [21]=
    {
        ["nID"]=21,
        ["nGroup"]=0,
        ["szGamePlay"]=""
    },
    [22]=
    {
        ["nID"]=22,
        ["nGroup"]=646,
        ["szGamePlay"]="Horse"
    },
    [23]=
    {
        ["nID"]=23,
        ["nGroup"]=655,
        ["szGamePlay"]="Horse"
    },
    [24]=
    {
        ["nID"]=24,
        ["nGroup"]=664,
        ["szGamePlay"]="Horse"
    },
    [25]=
    {
        ["nID"]=25,
        ["nGroup"]=1027,
        ["szGamePlay"]="Horse"
    }
}
