--*************************************** 工具生成 ***************************************
UIForceCampUniform = 
{
    [1]=
    {
        ["nIndex"]=1,
        ["nMapID"]=9,
        ["nWeekDay"]=2,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [2]=
    {
        ["nIndex"]=2,
        ["nMapID"]=9,
        ["nWeekDay"]=4,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [3]=
    {
        ["nIndex"]=3,
        ["nMapID"]=13,
        ["nWeekDay"]=2,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [4]=
    {
        ["nIndex"]=4,
        ["nMapID"]=13,
        ["nWeekDay"]=4,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [5]=
    {
        ["nIndex"]=5,
        ["nMapID"]=21,
        ["nWeekDay"]=2,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [6]=
    {
        ["nIndex"]=6,
        ["nMapID"]=21,
        ["nWeekDay"]=4,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [7]=
    {
        ["nIndex"]=7,
        ["nMapID"]=22,
        ["nWeekDay"]=2,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [8]=
    {
        ["nIndex"]=8,
        ["nMapID"]=22,
        ["nWeekDay"]=4,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [9]=
    {
        ["nIndex"]=9,
        ["nMapID"]=23,
        ["nWeekDay"]=2,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [10]=
    {
        ["nIndex"]=10,
        ["nMapID"]=23,
        ["nWeekDay"]=4,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [11]=
    {
        ["nIndex"]=11,
        ["nMapID"]=30,
        ["nWeekDay"]=2,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [12]=
    {
        ["nIndex"]=12,
        ["nMapID"]=30,
        ["nWeekDay"]=4,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [13]=
    {
        ["nIndex"]=13,
        ["nMapID"]=35,
        ["nWeekDay"]=2,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [14]=
    {
        ["nIndex"]=14,
        ["nMapID"]=35,
        ["nWeekDay"]=4,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [15]=
    {
        ["nIndex"]=15,
        ["nMapID"]=100,
        ["nWeekDay"]=2,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [16]=
    {
        ["nIndex"]=16,
        ["nMapID"]=100,
        ["nWeekDay"]=4,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [17]=
    {
        ["nIndex"]=17,
        ["nMapID"]=101,
        ["nWeekDay"]=2,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [18]=
    {
        ["nIndex"]=18,
        ["nMapID"]=101,
        ["nWeekDay"]=4,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [19]=
    {
        ["nIndex"]=19,
        ["nMapID"]=103,
        ["nWeekDay"]=2,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [20]=
    {
        ["nIndex"]=20,
        ["nMapID"]=103,
        ["nWeekDay"]=4,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [21]=
    {
        ["nIndex"]=21,
        ["nMapID"]=104,
        ["nWeekDay"]=2,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [22]=
    {
        ["nIndex"]=22,
        ["nMapID"]=104,
        ["nWeekDay"]=4,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [23]=
    {
        ["nIndex"]=23,
        ["nMapID"]=105,
        ["nWeekDay"]=2,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [24]=
    {
        ["nIndex"]=24,
        ["nMapID"]=105,
        ["nWeekDay"]=4,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [25]=
    {
        ["nIndex"]=25,
        ["nMapID"]=139,
        ["nWeekDay"]=2,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [26]=
    {
        ["nIndex"]=26,
        ["nMapID"]=139,
        ["nWeekDay"]=4,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [27]=
    {
        ["nIndex"]=27,
        ["nMapID"]=153,
        ["nWeekDay"]=2,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [28]=
    {
        ["nIndex"]=28,
        ["nMapID"]=153,
        ["nWeekDay"]=4,
        ["szEndTime"]="22:00",
        ["szBeginTime"]="19:30"
    },
    [29]=
    {
        ["nIndex"]=29,
        ["nMapID"]=25,
        ["nWeekDay"]=6,
        ["szEndTime"]="15:00",
        ["szBeginTime"]="12:20"
    },
    [30]=
    {
        ["nIndex"]=30,
        ["nMapID"]=25,
        ["nWeekDay"]=6,
        ["szEndTime"]="21:00",
        ["szBeginTime"]="18:20"
    },
    [31]=
    {
        ["nIndex"]=31,
        ["nMapID"]=25,
        ["nWeekDay"]=7,
        ["szEndTime"]="15:00",
        ["szBeginTime"]="12:20"
    },
    [32]=
    {
        ["nIndex"]=32,
        ["nMapID"]=25,
        ["nWeekDay"]=7,
        ["szEndTime"]="21:00",
        ["szBeginTime"]="18:20"
    },
    [33]=
    {
        ["nIndex"]=33,
        ["nMapID"]=27,
        ["nWeekDay"]=6,
        ["szEndTime"]="15:00",
        ["szBeginTime"]="12:20"
    },
    [34]=
    {
        ["nIndex"]=34,
        ["nMapID"]=27,
        ["nWeekDay"]=6,
        ["szEndTime"]="21:00",
        ["szBeginTime"]="18:20"
    },
    [35]=
    {
        ["nIndex"]=35,
        ["nMapID"]=27,
        ["nWeekDay"]=7,
        ["szEndTime"]="15:00",
        ["szBeginTime"]="12:20"
    },
    [36]=
    {
        ["nIndex"]=36,
        ["nMapID"]=27,
        ["nWeekDay"]=7,
        ["szEndTime"]="21:00",
        ["szBeginTime"]="18:20"
    },
    [37]=
    {
        ["nIndex"]=37,
        ["nMapID"]=151,
        ["nWeekDay"]=1,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [38]=
    {
        ["nIndex"]=38,
        ["nMapID"]=151,
        ["nWeekDay"]=3,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [39]=
    {
        ["nIndex"]=39,
        ["nMapID"]=151,
        ["nWeekDay"]=5,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [40]=
    {
        ["nIndex"]=40,
        ["nMapID"]=151,
        ["nWeekDay"]=6,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [41]=
    {
        ["nIndex"]=41,
        ["nMapID"]=151,
        ["nWeekDay"]=7,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [42]=
    {
        ["nIndex"]=42,
        ["nMapID"]=215,
        ["nWeekDay"]=1,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [43]=
    {
        ["nIndex"]=43,
        ["nMapID"]=215,
        ["nWeekDay"]=3,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [44]=
    {
        ["nIndex"]=44,
        ["nMapID"]=215,
        ["nWeekDay"]=5,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [45]=
    {
        ["nIndex"]=45,
        ["nMapID"]=215,
        ["nWeekDay"]=6,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [46]=
    {
        ["nIndex"]=46,
        ["nMapID"]=215,
        ["nWeekDay"]=7,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [47]=
    {
        ["nIndex"]=47,
        ["nMapID"]=216,
        ["nWeekDay"]=1,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [48]=
    {
        ["nIndex"]=48,
        ["nMapID"]=216,
        ["nWeekDay"]=3,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [49]=
    {
        ["nIndex"]=49,
        ["nMapID"]=216,
        ["nWeekDay"]=5,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [50]=
    {
        ["nIndex"]=50,
        ["nMapID"]=216,
        ["nWeekDay"]=6,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [51]=
    {
        ["nIndex"]=51,
        ["nMapID"]=216,
        ["nWeekDay"]=7,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [52]=
    {
        ["nIndex"]=52,
        ["nMapID"]=217,
        ["nWeekDay"]=1,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [53]=
    {
        ["nIndex"]=53,
        ["nMapID"]=217,
        ["nWeekDay"]=3,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [54]=
    {
        ["nIndex"]=54,
        ["nMapID"]=217,
        ["nWeekDay"]=5,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [55]=
    {
        ["nIndex"]=55,
        ["nMapID"]=217,
        ["nWeekDay"]=6,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [56]=
    {
        ["nIndex"]=56,
        ["nMapID"]=217,
        ["nWeekDay"]=7,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [57]=
    {
        ["nIndex"]=57,
        ["nMapID"]=330,
        ["nWeekDay"]=1,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [58]=
    {
        ["nIndex"]=58,
        ["nMapID"]=330,
        ["nWeekDay"]=3,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [59]=
    {
        ["nIndex"]=59,
        ["nMapID"]=330,
        ["nWeekDay"]=5,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [60]=
    {
        ["nIndex"]=60,
        ["nMapID"]=330,
        ["nWeekDay"]=6,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [61]=
    {
        ["nIndex"]=61,
        ["nMapID"]=330,
        ["nWeekDay"]=7,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [62]=
    {
        ["nIndex"]=62,
        ["nMapID"]=334,
        ["nWeekDay"]=1,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [63]=
    {
        ["nIndex"]=63,
        ["nMapID"]=334,
        ["nWeekDay"]=3,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [64]=
    {
        ["nIndex"]=64,
        ["nMapID"]=334,
        ["nWeekDay"]=5,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [65]=
    {
        ["nIndex"]=65,
        ["nMapID"]=334,
        ["nWeekDay"]=6,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [66]=
    {
        ["nIndex"]=66,
        ["nMapID"]=334,
        ["nWeekDay"]=7,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [67]=
    {
        ["nIndex"]=67,
        ["nMapID"]=411,
        ["nWeekDay"]=1,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [68]=
    {
        ["nIndex"]=68,
        ["nMapID"]=411,
        ["nWeekDay"]=3,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [69]=
    {
        ["nIndex"]=69,
        ["nMapID"]=411,
        ["nWeekDay"]=5,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [70]=
    {
        ["nIndex"]=70,
        ["nMapID"]=411,
        ["nWeekDay"]=6,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [71]=
    {
        ["nIndex"]=71,
        ["nMapID"]=411,
        ["nWeekDay"]=7,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [72]=
    {
        ["nIndex"]=72,
        ["nMapID"]=444,
        ["nWeekDay"]=1,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [73]=
    {
        ["nIndex"]=73,
        ["nMapID"]=444,
        ["nWeekDay"]=3,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [74]=
    {
        ["nIndex"]=74,
        ["nMapID"]=444,
        ["nWeekDay"]=5,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [75]=
    {
        ["nIndex"]=75,
        ["nMapID"]=444,
        ["nWeekDay"]=6,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [76]=
    {
        ["nIndex"]=76,
        ["nMapID"]=444,
        ["nWeekDay"]=7,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [77]=
    {
        ["nIndex"]=77,
        ["nMapID"]=473,
        ["nWeekDay"]=1,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [78]=
    {
        ["nIndex"]=78,
        ["nMapID"]=473,
        ["nWeekDay"]=3,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [79]=
    {
        ["nIndex"]=79,
        ["nMapID"]=473,
        ["nWeekDay"]=5,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [80]=
    {
        ["nIndex"]=80,
        ["nMapID"]=473,
        ["nWeekDay"]=6,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [81]=
    {
        ["nIndex"]=81,
        ["nMapID"]=473,
        ["nWeekDay"]=7,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [82]=
    {
        ["nIndex"]=82,
        ["nMapID"]=474,
        ["nWeekDay"]=1,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [83]=
    {
        ["nIndex"]=83,
        ["nMapID"]=474,
        ["nWeekDay"]=3,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [84]=
    {
        ["nIndex"]=84,
        ["nMapID"]=474,
        ["nWeekDay"]=5,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [85]=
    {
        ["nIndex"]=85,
        ["nMapID"]=474,
        ["nWeekDay"]=6,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [86]=
    {
        ["nIndex"]=86,
        ["nMapID"]=474,
        ["nWeekDay"]=7,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [87]=
    {
        ["nIndex"]=87,
        ["nMapID"]=475,
        ["nWeekDay"]=1,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [88]=
    {
        ["nIndex"]=88,
        ["nMapID"]=475,
        ["nWeekDay"]=3,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [89]=
    {
        ["nIndex"]=89,
        ["nMapID"]=475,
        ["nWeekDay"]=5,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [90]=
    {
        ["nIndex"]=90,
        ["nMapID"]=475,
        ["nWeekDay"]=6,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [91]=
    {
        ["nIndex"]=91,
        ["nMapID"]=475,
        ["nWeekDay"]=7,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [92]=
    {
        ["nIndex"]=92,
        ["nMapID"]=488,
        ["nWeekDay"]=1,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [93]=
    {
        ["nIndex"]=93,
        ["nMapID"]=488,
        ["nWeekDay"]=3,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [94]=
    {
        ["nIndex"]=94,
        ["nMapID"]=488,
        ["nWeekDay"]=5,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [95]=
    {
        ["nIndex"]=95,
        ["nMapID"]=488,
        ["nWeekDay"]=6,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [96]=
    {
        ["nIndex"]=96,
        ["nMapID"]=488,
        ["nWeekDay"]=7,
        ["szEndTime"]="22:30",
        ["szBeginTime"]="20:30"
    },
    [97]=
    {
        ["nIndex"]=97,
        ["nMapID"]=627,
        ["nWeekDay"]=1,
        ["szEndTime"]="24:00:00",
        ["szBeginTime"]="0:00"
    },
    [98]=
    {
        ["nIndex"]=98,
        ["nMapID"]=627,
        ["nWeekDay"]=2,
        ["szEndTime"]="24:00:00",
        ["szBeginTime"]="0:00"
    },
    [99]=
    {
        ["nIndex"]=99,
        ["nMapID"]=627,
        ["nWeekDay"]=3,
        ["szEndTime"]="24:00:00",
        ["szBeginTime"]="0:00"
    },
    [100]=
    {
        ["nIndex"]=100,
        ["nMapID"]=627,
        ["nWeekDay"]=4,
        ["szEndTime"]="24:00:00",
        ["szBeginTime"]="0:00"
    },
    [101]=
    {
        ["nIndex"]=101,
        ["nMapID"]=627,
        ["nWeekDay"]=5,
        ["szEndTime"]="24:00:00",
        ["szBeginTime"]="0:00"
    },
    [102]=
    {
        ["nIndex"]=102,
        ["nMapID"]=627,
        ["nWeekDay"]=6,
        ["szEndTime"]="24:00:00",
        ["szBeginTime"]="0:00"
    },
    [103]=
    {
        ["nIndex"]=103,
        ["nMapID"]=627,
        ["nWeekDay"]=7,
        ["szEndTime"]="24:00:00",
        ["szBeginTime"]="0:00"
    },
    [104]=
    {
        ["nIndex"]=104,
        ["nMapID"]=697,
        ["nWeekDay"]=1,
        ["szEndTime"]="24:00:00",
        ["szBeginTime"]="0:00"
    },
    [105]=
    {
        ["nIndex"]=105,
        ["nMapID"]=697,
        ["nWeekDay"]=2,
        ["szEndTime"]="24:00:00",
        ["szBeginTime"]="0:00"
    },
    [106]=
    {
        ["nIndex"]=106,
        ["nMapID"]=697,
        ["nWeekDay"]=3,
        ["szEndTime"]="24:00:00",
        ["szBeginTime"]="0:00"
    },
    [107]=
    {
        ["nIndex"]=107,
        ["nMapID"]=697,
        ["nWeekDay"]=4,
        ["szEndTime"]="24:00:00",
        ["szBeginTime"]="0:00"
    },
    [108]=
    {
        ["nIndex"]=108,
        ["nMapID"]=697,
        ["nWeekDay"]=5,
        ["szEndTime"]="24:00:00",
        ["szBeginTime"]="0:00"
    },
    [109]=
    {
        ["nIndex"]=109,
        ["nMapID"]=697,
        ["nWeekDay"]=6,
        ["szEndTime"]="24:00:00",
        ["szBeginTime"]="0:00"
    },
    [110]=
    {
        ["nIndex"]=110,
        ["nMapID"]=697,
        ["nWeekDay"]=7,
        ["szEndTime"]="24:00:00",
        ["szBeginTime"]="0:00"
    }
}
