--*************************************** 工具生成 ***************************************
UIHuaELouActivityTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["szDes"]="每日签到",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetDailySignInNew",
        ["szScript"]="",
        ["szSfxPath"]="data/source/other/HD特效/UI_M/Pss/OperationCenter/UI_江湖快报_每日签到.pss",
        ["szSmallImg"]="",
        ["nRedPointID"]=2401,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/Activity/DailySign.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=16,
        ["szLayoutBottom"]=""
    },
    [2]=
    {
        ["nID"]=2,
        ["szDes"]="盛夏之约",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetCommonSignInBtnPlus",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=137,
        ["szLayoutBottom"]=""
    },
    [3]=
    {
        ["nID"]=3,
        ["szDes"]="直升礼包",
        ["nBtnID"]=7,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/InstantUpgradeBg.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=52,
        ["szLayoutBottom"]=""
    },
    [4]=
    {
        ["nID"]=4,
        ["szDes"]="好友招募",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="WidgetFriendRecruitCell",
        ["szPrefab"]="",
        ["szScript"]="FriendRecruit",
        ["szSfxPath"]="data/source/other/HD特效/UI_M/Pss/OperationCenter/UI_江湖快报_好友招募BG.pss",
        ["szSmallImg"]="",
        ["nRedPointID"]=2445,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetFriendRecruitOperate",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/Activity/FriendRecruit.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=11,
        ["szLayoutBottom"]=""
    },
    [5]=
    {
        ["nID"]=5,
        ["szDes"]="月度充消",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="WidgetMonthlyPurchaseRewardCell",
        ["szPrefab"]="",
        ["szScript"]="MonthlyPurchase",
        ["szSfxPath"]="data/source/other/HD特效/UI_M/Pss/OperationCenter/UI_江湖快报_月度充消BG.pss",
        ["szSmallImg"]="",
        ["nRedPointID"]=2403,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetMonthlyPurchaseInfo,WidgetLayOutTaskList80",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/Activity/MonthlyPurchase.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=39,
        ["szLayoutBottom"]=""
    },
    [6]=
    {
        ["nID"]=6,
        ["szDes"]="赛季展望",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetSeasonPreview",
        ["szScript"]="",
        ["szSfxPath"]="data/source/other/HD特效/UI_M/Pss/OperationCenter/UI_江湖快报_家园赛季展望BG.pss",
        ["szSmallImg"]="",
        ["nRedPointID"]=2404,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/Activity/SeasonPreview.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=130,
        ["szLayoutBottom"]=""
    },
    [7]=
    {
        ["nID"]=7,
        ["szDes"]="回归礼包",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetReturnGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2406,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=131,
        ["szLayoutBottom"]=""
    },
    [8]=
    {
        ["nID"]=8,
        ["szDes"]="共战江湖",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="GongZhan",
        ["szSfxPath"]="data/source/other/HD特效/UI_M/Pss/OperationCenter/UI_江湖快报_共战江湖BG.pss",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,WidgetGongZhanReward,WidgetContentTitleTog80",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/JiangHuJingNang/GongZhan.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=2,
        ["dwOperatActID"]=132,
        ["szLayoutBottom"]=""
    },
    [9]=
    {
        ["nID"]=9,
        ["szDes"]="商城特惠",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="WidgetBtnImgLinkSmall",
        ["szPrefab"]="",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=116,
        ["szLayoutBottom"]=""
    },
    [10]=
    {
        ["nID"]=10,
        ["szDes"]="消费送真橙",
        ["nBtnID"]=3,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/ShoppingGift.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=118,
        ["szLayoutBottom"]=""
    },
    [11]=
    {
        ["nID"]=11,
        ["szDes"]="感恩回馈",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetRewardWithItem",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/WelfareGiven_2.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=145,
        ["szLayoutBottom"]=""
    },
    [12]=
    {
        ["nID"]=12,
        ["szDes"]="充消返券",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetChargeDiscount",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2416,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/RechargeGift_Two.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=105,
        ["szLayoutBottom"]=""
    },
    [13]=
    {
        ["nID"]=13,
        ["szDes"]="创作无疆",
        ["nBtnID"]=5,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/CreativePlan.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=142,
        ["szLayoutBottom"]=""
    },
    [14]=
    {
        ["nID"]=14,
        ["szDes"]="三人团购",
        ["nBtnID"]=6,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/GroupPromotion.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=143,
        ["szLayoutBottom"]=""
    },
    [15]=
    {
        ["nID"]=15,
        ["szDes"]="新年特惠",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetShoppingRecommend",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=9,
        ["szLayoutBottom"]=""
    },
    [16]=
    {
        ["nID"]=16,
        ["szDes"]="百战逐锋",
        ["nBtnID"]=8,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetBaizhan",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/BaizhanPlay.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=189,
        ["szLayoutBottom"]=""
    },
    [17]=
    {
        ["nID"]=17,
        ["szDes"]="薪火互助",
        ["nBtnID"]=9,
        ["nBtnID2"]=10,
        ["nBtnID3"]=11,
        ["szBottom"]="",
        ["szPrefab"]="WidgetMutualAid",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=134,
        ["szLayoutBottom"]=""
    },
    [18]=
    {
        ["nID"]=18,
        ["szDes"]="锦绣霓裳",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetJinXiuNiChang",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=51,
        ["szLayoutBottom"]=""
    },
    [19]=
    {
        ["nID"]=19,
        ["szDes"]="微信小管家",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/WeChatHelper_VK.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="not Platform.IsMobile()",
            [3]="Config.bIsCEVer"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=147,
        ["szLayoutBottom"]=""
    },
    [20]=
    {
        ["nID"]=20,
        ["szDes"]="签到活动",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetCommonSignInBtnPlus",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2402,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/Act_119/SignInGift.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=119,
        ["szLayoutBottom"]=""
    },
    [21]=
    {
        ["nID"]=21,
        ["szDes"]="好友邀约",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetTestPassSplit",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="HuaELouData.IgnoreOperacShow(152)",
            [3]="Config.bIsCEVer"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=152,
        ["szLayoutBottom"]=""
    },
    [22]=
    {
        ["nID"]=22,
        ["szDes"]="铸剑江湖",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2405,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/Activity/Equip_Distance.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=2,
        ["dwOperatActID"]=48,
        ["szLayoutBottom"]="WidgetEquipDistance"
    },
    [23]=
    {
        ["nID"]=23,
        ["szDes"]="风雨同舟",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetFengYuTongZhou",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=49,
        ["szLayoutBottom"]=""
    },
    [24]=
    {
        ["nID"]=24,
        ["szDes"]="秋意风清福禄到",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetFuLuBaoXiang",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/ChunFengYiNuan_Bg.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=70,
        ["szLayoutBottom"]=""
    },
    [25]=
    {
        ["nID"]=25,
        ["szDes"]="微信小管家",
        ["nBtnID"]=12,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/WeChatHelper.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="Platform.IsMobile()",
            [3]="Config.bIsCEVer"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=147,
        ["szLayoutBottom"]=""
    },
    [26]=
    {
        ["nID"]=26,
        ["szDes"]="新服捷令",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/NewServer.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=151,
        ["szLayoutBottom"]=""
    },
    [27]=
    {
        ["nID"]=27,
        ["szDes"]="锋芒百练",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/HighWeaponsPiecesUp.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=153,
        ["szLayoutBottom"]=""
    },
    [28]=
    {
        ["nID"]=28,
        ["szDes"]="萌新教学团",
        ["nBtnID"]=13,
        ["nBtnID2"]=14,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/RookieTutorialGroup.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="Platform.IsMobile()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=136,
        ["szLayoutBottom"]=""
    },
    [29]=
    {
        ["nID"]=29,
        ["szDes"]="萌新教学团",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/RookieTutorialGroup_VK.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="not Platform.IsMobile()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=136,
        ["szLayoutBottom"]=""
    },
    [30]=
    {
        ["nID"]=30,
        ["szDes"]="充值返还",
        ["nBtnID"]=15,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/ChargeBenefits.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="not Platform.IsIos()",
            [3]="HuaELouData.IgnoreOperacShow(158)",
            [4]="Config.bIsCEVer"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=158,
        ["szLayoutBottom"]=""
    },
    [31]=
    {
        ["nID"]=31,
        ["szDes"]="神兵出磐渊",
        ["nBtnID"]=16,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/OrangeWu.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=148,
        ["szLayoutBottom"]=""
    },
    [32]=
    {
        ["nID"]=32,
        ["szDes"]="刀剑扫猪邪",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetRewardWithItem",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2407,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/SweepDevil.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=154,
        ["szLayoutBottom"]=""
    },
    [33]=
    {
        ["nID"]=33,
        ["szDes"]="天降萌宠",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetTestLuckyMeetingGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2408,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/Img_LuckyMeetingGift.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=86,
        ["szLayoutBottom"]=""
    },
    [34]=
    {
        ["nID"]=34,
        ["szDes"]="感恩回馈",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetRewardWithItem",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2409,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/ShoppingRefund.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=72,
        ["szLayoutBottom"]=""
    },
    [35]=
    {
        ["nID"]=35,
        ["szDes"]="追风逐日",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetChasingStar",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2410,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/ChasingStar.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=157,
        ["szLayoutBottom"]=""
    },
    [36]=
    {
        ["nID"]=36,
        ["szDes"]="铸剑江湖",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetEquipScoreRush",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2405,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=156,
        ["szLayoutBottom"]=""
    },
    [37]=
    {
        ["nID"]=37,
        ["szDes"]="咸鱼赠礼",
        ["nBtnID"]=134,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetHuaELouPublic2BtnTip",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2411,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/Img_LuckyMeetingGift.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=160,
        ["szLayoutBottom"]=""
    },
    [38]=
    {
        ["nID"]=38,
        ["szDes"]="并马少年游",
        ["nBtnID"]=19,
        ["nBtnID2"]=10,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetBingMaYouthTravel",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2412,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=155,
        ["szLayoutBottom"]=""
    },
    [39]=
    {
        ["nID"]=39,
        ["szDes"]="萌新接引",
        ["nBtnID"]=12,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetRookieMentor",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/RookieMentor.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="Platform.IsMobile()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=135,
        ["szLayoutBottom"]=""
    },
    [40]=
    {
        ["nID"]=40,
        ["szDes"]="萌新接引",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetRookieMentor",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/RookieMentor_VK.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="not Platform.IsMobile()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=135,
        ["szLayoutBottom"]=""
    },
    [41]=
    {
        ["nID"]=41,
        ["szDes"]="轻舟闲游",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/RewardSpeedUp.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=159,
        ["szLayoutBottom"]=""
    },
    [42]=
    {
        ["nID"]=42,
        ["szDes"]="江湖无界",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/GongZhanRewardUp.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=161,
        ["szLayoutBottom"]=""
    },
    [43]=
    {
        ["nID"]=43,
        ["szDes"]="乐游纪·八荒衡鉴",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetLeYouBaHuang",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/LeYou_BaHuang.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=162,
        ["szLayoutBottom"]="WidgetLayOutRewardList"
    },
    [44]=
    {
        ["nID"]=44,
        ["szDes"]="丝路盛宴",
        ["nBtnID"]=32,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/ShaoWeiFeast.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=163,
        ["szLayoutBottom"]=""
    },
    [45]=
    {
        ["nID"]=45,
        ["szDes"]="消费送月卡",
        ["nBtnID"]=33,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetMonthlyGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/MonthCardGift.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=54,
        ["szLayoutBottom"]=""
    },
    [46]=
    {
        ["nID"]=46,
        ["szDes"]="掉率翻倍",
        ["nBtnID"]=34,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetInstantUpgradeGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/XuanJingDoubleRate.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=164,
        ["szLayoutBottom"]=""
    },
    [47]=
    {
        ["nID"]=47,
        ["szDes"]="满月赠礼",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGoldenHairGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2413,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/GoldenHairGift.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=165,
        ["szLayoutBottom"]=""
    },
    [48]=
    {
        ["nID"]=48,
        ["szDes"]="乐游纪·列星虚境",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetLeYouLieXing",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/LeYou_LieXing.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=166,
        ["szLayoutBottom"]=""
    },
    [49]=
    {
        ["nID"]=49,
        ["szDes"]="签到活动",
        ["nBtnID"]=138,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetCommonSignInBtnPlus",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2414,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/Act_119/SignInGift_6.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=168,
        ["szLayoutBottom"]=""
    },
    [50]=
    {
        ["nID"]=50,
        ["szDes"]="周年回馈",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetAnniversaryGiveBack",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2415,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=2,
        ["szLayoutBottom"]=""
    },
    [51]=
    {
        ["nID"]=51,
        ["szDes"]="点卡免费",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/FreePointCard.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=66,
        ["szLayoutBottom"]=""
    },
    [52]=
    {
        ["nID"]=52,
        ["szDes"]="千年行约",
        ["nBtnID"]=55,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/QianNianXingYue.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=170,
        ["szLayoutBottom"]=""
    },
    [53]=
    {
        ["nID"]=53,
        ["szDes"]="问题反馈",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/MacBetaFeedback.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="Platform.IsMac()",
            [3]="HuaELouData.IgnoreOperacShow(173)"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=173,
        ["szLayoutBottom"]=""
    },
    [54]=
    {
        ["nID"]=54,
        ["szDes"]="盛夏约·叁",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetCommonSignInBtnPlus",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2417,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/Act_119/SignInGift_7.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=169,
        ["szLayoutBottom"]=""
    },
    [55]=
    {
        ["nID"]=55,
        ["szDes"]="庆典·丰",
        ["nBtnID"]=44,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/DropDouble_Anniversary.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=171,
        ["szLayoutBottom"]=""
    },
    [56]=
    {
        ["nID"]=56,
        ["szDes"]="镜花梦影",
        ["nBtnID"]=39,
        ["nBtnID2"]=40,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetItemWithButtons",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/16thAnniLimitedReward.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=172,
        ["szLayoutBottom"]=""
    },
    [57]=
    {
        ["nID"]=57,
        ["szDes"]="新春购发有礼",
        ["nBtnID"]=115,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/FudaiHair.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=81,
        ["szLayoutBottom"]=""
    },
    [58]=
    {
        ["nID"]=58,
        ["szDes"]="天降宝堆",
        ["nBtnID"]=116,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/SurpriseTreasure.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=174,
        ["szLayoutBottom"]=""
    },
    [59]=
    {
        ["nID"]=59,
        ["szDes"]="冠军赠礼",
        ["nBtnID"]=46,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/ChampionReward.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=175,
        ["szLayoutBottom"]=""
    },
    [60]=
    {
        ["nID"]=60,
        ["szDes"]="福袋返场",
        ["nBtnID"]=47,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetFuDaiFanChang",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/FudaiFanChang.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=176,
        ["szLayoutBottom"]=""
    },
    [61]=
    {
        ["nID"]=61,
        ["szDes"]="武林争霸赛",
        ["nBtnID"]=48,
        ["nBtnID2"]=49,
        ["nBtnID3"]=50,
        ["szBottom"]="",
        ["szPrefab"]="WidgetBangHuiLianSaiShouMai",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/BangHuiLianSaiShouMai.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="HuaELouData.IgnoreOperacShow(177)"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=177,
        ["szLayoutBottom"]=""
    },
    [62]=
    {
        ["nID"]=62,
        ["szDes"]="书剑天涯",
        ["nBtnID"]=51,
        ["nBtnID2"]=52,
        ["nBtnID3"]=119,
        ["szBottom"]="",
        ["szPrefab"]="WidgetSaijipifeng",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/Shujiantianya.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=178,
        ["szLayoutBottom"]=""
    },
    [63]=
    {
        ["nID"]=63,
        ["szDes"]="乐游纪·尘世曼舞",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetLeYouManWu",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/LeYou_ManWu.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=141,
        ["szLayoutBottom"]=""
    },
    [64]=
    {
        ["nID"]=64,
        ["szDes"]="长进千里",
        ["nBtnID"]=89,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetRookieTutorialGroup",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/ChangJinQianLi2025.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=179,
        ["szLayoutBottom"]=""
    },
    [65]=
    {
        ["nID"]=65,
        ["szDes"]="消费返券",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetChargeDiscount",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2418,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/RechargeGift_Two.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=120,
        ["szLayoutBottom"]=""
    },
    [66]=
    {
        ["nID"]=66,
        ["szDes"]="通宝回馈",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetFanpaiShuang11",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2419,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=4,
        ["szLayoutBottom"]=""
    },
    [67]=
    {
        ["nID"]=67,
        ["szDes"]="外装投票",
        ["nBtnID"]=58,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetRewardWithItem",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2420,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/2024Tongrenwaizhuang.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=180,
        ["szLayoutBottom"]=""
    },
    [68]=
    {
        ["nID"]=68,
        ["szDes"]="特效投票",
        ["nBtnID"]=135,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetRewardWithItem",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2421,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/2024Tongrenwuqi.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=103,
        ["szLayoutBottom"]=""
    },
    [69]=
    {
        ["nID"]=69,
        ["szDes"]="乐游纪·飞火论锋",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetLeYouFeiHuo",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/LeYou_FeiHuo.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=181,
        ["szLayoutBottom"]=""
    },
    [70]=
    {
        ["nID"]=70,
        ["szDes"]="双十二福袋",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetDouble12FuDai",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/Double12/Double12FuDai.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=114,
        ["szLayoutBottom"]=""
    },
    [71]=
    {
        ["nID"]=71,
        ["szDes"]="故城墨影",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetQinShiGuChengMoYing",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/QinShi_GuChengMoYin.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=182,
        ["szLayoutBottom"]=""
    },
    [72]=
    {
        ["nID"]=72,
        ["szDes"]="名剑摧锋",
        ["nBtnID"]=64,
        ["nBtnID2"]=65,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetMingJianCuiFeng",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/MingJianCuiFeng.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=183,
        ["szLayoutBottom"]=""
    },
    [73]=
    {
        ["nID"]=73,
        ["szDes"]="河西飞剑",
        ["nBtnID"]=67,
        ["nBtnID2"]=68,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetHeXiFeiJian",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/HeXiFeiJian.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=184,
        ["szLayoutBottom"]=""
    },
    [74]=
    {
        ["nID"]=74,
        ["szDes"]="腊八节·签到活动",
        ["nBtnID"]=69,
        ["nBtnID2"]=70,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetCommonSignInBtnPlus",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2422,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/Act_119/SignInGift_8.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=185,
        ["szLayoutBottom"]=""
    },
    [75]=
    {
        ["nID"]=75,
        ["szDes"]="云图古韵赏",
        ["nBtnID"]=71,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetRewardWithItem",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2424,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/YunTuGuYunShang.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=186,
        ["szLayoutBottom"]=""
    },
    [76]=
    {
        ["nID"]=76,
        ["szDes"]="春节活动",
        ["nBtnID"]=72,
        ["nBtnID2"]=73,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetCommonSignInBtnPlus",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2423,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/Act_119/SignInGift_9.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=187,
        ["szLayoutBottom"]=""
    },
    [77]=
    {
        ["nID"]=77,
        ["szDes"]="年夜盛宴",
        ["nBtnID"]=74,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/Chuxishengyan.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=93,
        ["szLayoutBottom"]=""
    },
    [78]=
    {
        ["nID"]=78,
        ["szDes"]="消费送烟花",
        ["nBtnID"]=137,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetShoppingGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/2025ShoppingGiftFireworks.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=123,
        ["szLayoutBottom"]=""
    },
    [79]=
    {
        ["nID"]=79,
        ["szDes"]="充时返点卡",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetShoppingGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/2025ShoppingGiftPendant.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=12,
        ["szLayoutBottom"]=""
    },
    [80]=
    {
        ["nID"]=80,
        ["szDes"]="春节福袋",
        ["nBtnID"]=75,
        ["nBtnID2"]=76,
        ["nBtnID3"]=77,
        ["szBottom"]="",
        ["szPrefab"]="WidgetFuDaiHair3Btn",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/2025FudaiHair.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=44,
        ["szLayoutBottom"]=""
    },
    [81]=
    {
        ["nID"]=81,
        ["szDes"]="签到送奇遇",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetCommonSignInBtnPlus",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2425,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/Act_119/SignInGift_10.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=188,
        ["szLayoutBottom"]=""
    },
    [82]=
    {
        ["nID"]=82,
        ["szDes"]="登录送福",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="Widget2024TongRenWaiZhuang",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2426,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/LoginFirework.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=91,
        ["szLayoutBottom"]=""
    },
    [83]=
    {
        ["nID"]=83,
        ["szDes"]="除夕盛典",
        ["nBtnID"]=78,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/ChuXiShengYan.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=190,
        ["szLayoutBottom"]=""
    },
    [84]=
    {
        ["nID"]=84,
        ["szDes"]="元宵节",
        ["nBtnID"]=79,
        ["nBtnID2"]=80,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/YuanXiao2025.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=191,
        ["szLayoutBottom"]=""
    },
    [85]=
    {
        ["nID"]=85,
        ["szDes"]="速破黄砂",
        ["nBtnID"]=81,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/MonsterRacingChallenge.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=192,
        ["szLayoutBottom"]=""
    },
    [86]=
    {
        ["nID"]=86,
        ["szDes"]="女侠节",
        ["nBtnID"]=79,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetHuaELouPublic2BtnTip",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2427,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/JianghuLiying.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=40,
        ["szLayoutBottom"]=""
    },
    [87]=
    {
        ["nID"]=87,
        ["szDes"]="群英赛",
        ["nBtnID"]=82,
        ["nBtnID2"]=83,
        ["nBtnID3"]=84,
        ["szBottom"]="",
        ["szPrefab"]="WidgetXialuJingYingxiong",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/XialuJingYingxiong.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=193,
        ["szLayoutBottom"]=""
    },
    [88]=
    {
        ["nID"]=88,
        ["szDes"]="花朝节",
        ["nBtnID"]=79,
        ["nBtnID2"]=85,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetHuaELouPublic3BtnTip",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2428,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/FlowerFestival25.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=196,
        ["szLayoutBottom"]=""
    },
    [89]=
    {
        ["nID"]=89,
        ["szDes"]="乐游纪·李渡鬼域",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetLeYouLiDu",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/LeYou_LiDuGuiYu.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=195,
        ["szLayoutBottom"]=""
    },
    [90]=
    {
        ["nID"]=90,
        ["szDes"]="烽沙归途",
        ["nBtnID"]=87,
        ["nBtnID2"]=88,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetCreativePlan",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/FengShaGuiTu.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=194,
        ["szLayoutBottom"]=""
    },
    [91]=
    {
        ["nID"]=91,
        ["szDes"]="插旗大王",
        ["nBtnID"]=90,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/FlagKing.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=197,
        ["szLayoutBottom"]=""
    },
    [92]=
    {
        ["nID"]=92,
        ["szDes"]="江湖礼遇",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="Widget2024TongRenWaiZhuang",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2429,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/Jianghuliyu.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=198,
        ["szLayoutBottom"]=""
    },
    [93]=
    {
        ["nID"]=93,
        ["szDes"]="赛事赠礼",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetRewardWithItem",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2430,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/2025QunYingSaiZengLi.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=90,
        ["szLayoutBottom"]=""
    },
    [94]=
    {
        ["nID"]=94,
        ["szDes"]="清明节",
        ["nBtnID"]=91,
        ["nBtnID2"]=92,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2431,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/2025QingMing.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=199,
        ["szLayoutBottom"]=""
    },
    [95]=
    {
        ["nID"]=95,
        ["szDes"]="大唐逍遥手册",
        ["nBtnID"]=96,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/XiaoYaoHandBook.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="Platform.IsMobile()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=201,
        ["szLayoutBottom"]=""
    },
    [96]=
    {
        ["nID"]=96,
        ["szDes"]="大唐逍遥手册",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/XiaoYaoHandBook_VK.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="not Platform.IsMobile()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=201,
        ["szLayoutBottom"]=""
    },
    [97]=
    {
        ["nID"]=97,
        ["szDes"]="感恩回馈",
        ["nBtnID"]=97,
        ["nBtnID2"]=98,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/WelfareGiven_3.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=202,
        ["szLayoutBottom"]=""
    },
    [98]=
    {
        ["nID"]=98,
        ["szDes"]="儿童节",
        ["nBtnID"]=100,
        ["nBtnID2"]=101,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetHuaELouPublic3BtnTip",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2432,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/2025ErTongJie.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=204,
        ["szLayoutBottom"]=""
    },
    [99]=
    {
        ["nID"]=99,
        ["szDes"]="端午节",
        ["nBtnID"]=79,
        ["nBtnID2"]=102,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetHuaELouPublic3BtnTip",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2433,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/2025DuanWuJie.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=203,
        ["szLayoutBottom"]=""
    },
    [100]=
    {
        ["nID"]=100,
        ["szDes"]="酷礼随行",
        ["nBtnID"]=104,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetBingMaYouthTravel",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/ShenJianXinLianDong_1.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=205,
        ["szLayoutBottom"]=""
    },
    [101]=
    {
        ["nID"]=101,
        ["szDes"]="奇境寻宝",
        ["nBtnID"]=105,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetQinShiGuChengMoYing",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/QiJingXunBao.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=206,
        ["szLayoutBottom"]=""
    },
    [102]=
    {
        ["nID"]=102,
        ["szDes"]="南音行约",
        ["nBtnID"]=106,
        ["nBtnID2"]=107,
        ["nBtnID3"]=108,
        ["szBottom"]="",
        ["szPrefab"]="WidgetHuaELouPublic3BtnTip2",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/NanYinXingYue.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=207,
        ["szLayoutBottom"]=""
    },
    [103]=
    {
        ["nID"]=103,
        ["szDes"]="绝境·乱武",
        ["nBtnID"]=109,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetHuaELouPublic3BtnTip2",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/DesperalandHuntBrawl.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=208,
        ["szLayoutBottom"]=""
    },
    [104]=
    {
        ["nID"]=104,
        ["szDes"]="摸金同乐",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetRewardWithItem",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2434,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/MoJinTongLe.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=209,
        ["szLayoutBottom"]=""
    },
    [105]=
    {
        ["nID"]=105,
        ["szDes"]="抖音创作季",
        ["nBtnID"]=111,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/DouYinCreativeSeason.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="Platform.IsMobile()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=210,
        ["szLayoutBottom"]=""
    },
    [106]=
    {
        ["nID"]=106,
        ["szDes"]="抖音创作季",
        ["nBtnID"]=112,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/DouYinCreativeSeason.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="not Platform.IsMobile()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=210,
        ["szLayoutBottom"]=""
    },
    [107]=
    {
        ["nID"]=107,
        ["szDes"]="七夕节",
        ["nBtnID"]=113,
        ["nBtnID2"]=114,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetHuaELouPublic3BtnTip",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2435,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/QixiFestivalActivity.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=211,
        ["szLayoutBottom"]=""
    },
    [108]=
    {
        ["nID"]=108,
        ["szDes"]="使至塞上",
        ["nBtnID"]=120,
        ["nBtnID2"]=121,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetCreativePlan",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/NewWarmupEvent.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=212,
        ["szLayoutBottom"]=""
    },
    [109]=
    {
        ["nID"]=109,
        ["szDes"]="中元节",
        ["nBtnID"]=117,
        ["nBtnID2"]=118,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetHuaELouPublic3BtnTip",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2436,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/ZhongyuanFestival.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=213,
        ["szLayoutBottom"]=""
    },
    [110]=
    {
        ["nID"]=110,
        ["szDes"]="中秋节",
        ["nBtnID"]=122,
        ["nBtnID2"]=123,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetHuaELouPublic3BtnTip",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2437,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/ZhongqiuFestival.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=214,
        ["szLayoutBottom"]=""
    },
    [111]=
    {
        ["nID"]=111,
        ["szDes"]="重阳节",
        ["nBtnID"]=124,
        ["nBtnID2"]=125,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetHuaELouPublic3BtnTip",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2438,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/DoubleNinthFestival.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=215,
        ["szLayoutBottom"]=""
    },
    [112]=
    {
        ["nID"]=112,
        ["szDes"]="B站创作激励",
        ["nBtnID"]=126,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/BilibiliCreativeSeason.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="Platform.IsMobile()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=216,
        ["szLayoutBottom"]=""
    },
    [113]=
    {
        ["nID"]=113,
        ["szDes"]="B站创作激励",
        ["nBtnID"]=127,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/BilibiliCreativeSeason.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()",
            [2]="not Platform.IsMobile()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=216,
        ["szLayoutBottom"]=""
    },
    [114]=
    {
        ["nID"]=114,
        ["szDes"]="无相楼",
        ["nBtnID"]=128,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/NewSectGuideEvent.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=217,
        ["szLayoutBottom"]=""
    },
    [115]=
    {
        ["nID"]=115,
        ["szDes"]="消费送丸子",
        ["nBtnID"]=3,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetExpressDeliveryGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2439,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/ExpressDeliveryGift.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=218,
        ["szLayoutBottom"]=""
    },
    [116]=
    {
        ["nID"]=116,
        ["szDes"]="染发满赠",
        ["nBtnID"]=130,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetShoppingDyeingGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2440,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/ShoppingDyeingGift.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=219,
        ["szLayoutBottom"]=""
    },
    [117]=
    {
        ["nID"]=117,
        ["szDes"]="狂欢礼盒",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetCarnivalGiftPack",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2441,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/CarnivalGiftPack.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=220,
        ["szLayoutBottom"]=""
    },
    [118]=
    {
        ["nID"]=118,
        ["szDes"]="冬至",
        ["nBtnID"]=132,
        ["nBtnID2"]=133,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetHuaELouPublic3BtnTip",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2442,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/WinterSolsticeActivity.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=221,
        ["szLayoutBottom"]=""
    },
    [119]=
    {
        ["nID"]=119,
        ["szDes"]="百铸成天锋",
        ["nBtnID"]=136,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,WidgetPublicRewardShow",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/Activity/BZCTF.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=222,
        ["szLayoutBottom"]=""
    },
    [120]=
    {
        ["nID"]=120,
        ["szDes"]="春节",
        ["nBtnID"]=138,
        ["nBtnID2"]=72,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2423,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/NewYearHolidayGifts.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=223,
        ["szLayoutBottom"]=""
    },
    [121]=
    {
        ["nID"]=121,
        ["szDes"]="赛事竞猜",
        ["nBtnID"]=139,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetGratefulGift",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Texture/HuaELouReward/OperationActivity/MasterRaceGuessing.png",
        ["tbCheckFunc"]=
        {
            [1]="not AppReviewMgr.IsReview()"
        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=224,
        ["szLayoutBottom"]=""
    },
    [122]=
    {
        ["nID"]=122,
        ["szDes"]="新人签到",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetReturnGiftPage",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2443,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/JiangHuJingNang/SignInMengXin.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=225,
        ["szLayoutBottom"]=""
    },
    [123]=
    {
        ["nID"]=123,
        ["szDes"]="回归签到",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetReturnGiftPage",
        ["szScript"]="",
        ["szSfxPath"]="data/source/other/HD特效/UI_M/Pss/OperationCenter/UI_江湖快报_回归签到BG.pss",
        ["szSmallImg"]="",
        ["nRedPointID"]=2444,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/JiangHuJingNang/SignInHuiGui.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=226,
        ["szLayoutBottom"]=""
    },
    [124]=
    {
        ["nID"]=124,
        ["szDes"]="安全",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="SafePanel",
        ["szSfxPath"]="data/source/other/HD特效/UI_M/Pss/OperationCenter/UI_江湖快报_安全BG.pss",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetContentTitleTog100",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/JiangHuJingNang/Safe.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=2,
        ["dwOperatActID"]=227,
        ["szLayoutBottom"]=""
    },
    [125]=
    {
        ["nID"]=125,
        ["szDes"]="回归接引人",
        ["nBtnID"]=140,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="RecallGuide",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,WidgetQRcode",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/JiangHuJingNang/GuidePersonHuiGui.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=229,
        ["szLayoutBottom"]=""
    },
    [126]=
    {
        ["nID"]=126,
        ["szDes"]="追赶商店",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="Shop",
        ["szSfxPath"]="data/source/other/HD特效/UI_M/Pss/OperationCenter/UI_江湖快报_追赶商店BG.pss",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetAnchoreContentScrollWide",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/JiangHuJingNang/ZhuiGanShop.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=2,
        ["dwOperatActID"]=230,
        ["szLayoutBottom"]=""
    },
    [127]=
    {
        ["nID"]=127,
        ["szDes"]="四倍积分回馈",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="Resource/OperationCenter/ShoppingRecommend/Jifen.png",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,WidgetTaskList80",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/Activity/ShoppingRecommend_Jifen.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=231,
        ["szLayoutBottom"]=""
    },
    [128]=
    {
        ["nID"]=128,
        ["szDes"]="五档充值促销",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="Resource/OperationCenter/ShoppingRecommend/MonthlyPurchase.png",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,WidgetTaskList80",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/Activity/ShoppingRecommend_Monthly.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=232,
        ["szLayoutBottom"]=""
    },
    [129]=
    {
        ["nID"]=129,
        ["szDes"]="免金币拓印",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="Resource/OperationCenter/ShoppingRecommend/Taying.png",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,WidgetTaskList80",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/Activity/ShoppingRecommend_Taying.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=233,
        ["szLayoutBottom"]=""
    },
    [130]=
    {
        ["nID"]=130,
        ["szDes"]="萌新接引人",
        ["nBtnID"]=141,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="GuideNew",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2446,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,WidgetQRcode",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/JiangHuJingNang/GuidePersonMengXin.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=234,
        ["szLayoutBottom"]="WidgetMengXinReward,WidgetLayOutRewardList"
    },
    [131]=
    {
        ["nID"]=131,
        ["szDes"]="萌新教学团",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="TeachNew",
        ["szSfxPath"]="data/source/other/HD特效/UI_M/Pss/OperationCenter/UI_江湖快报_萌新教学团BG.pss",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetAnchoreContentScrollWide",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/JiangHuJingNang/MengXinJiaoXueTuan.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=2,
        ["dwOperatActID"]=235,
        ["szLayoutBottom"]=""
    },
    [132]=
    {
        ["nID"]=132,
        ["szDes"]="总览",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetNewInfoUpdate",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/NewInfo/NewInfoUpDate.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=0,
        ["dwOperatActID"]=236,
        ["szLayoutBottom"]=""
    },
    [133]=
    {
        ["nID"]=133,
        ["szDes"]="唐简传",
        ["nBtnID"]=142,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="TangJianZhuan",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent",
        ["szVideoPath"]="OperationCenter/TJZ_Loop.bk2",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/NewInfo/TangJianZhuan.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=237,
        ["szLayoutBottom"]="WidgetLayOutRewardList"
    },
    [134]=
    {
        ["nID"]=134,
        ["szDes"]="阆风悬城",
        ["nBtnID"]=153,
        ["nBtnID2"]=143,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="LangFengXuanCheng",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=4401,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,WidgetTaskList100",
        ["szVideoPath"]="OperationCenter/CS_20260414.bk2",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=238,
        ["szLayoutBottom"]=" WidgetLayOutRewardList"
    },
    [135]=
    {
        ["nID"]=135,
        ["szDes"]="扬刀大会·影",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent",
        ["szVideoPath"]="OperationCenter/YDDH_Y.bk2",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/NewInfo/YangDao.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=239,
        ["szLayoutBottom"]="WidgetLayOutRewardList"
    },
    [136]=
    {
        ["nID"]=136,
        ["szDes"]="武林争霸赛",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,WidgetContentTitleTog100",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/NewInfo/WuLinZhengBa.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=2,
        ["dwOperatActID"]=240,
        ["szLayoutBottom"]="WidgetLayOutRewardList"
    },
    [137]=
    {
        ["nID"]=137,
        ["szDes"]="版本优化",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="WidgetBtnImgLinkSmall",
        ["szPrefab"]="",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=241,
        ["szLayoutBottom"]=""
    },
    [138]=
    {
        ["nID"]=138,
        ["szDes"]="探索画质升级",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="Resource/OperationCenter/NewInfoUpdate/pic_1tshzsj.png",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent",
        ["szVideoPath"]="OperationCenter/TSHZTS.bk2",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=242,
        ["szLayoutBottom"]=""
    },
    [139]=
    {
        ["nID"]=139,
        ["szDes"]="全门派技改",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="Resource/OperationCenter/NewInfoUpdate/pic_2qmpjg.png",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,WidgetTaskList80",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/NewInfo/JiGai.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=243,
        ["szLayoutBottom"]=""
    },
    [140]=
    {
        ["nID"]=140,
        ["szDes"]="橙武补全",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="ChengWu",
        ["szSfxPath"]="",
        ["szSmallImg"]="Resource/OperationCenter/NewInfoUpdate/pic_3cwbq.png",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,WidgetNon,WidgetLayOutTaskListDouble100",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=244,
        ["szLayoutBottom"]=""
    },
    [141]=
    {
        ["nID"]=141,
        ["szDes"]="新宠物",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="Adventure",
        ["szSfxPath"]="",
        ["szSmallImg"]="Resource/OperationCenter/NewInfoUpdate/pic_4xcw.png",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,WidgetLayOutTaskList80",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/NewInfo/ChongWu.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=2,
        ["dwOperatActID"]=245,
        ["szLayoutBottom"]=""
    },
    [142]=
    {
        ["nID"]=142,
        ["szDes"]="侠缘聊天",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="Resource/OperationCenter/NewInfoUpdate/pic_5xylt.png",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,WidgetTaskList80",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=246,
        ["szLayoutBottom"]=""
    },
    [143]=
    {
        ["nID"]=143,
        ["szDes"]="一键成片",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="Resource/OperationCenter/NewInfoUpdate/pic_6yjcp.png",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,WidgetTaskList80",
        ["szVideoPath"]="",
        ["szbgImgPath"]="",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=247,
        ["szLayoutBottom"]=""
    },
    [144]=
    {
        ["nID"]=144,
        ["szDes"]="名望诛恶",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="FameAndPunishEvil",
        ["szSfxPath"]="",
        ["szSmallImg"]="Resource/OperationCenter/NewInfoUpdate/pic_7mwze.png",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetContentTitleTog100",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/NewInfo/MWZE.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=248,
        ["szLayoutBottom"]=""
    },
    [145]=
    {
        ["nID"]=145,
        ["szDes"]="奖励上新",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="RewardPreview",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetAnchoreContentScrollWide",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/NewInfo/RewardUpdate.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=249,
        ["szLayoutBottom"]=""
    },
    [146]=
    {
        ["nID"]=146,
        ["szDes"]="双剑相逢",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="WidgetReturnGiftPage",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2447,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,WidgetTaskList100",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/Activity/XianJian.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=250,
        ["szLayoutBottom"]=""
    },
    [147]=
    {
        ["nID"]=147,
        ["szDes"]="登录好礼",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="RewardWithItem",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=2448,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent,",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/Activity/DLHL.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=251,
        ["szLayoutBottom"]="WidgetLayOutRewardList"
    },
    [148]=
    {
        ["nID"]=148,
        ["szDes"]="乐游记",
        ["nBtnID"]=0,
        ["nBtnID2"]=0,
        ["nBtnID3"]=0,
        ["szBottom"]="",
        ["szPrefab"]="",
        ["szScript"]="",
        ["szSfxPath"]="",
        ["szSmallImg"]="",
        ["nRedPointID"]=0,
        ["szLayoutTop"]="WidgetLayOutWidgetPublicTitle,WidgetLabelContent",
        ["szVideoPath"]="",
        ["szbgImgPath"]="Resource/OperationCenter/Bg/Activity/LeYouJi.png",
        ["tbCheckFunc"]=
        {

        },
        ["nLayoutStyle"]=1,
        ["dwOperatActID"]=252,
        ["szLayoutBottom"]="WidgetLayOutRewardList"
    }
}
