--*************************************** 工具生成 ***************************************
UIHuaELouOperatActTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="3倍积分回馈",
        ["szEndTime"]="1775430000",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_1.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_ShangChengJiFen.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1775084400",
        ["nOperatActID"]=116,
        ["szCustomTime"]="4月2日7:00-4月6日7:00"
    },
    [2]=
    {
        ["nID"]=2,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="五档充值促销",
        ["szEndTime"]="1776898800",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_2.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_ChongZhiCuXiao.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1775084400",
        ["nOperatActID"]=116,
        ["szCustomTime"]="4月2日7:00-4月23日7:00"
    },
    [3]=
    {
        ["nID"]=3,
        ["szDes"]="商城特惠",
        ["nBtnID"]=24,
        ["szTitle"]="购发有礼",
        ["szEndTime"]="1773615600",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_3.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_FaXing.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1771257600",
        ["nOperatActID"]=116,
        ["szCustomTime"]="2月17日0:00-3月16日7:00"
    },
    [4]=
    {
        ["nID"]=4,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="消费送烟花",
        ["szEndTime"]="1772665200",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_4.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_LiHua.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1770246000",
        ["nOperatActID"]=116,
        ["szCustomTime"]="2月5日7:00-3月5日7:00"
    },
    [5]=
    {
        ["nID"]=5,
        ["szDes"]="商城特惠",
        ["nBtnID"]=24,
        ["szTitle"]="发型九折",
        ["szEndTime"]="1765555200",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_5.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_FaXing.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1764802800",
        ["nOperatActID"]=116,
        ["szCustomTime"]="12月4日7:00-12月12日24:00"
    },
    [6]=
    {
        ["nID"]=6,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="消费送券",
        ["szEndTime"]="1765555200",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_6.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_TuPu.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1764802800",
        ["nOperatActID"]=116,
        ["szCustomTime"]="12月4日7:00-12月12日24:00"
    },
    [7]=
    {
        ["nID"]=7,
        ["szDes"]="商城特惠",
        ["nBtnID"]=24,
        ["szTitle"]="购发有礼",
        ["szEndTime"]="1765555200",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_7.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_FaXing.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1764802800",
        ["nOperatActID"]=116,
        ["szCustomTime"]="12月4日7:00-12月12日24:00"
    },
    [8]=
    {
        ["nID"]=8,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="五档充值促销",
        ["szEndTime"]="1768431600",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_8.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_ChongZhiCuXiao.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1764802800",
        ["nOperatActID"]=116,
        ["szCustomTime"]="12月4日7:00-1月15日7:00"
    },
    [9]=
    {
        ["nID"]=9,
        ["szDes"]="商城特惠",
        ["nBtnID"]=20,
        ["szTitle"]="家园区8折",
        ["szEndTime"]="1762876800",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_9.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_JiaYuan.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1761778800",
        ["nOperatActID"]=116,
        ["szCustomTime"]="10月30日7:00-11月11日24:00"
    },
    [10]=
    {
        ["nID"]=10,
        ["szDes"]="商城特惠",
        ["nBtnID"]=129,
        ["szTitle"]="校服免金币拓印",
        ["szEndTime"]="1763334000",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_10.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_TuPu.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1761778800",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [11]=
    {
        ["nID"]=11,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="五档充值促销",
        ["szEndTime"]="1764802800",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_11.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_ChongZhiCuXiao.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1762383600",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [12]=
    {
        ["nID"]=12,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="周年充消回馈",
        ["szEndTime"]="1767196800",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_12.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_XiaoFeiHongBao.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1755126000",
        ["nOperatActID"]=116,
        ["szCustomTime"]="8月14日7:00-12月31日24:00"
    },
    [13]=
    {
        ["nID"]=13,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="消费送月卡",
        ["szEndTime"]="1756681200",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_3.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_ZheKouFreeDianKa.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1755126000",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [14]=
    {
        ["nID"]=14,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="七夕购买送烟花",
        ["szEndTime"]="1756681200",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_4.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_LiHua.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1755126000",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [15]=
    {
        ["nID"]=15,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="充消返券",
        ["szEndTime"]="1756681200",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_5.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_TuPu.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1755126000",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [16]=
    {
        ["nID"]=16,
        ["szDes"]="商城特惠",
        ["nBtnID"]=24,
        ["szTitle"]="购发有礼",
        ["szEndTime"]="1756681200",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_6.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_FaXing.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1756335600",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [17]=
    {
        ["nID"]=17,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="登录领折扣券",
        ["szEndTime"]="1755126000",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_3.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_ZheKouFreeDianKa.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1752706800",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [18]=
    {
        ["nID"]=18,
        ["szDes"]="商城特惠",
        ["nBtnID"]=22,
        ["szTitle"]="常驻外装打折",
        ["szEndTime"]="1749078000",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_6.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_ChengYiWaiZhuang.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1748473200",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [19]=
    {
        ["nID"]=19,
        ["szDes"]="商城特惠",
        ["nBtnID"]=23,
        ["szTitle"]="捏脸5折",
        ["szEndTime"]="1749078000",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_8.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_YiRong.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1748473200",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [20]=
    {
        ["nID"]=20,
        ["szDes"]="商城特惠",
        ["nBtnID"]=24,
        ["szTitle"]="全场发型9折、体型5折",
        ["szEndTime"]="1749078000",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_9.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_FaXing.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1748473200",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [21]=
    {
        ["nID"]=21,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="登录领神兽下凡折扣券",
        ["szEndTime"]="1749078000",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_10.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_ZheKouFreeDianKa.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1748473200",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [22]=
    {
        ["nID"]=22,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="登录领灵魅幻面折扣券",
        ["szEndTime"]="1749078000",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_11.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_ZheKouFreeDianKa.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1748473200",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [23]=
    {
        ["nID"]=23,
        ["szDes"]="商城特惠",
        ["nBtnID"]=20,
        ["szTitle"]="积木6.8折",
        ["szEndTime"]="1745449200",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_3.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_JiaYuan.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1744844400",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [24]=
    {
        ["nID"]=24,
        ["szDes"]="商城特惠",
        ["nBtnID"]=95,
        ["szTitle"]="登录领校服拓印券",
        ["szEndTime"]="1745449200",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_4.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_TaYin.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1744844400",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [25]=
    {
        ["nID"]=25,
        ["szDes"]="商城特惠",
        ["nBtnID"]=24,
        ["szTitle"]="发型9折",
        ["szEndTime"]="1742166000",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_4.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_FaXing.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1741820400",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [26]=
    {
        ["nID"]=26,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="充时间返点卡",
        ["szEndTime"]="1740006000",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_6.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_ChongDianKa.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1736982000",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [27]=
    {
        ["nID"]=27,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="登录送福",
        ["szEndTime"]="1739746800",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_7.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_LiHua.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1737586800",
        ["nOperatActID"]=116,
        ["szCustomTime"]="1月28日0:00-2月17日7:00"
    },
    [28]=
    {
        ["nID"]=28,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="全民消费送折扣券",
        ["szEndTime"]="1734019200",
        ["szImgPath"]="Texture/HuaELouReward/Double12/Banner_6.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_ZheKouFreeDianKa.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1733353200",
        ["nOperatActID"]=116,
        ["szCustomTime"]="12月5日7:00-12月12日24:00"
    },
    [29]=
    {
        ["nID"]=29,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="通宝回馈",
        ["szEndTime"]="1734613200",
        ["szImgPath"]="Texture/HuaELouReward/Double12/Banner_7.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_XiaoFeiHongBao.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1733353200",
        ["nOperatActID"]=116,
        ["szCustomTime"]="12月5日21:00-12月19日21:00"
    },
    [30]=
    {
        ["nID"]=30,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="周年回馈",
        ["szEndTime"]="1735660799",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_12.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_ChongZhiCuXiao.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1723071600",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    },
    [31]=
    {
        ["nID"]=31,
        ["szDes"]="商城特惠",
        ["nBtnID"]=3,
        ["szTitle"]="消费送真橙之心",
        ["szEndTime"]="1731340800",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_10.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_LiHua.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1729724400",
        ["nOperatActID"]=116,
        ["szCustomTime"]="10月24日7:00-11月11日24:00"
    },
    [32]=
    {
        ["nID"]=32,
        ["szDes"]="商城特惠",
        ["nBtnID"]=29,
        ["szTitle"]="非人哉家具免费送",
        ["szEndTime"]="1720998000",
        ["szImgPath"]="Texture/HuaELouReward/ActivityMenu/ActivityBanner_1.png",
        ["szIconPath"]="UIAtlas2_HuaELou_ShoppingRecommend_Img_JiaYuan.png",
        ["tbBtnPosXY"]=
        {
            [1]=0,
            [2]=0
        },
        ["szStartTime"]="1717059600",
        ["nOperatActID"]=116,
        ["szCustomTime"]=""
    }
}
