--*************************************** 工具生成 ***************************************
UILoginScenePresetEffectTab = 
{
    [1]=
    {
        ["nIndex"]=1,
        ["vScale"]=
        {
            [1]=1,
            [2]=1,
            [3]=1
        },
        ["vPosition"]=
        {
            [1]=29.2,
            [2]=43,
            [3]=217.1
        },
        ["vRotation"]=
        {
            [1]=0,
            [2]=0,
            [3]=0
        },
        ["szIconPath"]="Texture/NieLian/Environment/环境预设_橙.png",
        ["szEffectPath"]="data/source/other/HD特效/其他/Pss/D_登录背景_氛围黄01.pss",
        ["szPresetName"]="测试_橙"
    },
    [2]=
    {
        ["nIndex"]=2,
        ["vScale"]=
        {
            [1]=1,
            [2]=1,
            [3]=1
        },
        ["vPosition"]=
        {
            [1]=-96.9,
            [2]=-24.8,
            [3]=217.1
        },
        ["vRotation"]=
        {
            [1]=0,
            [2]=0,
            [3]=0
        },
        ["szIconPath"]="Texture/NieLian/Environment/环境预设_青.png",
        ["szEffectPath"]="data/source/other/HD特效/其他/Pss/D_登录背景_氛围蓝01.pss",
        ["szPresetName"]="测试_青"
    },
    [3]=
    {
        ["nIndex"]=3,
        ["vScale"]=
        {
            [1]=1,
            [2]=1,
            [3]=1
        },
        ["vPosition"]=
        {
            [1]=29.2,
            [2]=43,
            [3]=217.1
        },
        ["vRotation"]=
        {
            [1]=0,
            [2]=0,
            [3]=0
        },
        ["szIconPath"]="Texture/NieLian/Environment/环境预设_青.png",
        ["szEffectPath"]="data/source/other/HD特效/其他/Pss/D_登录背景_氛围蓝01.pss",
        ["szPresetName"]="测试_青"
    },
    [4]=
    {
        ["nIndex"]=4,
        ["vScale"]=
        {
            [1]=0.673,
            [2]=0.673,
            [3]=0.673
        },
        ["vPosition"]=
        {
            [1]=-3.1,
            [2]=102.2,
            [3]=159.5
        },
        ["vRotation"]=
        {
            [1]=0,
            [2]=0,
            [3]=0
        },
        ["szIconPath"]="Texture/NieLian/Environment/环境预设_绿.png",
        ["szEffectPath"]="data/source/other/HD特效/其他/Pss/D_登录背景_氛围绿01.pss",
        ["szPresetName"]="测试_紫"
    },
    [5]=
    {
        ["nIndex"]=5,
        ["vScale"]=
        {
            [1]=1,
            [2]=1,
            [3]=1
        },
        ["vPosition"]=
        {
            [1]=29.2,
            [2]=43,
            [3]=217.1
        },
        ["vRotation"]=
        {
            [1]=0,
            [2]=0,
            [3]=0
        },
        ["szIconPath"]="Texture/NieLian/Environment/环境预设_紫.png",
        ["szEffectPath"]="data/source/other/HD特效/其他/Pss/D_登录背景_星河紫01.pss",
        ["szPresetName"]="测试_绿"
    },
    [6]=
    {
        ["nIndex"]=6,
        ["vScale"]=
        {
            [1]=0.3,
            [2]=0.3,
            [3]=0.3
        },
        ["vPosition"]=
        {
            [1]=133419,
            [2]=4743,
            [3]=36024
        },
        ["vRotation"]=
        {
            [1]=0,
            [2]=-71.5,
            [3]=0
        },
        ["szIconPath"]="Texture/NieLian/Environment/环境预设_灰.png",
        ["szEffectPath"]="",
        ["szPresetName"]="测试_灰"
    },
    [7]=
    {
        ["nIndex"]=7,
        ["vScale"]=
        {
            [1]=0.324,
            [2]=0.324,
            [3]=0.324
        },
        ["vPosition"]=
        {
            [1]=-5.5,
            [2]=59,
            [3]=61.6
        },
        ["vRotation"]=
        {
            [1]=0,
            [2]=0,
            [3]=0
        },
        ["szIconPath"]="Texture/NieLian/Environment/环境预设_默认.png",
        ["szEffectPath"]="data/source/other/HD特效/其他/Pss/D_登录背景_落花_粉02.pss",
        ["szPresetName"]="测试_门派"
    },
    [8]=
    {
        ["nIndex"]=8,
        ["vScale"]=
        {
            [1]=0.45,
            [2]=0.45,
            [3]=0.45
        },
        ["vPosition"]=
        {
            [1]=-53.2,
            [2]=-2.1,
            [3]=5
        },
        ["vRotation"]=
        {
            [1]=0,
            [2]=0,
            [3]=0
        },
        ["szIconPath"]="Texture/NieLian/Environment/环境预设_默认.png",
        ["szEffectPath"]="data/source/other/HD特效/其他/Pss/D_登录背景_地面花_粉02.pss",
        ["szPresetName"]="测试_门派"
    },
    [9]=
    {
        ["nIndex"]=9,
        ["vScale"]=
        {
            [1]=0.45,
            [2]=0.45,
            [3]=0.45
        },
        ["vPosition"]=
        {
            [1]=38.2,
            [2]=-2.1,
            [3]=5
        },
        ["vRotation"]=
        {
            [1]=0,
            [2]=-43.5,
            [3]=0
        },
        ["szIconPath"]="Texture/NieLian/Environment/环境预设_默认.png",
        ["szEffectPath"]="data/source/other/HD特效/其他/Pss/D_登录背景_地面花_粉02.pss",
        ["szPresetName"]="测试_门派"
    },
    [10]=
    {
        ["nIndex"]=10,
        ["vScale"]=
        {
            [1]=0.324,
            [2]=0.324,
            [3]=0.324
        },
        ["vPosition"]=
        {
            [1]=-5.5,
            [2]=59,
            [3]=61.6
        },
        ["vRotation"]=
        {
            [1]=0,
            [2]=0,
            [3]=0
        },
        ["szIconPath"]="Texture/NieLian/Environment/环境预设_默认.png",
        ["szEffectPath"]="data/source/other/HD特效/其他/Pss/D_登录背景_落花_粉02.pss",
        ["szPresetName"]="测试_默认"
    },
    [11]=
    {
        ["nIndex"]=11,
        ["vScale"]=
        {
            [1]=0.45,
            [2]=0.45,
            [3]=0.45
        },
        ["vPosition"]=
        {
            [1]=-53.2,
            [2]=-2.1,
            [3]=5
        },
        ["vRotation"]=
        {
            [1]=0,
            [2]=0,
            [3]=0
        },
        ["szIconPath"]="Texture/NieLian/Environment/环境预设_默认.png",
        ["szEffectPath"]="data/source/other/HD特效/其他/Pss/D_登录背景_地面花_粉02.pss",
        ["szPresetName"]="测试_默认"
    },
    [12]=
    {
        ["nIndex"]=12,
        ["vScale"]=
        {
            [1]=0.45,
            [2]=0.45,
            [3]=0.45
        },
        ["vPosition"]=
        {
            [1]=38.2,
            [2]=-2.1,
            [3]=5
        },
        ["vRotation"]=
        {
            [1]=0,
            [2]=-43.5,
            [3]=0
        },
        ["szIconPath"]="Texture/NieLian/Environment/环境预设_默认.png",
        ["szEffectPath"]="data/source/other/HD特效/其他/Pss/D_登录背景_地面花_粉02.pss",
        ["szPresetName"]="测试_默认"
    }
}
