--*************************************** 工具生成 ***************************************
UIMiddleMapIconTab = 
{
    [1]=
    {
        [1]=
        {
            ["nID"]=1,
            ["nType"]=1,
            ["nIndex"]=1,
            ["szFrame"]="UIAtlas2_Map_MapIcon_icon_mineral.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [2]=
        {
            ["nID"]=2,
            ["nType"]=1,
            ["nIndex"]=2,
            ["szFrame"]="UIAtlas2_Map_MapIcon_icon_herb.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [3]=
        {
            ["nID"]=3,
            ["nType"]=1,
            ["nIndex"]=3,
            ["szFrame"]="UIAtlas2_Map_MapIcon_icon_meat.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        }
    },
    [2]=
    {
        [1]=
        {
            ["nID"]=1,
            ["nType"]=2,
            ["nIndex"]=4,
            ["szFrame"]="UIAtlas2_Map_MapIcon_icon_kuang.png",
            ["szBgFrame"]="UIAtlas2_Map_MapIcon_icon_zidingyiBg",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [2]=
        {
            ["nID"]=2,
            ["nType"]=2,
            ["nIndex"]=5,
            ["szFrame"]="UIAtlas2_Map_MapIcon_icon_caoyao.png",
            ["szBgFrame"]="UIAtlas2_Map_MapIcon_icon_zidingyiBg",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [3]=
        {
            ["nID"]=3,
            ["nType"]=2,
            ["nIndex"]=6,
            ["szFrame"]="UIAtlas2_Map_MapIcon_icon_yuanbao.png",
            ["szBgFrame"]="UIAtlas2_Map_MapIcon_icon_zidingyiBg",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [4]=
        {
            ["nID"]=4,
            ["nType"]=2,
            ["nIndex"]=7,
            ["szFrame"]="UIAtlas2_Map_MapIcon_icon_qizi.png",
            ["szBgFrame"]="UIAtlas2_Map_MapIcon_icon_zidingyiBg",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [5]=
        {
            ["nID"]=5,
            ["nType"]=2,
            ["nIndex"]=8,
            ["szFrame"]="UIAtlas2_Map_MapIcon_icon_hu.png",
            ["szBgFrame"]="UIAtlas2_Map_MapIcon_icon_zidingyiBg",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [6]=
        {
            ["nID"]=6,
            ["nType"]=2,
            ["nIndex"]=9,
            ["szFrame"]="UIAtlas2_Map_MapIcon_icon_baoxiang.png",
            ["szBgFrame"]="UIAtlas2_Map_MapIcon_icon_zidingyiBg",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [7]=
        {
            ["nID"]=7,
            ["nType"]=2,
            ["nIndex"]=10,
            ["szFrame"]="UIAtlas2_Map_MapIcon_icon_qizi.png",
            ["szBgFrame"]="UIAtlas2_Map_MapIcon_icon_zidingyiBg",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [8]=
        {
            ["nID"]=8,
            ["nType"]=2,
            ["nIndex"]=11,
            ["szFrame"]="UIAtlas2_Map_MapIcon_img_icon_team.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        }
    },
    [3]=
    {
        [1]=
        {
            ["nID"]=1,
            ["nType"]=3,
            ["nIndex"]=12,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_renwu_cheng.png",
            ["szBgFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_MapIconBg6.png",
            ["nQuestType"]=1,
            ["nQuestState"]=1,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [2]=
        {
            ["nID"]=2,
            ["nType"]=3,
            ["nIndex"]=13,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_renwuWC_cheng.png",
            ["szBgFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_MapIconBg6.png",
            ["nQuestType"]=1,
            ["nQuestState"]=2,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [3]=
        {
            ["nID"]=3,
            ["nType"]=3,
            ["nIndex"]=14,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_renwu_zi.png",
            ["szBgFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_MapIconBg4.png",
            ["nQuestType"]=2,
            ["nQuestState"]=1,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [4]=
        {
            ["nID"]=4,
            ["nType"]=3,
            ["nIndex"]=15,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_renwuWC_zi.png",
            ["szBgFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_MapIconBg4.png",
            ["nQuestType"]=2,
            ["nQuestState"]=2,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [5]=
        {
            ["nID"]=5,
            ["nType"]=3,
            ["nIndex"]=16,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_renwu_lan.png",
            ["szBgFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_MapIconBg3.png",
            ["nQuestType"]=3,
            ["nQuestState"]=1,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [6]=
        {
            ["nID"]=6,
            ["nType"]=3,
            ["nIndex"]=17,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_renwuWC_lan.png",
            ["szBgFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_MapIconBg3.png",
            ["nQuestType"]=3,
            ["nQuestState"]=2,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [7]=
        {
            ["nID"]=7,
            ["nType"]=3,
            ["nIndex"]=18,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_renwu_hui.png",
            ["szBgFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_MapIconBg1.png",
            ["nQuestType"]=4,
            ["nQuestState"]=1,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [8]=
        {
            ["nID"]=8,
            ["nType"]=3,
            ["nIndex"]=19,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_renwuWC_hui.png",
            ["szBgFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_MapIconBg1.png",
            ["nQuestType"]=4,
            ["nQuestState"]=2,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [9]=
        {
            ["nID"]=9,
            ["nType"]=3,
            ["nIndex"]=20,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_renwu_huang.png",
            ["szBgFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_MapIconBg5.png",
            ["nQuestType"]=5,
            ["nQuestState"]=1,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        },
        [10]=
        {
            ["nID"]=10,
            ["nType"]=3,
            ["nIndex"]=21,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_renwuWC_huang.png",
            ["szBgFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_MapIconBg5.png",
            ["nQuestType"]=5,
            ["nQuestState"]=2,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]=""
        }
    },
    [4]=
    {
        [1]=
        {
            ["nID"]=1,
            ["nType"]=4,
            ["nIndex"]=22,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_shenxing1.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]="地图内交通"
        },
        [2]=
        {
            ["nID"]=2,
            ["nType"]=4,
            ["nIndex"]=23,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_shenxing2.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=0,
            ["nNpcCatalogueCommnet"]="跨地图交通"
        },
        [3]=
        {
            ["nID"]=3,
            ["nType"]=4,
            ["nIndex"]=24,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="材料供应商"
        },
        [4]=
        {
            ["nID"]=4,
            ["nType"]=4,
            ["nIndex"]=25,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_img_CangKu.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=4,
            ["nNpcCatalogueCommnet"]="仓库"
        },
        [5]=
        {
            ["nID"]=5,
            ["nType"]=4,
            ["nIndex"]=26,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_messenger.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=2,
            ["nNpcCatalogueCommnet"]="信使"
        },
        [6]=
        {
            ["nID"]=6,
            ["nType"]=4,
            ["nIndex"]=27,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="交易师"
        },
        [7]=
        {
            ["nID"]=7,
            ["nType"]=4,
            ["nIndex"]=28,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="马匹与饲料商"
        },
        [8]=
        {
            ["nID"]=8,
            ["nType"]=4,
            ["nIndex"]=29,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="门派技能训练师"
        },
        [9]=
        {
            ["nID"]=9,
            ["nType"]=4,
            ["nIndex"]=30,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="技艺训练师"
        },
        [10]=
        {
            ["nID"]=10,
            ["nType"]=4,
            ["nIndex"]=31,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="门派掌门"
        },
        [11]=
        {
            ["nID"]=11,
            ["nType"]=4,
            ["nIndex"]=32,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_wanfa.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=3,
            ["nNpcCatalogueCommnet"]="茶馆任务"
        },
        [12]=
        {
            ["nID"]=12,
            ["nType"]=4,
            ["nIndex"]=33,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_wanfa.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=3,
            ["nNpcCatalogueCommnet"]="秘境接引人"
        },
        [13]=
        {
            ["nID"]=13,
            ["nType"]=4,
            ["nIndex"]=34,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="稀有物品商人"
        },
        [14]=
        {
            ["nID"]=14,
            ["nType"]=4,
            ["nIndex"]=35,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_wanfa.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=3,
            ["nNpcCatalogueCommnet"]="活动"
        },
        [15]=
        {
            ["nID"]=15,
            ["nType"]=4,
            ["nIndex"]=36,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="江湖贡献商"
        },
        [16]=
        {
            ["nID"]=16,
            ["nType"]=4,
            ["nIndex"]=37,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="拜师堂"
        },
        [17]=
        {
            ["nID"]=17,
            ["nType"]=4,
            ["nIndex"]=38,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="帮会"
        },
        [18]=
        {
            ["nID"]=18,
            ["nType"]=4,
            ["nIndex"]=39,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_img_CangKu.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=4,
            ["nNpcCatalogueCommnet"]="帮会仓库"
        },
        [19]=
        {
            ["nID"]=19,
            ["nType"]=4,
            ["nIndex"]=40,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="帮会物资商"
        },
        [20]=
        {
            ["nID"]=20,
            ["nType"]=4,
            ["nIndex"]=41,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="套装商"
        },
        [21]=
        {
            ["nID"]=21,
            ["nType"]=4,
            ["nIndex"]=42,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_wanfa.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=3,
            ["nNpcCatalogueCommnet"]="日常任务"
        },
        [22]=
        {
            ["nID"]=22,
            ["nType"]=4,
            ["nIndex"]=43,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="声望商"
        },
        [23]=
        {
            ["nID"]=23,
            ["nType"]=4,
            ["nIndex"]=44,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="食品商"
        },
        [24]=
        {
            ["nID"]=24,
            ["nType"]=4,
            ["nIndex"]=45,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="阅读与书籍"
        },
        [25]=
        {
            ["nID"]=25,
            ["nType"]=4,
            ["nIndex"]=46,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="杂货商"
        },
        [26]=
        {
            ["nID"]=26,
            ["nType"]=4,
            ["nIndex"]=47,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="新手门派接引人"
        },
        [27]=
        {
            ["nID"]=27,
            ["nType"]=4,
            ["nIndex"]=48,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="门派阵营接引人"
        },
        [28]=
        {
            ["nID"]=28,
            ["nType"]=4,
            ["nIndex"]=49,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="新手武学训练师"
        },
        [29]=
        {
            ["nID"]=29,
            ["nType"]=4,
            ["nIndex"]=50,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="第二门派训练师"
        },
        [30]=
        {
            ["nID"]=30,
            ["nType"]=4,
            ["nIndex"]=51,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_wanfa.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=3,
            ["nNpcCatalogueCommnet"]="阵营与战场"
        },
        [31]=
        {
            ["nID"]=31,
            ["nType"]=4,
            ["nIndex"]=52,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_wanfa.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=3,
            ["nNpcCatalogueCommnet"]="阵营日常"
        },
        [32]=
        {
            ["nID"]=32,
            ["nType"]=4,
            ["nIndex"]=53,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="秘笈书库"
        },
        [33]=
        {
            ["nID"]=33,
            ["nType"]=4,
            ["nIndex"]=54,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_wanfa.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=3,
            ["nNpcCatalogueCommnet"]="名剑大会"
        },
        [34]=
        {
            ["nID"]=34,
            ["nType"]=4,
            ["nIndex"]=55,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="其他商人"
        },
        [35]=
        {
            ["nID"]=35,
            ["nType"]=4,
            ["nIndex"]=56,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_wanfa.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=3,
            ["nNpcCatalogueCommnet"]="试炼之地接引人"
        },
        [36]=
        {
            ["nID"]=36,
            ["nType"]=4,
            ["nIndex"]=57,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="天工树管理员"
        },
        [37]=
        {
            ["nID"]=37,
            ["nType"]=4,
            ["nIndex"]=58,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="装备商"
        },
        [38]=
        {
            ["nID"]=38,
            ["nType"]=4,
            ["nIndex"]=59,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="门派换线人"
        },
        [39]=
        {
            ["nID"]=39,
            ["nType"]=4,
            ["nIndex"]=60,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="新手村换线人"
        },
        [40]=
        {
            ["nID"]=40,
            ["nType"]=4,
            ["nIndex"]=61,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="任务NPC"
        },
        [41]=
        {
            ["nID"]=41,
            ["nType"]=4,
            ["nIndex"]=62,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="宝物商人"
        },
        [42]=
        {
            ["nID"]=42,
            ["nType"]=4,
            ["nIndex"]=63,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="种子商"
        },
        [43]=
        {
            ["nID"]=43,
            ["nType"]=4,
            ["nIndex"]=64,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="钓鱼商"
        },
        [44]=
        {
            ["nID"]=44,
            ["nType"]=4,
            ["nIndex"]=65,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="仙人指路"
        },
        [45]=
        {
            ["nID"]=45,
            ["nType"]=4,
            ["nIndex"]=66,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="花盆商"
        },
        [46]=
        {
            ["nID"]=46,
            ["nType"]=4,
            ["nIndex"]=67,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="牌匾商"
        },
        [47]=
        {
            ["nID"]=47,
            ["nType"]=4,
            ["nIndex"]=68,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="奇宝商人"
        },
        [48]=
        {
            ["nID"]=48,
            ["nType"]=4,
            ["nIndex"]=69,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="兽医"
        },
        [49]=
        {
            ["nID"]=49,
            ["nType"]=4,
            ["nIndex"]=70,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="战旗商人"
        },
        [50]=
        {
            ["nID"]=50,
            ["nType"]=4,
            ["nIndex"]=71,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="过往场景接引人"
        },
        [51]=
        {
            ["nID"]=51,
            ["nType"]=4,
            ["nIndex"]=72,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_beiming.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=3,
            ["nNpcCatalogueCommnet"]="碑铭"
        },
        [54]=
        {
            ["nID"]=54,
            ["nType"]=4,
            ["nIndex"]=73,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="门派大师兄"
        },
        [55]=
        {
            ["nID"]=55,
            ["nType"]=4,
            ["nIndex"]=74,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="秘境镖局接引人"
        },
        [56]=
        {
            ["nID"]=56,
            ["nType"]=4,
            ["nIndex"]=75,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="天街灯市接引人"
        },
        [57]=
        {
            ["nID"]=57,
            ["nType"]=4,
            ["nIndex"]=76,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="说书人"
        },
        [58]=
        {
            ["nID"]=58,
            ["nType"]=4,
            ["nIndex"]=77,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_wanfa.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=3,
            ["nNpcCatalogueCommnet"]="阵营复活点"
        },
        [59]=
        {
            ["nID"]=59,
            ["nType"]=4,
            ["nIndex"]=78,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_wanfa.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=3,
            ["nNpcCatalogueCommnet"]="飞火论锋接引人"
        },
        [60]=
        {
            ["nID"]=60,
            ["nType"]=4,
            ["nIndex"]=79,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="万宝楼执事"
        },
        [61]=
        {
            ["nID"]=61,
            ["nType"]=4,
            ["nIndex"]=80,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_wanfa.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=3,
            ["nNpcCatalogueCommnet"]="家园"
        },
        [62]=
        {
            ["nID"]=62,
            ["nType"]=4,
            ["nIndex"]=81,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="收花人"
        },
        [63]=
        {
            ["nID"]=63,
            ["nType"]=4,
            ["nIndex"]=82,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="家具商"
        },
        [64]=
        {
            ["nID"]=64,
            ["nType"]=4,
            ["nIndex"]=83,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="内宅舍管事"
        },
        [65]=
        {
            ["nID"]=65,
            ["nType"]=4,
            ["nIndex"]=84,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="居业行管事"
        },
        [66]=
        {
            ["nID"]=66,
            ["nType"]=4,
            ["nIndex"]=85,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_else.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="接引人"
        },
        [67]=
        {
            ["nID"]=67,
            ["nType"]=4,
            ["nIndex"]=86,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="侠行点商人"
        },
        [68]=
        {
            ["nID"]=68,
            ["nType"]=4,
            ["nIndex"]=87,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_qiyu.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=3,
            ["nNpcCatalogueCommnet"]="宠物奇遇"
        },
        [73]=
        {
            ["nID"]=73,
            ["nType"]=4,
            ["nIndex"]=88,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_messenger.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=2,
            ["nNpcCatalogueCommnet"]="信使(名望等级7解锁)"
        },
        [74]=
        {
            ["nID"]=74,
            ["nType"]=4,
            ["nIndex"]=89,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_img_CangKu.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=4,
            ["nNpcCatalogueCommnet"]="仓库(名望等级7解锁)"
        },
        [75]=
        {
            ["nID"]=75,
            ["nType"]=4,
            ["nIndex"]=90,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="交易师(名望等级11解锁)"
        },
        [76]=
        {
            ["nID"]=76,
            ["nType"]=4,
            ["nIndex"]=91,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_wanfa.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=3,
            ["nNpcCatalogueCommnet"]="试炼之地(名望等级11解锁)"
        },
        [77]=
        {
            ["nID"]=77,
            ["nType"]=4,
            ["nIndex"]=92,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_icon_cave.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="洞穴出入口"
        },
        [78]=
        {
            ["nID"]=78,
            ["nType"]=4,
            ["nIndex"]=93,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="五行石商人(名望等级35解锁)"
        },
        [79]=
        {
            ["nID"]=79,
            ["nType"]=4,
            ["nIndex"]=94,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_btn_merchant.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=1,
            ["nNpcCatalogueCommnet"]="名望商人"
        },
        [90]=
        {
            ["nID"]=90,
            ["nType"]=4,
            ["nIndex"]=95,
            ["szFrame"]="UIAtlas2_Public_PublicIcon_PublicIcon1_img_Boss.png",
            ["szBgFrame"]="",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="通用BOSS"
        },
        [91]=
        {
            ["nID"]=91,
            ["nType"]=4,
            ["nIndex"]=96,
            ["szFrame"]="UIAtlas2_Map_MapButton_btn_boss2.png",
            ["szBgFrame"]="UIAtlas2_Map_MapButton_btn_boss2_bg.png",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="自动寻路BOSS打之前"
        },
        [92]=
        {
            ["nID"]=92,
            ["nType"]=4,
            ["nIndex"]=97,
            ["szFrame"]="UIAtlas2_Map_MapButton_btn_boss.png",
            ["szBgFrame"]="UIAtlas2_Map_MapButton_btn_boss_bg.png",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="自动寻路BOSS打之后"
        },
        [93]=
        {
            ["nID"]=93,
            ["nType"]=4,
            ["nIndex"]=98,
            ["szFrame"]="UIAtlas2_Map_MapButton_btn_boss4.png",
            ["szBgFrame"]="UIAtlas2_Map_MapButton_btn_boss2_bg.png",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="自动寻路关卡打之前"
        },
        [94]=
        {
            ["nID"]=94,
            ["nType"]=4,
            ["nIndex"]=99,
            ["szFrame"]="UIAtlas2_Map_MapButton_btn_boss3.png",
            ["szBgFrame"]="UIAtlas2_Map_MapButton_btn_boss_bg.png",
            ["nQuestType"]=0,
            ["nQuestState"]=0,
            ["nNpcCatalogue"]=5,
            ["nNpcCatalogueCommnet"]="自动寻路关卡打之后"
        }
    }
}
