--*************************************** 工具生成 ***************************************
UINameCardTab = 
{
    [0]=
    {
        ["nID"]=0,
        ["szName"]="纸笺·空白",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_xxx.png"
    },
    [1]=
    {
        ["nID"]=1,
        ["szName"]="纸笺·小玩意",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_xiaowanyier.png"
    },
    [2]=
    {
        ["nID"]=2,
        ["szName"]="纸笺·时尚称号",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_shishangchenghao.png"
    },
    [3]=
    {
        ["nID"]=3,
        ["szName"]="纸笺·萌宠",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_mengchong.png"
    },
    [4]=
    {
        ["nID"]=4,
        ["szName"]="纸笺·名剑大会",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_mingjiandahui.png"
    },
    [5]=
    {
        ["nID"]=5,
        ["szName"]="纸笺·蜃海渊",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_shenhaiyuan.png"
    },
    [6]=
    {
        ["nID"]=6,
        ["szName"]="纸笺·叠银岭",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_dieyinling.png"
    },
    [7]=
    {
        ["nID"]=7,
        ["szName"]="纸笺·华裳",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_huachang.png"
    },
    [8]=
    {
        ["nID"]=8,
        ["szName"]="纸笺·隐元秘鉴",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_yinyuanmijian.png"
    },
    [9]=
    {
        ["nID"]=9,
        ["szName"]="纸笺·奇趣坐骑",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_qiquzuoqi.png"
    },
    [10]=
    {
        ["nID"]=10,
        ["szName"]="纸笺·薰风渡",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_xunfengdu.png"
    },
    [11]=
    {
        ["nID"]=11,
        ["szName"]="纸笺·冰雪逐梦",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_bingxuezhumeng.png"
    },
    [12]=
    {
        ["nID"]=12,
        ["szName"]="纸笺·玉樽",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_yuzun.png"
    },
    [13]=
    {
        ["nID"]=13,
        ["szName"]="纸笺·金丝",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_jinsi.png"
    },
    [14]=
    {
        ["nID"]=14,
        ["szName"]="纸笺·朱凤",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_zhufeng.png"
    },
    [15]=
    {
        ["nID"]=15,
        ["szName"]="纸笺·出云岭",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_chuyunling.png"
    },
    [16]=
    {
        ["nID"]=16,
        ["szName"]="纸笺·千灯胜境",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_qiandengshengjing.png"
    },
    [17]=
    {
        ["nID"]=17,
        ["szName"]="纸笺·霜枫岭",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_shuangfengling.png"
    },
    [18]=
    {
        ["nID"]=18,
        ["szName"]="纸笺·明宵灯暖",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_mingxiaodengnuan.png"
    },
    [19]=
    {
        ["nID"]=19,
        ["szName"]="纸笺·沙海吟风",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_shahaiyinfeng.png"
    },
    [20]=
    {
        ["nID"]=20,
        ["szName"]="纸笺·武陵源",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_wulingyuan.png"
    },
    [21]=
    {
        ["nID"]=21,
        ["szName"]="纸笺·重霄阆苑",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_chongxiaolangyuan.png"
    },
    [22]=
    {
        ["nID"]=22,
        ["szName"]="纸笺·幽隐乡",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_youyinxiang.png"
    },
    [23]=
    {
        ["nID"]=23,
        ["szName"]="纸笺·翡翠宫下",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_feicuigongxia.png"
    },
    [24]=
    {
        ["nID"]=24,
        ["szName"]="纸笺·丹丘闲居",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_danqiuxianju.png"
    },
    [25]=
    {
        ["nID"]=25,
        ["szName"]="纸笺·西湖",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_xihu.png"
    },
    [26]=
    {
        ["nID"]=26,
        ["szName"]="纸笺·机关城",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_jiguancheng.png"
    },
    [27]=
    {
        ["nID"]=27,
        ["szName"]="纸笺·繁花",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_fanhua.png"
    },
    [28]=
    {
        ["nID"]=28,
        ["szName"]="纸笺·生花笔",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_shenghuabi.png"
    },
    [29]=
    {
        ["nID"]=29,
        ["szName"]="纸笺·争锋令",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_BangHui.png"
    },
    [30]=
    {
        ["nID"]=30,
        ["szName"]="纸笺·雪岭镜湖",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_xuelingjinghu.png"
    },
    [31]=
    {
        ["nID"]=31,
        ["szName"]="纸笺·苍龙蛰渊",
        ["szVisitCardPath"]="Resource/NameCardSkin/img_skin_CangLongZheYuan.png"
    }	
}
