--*************************************** 工具生成 ***************************************
UIPQAtrriubuteShowTab = 
{
    [266]=
    {
        ["PQID"]=266,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [267]=
    {
        ["PQID"]=267,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [268]=
    {
        ["PQID"]=268,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [269]=
    {
        ["PQID"]=269,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [270]=
    {
        ["PQID"]=270,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [271]=
    {
        ["PQID"]=271,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [272]=
    {
        ["PQID"]=272,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [273]=
    {
        ["PQID"]=273,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [274]=
    {
        ["PQID"]=274,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [275]=
    {
        ["PQID"]=275,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [276]=
    {
        ["PQID"]=276,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [277]=
    {
        ["PQID"]=277,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [278]=
    {
        ["PQID"]=278,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [279]=
    {
        ["PQID"]=279,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [280]=
    {
        ["PQID"]=280,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [281]=
    {
        ["PQID"]=281,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [282]=
    {
        ["PQID"]=282,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [283]=
    {
        ["PQID"]=283,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [284]=
    {
        ["PQID"]=284,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [285]=
    {
        ["PQID"]=285,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [350]=
    {
        ["PQID"]=350,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [351]=
    {
        ["PQID"]=351,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [352]=
    {
        ["PQID"]=352,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [353]=
    {
        ["PQID"]=353,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [354]=
    {
        ["PQID"]=354,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [355]=
    {
        ["PQID"]=355,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [356]=
    {
        ["PQID"]=356,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [357]=
    {
        ["PQID"]=357,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [358]=
    {
        ["PQID"]=358,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [359]=
    {
        ["PQID"]=359,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [360]=
    {
        ["PQID"]=360,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [361]=
    {
        ["PQID"]=361,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [362]=
    {
        ["PQID"]=362,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [363]=
    {
        ["PQID"]=363,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [364]=
    {
        ["PQID"]=364,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [365]=
    {
        ["PQID"]=365,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [366]=
    {
        ["PQID"]=366,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [367]=
    {
        ["PQID"]=367,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [368]=
    {
        ["PQID"]=368,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [369]=
    {
        ["PQID"]=369,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [370]=
    {
        ["PQID"]=370,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [371]=
    {
        ["PQID"]=371,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [372]=
    {
        ["PQID"]=372,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [373]=
    {
        ["PQID"]=373,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [374]=
    {
        ["PQID"]=374,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [375]=
    {
        ["PQID"]=375,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [377]=
    {
        ["PQID"]=377,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    },
    [378]=
    {
        ["PQID"]=378,
        ["ShowSubText"]=true,
        ["ShowMainText"]=true,
        ["ShowSubTitle"]=false
    }
}
