--*************************************** 工具生成 ***************************************
UIRoadChivalrousTab = 
{
    [1]=
    {
        ["IconID"]=1,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg1",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg1",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1"
    },
    [2]=
    {
        ["IconID"]=2,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg2",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg2",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2"
    },
    [3]=
    {
        ["IconID"]=3,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg2",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg2",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2"
    },
    [4]=
    {
        ["IconID"]=4,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg1",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg1",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1"
    },
    [5]=
    {
        ["IconID"]=5,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg3",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg3",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg3",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg3"
    },
    [6]=
    {
        ["IconID"]=6,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg1",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg1",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1"
    },
    [7]=
    {
        ["IconID"]=7,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg1",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg1",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1"
    },
    [8]=
    {
        ["IconID"]=8,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg2",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg2",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2"
    },
    [9]=
    {
        ["IconID"]=9,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg2",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg2",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2"
    },
    [10]=
    {
        ["IconID"]=10,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg3",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg3",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg3",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg3"
    },
    [11]=
    {
        ["IconID"]=11,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg3",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg3",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg3",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg3"
    },
    [12]=
    {
        ["IconID"]=12,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg2",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg2",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2"
    },
    [13]=
    {
        ["IconID"]=13,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg3",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg3",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg3",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg3"
    },
    [14]=
    {
        ["IconID"]=14,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg1",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg1",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1"
    },
    [15]=
    {
        ["IconID"]=15,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg1",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg1",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1"
    },
    [16]=
    {
        ["IconID"]=16,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg2",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg2",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2"
    },
    [17]=
    {
        ["IconID"]=17,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg2",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg2",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2"
    },
    [18]=
    {
        ["IconID"]=18,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg2",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg2",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2"
    },
    [19]=
    {
        ["IconID"]=19,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg2",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg2",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2"
    },
    [20]=
    {
        ["IconID"]=20,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg2",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg2",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2"
    },
    [21]=
    {
        ["IconID"]=21,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg2",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg2",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2"
    },
    [22]=
    {
        ["IconID"]=22,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg1",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg1",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1"
    },
    [23]=
    {
        ["IconID"]=23,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg1",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg1",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg1"
    },
    [24]=
    {
        ["IconID"]=24,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg2",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg2",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2"
    },
    [25]=
    {
        ["IconID"]=25,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg2",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg2",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2"
    },
    [26]=
    {
        ["IconID"]=26,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg2",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg2",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2"
    },
    [27]=
    {
        ["IconID"]=27,
        ["NormalPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2",
        ["InActivePath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotLockedBg2",
        ["GotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotAquiredBg2",
        ["NotRewardPath"]="UIAtlas2_Task_RoadChivalrous_Img_KnotNormalBg2"
    }
}
