--*************************************** 工具生成 ***************************************
UISidePageViewTab = 
{
    [24]=
    {
        ["nID"]=1,
        ["bRight"]=true,
        ["nViewID"]=24,
        ["szHideAnim"]="AniRightHide2",
        ["szShowAnim"]="AniRightShow2",
        ["szViewName"]="主界面系统菜单"
    },
    [26]=
    {
        ["nID"]=2,
        ["bRight"]=true,
        ["nViewID"]=26,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="主界面气泡侧面弹窗"
    },
    [29]=
    {
        ["nID"]=37,
        ["bRight"]=false,
        ["nViewID"]=29,
        ["szHideAnim"]="AniLeftHide",
        ["szShowAnim"]="AniLeftShow",
        ["szViewName"]="编辑快捷栏"
    },
    [32]=
    {
        ["nID"]=3,
        ["bRight"]=true,
        ["nViewID"]=32,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="主界面快捷面板"
    },
    [33]=
    {
        ["nID"]=10,
        ["bRight"]=false,
        ["nViewID"]=33,
        ["szHideAnim"]="AniLeftHide",
        ["szShowAnim"]="AniLeftShow",
        ["szViewName"]="玩具箱"
    },
    [34]=
    {
        ["nID"]=8,
        ["bRight"]=false,
        ["nViewID"]=34,
        ["szHideAnim"]="AniLeftHide",
        ["szShowAnim"]="AniLeftShow",
        ["szViewName"]="挂件动作/动作表情"
    },
    [75]=
    {
        ["nID"]=45,
        ["bRight"]=true,
        ["nViewID"]=75,
        ["szHideAnim"]="AniBottomHide",
        ["szShowAnim"]="AniBottomShow",
        ["szViewName"]="装备推荐-云端配装方案"
    },
    [117]=
    {
        ["nID"]=9,
        ["bRight"]=true,
        ["nViewID"]=117,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="背包"
    },
    [120]=
    {
        ["nID"]=44,
        ["bRight"]=true,
        ["nViewID"]=120,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="背包"
    },
    [121]=
    {
        ["nID"]=26,
        ["bRight"]=false,
        ["nViewID"]=121,
        ["szHideAnim"]="AniLeftHide",
        ["szShowAnim"]="AniLeftShow",
        ["szViewName"]="仓库"
    },
    [173]=
    {
        ["nID"]=36,
        ["bRight"]=true,
        ["nViewID"]=173,
        ["szHideAnim"]="AniRightHide2",
        ["szShowAnim"]="AniRightShow2",
        ["szViewName"]="老对话面板"
    },
    [282]=
    {
        ["nID"]=17,
        ["bRight"]=true,
        ["nViewID"]=282,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="任务-大侠之路-右侧面板"
    },
    [284]=
    {
        ["nID"]=39,
        ["bRight"]=true,
        ["nViewID"]=284,
        ["szHideAnim"]="AniBottomHide",
        ["szShowAnim"]="AniBottomShow",
        ["szViewName"]="任务详情侧面板"
    },
    [308]=
    {
        ["nID"]=20,
        ["bRight"]=false,
        ["nViewID"]=308,
        ["szHideAnim"]="AniLeftHide",
        ["szShowAnim"]="AniLeftShow",
        ["szViewName"]="通用左侧背包侧面板"
    },
    [310]=
    {
        ["nID"]=29,
        ["bRight"]=true,
        ["nViewID"]=310,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="通用右侧背包侧面板"
    },
    [551]=
    {
        ["nID"]=6,
        ["bRight"]=false,
        ["nViewID"]=551,
        ["szHideAnim"]="AniLeftHide",
        ["szShowAnim"]="AniLeftShow",
        ["szViewName"]="聊天"
    },
    [555]=
    {
        ["nID"]=24,
        ["bRight"]=false,
        ["nViewID"]=555,
        ["szHideAnim"]="AniLeftHide",
        ["szShowAnim"]="AniLeftShow",
        ["szViewName"]="社交"
    },
    [556]=
    {
        ["nID"]=25,
        ["bRight"]=false,
        ["nViewID"]=556,
        ["szHideAnim"]="AniLeftHide",
        ["szShowAnim"]="AniLeftShow",
        ["szViewName"]="密聊"
    },
    [703]=
    {
        ["nID"]=4,
        ["bRight"]=true,
        ["nViewID"]=703,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="社交"
    },
    [861]=
    {
        ["nID"]=35,
        ["bRight"]=true,
        ["nViewID"]=861,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="团拍掉落列表"
    },
    [964]=
    {
        ["nID"]=18,
        ["bRight"]=false,
        ["nViewID"]=964,
        ["szHideAnim"]="AniLeftHide",
        ["szShowAnim"]="AniLeftShow",
        ["szViewName"]="商城-查找"
    },
    [965]=
    {
        ["nID"]=19,
        ["bRight"]=true,
        ["nViewID"]=965,
        ["szHideAnim"]="",
        ["szShowAnim"]="",
        ["szViewName"]="商城-筛选"
    },
    [966]=
    {
        ["nID"]=22,
        ["bRight"]=false,
        ["nViewID"]=966,
        ["szHideAnim"]="AniBottomHide",
        ["szShowAnim"]="AniBottomShow",
        ["szViewName"]="商城-捏脸细节调整"
    },
    [967]=
    {
        ["nID"]=21,
        ["bRight"]=false,
        ["nViewID"]=967,
        ["szHideAnim"]="AniBottomHide",
        ["szShowAnim"]="AniBottomShow",
        ["szViewName"]="商城-捏脸详情"
    },
    [968]=
    {
        ["nID"]=41,
        ["bRight"]=true,
        ["nViewID"]=968,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="捏脸码侧面板"
    },
    [973]=
    {
        ["nID"]=40,
        ["bRight"]=true,
        ["nViewID"]=973,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="体型码侧面板"
    },
    [1404]=
    {
        ["nID"]=28,
        ["bRight"]=false,
        ["nViewID"]=1404,
        ["szHideAnim"]="AniLeftHide",
        ["szShowAnim"]="AniLeftShow",
        ["szViewName"]="坐骑-马具包"
    },
    [1610]=
    {
        ["nID"]=43,
        ["bRight"]=true,
        ["nViewID"]=1610,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="地图成就"
    },
    [2051]=
    {
        ["nID"]=5,
        ["bRight"]=true,
        ["nViewID"]=2051,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="主界面侧面弹窗自定义头像"
    },
    [2832]=
    {
        ["nID"]=15,
        ["bRight"]=true,
        ["nViewID"]=2832,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="家园-结庐江湖-家具详情侧面板"
    },
    [2851]=
    {
        ["nID"]=16,
        ["bRight"]=true,
        ["nViewID"]=2851,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="家园-宅园会赛-右边弹窗"
    },
    [2905]=
    {
        ["nID"]=33,
        ["bRight"]=true,
        ["nViewID"]=2905,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="家园建造-分区管理侧面板"
    },
    [2906]=
    {
        ["nID"]=38,
        ["bRight"]=true,
        ["nViewID"]=2906,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="家园建造-分区解锁侧面板"
    },
    [2907]=
    {
        ["nID"]=31,
        ["bRight"]=false,
        ["nViewID"]=2907,
        ["szHideAnim"]="AniLeftHide",
        ["szShowAnim"]="AniLeftShow",
        ["szViewName"]="家园建造-设置侧面板"
    },
    [2908]=
    {
        ["nID"]=32,
        ["bRight"]=true,
        ["nViewID"]=2908,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="家园建造-已放置物件列表侧面板"
    },
    [2913]=
    {
        ["nID"]=34,
        ["bRight"]=true,
        ["nViewID"]=2913,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="家园建造-本地蓝图列表侧面板"
    },
    [2925]=
    {
        ["nID"]=23,
        ["bRight"]=true,
        ["nViewID"]=2925,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="家园-大唐家园-家园设计场"
    },
    [2951]=
    {
        ["nID"]=12,
        ["bRight"]=true,
        ["nViewID"]=2951,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="家园-大唐家园-定制购买-右边弹窗"
    },
    [2953]=
    {
        ["nID"]=13,
        ["bRight"]=true,
        ["nViewID"]=2953,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="家园-大唐家园-家园日志-右边弹窗"
    },
    [2955]=
    {
        ["nID"]=14,
        ["bRight"]=false,
        ["nViewID"]=2955,
        ["szHideAnim"]="AniLeftHide",
        ["szShowAnim"]="AniLeftShow",
        ["szViewName"]="家园-大唐家园-推荐排行榜"
    },
    [2956]=
    {
        ["nID"]=42,
        ["bRight"]=false,
        ["nViewID"]=2956,
        ["szHideAnim"]="AniLeftHide",
        ["szShowAnim"]="AniLeftShow",
        ["szViewName"]="家园-大唐家园-快捷购买"
    },
    [4007]=
    {
        ["nID"]=47,
        ["bRight"]=true,
        ["nViewID"]=4007,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="时光漫游"
    },
    [4014]=
    {
        ["nID"]=48,
        ["bRight"]=true,
        ["nViewID"]=4014,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="时光漫游_参数调整"
    },
    [4015]=
    {
        ["nID"]=49,
        ["bRight"]=true,
        ["nViewID"]=4015,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="时光漫游_覆盖原有预设的功能"
    },
    [4686]=
    {
        ["nID"]=27,
        ["bRight"]=true,
        ["nViewID"]=4686,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="家园-家园身份-小吃车-右边弹窗"
    },
    [5101]=
    {
        ["nID"]=30,
        ["bRight"]=true,
        ["nViewID"]=5101,
        ["szHideAnim"]="AniRightHide",
        ["szShowAnim"]="AniRightShow",
        ["szViewName"]="种花侧面板"
    },
    [5306]=
    {
        ["nID"]=46,
        ["bRight"]=true,
        ["nViewID"]=5306,
        ["szHideAnim"]="AniRightHide2",
        ["szShowAnim"]="AniRightShow2",
        ["szViewName"]="小游戏关卡选择侧面板"
    }
}
