--*************************************** 工具生成 ***************************************
UISystemMenuTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["szDesc"]="打开菜单界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="菜单",
        ["nGroupID"]=0,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelSystemMenu)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="Esc",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [2]=
    {
        ["nID"]=2,
        ["szDesc"]="打开外观商城界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam12.png",
        ["szImgBg"]="",
        ["szTitle"]="外观",
        ["nGroupID"]=1,
        ["szAction"]="CoinShopData.Open()",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=5,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="Shift+E",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [3]=
    {
        ["nID"]=3,
        ["szDesc"]="打开背包",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam2.png",
        ["szImgBg"]="",
        ["szTitle"]="背包",
        ["nGroupID"]=0,
        ["szAction"]="ItemData.OpenBag()",
        ["bHideSelf"]=false,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=4,
        ["szShortcutKey"]="B",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [4]=
    {
        ["nID"]=4,
        ["szDesc"]="打开武学界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam15.png",
        ["szImgBg"]="",
        ["szTitle"]="武学",
        ["nGroupID"]=1,
        ["szAction"]="SkillData.TryOpenPanelSkillNew()",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=2,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=1901,
            [2]=1905
        },
        ["nSystemOpenID"]=7,
        ["szShortcutKey"]="P",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [5]=
    {
        ["nID"]=5,
        ["szDesc"]="打开任务界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam11.png",
        ["szImgBg"]="",
        ["szTitle"]="任务",
        ["nGroupID"]=1,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelTask)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=4,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=3,
        ["szShortcutKey"]="L",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [6]=
    {
        ["nID"]=6,
        ["szDesc"]="打开活动界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam21.png",
        ["szImgBg"]="",
        ["szTitle"]="日历",
        ["nGroupID"]=3,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelActivityCalendar)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=7,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=3601
        },
        ["nSystemOpenID"]=1,
        ["szShortcutKey"]="Shift+C",
        ["bUseNewRedPoint"]=true,
        ["nNewFeatureAniType"]=0
    },
    [7]=
    {
        ["nID"]=7,
        ["szDesc"]="打开角色界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam8.png",
        ["szImgBg"]="",
        ["szTitle"]="角色",
        ["nGroupID"]=1,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelCharacter)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=1,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=5,
        ["szShortcutKey"]="C",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [8]=
    {
        ["nID"]=8,
        ["szDesc"]="打开秘境大全界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam9.png",
        ["szImgBg"]="",
        ["szTitle"]="秘境",
        ["nGroupID"]=2,
        ["szAction"]="CollectionData.OpenCollection(2)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=4,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=2,
        ["szShortcutKey"]="Shift+B",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=1
    },
    [9]=
    {
        ["nID"]=9,
        ["szDesc"]="打开竞技界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam25.png",
        ["szImgBg"]="",
        ["szTitle"]="竞技",
        ["nGroupID"]=2,
        ["szAction"]="CollectionData.OpenCollection(3)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=2,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=2601,
            [2]=3501,
            [3]=3502,
            [4]=3503
        },
        ["nSystemOpenID"]=44,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=1
    },
    [10]=
    {
        ["nID"]=10,
        ["szDesc"]="打开阵营界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam16.png",
        ["szImgBg"]="",
        ["szTitle"]="阵营",
        ["nGroupID"]=2,
        ["szAction"]="CollectionData.OpenCollection(4)",
        ["bHideSelf"]=false,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=3,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=2501,
            [2]=2502,
            [3]=4001,
            [4]=4002
        },
        ["nSystemOpenID"]=16,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=1
    },
    [11]=
    {
        ["nID"]=11,
        ["szDesc"]="打开绝境战场界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam24.png",
        ["szImgBg"]="",
        ["szTitle"]="绝境战场",
        ["nGroupID"]=0,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelImpasseMatching)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="Ctrl+L",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [12]=
    {
        ["nID"]=12,
        ["szDesc"]="打开社交界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam13.png",
        ["szImgBg"]="",
        ["szTitle"]="社交",
        ["nGroupID"]=0,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelChatSocial,2)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=12,
        ["szShortcutKey"]="O",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [13]=
    {
        ["nID"]=13,
        ["szDesc"]="打开家园界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam22.png",
        ["szImgBg"]="",
        ["szTitle"]="家园",
        ["nGroupID"]=2,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelHome)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=1,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=3803,
            [2]=3804
        },
        ["nSystemOpenID"]=15,
        ["szShortcutKey"]="Shift+M",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [14]=
    {
        ["nID"]=14,
        ["szDesc"]="打开帮会界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam1.png",
        ["szImgBg"]="",
        ["szTitle"]="帮会",
        ["nGroupID"]=3,
        ["szAction"]="TongData.OpenTongPanel()",
        ["bHideSelf"]=false,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=2,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=3001
        },
        ["nSystemOpenID"]=11,
        ["szShortcutKey"]="K",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=1
    },
    [15]=
    {
        ["nID"]=15,
        ["szDesc"]="打开坐骑界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam17.png",
        ["szImgBg"]="",
        ["szTitle"]="坐骑",
        ["nGroupID"]=1,
        ["szAction"]="Global.OpenHorsePanel()",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=7,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=1401,
            [2]=1402
        },
        ["nSystemOpenID"]=9,
        ["szShortcutKey"]="Shift+T",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [16]=
    {
        ["nID"]=16,
        ["szDesc"]="打开强化界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam10.png",
        ["szImgBg"]="",
        ["szTitle"]="强化",
        ["nGroupID"]=0,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelPowerUp)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=6,
        ["szShortcutKey"]="Shift+F",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [17]=
    {
        ["nID"]=17,
        ["szDesc"]="打开装备物资界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam30.png",
        ["szImgBg"]="",
        ["szTitle"]="商店",
        ["nGroupID"]=1,
        ["szAction"]="ShopData.ShortcutOpenSystemShop()",
        ["bHideSelf"]=false,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=6,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=4101
        },
        ["nSystemOpenID"]=13,
        ["szShortcutKey"]="Ctrl+B",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [18]=
    {
        ["nID"]=18,
        ["szDesc"]="打开隐元秘鉴界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam29.png",
        ["szImgBg"]="",
        ["szTitle"]="成就",
        ["nGroupID"]=3,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelAchievementMian)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=8,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="Y",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [19]=
    {
        ["nID"]=19,
        ["szDesc"]="打开宠物界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam5.png",
        ["szImgBg"]="",
        ["szTitle"]="宠物",
        ["nGroupID"]=3,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelPetMap)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=4,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=1501
        },
        ["nSystemOpenID"]=28,
        ["szShortcutKey"]="Ctrl+P",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [20]=
    {
        ["nID"]=20,
        ["szDesc"]="打开奇遇界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam27.png",
        ["szImgBg"]="",
        ["szTitle"]="奇遇",
        ["nGroupID"]=3,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelQiYu)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=3,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=29,
        ["szShortcutKey"]="Ctrl+J",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [21]=
    {
        ["nID"]=21,
        ["szDesc"]="打开风云录界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam18.png",
        ["szImgBg"]="",
        ["szTitle"]="风云录",
        ["nGroupID"]=3,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelFengYunLu)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=10,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=30,
        ["szShortcutKey"]="Ctrl+V",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [22]=
    {
        ["nID"]=22,
        ["szDesc"]="打开红尘侠影界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam20.png",
        ["szImgBg"]="",
        ["szTitle"]="侠影",
        ["nGroupID"]=1,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelPartner)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=8,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=3701,
            [2]=3702
        },
        ["nSystemOpenID"]=14,
        ["szShortcutKey"]="Ctrl+C",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [23]=
    {
        ["nID"]=23,
        ["szDesc"]="打开生活技艺界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam7.png",
        ["szImgBg"]="",
        ["szTitle"]="技艺",
        ["nGroupID"]=3,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelLifeMain)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=6,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=8,
        ["szShortcutKey"]="I",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [24]=
    {
        ["nID"]=24,
        ["szDesc"]="打开声望界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam14.png",
        ["szImgBg"]="",
        ["szTitle"]="声望",
        ["nGroupID"]=3,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelRenownList)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=12,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=36,
        ["szShortcutKey"]="Ctrl+R",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [25]=
    {
        ["nID"]=25,
        ["szDesc"]="打开名望界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam26.png",
        ["szImgBg"]="",
        ["szTitle"]="名望",
        ["nGroupID"]=3,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelFame)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=11,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=45,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [26]=
    {
        ["nID"]=26,
        ["szDesc"]="打开称号界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam3.png",
        ["szImgBg"]="",
        ["szTitle"]="称号",
        ["nGroupID"]=1,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelPersonalTitle)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=4,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=1301
        },
        ["nSystemOpenID"]=32,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [27]=
    {
        ["nID"]=27,
        ["szDesc"]="打开武林通鉴界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam28.png",
        ["szImgBg"]="",
        ["szTitle"]="武林通鉴",
        ["nGroupID"]=3,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelWuLinTongJian)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=9,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=2201
        },
        ["nSystemOpenID"]=22,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [28]=
    {
        ["nID"]=28,
        ["szDesc"]="打开江湖百态界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam23.png",
        ["szImgBg"]="",
        ["szTitle"]="江湖百态",
        ["nGroupID"]=3,
        ["szAction"]="JiangHuData.OnClickEntrance()",
        ["bHideSelf"]=false,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=13,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=23,
        ["szShortcutKey"]="Ctrl+K",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [29]=
    {
        ["nID"]=29,
        ["szDesc"]="打开个人生涯界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam19.png",
        ["szImgBg"]="",
        ["szTitle"]="个人生涯",
        ["nGroupID"]=3,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelCareer)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=14,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [30]=
    {
        ["nID"]=30,
        ["szDesc"]="打开地图界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="地图",
        ["nGroupID"]=0,
        ["szAction"]="MapMgr.OpenMiddleMap()",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="M",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [31]=
    {
        ["nID"]=31,
        ["szDesc"]="打开运营活动界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam6.png",
        ["szImgBg"]="",
        ["szTitle"]="花萼楼",
        ["nGroupID"]=0,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelOperationCenter)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="N",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [32]=
    {
        ["nID"]=32,
        ["szDesc"]="打开充值界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam4.png",
        ["szImgBg"]="",
        ["szTitle"]="充值",
        ["nGroupID"]=0,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelTopUpMain)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="Shift+R",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [33]=
    {
        ["nID"]=33,
        ["szDesc"]="打开帮助界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam33.png",
        ["szImgBg"]="",
        ["szTitle"]="帮助",
        ["nGroupID"]=0,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelTutorialCollection)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="Shift+H",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [34]=
    {
        ["nID"]=34,
        ["szDesc"]="打开师徒界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam32.png",
        ["szImgBg"]="",
        ["szTitle"]="师徒",
        ["nGroupID"]=3,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelApprenticeNew)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=1,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=3301
        },
        ["nSystemOpenID"]=12,
        ["szShortcutKey"]="U",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [35]=
    {
        ["nID"]=35,
        ["szDesc"]="打开阅读界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam31.png",
        ["szImgBg"]="",
        ["szTitle"]="阅读",
        ["nGroupID"]=3,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelReadMain)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=16,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=31,
        ["szShortcutKey"]="Alt+J",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [36]=
    {
        ["nID"]=36,
        ["szDesc"]="打开邮件界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_Btn7.png",
        ["szImgBg"]="",
        ["szTitle"]="邮件",
        ["nGroupID"]=0,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelEmail)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [37]=
    {
        ["nID"]=37,
        ["szDesc"]="打开武斗值界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam34.png",
        ["szImgBg"]="",
        ["szTitle"]="武斗",
        ["nGroupID"]=3,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelWuDou)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=15,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=47,
        ["szShortcutKey"]="Shift+G",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [38]=
    {
        ["nID"]=38,
        ["szDesc"]="打开设置界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="设置",
        ["nGroupID"]=0,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelGameSettings)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [39]=
    {
        ["nID"]=39,
        ["szDesc"]="打开聊天界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="聊天",
        ["nGroupID"]=0,
        ["szAction"]="ChatHelper.Chat()",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="Enter",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [40]=
    {
        ["nID"]=40,
        ["szDesc"]="打开快捷使用界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="快捷使用",
        ["nGroupID"]=0,
        ["szAction"]="Event.Dispatch(\"OnSwitchQuickUseTip\")",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="Shift+F1",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [41]=
    {
        ["nID"]=41,
        ["szDesc"]="打开快捷操作界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="快捷操作",
        ["nGroupID"]=0,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelQuickOperation)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="Shift+F2",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [42]=
    {
        ["nID"]=42,
        ["szDesc"]="打开队伍招募界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="队伍招募",
        ["nGroupID"]=0,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelTeam)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="Ctrl+T",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [43]=
    {
        ["nID"]=43,
        ["szDesc"]="打开战争沙盘界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="战争沙盘",
        ["nGroupID"]=0,
        ["szAction"]="CampData.OnClickCampMap()",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="Ctrl+M",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [44]=
    {
        ["nID"]=44,
        ["szDesc"]="打开名剑大会界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="名剑大会",
        ["nGroupID"]=0,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelPvPMatching,nil,2)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="Ctrl+A",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [45]=
    {
        ["nID"]=45,
        ["szDesc"]="打开幻境云图界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="幻境云图",
        ["nGroupID"]=0,
        ["szAction"]="Event.Dispatch(\"OpenCameraPanel\")",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="Ctrl+H",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [46]=
    {
        ["nID"]=46,
        ["szDesc"]="打开寻宝界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="寻宝",
        ["nGroupID"]=0,
        ["szAction"]="APIHelper.TreasureHunting(not APIHelper.TreasureHuntingCheck())",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=25,
        ["szShortcutKey"]="Alt+H",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [47]=
    {
        ["nID"]=47,
        ["szDesc"]="打开驯养界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="驯养",
        ["nGroupID"]=0,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelLifePage, {nDefaultCraftPanel = CRAFT_PANEL.Demosticate,})",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=8,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [48]=
    {
        ["nID"]=48,
        ["szDesc"]="打开外观预设界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="外观预设",
        ["nGroupID"]=0,
        ["szAction"]="Event.Dispatch(\"EVENT_LINK_NOTIFY\", \"CoinShopMy/Outfit\")",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="Ctrl+E",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [49]=
    {
        ["nID"]=49,
        ["szDesc"]="打开千里伐逐界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="千里伐逐",
        ["nGroupID"]=0,
        ["szAction"]="CampData.OnClickCampPVPField()",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="Ctrl+Z",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [50]=
    {
        ["nID"]=50,
        ["szDesc"]="打开江湖行记界面",
        ["szIcon"]="UIAtlas2_MainCity_MainCity1_icon_Xingji.png",
        ["szImgBg"]="",
        ["szTitle"]="江湖行记",
        ["nGroupID"]=0,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelBenefits)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=57,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=2
    },
    [51]=
    {
        ["nID"]=51,
        ["szDesc"]="打开消息提示界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="消息提示",
        ["nGroupID"]=0,
        ["szAction"]="BubbleMsgData.OpenMsgPanel()",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [52]=
    {
        ["nID"]=52,
        ["szDesc"]="打开大侠之路界面",
        ["szIcon"]="UIAtlas2_MainCity_MainCity1_icon_DaXia.png",
        ["szImgBg"]="",
        ["szTitle"]="大侠之路",
        ["nGroupID"]=0,
        ["szAction"]="CollectionData.OpenCollection(1)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=52,
        ["szShortcutKey"]="H",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=2
    },
    [53]=
    {
        ["nID"]=53,
        ["szDesc"]="打开神兵百炼界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam35.png",
        ["szImgBg"]="",
        ["szTitle"]="神兵",
        ["nGroupID"]=1,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelShenBingUpgrade)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=3,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=2901
        },
        ["nSystemOpenID"]=67,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [54]=
    {
        ["nID"]=54,
        ["szDesc"]="打开剑侠录界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam36.png",
        ["szImgBg"]="",
        ["szTitle"]="剑侠录",
        ["nGroupID"]=3,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelSwordMemories)",
        ["bHideSelf"]=false,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=5,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=4201
        },
        ["nSystemOpenID"]=74,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [55]=
    {
        ["nID"]=55,
        ["szDesc"]="打开教学盒子界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam39.png",
        ["szImgBg"]="",
        ["szTitle"]="指引",
        ["nGroupID"]=4,
        ["szAction"]="TeachBoxData.OpenTutorialCollectionPanel(TutorialPageIndex.TEACH_BOX)",
        ["bHideSelf"]=false,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=1,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=3201
        },
        ["nSystemOpenID"]=73,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [56]=
    {
        ["nID"]=56,
        ["szDesc"]="打开武学全书界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam38.png",
        ["szImgBg"]="",
        ["szTitle"]="武学全书",
        ["nGroupID"]=4,
        ["szAction"]="TeachBoxData.OpenTutorialCollectionPanel(TutorialPageIndex.SKILL)",
        ["bHideSelf"]=false,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=2,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=73,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [57]=
    {
        ["nID"]=57,
        ["szDesc"]="打开客服中心界面",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam37.png",
        ["szImgBg"]="",
        ["szTitle"]="客服中心",
        ["nGroupID"]=4,
        ["szAction"]="TeachBoxData.OpenTutorialCollectionPanel(TutorialPageIndex.SERVICE)",
        ["bHideSelf"]=false,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=3,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {
            [1]=4301
        },
        ["nSystemOpenID"]=73,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [58]=
    {
        ["nID"]=58,
        ["szDesc"]="打开时光漫游",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam40.png",
        ["szImgBg"]="",
        ["szTitle"]="时光漫游",
        ["nGroupID"]=4,
        ["szAction"]="UIMgr.Open(VIEW_ID.PanelAtmosphere)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=4,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=0,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [59]=
    {
        ["nID"]=59,
        ["szDesc"]="打开战场界面",
        ["szIcon"]="1-1.png",
        ["szImgBg"]="",
        ["szTitle"]="阵营战场",
        ["nGroupID"]=0,
        ["szAction"]="CollectionFuncList.OpenBattleField()",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=false,
        ["nGroupIndex"]=0,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=56,
        ["szShortcutKey"]="J",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    },
    [60]=
    {
        ["nID"]=60,
        ["szDesc"]="打开商城-设计站",
        ["szIcon"]="UIAtlas2_MainCity_SystemMenu_IconSysteam41.png",
        ["szImgBg"]="",
        ["szTitle"]="设计站",
        ["nGroupID"]=3,
        ["szAction"]="ShareStationData.OpenShareStation(SHARE_DATA_TYPE.EXTERIOR)",
        ["bHideSelf"]=true,
        ["bCloseSelf"]=false,
        ["bIsDisplay"]=true,
        ["nGroupIndex"]=17,
        ["tbCheckFunc"]=
        {

        },
        ["tbFontColor"]=
        {
            [1]=255,
            [2]=255,
            [3]=255,
            [4]=255
        },
        ["tbRedPointID"]=
        {

        },
        ["nSystemOpenID"]=81,
        ["szShortcutKey"]="",
        ["bUseNewRedPoint"]=false,
        ["nNewFeatureAniType"]=0
    }
}
