--通过策划工具 移动端|教学 导出
UITeachBoxTab =
{
	[1] =
	{
		["nID"] = 1,
		["szLink"] = "",
		["szName"] = "移动",
		["szDesc1"] = "滑动左下角<color=#F0DC82>摇杆</color>（极速端可按住键盘WASD），可操控角色进行<color=#F0DC82>移动</color>。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,1,1",
		["szImage1"] = "TeachBox/Teach_01.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,基础操作"
	},
	[2] =
	{
		["nID"] = 2,
		["szLink"] = "",
		["szName"] = "镜头",
		["szDesc1"] = "<color=#F0DC82>按住屏幕</color>拖动（极速端可按住鼠标左键或者右键拖动），可转动镜头观察四周。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,1,2",
		["szImage1"] = "TeachBox/Teach_02.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,基础操作"
	},
	[3] =
	{
		["nID"] = 3,
		["szLink"] = "",
		["szName"] = "跳跃",
		["szDesc1"] = "点击<color=#F0DC82>跳跃</color>按钮，可操控角色凌空跃起。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,1,3",
		["szImage1"] = "TeachBox/Teach_03.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,基础操作"
	},
	[4] =
	{
		["nID"] = 4,
		["szLink"] = "",
		["szName"] = "二段跳",
		["szDesc1"] = "跳跃状态下，再次使用<color=#F0DC82>跳跃技</color>，可使角色再次凌空跃起。\n小技巧：从高空落下在即将落地时使用二段跳，可以避免从高空摔落损失气血。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,1,4",
		["szImage1"] = "TeachBox/Teach_04.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,基础操作"
	},
	[5] =
	{
		["nID"] = 5,
		["szLink"] = "",
		["szName"] = "疾跑",
		["szDesc1"] = "在非战斗状态下，点击<color=#F0DC82>轻功</color>按钮可使角色进入疾跑状态，滑动摇杆，可控制角色方向。维持疾跑状态需要消耗气力值。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,1,5",
		["szImage1"] = "TeachBox/Teach_05.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,基础操作"
	},
	[6] =
	{
		["nID"] = 6,
		["szLink"] = "",
		["szName"] = "蹑云",
		["szDesc1"] = "点击<color=#F0DC82>蹑云</color>按钮可操控角色向前冲刺一段距离。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,1,6",
		["szImage1"] = "TeachBox/Teach_06.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,基础操作"
	},
	[7] =
	{
		["nID"] = 7,
		["szLink"] = "",
		["szName"] = "扶摇",
		["szDesc1"] = "在站立状态下，点击<color=#F0DC82>扶摇</color>后点击<color=#F0DC82>跳跃</color>可操控角色高高跃起。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,1,7",
		["szImage1"] = "TeachBox/Teach_07.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,基础操作"
	},
	[8] =
	{
		["nID"] = 8,
		["szLink"] = "",
		["szName"] = "骑乘",
		["szDesc1"] = "在装备马匹后，点击<color=#F0DC82>骑乘</color>按钮，可召唤马匹进入骑御状态，骑御状态下移动速度大大增加。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,1,8",
		["szImage1"] = "TeachBox/Teach_09.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,基础操作"
	},
	[9] =
	{
		["nID"] = 9,
		["szLink"] = "",
		["szName"] = "大轻功-跃起",
		["szDesc1"] = "疾跑状态下，点击<color=#F0DC82>纵跃</color>按钮，可快速跃起进入大轻功状态。维持大轻功状态需要消耗气力值。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,2,1",
		["szImage1"] = "TeachBox/Teach_10.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,进阶移动"
	},
	[10] =
	{
		["nID"] = 10,
		["szLink"] = "",
		["szName"] = "大轻功-飞行",
		["szDesc1"] = "在进入大轻功状态后，再次点击<color=#F0DC82>轻功</color>按钮可进入飞行段，在轻功飞行过程中可连续多次点击轻功按钮，持续<color=#F0DC82>飞行</color>。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,2,2",
		["szImage1"] = "TeachBox/Teach_11.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,进阶移动"
	},
	[11] =
	{
		["nID"] = 11,
		["szLink"] = "",
		["szName"] = "大轻功-退出",
		["szDesc1"] = "在大轻功状态下，点击<color=#F0DC82>退出轻功</color>按钮可退出大轻功状态。\n小技巧：从高空落下在即将落地时使用二段跳，可以避免高空摔落损失气血。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,2,3",
		["szImage1"] = "TeachBox/Teach_12.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,进阶移动"
	},
	[12] =
	{
		["nID"] = 12,
		["szLink"] = "",
		["szName"] = "游泳",
		["szDesc1"] = "角色进入水中将自动进入游泳状态，滑动摇杆可以操控角色在水中游动。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,2,4",
		["szImage1"] = "TeachBox/Teach_13.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,进阶移动"
	},
	[13] =
	{
		["nID"] = 13,
		["szLink"] = "",
		["szName"] = "游泳-下潜",
		["szDesc1"] = "游泳状态下，<color=#F0DC82>按住屏幕</color>向下拖动面朝水下，同时滑动<color=#F0DC82>摇杆</color>可操控角色潜入水中。在水中呼吸不畅，需要及时浮出水面呼吸，否则会导致损失气血。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,2,5",
		["szImage1"] = "TeachBox/Teach_14.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,进阶移动"
	},
	[14] =
	{
		["nID"] = 14,
		["szLink"] = "",
		["szName"] = "游泳-浮起",
		["szDesc1"] = "在潜水状态下，<color=#F0DC82>按住屏幕</color>向上拖动面朝水面，同时滑动<color=#F0DC82>摇杆</color>可操控角色浮出水面。亦可点击<color=#F0DC82>跳跃</color>浮出水面。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,2,6",
		["szImage1"] = "TeachBox/Teach_15.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,进阶移动"
	},
	[15] =
	{
		["nID"] = 15,
		["szLink"] = "",
		["szName"] = "水上轻功-跃起",
		["szDesc1"] = "游泳状态下，点击<color=#F0DC82>轻功</color>按钮，可操控角色在水面疾行。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,2,7",
		["szImage1"] = "TeachBox/Teach_16.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,进阶移动"
	},
	[16] =
	{
		["nID"] = 16,
		["szLink"] = "",
		["szName"] = "水上轻功-凌波击水",
		["szDesc1"] = "在水面疾行状态下，点击<color=#F0DC82>水花</color>按钮，可操控角色在水中冲刺，过程中点击<color=#F0DC82>出水</color>按钮，可操控角色冲出水面凌空跃起。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,2,8",
		["szImage1"] = "TeachBox/Teach_17.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,进阶移动"
	},
	[17] =
	{
		["nID"] = 17,
		["szLink"] = "",
		["szName"] = "神行千里",
		["szDesc1"] = "打开地图找到神行图标点击后展开列表，确认使用神行可施展神行快速移动到该地点。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,2,9",
		["szImage1"] = "TeachBox/Teach_47.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,进阶移动"
	},
	[18] =
	{
		["nID"] = 18,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelSkillNew)",
		["szName"] = "心法选择",
		["szDesc1"] = "非单心法门派，可在武学面板进行<color=#F0DC82>心法切换</color>。\n选择心法点击<color=#F0DC82>应用心法</color>即可完成心法切换。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "2,1,1",
		["szImage1"] = "TeachBox/Teach_20.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "武学,武学配置"
	},
	[19] =
	{
		["nID"] = 19,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelSkillNew)",
		["szName"] = "更换奇穴",
		["szDesc1"] = "在武学面板，可进行<color=#F0DC82>奇穴</color>配置。\n奇穴配置共有四重，每一重可在两个奇穴中选择一个，点击装备即可<color=#F0DC82>更换奇穴</color>。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "2,1,2",
		["szImage1"] = "Video\\%s\\Teach\\Teach_QiXue.bk2",
		["szImage2"] = "TeachBox/Teach_21.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "武学,武学配置"
	},
	[20] =
	{
		["nID"] = 20,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelSkillNew)",
		["szName"] = "招式配置",
		["szDesc1"] = "在武学面板，可进行<color=#F0DC82>武学招式</color>配置。\n点击招式配置按钮，可自定义武学招式配置。\n在武学配置面板，<color=#F0DC82>拖放</color>招式到对应栏位即可更换武学配置。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "2,1,3",
		["szImage1"] = "Video\\%s\\Teach\\Teach_ZBjineng.bk2",
		["szImage2"] = "TeachBox/Teach_22.png",
		["szImage3"] = "TeachBox/Teach_23.png",
		["szImage4"] = "",
		["szGroupDesc"] = "武学,武学配置"
	},
	[21] =
	{
		["nID"] = 21,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelSkillNew)",
		["szName"] = "配置预设",
		["szDesc1"] = "在武学面板，可更换预设配置。\n点击<color=#F0DC82>推荐</color>按钮，可进入武学配置推荐。",
		["szDesc2"] = "武学配置推荐中预设了<color=#F0DC82>秘境推荐</color>和<color=#F0DC82>竞技推荐</color>两种配置，可根据需求选择其中一种<color=#F0DC82>应用配置</color>即可。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "2,1,4",
		["szImage1"] = "TeachBox/Teach_24.png",
		["szImage2"] = "TeachBox/Teach_25.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "武学,武学配置"
	},
	[22] =
	{
		["nID"] = 22,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelSkillNew)",
		["szName"] = "武学详情",
		["szDesc1"] = "在武学面板，点击武学详情即可进入武学详情面板。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "2,1,5",
		["szImage1"] = "TeachBox/Teach_26.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "武学,武学配置"
	},
	[23] =
	{
		["nID"] = 23,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelSkillNew)",
		["szName"] = "装配秘籍",
		["szDesc1"] = "选中武学招式，可查看该武学招式的<color=#F0DC82>详细说明</color>和<color=#F0DC82>秘籍</color>装配情况。\n装配秘籍可增强当前招式，秘籍只可<color=#F0DC82>二选一</color>。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "2,1,6",
		["szImage1"] = "Video\\%s\\Teach\\Teach_MiJi.bk2",
		["szImage2"] = "TeachBox/Teach_27.png",
		["szImage3"] = "TeachBox/Teach_27.1.png",
		["szImage4"] = "",
		["szGroupDesc"] = "武学,武学配置"
	},
	[24] =
	{
		["nID"] = 24,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelSkillNew)",
		["szName"] = "武学助手",
		["szDesc1"] = "打开助手配置面板，可以自定义武学助手招式队列，<color=#F0DC82>拖放</color>招式到对应栏位即可更换配置。\n配置完成后打开自定义开关，使用武学助手时即可自动使用自定义队列里的招式。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "2,1,7",
		["szImage1"] = "TeachBox/Teach_28.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "武学,武学配置"
	},
	[25] =
	{
		["nID"] = 25,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelPartner)",
		["szName"] = "结交侠客",
		["szDesc1"] = "打开红尘侠影(菜单-侠影)面板，选择一个未获得的侠客，可查看该侠客的获取详情。",
		["szDesc2"] = "在<color=#F0DC82>未结识的</color>侠客详情界面，点击<color=#F0DC82>前往寻访</color>即可打开寻访面板，点击<color=#F0DC82>开始翻阅</color>，每次消耗一个\"<color=#F0DC82>上品茶饼</color>\"，有一定概率结交到侠客。",
		["szDesc3"] = "与结交地点的赵云睿对话拿到道具\"<color=#F0DC82>上品茶饼</color>\"，每日可以获得一次，侠士亦可通过交易行进行购买。\n找到\"<color=#F0DC82>空闲茶具</color>\"并进行交互，每次消耗一个\"上品茶饼\"，有一定概率结交到侠客。",
		["szDesc4"] = "",
		["szGroup"] = "6,1,1",
		["szImage1"] = "TeachBox/Teach_29.png",
		["szImage2"] = "TeachBox/Teach_30.1.png",
		["szImage3"] = "TeachBox/Teach_30.png",
		["szImage4"] = "",
		["szGroupDesc"] = "侠客,红尘侠影"
	},
	[26] =
	{
		["nID"] = 26,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelPartner)",
		["szName"] = "侠客共鸣",
		["szDesc1"] = "在共鸣配置分页可以将侠客加入或移除共鸣队伍，最多可同时加三个侠客编入队伍。",
		["szDesc2"] = "侠客共鸣值达到一定程度时，可以操作配置角色进行战斗。（部分场景限制使用）\n快捷操作界面中可进行显示或者隐藏共鸣操作条。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "6,1,2",
		["szImage1"] = "TeachBox/Teach_31.png",
		["szImage2"] = "TeachBox/Teach_32.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "侠客,红尘侠影"
	},
	[27] =
	{
		["nID"] = 27,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelPartner)",
		["szName"] = "侠客助战",
		["szDesc1"] = "在助战配置分页可以将侠客加入或移除助战队伍，最多可同时加三个侠客编入队伍。",
		["szDesc2"] = "快捷操作界面可以使用各类侠客指令，也可通过编辑快捷指令将这些侠客指令放入主界面。\n召请/召回侠客：召请、召回助战侠客。在不同场景中可以召唤的侠客数量有所不同。\n侠客开战：指挥所有防御类型的侠客率先执行攻击指令。\n侠客跟随/侠客攻击/侠客停留：指挥全体侠客进行跟随、攻击、停留指令。\n显示/隐藏共鸣：在主界面显示、隐藏侠客共鸣按钮。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "6,1,3",
		["szImage1"] = "TeachBox/Teach_33.png",
		["szImage2"] = "TeachBox/Teach_34.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "侠客,红尘侠影"
	},
	[28] =
	{
		["nID"] = 28,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelDungeonEntrance)",
		["szName"] = "单人秘境",
		["szDesc1"] = "部分5人英雄秘境可以选择单人模式，进入单人模式后，打开侠影界面会自动获得单人模式侠客角色，如果侠客并未配置或者配满助战侠客，则会自动补充单人模式侠客角色，侠士可以点击助战配置自己决定侠客配置。",
		["szDesc2"] = "快捷操作界面中可进行召请或召回侠客操作。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "6,1,4",
		["szImage1"] = "TeachBox/Teach_35.png",
		["szImage2"] = "TeachBox/Teach_36.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "侠客,红尘侠影"
	},
	[29] =
	{
		["nID"] = 29,
		["szLink"] = "UIMgr.Open(VIEW_ID. PanelFactionList)",
		["szName"] = "创建帮会",
		["szDesc1"] = "打开帮会(菜单-帮会）界面，点击\"创建帮会\"，可以定位到帮会登记人\"玄字贰壹\"位置。",
		["szDesc2"] = "在各大主城找到帮会登记人，登记创建帮会。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "7,1,1",
		["szImage1"] = "TeachBox/Teach_37.png",
		["szImage2"] = "TeachBox/Teach_38.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "帮会,加入帮会"
	},
	[30] =
	{
		["nID"] = 30,
		["szLink"] = "UIMgr.Open(VIEW_ID. PanelFactionList)",
		["szName"] = "加入帮会",
		["szDesc1"] = "可在帮会列表中选择一个帮会申请加入，也可以在搜索框中搜索帮会名称快速加入。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "7,1,2",
		["szImage1"] = "TeachBox/Teach_39.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "帮会,加入帮会"
	},
	[31] =
	{
		["nID"] = 31,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelHome)",
		["szName"] = "社区家园",
		["szDesc1"] = "在大唐家园（菜单-家园）界面，可点击社区下拉框选择区域，查看其他分线可选择更多分线。",
		["szDesc2"] = "社区家园中带“<color=#F0DC82>售</color>”字图标的地块为可购买的家园位置，点击可查看购买条件。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "5,1,1",
		["szImage1"] = "TeachBox/Teach_40.png",
		["szImage2"] = "TeachBox/Teach_41.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "家园,大唐家园"
	},
	[32] =
	{
		["nID"] = 32,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelHome)",
		["szName"] = "定制社区",
		["szDesc1"] = "社区定制需要满足一定条件，当满足条件后选择选择【枫叶泊】社区后，可开始社区定制购买。",
		["szDesc2"] = "在定制购买界面，可以邀请团购成员，分配地块。定制购买时必须满员且成员满足购买条件。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "5,1,2",
		["szImage1"] = "TeachBox/Teach_42.png",
		["szImage2"] = "TeachBox/Teach_43.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "家园,大唐家园"
	},
	[33] =
	{
		["nID"] = 33,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelHome)",
		["szName"] = "家园共居",
		["szDesc1"] = "在社区家园中，可以邀请其他侠士共居，可在管家阿甘处申请。\n满足条件，会向邀请入发送邀请，30秒内确认即可共居。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "5,1,3",
		["szImage1"] = "TeachBox/Teach_46.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "家园,大唐家园"
	},
	[34] =
	{
		["nID"] = 34,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelHome)",
		["szName"] = "家园总览",
		["szDesc1"] = "在家园场景中，点击总览可查看家园活动玩法相关。完成家园活动可以获得<color=#F0DC82>家园活跃度</color>，活跃度达到一定值可领取奖励。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "5,1,4",
		["szImage1"] = "TeachBox/Teach_45.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "家园,大唐家园"
	},
	[35] =
	{
		["nID"] = 35,
		["szLink"] = "",
		["szName"] = "垂钓",
		["szDesc1"] = "靠近水边可在快捷操作中点击<color=#F0DC82>垂钓</color>按钮开始垂钓，私邸宅院则需要与鱼池交互进入垂钓。垂钓需要消耗\"<color=#F0DC82>鱼饵</color>\"，可在家园商店(菜单-商店-家园-鱼-垂钓客)购买获得。",
		["szDesc2"] = "垂钓可以提升<color=#F0DC82>垂钓客</color>等级，等级提升后可解锁新的垂钓能力。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "5,3,1",
		["szImage1"] = "TeachBox/Teach_44.png",
		["szImage2"] = "TeachBox/Teach_44.1.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "家园,垂钓客"
	},
	[36] =
	{
		["nID"] = 36,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelTeam)",
		["szName"] = "队长权限",
		["szDesc1"] = "队长在组队界面，选中队友，可以<color=#F0DC82>移交队长、分配权限、阵眼以及标记权限</color>，也可以回收这些权限。\n在参与某些功能时，队长还可以将小队转换为<color=#F0DC82>团队模式</color>，团队模式下某些任务可能无法继续进行，同时击败怪不能获得阅历。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,3,1",
		["szImage1"] = "TeachBox/Teach_48.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,组队"
	},
	[37] =
	{
		["nID"] = 37,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelTeam)",
		["szName"] = "分配权限",
		["szDesc1"] = "侠士拥有分配权限后，在组队界面点击右上角\"设置\"按钮，可以修改当前的<color=#F0DC82>分配等级</color>和<color=#F0DC82>分配模式</color>。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,3,2",
		["szImage1"] = "TeachBox/Teach_49.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,组队"
	},
	[38] =
	{
		["nID"] = 38,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelTeam)",
		["szName"] = "标记权限",
		["szDesc1"] = "标记功能，适用于游戏内可选中的所有角色。侠士拥有标记权限后，可根据需要选中角色，进行快速标记。角色被标记的图案，小队或团队成员全部可见。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,3,3",
		["szImage1"] = "TeachBox/Teach_50.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,组队"
	},
	[39] =
	{
		["nID"] = 39,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelBaizhanMain)",
		["szName"] = "选层",
		["szDesc1"] = "每周可以有<color=#F0DC82>6次定向转移</color>和<color=#F0DC82>12次随机前进</color>机会。部分层数有特殊效果，该效果在<color=#F0DC82>随机前进</color>时到达才会触发。\n<color=#F0DC82>随机前进</color>时可以预测到达格子，如果预测成功，则可以获得一份随机额外奖励。\n每周每层特殊效果<color=#F0DC82>只触发一次</color>，击败首领后奖励只能获得一次。\n<color=#F0DC82>免消耗层</color>：定向转移到该层时不消耗转移次数，随机前进抵达该层时不消耗随机次数。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,2,1",
		["szImage1"] = "TeachBox/Teach_51.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,百战异闻录"
	},
	[40] =
	{
		["nID"] = 40,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelBaizhanMain)",
		["szName"] = "精耐",
		["szDesc1"] = "侠士精神值每减少1%，<color=#F0DC82>治疗效果</color>降低1%，耐力每减少1%，<color=#F0DC82>受到伤害</color>提高1%。\n精耐上限提升：<color=#F0DC82>首次收集三本同级百战招式</color>，精耐上限增加，增加上限与收集技能等级有关；\n<color=#F0DC82>收集某个首领的全部招式</color>，精耐上限增加，增加的上限与收集首领招式等级相关。",
		["szDesc2"] = "<color=#F0DC82>首领精神值降低时</color>：受到的治疗效果降低；受百战招式的伤害提升；耐力恢复减慢；被百战招式控制概率和时间增加。\n<color=#F0DC82>首领耐力值降低时</color>：受到的伤害提高；防御力下降；闪避降低。首领的精耐值会缓慢恢复。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,2,2",
		["szImage1"] = "TeachBox/Teach_52.1.png",
		["szImage2"] = "TeachBox/Teach_52.2.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,百战异闻录"
	},
	[41] =
	{
		["nID"] = 41,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelBaizhanMain)",
		["szName"] = "破绽",
		["szDesc1"] = "使用相同样色的百战招式可以<color=#F0DC82>击破破绽</color>造成<color=#F0DC82>额外伤害</color>。",
		["szDesc2"] = "破绽有<color=#F0DC82>小中大</color>三个等级，<color=#F0DC82>破绽越大</color>击破后的特效越强，百战招式<color=#F0DC82>调息越长，击破能力越强</color>；\n<color=#F0DC82>破绽存在时</color>，对首领造成的百战招式或精耐伤害有<color=#F0DC82>额外收益</color>；\n百战招式<color=#F0DC82>击中</color>更低或同等级破绽能<color=#F0DC82>触发额外收益</color>。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,2,3",
		["szImage1"] = "TeachBox/Teach_53.1.png",
		["szImage2"] = "TeachBox/Teach_53.2.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,百战异闻录"
	},
	[42] =
	{
		["nID"] = 42,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelBaizhanMain)",
		["szName"] = "百战武学",
		["szDesc1"] = "激活招式需要消耗点数，不同招式消耗点数不同，招式消耗点最多不能超过3点。\n可通过消耗<color=#F0DC82>招式通本</color>或对应的<color=#F0DC82>招式要诀</color>进行等级提升。可以通过预设百战招式的携带方案功能来预设多种百战招式搭配方案。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,2,4",
		["szImage1"] = "TeachBox/Teach_54.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,百战异闻录"
	},
	[43] =
	{
		["nID"] = 43,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelBaizhanMain)",
		["szName"] = "挑战进度",
		["szDesc1"] = "切换队伍人员之后需要<color=#F0DC82>重置进度</color>之后才可继续组队，但是重置进度<color=#F0DC82>不能重置</color>已经获得的首领奖励和层数特殊效果。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,2,5",
		["szImage1"] = "TeachBox/Teach_55.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,百战异闻录"
	},
	[44] =
	{
		["nID"] = 44,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelBaizhanMain)",
		["szName"] = "传授招式",
		["szDesc1"] = "在百战异闻录场景内，可以对队友传授招式，传授招式需要消耗传授者的<color=#F0DC82>传授内力</color>和被传授的<color=#F0DC82>传授次数</color>。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,2,6",
		["szImage1"] = "TeachBox/Teach_56.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,百战异闻录"
	},
	[45] =
	{
		["nID"] = 45,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelPowerUp)",
		["szName"] = "装备栏精炼",
		["szDesc1"] = "选择一个装备栏位，可以投入五行石进行栏位强化，五行石<color=#F0DC82>等级</color>和<color=#F0DC82>数量</color>会影响精炼成功率。强化后的栏位会使本栏位的装备属性提高。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "4,1,1",
		["szImage1"] = "TeachBox/Teach_57.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "装备,装备强化"
	},
	[46] =
	{
		["nID"] = 46,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelPowerUp)",
		["szName"] = "装备熔嵌",
		["szDesc1"] = "五行石熔嵌：选择一个装备栏位，可以使用五行石进行熔嵌，熔嵌后可以激活装备栏位的<color=#F0DC82>熔嵌属性</color>。不同等级的五行石激活的属性数值不同。",
		["szDesc2"] = "五彩石熔嵌：五彩石只能熔嵌在武器栏位，熔嵌后可以根据全身装备栏位的五行石精炼数量和等级激活五彩石的熔嵌属性。不同五彩石可激活的属性和数值不同。",
		["szDesc3"] = "五彩石预设绑定：可根据预设调整武器和五彩石之间的搭配。切换预设中的不同装备，可立即生效对应的五彩石属性。",
		["szDesc4"] = "在该面板中，点击五彩石可以查看规则说明。",
		["szGroup"] = "4,1,2",
		["szImage1"] = "TeachBox/Teach_58.1.png",
		["szImage2"] = "TeachBox/Teach_58.2.png",
		["szImage3"] = "TeachBox/Teach_58.3.png",
		["szImage4"] = "TeachBox/Teach_58.3-1.png",
		["szGroupDesc"] = "装备,装备强化"
	},
	[47] =
	{
		["nID"] = 47,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelPowerUp)",
		["szName"] = "装备附魔",
		["szDesc1"] = "可以对装备附魔增加额外增益效果，附魔增益分为永久和限时两种。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "4,1,3",
		["szImage1"] = "TeachBox/Teach_59.1.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "装备,装备强化"
	},
	[48] =
	{
		["nID"] = 48,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelPowerUp)",
		["szName"] = "精炼剥离",
		["szDesc1"] = "精炼剥离可以将对应装备栏位的精炼等级重置，剥离时可获得五行石产物。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "4,1,4",
		["szImage1"] = "TeachBox/Teach_60.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "装备,装备强化"
	},
	[49] =
	{
		["nID"] = 49,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelPowerUp)",
		["szName"] = "精炼升级",
		["szDesc1"] = "可以自定义配方来强化五行石或五彩石，置入的材料越多越可能出现跨级产物，置入材料时可以查看成功率以及产物。",
		["szDesc2"] = "快速精炼五行石无法修改配方，只能使用五行石（一级），在精炼五行石（六级）时有几率直接获得五行石（七级）和五行石（八级）。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "4,1,5",
		["szImage1"] = "TeachBox/Teach_61.png",
		["szImage2"] = "TeachBox/Teach_62.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "装备,装备强化"
	},
	[50] =
	{
		["nID"] = 50,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelWorldMap)",
		["szName"] = "常用神行地图",
		["szDesc1"] = "在世界地图界面，选中任意城镇，可将其设置为<color=#F0DC82>常用神行点</color>。\n切换到场景地图时，可以在地图右边的常用神行地图列表中快速前往该城镇。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,4,1",
		["szImage1"] = "TeachBox/Teach_66.1.png",
		["szImage2"] = "TeachBox/Teach_66.2.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,地图"
	},
	[51] =
	{
		["nID"] = 51,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelMiddleMap)",
		["szName"] = "创建标记",
		["szDesc1"] = "在场景地图界面中，点击地图任意位置可以创建标记，创建标记时可以选择不同图标以作区别。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,4,2",
		["szImage1"] = "TeachBox/Teach_63.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,地图"
	},
	[52] =
	{
		["nID"] = 52,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelMiddleMap)",
		["szName"] = "角色标记",
		["szDesc1"] = "在场景地图界面中，点击地图右下角标记按钮，可以打开当前地图的常用标记列表，可以快速定位列表中的角色位置。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,4,3",
		["szImage1"] = "TeachBox/Teach_64.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,地图"
	},
	[53] =
	{
		["nID"] = 53,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelMiddleMap)",
		["szName"] = "采集标记",
		["szDesc1"] = "在场景地图界面中，点击地图右下角采集按钮，可以打开当前地图的采集显示列表，可以在列表中选择选择一种或多种矿产、草药以及野兽位置。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,4,4",
		["szImage1"] = "TeachBox/Teach_65.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,地图"
	},
	[54] =
	{
		["nID"] = 54,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelLifeMain)",
		["szName"] = "采集",
		["szDesc1"] = "<color=#F0DC82>神农：</color>学习神农技艺后，可在野外场景中采集草药；\n<color=#F0DC82>采金：</color>学习采金技艺后，可在野外场景中采掘矿石；\n<color=#F0DC82>庖丁：</color>学习庖丁技艺后，可获取野兽的皮毛和肉。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "9,1,1",
		["szImage1"] = "TeachBox/Teach_69.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "技艺,技艺"
	},
	[55] =
	{
		["nID"] = 55,
		["szLink"] = "",
		["szName"] = "套马",
		["szDesc1"] = "玩家学会套马技能后，在苍山洱海的山巅牧场或者帮会领地的落日牧场里，找到野生的马匹，可对其施展套马招式，成功后可获得马驹。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "9,1,2",
		["szImage1"] = "TeachBox/Teach_67.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "技艺,技艺"
	},
	[56] =
	{
		["nID"] = 56,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelLifeMain)",
		["szName"] = "驯养",
		["szDesc1"] = "获得马驹后，可在驯养面板中开始驯养马驹，同时只可驯养一匹马驹",
		["szDesc2"] = "驯养马驹需要及时补充草料保持马匹饱食度。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "9,1,3",
		["szImage1"] = "TeachBox/Teach_68.1.png",
		["szImage2"] = "TeachBox/Teach_68.2.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "技艺,技艺"
	},
	[57] =
	{
		["nID"] = 57,
		["szLink"] = "",
		["szName"] = "矿车日常",
		["szDesc1"] = "<color=#F0DC82>收集</color>散落的<color=#F0DC82>物资</color>，获取<color=#F0DC82>少量</color>功勋。参与击<color=#F0DC82>杀蜂群蟊贼</color>，获取<color=#F0DC82>少量</color>功勋。（收集<color=#F0DC82>满10000</color>，<color=#F0DC82>本阵营</color>开始<color=#F0DC82>押送</color>物资）占领<color=#F0DC82>无主瓷窑</color>，<color=#F0DC82>大幅</color>提高本阵营<color=#F0DC82>收集进度</color>。",
		["szDesc2"] = "<color=#F0DC82>保护我方</color>押运<color=#F0DC82>物资车</color>，获取<color=#F0DC82>大量</color>功勋。参与<color=#F0DC82>摧毁敌方</color>押运<color=#F0DC82>物资车</color>，获取<color=#F0DC82>大量</color>功勋。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "8,1,1",
		["szImage1"] = "TeachBox/Teach_75.1.png",
		["szImage2"] = "TeachBox/Teach_75.2.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "阵营,千里伐逐"
	},
	[58] =
	{
		["nID"] = 58,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelTeam)",
		["szName"] = "队伍面板",
		["szDesc1"] = "点击队伍切页按钮，可以进入队伍面板。\n在未组队时，在此处可以查看正在招募的队伍列表，寻找合适的队伍加入，也可以发布招募寻找队友。已组队的情况下，可以查看队友进行队伍操作。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,3,4",
		["szImage1"] = "TeachBox/Teach_70.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,组队"
	},
	[59] =
	{
		["nID"] = 59,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelBaizhanMain)",
		["szName"] = "机缘宝箱与盗宝贼",
		["szDesc1"] = "当侠士挑战1~80层首领时场上会出现机缘宝箱（仅在3人模式下），击破宝箱后会掉落各种增益效果或者陷阱。\n其中<color=#F0DC82>进入战斗前</color>的大宝箱必定出现大幅增加精神耐力打击的增益效果。\n<color=#F0DC82>推荐先获得增加精神耐力打击再开始战斗。</color>",
		["szDesc2"] = "<color=#F0DC82>进入战斗后</color>宝箱每分钟将会刷新一次，同时场上会出现盗宝贼盗取宝箱。若盗宝贼成功盗取宝箱后，将其击败必定会掉落增益效果。",
		["szDesc3"] = "充分利用击破宝箱掉落的各种增益效果能够更有效地攻略首领。",
		["szDesc4"] = "",
		["szGroup"] = "3,2,7",
		["szImage1"] = "TeachBox/Teach_71.1.png",
		["szImage2"] = "TeachBox/Teach_71.2.png",
		["szImage3"] = "TeachBox/Teach_71.3.png",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,百战异闻录"
	},
	[60] =
	{
		["nID"] = 60,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelBaizhanMain)",
		["szName"] = "首领难度与掉落关系",
		["szDesc1"] = "百战异闻录的首领共有3档难度：<color=#F0DC82>小于等于3人：3人难度；大于3人小于等于6人：6人难度；大于6人：10人难度</color>。\n<color=#F0DC82>助战侠客</color>的数量也会计算在内。\n难度档位会影响首领的气血、精神、耐力以及招式机制。\n如果是单人参与，建议召唤侠客助战。",
		["szDesc2"] = "掉落与层数成正相关，即层数越高，掉落的奖励越丰厚。其中<color=#F0DC82>每10层的精英首领</color>掉落最为丰厚，如果可以的话，每周要尝试击败力所能及的精英首领。",
		["szDesc3"] = "掉落与拥有拾取权限的实际侠士数成正相关，即<color=#F0DC82>组队参与的实际侠士越多</color>，奖励越丰厚。",
		["szDesc4"] = "掉落与每个侠士在战斗中的存活时长与总战斗时长的比例成正相关，尝试尽量保证自己的生存，以获得本场战斗最高的奖励。",
		["szGroup"] = "3,2,8",
		["szImage1"] = "TeachBox/Teach_72.png",
		["szImage2"] = "TeachBox/Teach_73.png",
		["szImage3"] = "TeachBox/Teach_74.1.png",
		["szImage4"] = "TeachBox/Teach_74.2.png",
		["szGroupDesc"] = "秘境,百战异闻录"
	},
	[61] =
	{
		["nID"] = 61,
		["szLink"] = "",
		["szName"] = "世界首领",
		["szDesc1"] = "活动期间可选择任意【千里伐逐】界面的各个服务器主线或【前尘影事】中的支线服务器前往场景。",
		["szDesc2"] = "进入活动场景后，打开地图可查看世界首领所在位置。",
		["szDesc3"] = "持续参与攻击世界首领，进入战斗状态达<color=#F0DC82>180秒及以上</color>。世界首领被击败后，当日晚上<color=#F0DC82>12点前</color>可拾取首领财宝堆奖励。",
		["szDesc4"] = "",
		["szGroup"] = "8,1,2",
		["szImage1"] = "TeachBox/Teach_76.1.png",
		["szImage2"] = "TeachBox/Teach_76.2.png",
		["szImage3"] = "TeachBox/Teach_77.png",
		["szImage4"] = "",
		["szGroupDesc"] = "阵营,千里伐逐"
	},
	[62] =
	{
		["nID"] = 62,
		["szLink"] = "",
		["szName"] = "主界面自定义",
		["szDesc1"] = "主界面的界面布局可以进行自定义调整，可在主界面布局开启自定义调整。\n（主界面右上角小扳手-主界面设置-主界面界面布局-自定义）",
		["szDesc2"] = "白色线框表示选中的组件，按住组件可进行拖动，绿色线框表示当前组件可以拖动的范围。\n在模块设置中可一键调整组件大小以及开关组件中的文本信息。",
		["szDesc3"] = "聊天组件除了可以移动位置以及一键设置组件大小以外，还可以按住组件边缘进行拖动，调整组件的高度和宽度，调整范围不可超过绿框大小。",
		["szDesc4"] = "所有组件都不能和其他组件有重叠，当组件边缘出现红色线框时，则表示组件有重叠，在解决重叠之前无法保存自定义配置。",
		["szGroup"] = "1,5,1",
		["szImage1"] = "TeachBox/Teach_78.1.png",
		["szImage2"] = "TeachBox/Teach_78.2.png",
		["szImage3"] = "TeachBox/Teach_78.3.png",
		["szImage4"] = "TeachBox/Teach_78.4.png",
		["szGroupDesc"] = "基础,主界面布局"
	},
	[63] =
	{
		["nID"] = 63,
		["szLink"] = "",
		["szName"] = "基础规则",
		["szDesc1"] = "与<color=#F0DC82>昭昭魂灯</color>互动开启关卡，击溃源源不绝的来敌，在限定时间内生存下来即可通关。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,3,1",
		["szImage1"] = "TeachBox/Teach_79.0.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,八荒衡鉴"
	},
	[64] =
	{
		["nID"] = 64,
		["szLink"] = "",
		["szName"] = "秘术",
		["szDesc1"] = "<color=#F0DC82>击败敌人</color>会掉落<color=#F0DC82>秘术</color>，触碰即可拾取，在秘境中会时常刷新宝箱，开启宝箱也会掉落<color=#F0DC82>秘术</color>。",
		["szDesc2"] = "拾取秘术后，可以在配置界面的<color=#F0DC82>秘术分页</color>中查看，点击秘术可查看详情，可<color=#F0DC82>卸下</color>或<color=#F0DC82>丢弃</color>秘术，秘术最多可生效6个。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,3,2",
		["szImage1"] = "TeachBox/Teach_79.2.png",
		["szImage2"] = "TeachBox/Teach_79.1.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,八荒衡鉴"
	},
	[65] =
	{
		["nID"] = 65,
		["szLink"] = "",
		["szName"] = "技能",
		["szDesc1"] = "秘境中会时常刷新日无暇晷，前往日晷处可开启<color=#F0DC82>日晷挑战</color>，在限定时间内击杀目标敌人，可掉落<color=#F0DC82>主动技能</color>，触碰即可拾取。",
		["szDesc2"] = "拾取技能后，可以在配置界面的<color=#F0DC82>技能分页</color>中查看，点击技能可查看详情，点击“-”可<color=#F0DC82>丢弃</color>技能。",
		["szDesc3"] = "在配置界面的设置分页中，可根据技能情况设置自动释放技能。",
		["szDesc4"] = "",
		["szGroup"] = "3,3,3",
		["szImage1"] = "TeachBox/Teach_79.3.png",
		["szImage2"] = "TeachBox/Teach_79.4.png",
		["szImage3"] = "TeachBox/Teach_79.5.png",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,八荒衡鉴"
	},
	[66] =
	{
		["nID"] = 66,
		["szLink"] = "",
		["szName"] = "菜园保卫战",
		["szDesc1"] = "<color=#F0DC82>菜园保卫战</color>活动开启后，帮会领地内将出现<color=#F0DC82>猪九戒</color>，打开帮会地图可查看猪九戒所在位置。",
		["szDesc2"] = "通过拾取帮会领地内的特殊物品，获取击败猪九戒的强力道具。",
		["szDesc3"] = "成功击败猪九戒后，帮会将获得帮会资金，所有非预备期玩家均可拾取紫陨获得一份奖励。",
		["szDesc4"] = "",
		["szGroup"] = "7,2,10",
		["szImage1"] = "TeachBox/Teach_80.0.png",
		["szImage2"] = "TeachBox/Teach_80.1.png",
		["szImage3"] = "TeachBox/Teach_80.2.png",
		["szImage4"] = "",
		["szGroupDesc"] = "帮会,帮会活动"
	},
	[67] =
	{
		["nID"] = 67,
		["szLink"] = "",
		["szName"] = "小猪快跑",
		["szDesc1"] = "<color=#F0DC82>落日牧场的三石叔</color>饲养的小猪跑出了猪圈，需要侠士在<color=#F0DC82> 40 </color>分钟内帮他找回来。",
		["szDesc2"] = "侠士可在帮会领地内找到逃窜的小猪，用从三石叔处领到的<color=#F0DC82>赶猪棒</color>将小猪带回给三石叔。",
		["szDesc3"] = "每成功带回一只小猪就会记录分数，当帮会分数成功到达500分时，帮会将获得帮会资金，所有参与小猪快跑活动的侠士都可在三石叔处领取奖励。不同的小猪对应不同的分数，小白猪15分，小黑猪30分，大野猪45分。",
		["szDesc4"] = "",
		["szGroup"] = "7,2,11",
		["szImage1"] = "TeachBox/Teach_81.0.png",
		["szImage2"] = "TeachBox/Teach_81.1.png",
		["szImage3"] = "TeachBox/Teach_81.2.png",
		["szImage4"] = "",
		["szGroupDesc"] = "帮会,帮会活动"
	},
	[68] =
	{
		["nID"] = 68,
		["szLink"] = "",
		["szName"] = "名剑大会",
		["szDesc1"] = "进入名剑大会竞技场地后，在等待时间内，可以调整武学配置。\n点击敌方玩家头像可以选中该玩家。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,1,1",
		["szImage1"] = "TeachBox/Teach_87.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,名剑大会"
	},
	[69] =
	{
		["nID"] = 69,
		["szLink"] = "",
		["szName"] = "战场开始",
		["szDesc1"] = "绝境战场开始后，所有玩家会乘坐绝境飞鸢前往战场。可以在合适的区域点击<color=#F0DC82>降落按钮</color>下降到地面。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,2,1",
		["szImage1"] = "TeachBox/Teach_86.1.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,绝境战场"
	},
	[70] =
	{
		["nID"] = 70,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelHalfBag)",
		["szName"] = "拖动道具",
		["szDesc1"] = "在背包界面，<color=#F0DC82>长按道具2秒</color>可以进入拖动道具状态，在此状态下可以将当前选中的道具拖动到背包栏的任意位置。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,6,1",
		["szImage1"] = "TeachBox/Teach_82.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,背包"
	},
	[71] =
	{
		["nID"] = 71,
		["szLink"] = "",
		["szName"] = "走路状态",
		["szDesc1"] = "在快捷操作的玩法功能分组中点击<color=#F0DC82>切换走路</color>按钮，可使角色移动时由跑步状态切换到<color=#F0DC82>走路</color>状态，再次点击关闭走路按钮可以切换到跑步状态。\n（主界面右上角小扳手可进入快捷操作面板）",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,2,10",
		["szImage1"] = "TeachBox/Teach_83.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,进阶移动"
	},
	[72] =
	{
		["nID"] = 72,
		["szLink"] = "",
		["szName"] = "自动行走",
		["szDesc1"] = "在快捷操作的玩法功能分组中点击<color=#F0DC82>自动行走</color>按钮，可开启<color=#F0DC82>自动前进</color>，再次点击该按钮可以关闭自动前进。\n（主界面右上角小扳手可进入快捷操作面板）",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,2,11",
		["szImage1"] = "TeachBox/Teach_84.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,进阶移动"
	},
	[73] =
	{
		["nID"] = 73,
		["szLink"] = "",
		["szName"] = "寻找物品",
		["szDesc1"] = "战场中各处会有可以拾取的武器装备、药品和马匹等道具。尽快寻找到这些物品可大大增加生存能力。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,2,2",
		["szImage1"] = "TeachBox/Teach_86.2.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,绝境战场"
	},
	[74] =
	{
		["nID"] = 74,
		["szLink"] = "",
		["szName"] = "安全区域",
		["szDesc1"] = "战斗开始一段时间后，安全区开始缩小，处于安全区外将受到持续伤害，请尽快进入安全区域。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,2,3",
		["szImage1"] = "TeachBox/Teach_86.3.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,绝境战场"
	},
	[75] =
	{
		["nID"] = 75,
		["szLink"] = "",
		["szName"] = "快捷使用道具",
		["szDesc1"] = "在快捷操作栏可以快捷使用道具物品而不必开启背包。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,2,4",
		["szImage1"] = "TeachBox/Teach_86.4.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,绝境战场"
	},
	[76] =
	{
		["nID"] = 76,
		["szLink"] = "",
		["szName"] = "对局状态",
		["szDesc1"] = "在战场中，可以根据右上角的状态栏随时了解对局情况。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,2,5",
		["szImage1"] = "TeachBox/Teach_86.5.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,绝境战场"
	},
	[77] =
	{
		["nID"] = 77,
		["szLink"] = "",
		["szName"] = "背包操作",
		["szDesc1"] = "在装备背包界面中(点击主界面右上角背包按钮可以打开)，可以快速丢弃一个或多个用不到的道具物品，可查看当前可用的马匹状态。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,2,6",
		["szImage1"] = "TeachBox/Teach_86.6.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,绝境战场"
	},
	[78] =
	{
		["nID"] = 78,
		["szLink"] = "",
		["szName"] = "马匹操作",
		["szDesc1"] = "在马匹界面可以查看当前可用的马匹速度和饱食度状态，当马匹饱食度不足时，将无法骑乘。可在战场中寻找草料喂食马匹以增加饱食度。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,2,7",
		["szImage1"] = "TeachBox/Teach_86.7.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,绝境战场"
	},
	[79] =
	{
		["nID"] = 79,
		["szLink"] = "",
		["szName"] = "寻宝罗盘",
		["szDesc1"] = "在快捷操作的玩法功能分组中点击<color=#F0DC82>寻宝</color>按钮，可开启<color=#F0DC82>寻宝罗盘</color>，再次点击可以关闭寻宝罗盘。点击罗盘即可开始寻宝。\n(部分场景无法寻宝，如战场、秘境等)",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,1,1",
		["szImage1"] = "TeachBox/Teach_88.1.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,江湖寻宝"
	},
	[80] =
	{
		["nID"] = 80,
		["szLink"] = "",
		["szName"] = "开始寻宝",
		["szDesc1"] = "点击罗盘开始寻宝后，跟随罗盘指引可前往寻宝目的地。到达目标点后，点击<color=#F0DC82>罗盘或<color=#F0DC82>发现</color>交互按钮即可发掘宝藏。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,1,2",
		["szImage1"] = "TeachBox/Teach_88.2.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,江湖寻宝"
	},
	[82] =
	{
		["nID"] = 82,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelDungeonEntrance)",
		["szName"] = "进入秘境",
		["szDesc1"] = "在秘境大全界面中，选中目标秘境后，可以点击<color=#F0DC82>组队前往</color>或<color=#F0DC82>单人前往</color>进入秘境。",
		["szDesc2"] = "可在世界地图中搜索对应的秘境名称进行传送，通过这种方式可以传送到秘境门口。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,1,1",
		["szImage1"] = "TeachBox/Teach_89.1.png",
		["szImage2"] = "TeachBox/Teach_89.2.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,通用规则"
	},
	[83] =
	{
		["nID"] = 83,
		["szLink"] = "",
		["szName"] = "秘境内传送",
		["szDesc1"] = "在秘境挑战中阵亡复活后，可以在秘境起始处的接引人快速传送到已挑战完毕的首领处。\n（未完成挑战的区域不可传送）",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,1,2",
		["szImage1"] = "TeachBox/Teach_89.3.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,通用规则"
	},
	[84] =
	{
		["nID"] = 84,
		["szLink"] = "",
		["szName"] = "离开秘境",
		["szDesc1"] = "点击屏幕右上角的退出按钮可以<color=#F0DC82>退出</color>当前秘境。\n(如果没有看到退出按钮，请尝试点击切换功能菜单按钮)",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,1,3",
		["szImage1"] = "TeachBox/Teach_89.4.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,通用规则"
	},
	[85] =
	{
		["nID"] = 85,
		["szLink"] = "",
		["szName"] = "擂台",
		["szDesc1"] = "在快捷操作的玩法功能分组中点击<color=#F0DC82>摆擂</color>按钮，可打开<color=#F0DC82>擂台</color>界面，点击<color=#F0DC82>开始擂台</color>即可摆出擂台。",
		["szDesc2"] = "擂台摆出后，其他侠士可与”切磋旗“交互，查看擂主切磋胜负情况。点击挑战即可与擂主切磋。",
		["szDesc3"] = "挑战开始开始后，切磋的任意一方的气血耗尽则战斗结束。",
		["szDesc4"] = "",
		["szGroup"] = "10,9,1",
		["szImage1"] = "TeachBox/Teach_85.0.png",
		["szImage2"] = "TeachBox/Teach_85.1.png",
		["szImage3"] = "TeachBox/Teach_85.2.png",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,摆擂"
	},
	[86] =
	{
		["nID"] = 86,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelChooseLv)",
		["szName"] = "进入浪客行",
		["szDesc1"] = "在主城中可以找到<color=#F0DC82>浪客行接引人蒋玉凤</color>，与其对话进入浪客行玩法。或通过<color=#F0DC82>大侠之路</color>找到浪客行玩法卡片（大侠之路-秘境-浪客行）选择进入。",
		["szDesc2"] = "浪客行玩法分为普通和挑战两个难度，挑战难度怪物更强，对应的奖励也更丰厚。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,4,1",
		["szImage1"] = "TeachBox/Teach_90.1.png",
		["szImage2"] = "TeachBox/Teach_90.2.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,浪客行"
	},
	[87] =
	{
		["nID"] = 87,
		["szLink"] = "",
		["szName"] = "界面介绍",
		["szDesc1"] = "<color=#F0DC82>心情值</color>和<color=#F0DC82>饱食度</color>会影响角色属性，可通过食用酒、食物来增加。\n在挑战关卡时，会获得一些<color=#F0DC82>负面效果</color>，这些效果会影响战斗效率，需要通过药物或休息来驱散。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,4,2",
		["szImage1"] = "TeachBox/Teach_91.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,浪客行"
	},
	[88] =
	{
		["nID"] = 88,
		["szLink"] = "",
		["szName"] = "浪客行说书人",
		["szDesc1"] = "关卡起始位置和<color=#F0DC82>浪客行说书人·始</color>对话可以为挑战开始做准备。",
		["szDesc2"] = "关卡终点位置和<color=#F0DC82>浪客行说书人·终</color>对话可以做休整并前往下一关。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,4,3",
		["szImage1"] = "TeachBox/Teach_92.1.png",
		["szImage2"] = "TeachBox/Teach_92.2.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,浪客行"
	},
	[89] =
	{
		["nID"] = 89,
		["szLink"] = "",
		["szName"] = "物资收集",
		["szDesc1"] = "在关卡中通过击杀敌人、采集草药、打猎、搜寻宝箱来获得装备、材料、制造配方等物品。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,4,4",
		["szImage1"] = "TeachBox/Teach_93.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,浪客行"
	},
	[90] =
	{
		["nID"] = 90,
		["szLink"] = "",
		["szName"] = "关卡技艺",
		["szDesc1"] = "在关卡终点处可以进行<color=#F0DC82>烹饪</color>和<color=#F0DC82>制药</color>，制造所需的材料可以在挑战过程中获得，也可在商人处购买兑换。\n制作所需的配方可以挑战关卡过程中获得。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,4,5",
		["szImage1"] = "TeachBox/Teach_94.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,浪客行"
	},
	[91] =
	{
		["nID"] = 91,
		["szLink"] = "",
		["szName"] = "关卡商人",
		["szDesc1"] = "在客栈中可以在商人处购买或兑换装备、材料等物品，在挑战关卡中也有可能会遇到他们。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,4,6",
		["szImage1"] = "TeachBox/Teach_95.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,浪客行"
	},
	[92] =
	{
		["nID"] = 92,
		["szLink"] = "",
		["szName"] = "浪客笺",
		["szDesc1"] = "每完成一个关卡都会获得一定数量的<color=#F0DC82>浪客笺</color>，可在邮箱中领取。收集足够数量的浪客笺后，可在浪客行商店中购买装备物资。",
		["szDesc2"] = "可在主城中找到浪客笺兑换商人<color=#F0DC82>陈只鱼</color>打开浪客行商店，也可以通过主菜单中的商店功能（菜单-商店-秘境商店-浪客行）打开。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,4,7",
		["szImage1"] = "TeachBox/Teach_96.1.png",
		["szImage2"] = "TeachBox/Teach_96.2.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,浪客行"
	},
	[93] =
	{
		["nID"] = 93,
		["szLink"] = "",
		["szName"] = "秘境进度",
		["szDesc1"] = "秘境首领被击败后，小队秘境可以消耗一定数量的精力值来<color=#F0DC82>重置秘境</color>，部分非当季团队秘境可以使用<color=#F0DC82>忆昔石</color>来<color=#F0DC82>重置秘境</color>，重置的秘境在击败首领后，可以正常产生掉落。",
		["szDesc2"] = "组队挑战团队秘境时，当队长秘境进度与自身秘境进度不匹配时，可以通过<color=#F0DC82>刷新场景</color>按钮恢复为无进度状态，协助其他侠士进行秘境挑战。\n如果自身为队长时使用刷新场景按钮再次进入秘境场景，仍会以当前个人进度创建场景。\n刷新场景<color=#F0DC82>无法刷新个人领奖记录</color>，也无法参与奖励分配。",
		["szDesc3"] = "组队状态下，可在秘境大全页面查看队友当前秘境的进度情况。",
		["szDesc4"] = "",
		["szGroup"] = "3,1,4",
		["szImage1"] = "TeachBox/Teach_99.1.png",
		["szImage2"] = "TeachBox/Teach_99.2.png",
		["szImage3"] = "TeachBox/Teach_99.3.png",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,通用规则"
	},
	[94] =
	{
		["nID"] = 94,
		["szLink"] = "",
		["szName"] = "频道设置",
		["szDesc1"] = "聊天界面中可以设置各个聊天分页中<color=#F0DC82>可接收</color>的聊天频道信息。",
		["szDesc2"] = "所有非置灰的聊天频道都可以进行设置，保存设置后，该聊天分页将只能接收到打 √ 的频道信息。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,7,1",
		["szImage1"] = "TeachBox/Teach_98.1.png",
		["szImage2"] = "TeachBox/Teach_98.2.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,聊天"
	},
	[95] =
	{
		["nID"] = 95,
		["szLink"] = "",
		["szName"] = "查看信誉分",
		["szDesc1"] = "查看自己的信誉分：通过菜单栏可以打开自己的信誉分列表。\n查看他人的信誉分：点击侠士头像可以在弹出的菜单中查看该侠士的信誉分。",
		["szDesc2"] = "信誉分过低时将<color=#F0DC82>无法参与</color>对应的活动玩法，可通过正常的游戏行为来恢复信誉分。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,8,1",
		["szImage1"] = "TeachBox/Teach_97.1.png",
		["szImage2"] = "TeachBox/Teach_97.2.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,信誉分"
	},
	[96] =
	{
		["nID"] = 96,
		["szLink"] = "",
		["szName"] = "战场总览",
		["szDesc1"] = "进入战场后，所有玩家被分为两个阵营，积分先到达六百分，或者战场结束时积分领先的一方获得胜利。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,3,1",
		["szImage1"] = "TeachBox/Teach_106.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,浮香丘"
	},
	[97] =
	{
		["nID"] = 97,
		["szLink"] = "",
		["szName"] = "占领据点",
		["szDesc1"] = "在旗帜附近即可增加占领据点进度，当旗帜变为本方旗帜时即为占领成功，旗帜附近己方玩家侠士越多占领速度越快。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,3,2",
		["szImage1"] = "TeachBox/Teach_107.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,浮香丘"
	},
	[98] =
	{
		["nID"] = 98,
		["szLink"] = "",
		["szName"] = "抢夺物资",
		["szDesc1"] = "每隔一段时间，已被占领的据点内会刷出本方的冷香菌宝箱，抢夺菌箱并带回营地。菌箱位置会暴露在地图上，注意保护己方菌箱/抢夺敌方菌箱。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,3,3",
		["szImage1"] = "TeachBox/Teach_108.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,浮香丘"
	},
	[99] =
	{
		["nID"] = 99,
		["szLink"] = "",
		["szName"] = "运送物资",
		["szDesc1"] = "携带菌箱的侠士将菌箱运回己方营地即可获得大量积分。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,3,4",
		["szImage1"] = "TeachBox/Teach_109.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,浮香丘"
	},
	[100] =
	{
		["nID"] = 100,
		["szLink"] = "",
		["szName"] = "战场总览",
		["szDesc1"] = "进入战场后，所有玩家被分为两个阵营，积分先到达一百分，或者战场结束时积分领先的一方获得胜利。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,5,1",
		["szImage1"] = "TeachBox/Teach_103.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,云湖天池"
	},
	[101] =
	{
		["nID"] = 101,
		["szLink"] = "",
		["szName"] = "抢夺擂旗",
		["szDesc1"] = "每隔一段时间，在场地中央的擂台上会刷新擂旗，成功夺得擂旗的一方会获得高分奖励。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,5,2",
		["szImage1"] = "TeachBox/Teach_104.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,云湖天池"
	},
	[102] =
	{
		["nID"] = 102,
		["szLink"] = "",
		["szName"] = "战场总览",
		["szDesc1"] = "进入战场后，所有玩家被分为两个阵营，成功运送完三个物资箱的一方获得胜利。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,4,1",
		["szImage1"] = "TeachBox/Teach_110.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,神农洇"
	},
	[103] =
	{
		["nID"] = 103,
		["szLink"] = "",
		["szName"] = "抢夺物资",
		["szDesc1"] = "每隔一段时间，天一教祭坛会刷出神秘物资宝箱，抢夺物资并带回营地即可获得分数。物资箱位置会暴露在地图上，注意保护己方物资运送者/抢夺敌方物资。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,4,2",
		["szImage1"] = "TeachBox/Teach_111.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,神农洇"
	},
	[104] =
	{
		["nID"] = 104,
		["szLink"] = "",
		["szName"] = "战场总览",
		["szDesc1"] = "进入战场后，所有玩家被分为两个阵营，积分先到达五百分，或者战场结束时积分领先的一方获得胜利。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,8,1",
		["szImage1"] = "TeachBox/Teach_117.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,三国古战场"
	},
	[105] =
	{
		["nID"] = 105,
		["szLink"] = "",
		["szName"] = "占领据点",
		["szDesc1"] = "在旗帜附近即可增加占领据点进度，当旗帜变为本方旗帜时即为占领成功，旗帜附近己方玩家侠士越多占领速度越快。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,8,2",
		["szImage1"] = "TeachBox/Teach_118.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,三国古战场"
	},
	[106] =
	{
		["nID"] = 106,
		["szLink"] = "",
		["szName"] = "战场总览",
		["szDesc1"] = "进入战场后，所有玩家被分为两个阵营，积分先到达一千分，或者战场结束时积分领先的一方获得胜利。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,7,1",
		["szImage1"] = "TeachBox/Teach_112.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,西风古道"
	},
	[107] =
	{
		["nID"] = 107,
		["szLink"] = "",
		["szName"] = "战场总览",
		["szDesc1"] = "进入战场后，所有玩家被分为两个阵营，积分先到达一千分，或者战场结束时积分领先的一方获得胜利。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,6,1",
		["szImage1"] = "TeachBox/Teach_100.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,九宫棋谷"
	},
	[108] =
	{
		["nID"] = 108,
		["szLink"] = "",
		["szName"] = "珍珑宝箱",
		["szDesc1"] = "每隔一段时间，在谷地的高台和中央的河谷中会刷新珍珑宝箱，成功开启宝箱的一方会获得高分奖励。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,6,2",
		["szImage1"] = "TeachBox/Teach_101.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,九宫棋谷"
	},
	[109] =
	{
		["nID"] = 109,
		["szLink"] = "",
		["szName"] = "武典残页",
		["szDesc1"] = "谷地四处会随机飘落武典残页，夺取残页可以获得积分奖励",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,6,3",
		["szImage1"] = "TeachBox/Teach_102.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,九宫棋谷"
	},
	[110] =
	{
		["nID"] = 110,
		["szLink"] = "",
		["szName"] = "占领据点",
		["szDesc1"] = "开启据点旗帜即可占领据点，当旗帜变为本方旗帜时即为占领成功。占领据点每隔一段时间可以获得积分。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,7,2",
		["szImage1"] = "TeachBox/Teach_113.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,西风古道"
	},
	[111] =
	{
		["nID"] = 111,
		["szLink"] = "",
		["szName"] = "运送镖银",
		["szDesc1"] = "战场开始后，可以与营地中的总镖头对话领取镖银，将镖银成功送到目的地即可获得积分。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,7,3",
		["szImage1"] = "TeachBox/Teach_114.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,西风古道"
	},
	[112] =
	{
		["nID"] = 112,
		["szLink"] = "",
		["szName"] = "阵营镖车",
		["szDesc1"] = "一方积分到达500分时，则会根据其占领的据点数量发出镖车，保护镖车到达运镖终点即可获得100积分，拦截敌方镖车可获得50积分。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,7,4",
		["szImage1"] = "TeachBox/Teach_115.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,西风古道"
	},
	[113] =
	{
		["nID"] = 113,
		["szLink"] = "",
		["szName"] = "运镖终点",
		["szDesc1"] = "双方的运镖终点均在敌方营地两侧，占据有利据点才能保护好货运路线。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,7,5",
		["szImage1"] = "TeachBox/Teach_116.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,西风古道"
	},
	[114] =
	{
		["nID"] = 114,
		["szLink"] = "",
		["szName"] = "习得身份",
		["szDesc1"] = "打开江湖百态（菜单-江湖百态）面板中查看艺人身份，点击追踪可查看解锁艺人身份相关NPC位置，在马嵬驿场景找到<color=#F0DC82>薛伶官</color>，开始艺人身份相关任务，完成任务后即可习得艺人身份。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "9,2,1",
		["szImage1"] = "TeachBox/Teach_119.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "技艺,艺人"
	},
	[115] =
	{
		["nID"] = 115,
		["szLink"] = "",
		["szName"] = "艺人表演",
		["szDesc1"] = "在习得艺人身份后在江湖百态中<color=#F0DC82>开启艺人</color>，可在地势平坦的区域开始<color=#F0DC82>艺人表演</color>，艺人表演中可展示舞姿。艺人表演可获得艺人经验，可提升艺人等级。",
		["szDesc2"] = "在艺人技能栏配置中，可以设置表演时的舞姿和表情动作，艺人等提升可解锁更多舞姿，也可通过艺人动作图纸习得更多舞姿。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "9,2,2",
		["szImage1"] = "TeachBox/Teach_120.png",
		["szImage2"] = "TeachBox/Teach_121.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "技艺,艺人"
	},
	[116] =
	{
		["nID"] = 116,
		["szLink"] = "",
		["szName"] = "打赏艺人",
		["szDesc1"] = "其他侠士在进行艺人表演时，其他侠士可通过与艺人花篮交互并<color=#F0DC82>打赏艺人</color>。",
		["szDesc2"] = "艺人收到打赏后，可以在礼物界面与打赏者进行互动。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "9,2,3",
		["szImage1"] = "TeachBox/Teach_122.png",
		["szImage2"] = "TeachBox/Teach_123.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "技艺,艺人"
	},
	[117] =
	{
		["nID"] = 117,
		["szLink"] = "",
		["szName"] = "习得身份",
		["szDesc1"] = "<color=#F0DC82>加入阵营</color>后，打开江湖百态（菜单-江湖百态）面板中查看镖师身份，点击追踪可查看解锁镖师身份相关NPC位置，在太原场景找到<color=#F0DC82>李放</color>，开始镖师身份相关任务，完成任务后即可习得镖师身份。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "9,3,1",
		["szImage1"] = "TeachBox/Teach_124.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "技艺,镖师"
	},
	[118] =
	{
		["nID"] = 118,
		["szLink"] = "",
		["szName"] = "护镖",
		["szDesc1"] = "在习得镖师身份后在江湖百态中<color=#F0DC82>开启镖师</color>，可与正在进行据点贸易（阵营跑商）的侠士组队，选中该侠士申请成为镖师，<color=#F0DC82>护送</color>其运送阵营货物。\n雇主成功将阵营货物运送到目的地后，即为完成一次护镖。",
		["szDesc2"] = "护镖过程中不可离雇主太远，每隔一段时间可获得镖师经验，可提升镖师等级。镖师等级越高能为雇主承受伤害的距离越大。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "9,3,2",
		["szImage1"] = "TeachBox/Teach_125.png",
		["szImage2"] = "TeachBox/Teach_126.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "技艺,镖师"
	},
	[119] =
	{
		["nID"] = 119,
		["szLink"] = "",
		["szName"] = "习得身份",
		["szDesc1"] = "打开江湖百态（菜单-江湖百态）面板中查看方士身份，点击追踪可查看解锁方士身份相关NPC位置，在扬州场景找到<color=#F0DC82>南宫麒</color>，开始方士身份相关任务，完成任务后即可习得方士身份。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "9,4,1",
		["szImage1"] = "TeachBox/Teach_127.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "技艺,方士"
	},
	[120] =
	{
		["nID"] = 120,
		["szLink"] = "",
		["szName"] = "进入魂墟",
		["szDesc1"] = "在习得方士身份后在江湖百态中<color=#F0DC82>开启方士</color>，可在扬州城使用出魂入定<color=#F0DC82>进入魂墟</color>。进入魂墟后对<color=#F0DC82>阴阳之力</color>使用点罡破煞技能可将其封印。\n使用还魂归体可<color=#F0DC82>退出魂墟</color>，前往该点打开寻宝轮盘即可开始挖宝。",
		["szDesc2"] = "已被封印的阴阳之力会被自动标记在中地图上，退出魂墟后可寻路到该点开始挖宝。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "9,4,2",
		["szImage1"] = "TeachBox/Teach_128.png",
		["szImage2"] = "TeachBox/Teach_129.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "技艺,方士"
	},
	[121] =
	{
		["nID"] = 121,
		["szLink"] = "",
		["szName"] = "探索魂墟",
		["szDesc1"] = "在魂墟中探索还有可能遭遇强大的精英魂灵，击败魂灵可获得丰厚奖励。除了魂灵之外，还会有其他际遇等着侠士探索。\n随着方士等级提升，还可解锁更多可入定的场景，每次入定时间也会随之提升。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "9,4,3",
		["szImage1"] = "TeachBox/Teach_130.png",
		["szImage2"] = "TeachBox/Teach_131.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "技艺,方士"
	},
	[122] =
	{
		["nID"] = 122,
		["szLink"] = "",
		["szName"] = "习得身份",
		["szDesc1"] = "打开江湖百态（菜单-江湖百态）面板中查看驭兽师身份，点击追踪可查看解锁驭兽师身份相关NPC位置，在成都地图找到<color=#F0DC82>秦玉川</color>，开始驭兽师身份相关任务，完成任务后即可习得驭兽师身份。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "9,5,1",
		["szImage1"] = "TeachBox/Teach_132.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "技艺,驭兽师"
	},
	[123] =
	{
		["nID"] = 123,
		["szLink"] = "",
		["szName"] = "驭兽",
		["szDesc1"] = "在习得驭兽师身份后在江湖百态中<color=#F0DC82>开启驭兽师</color>，可通过驭兽技能进入宠物操控视角，同时可以使用宠物相关技能。\n使用驭兽技能时，必须先将对应的宠物召唤出来，并且驭兽师不同等级下可以操控的宠物也不一样。\n可通过进入驭兽状态和宠物玩耍或参加宠物相关的活动来获取驭兽经验提升驭兽师等级",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "9,5,2",
		["szImage1"] = "TeachBox/Teach_133.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "技艺,驭兽师"
	},
	[124] =
	{
		["nID"] = 124,
		["szLink"] = "",
		["szName"] = "习得身份",
		["szDesc1"] = "<color=#F0DC82>加入阵营</color>后，打开江湖百态（菜单-江湖百态）面板中查看绿林身份，点击追踪可查看解锁绿林身份相关NPC位置，恶人谷在地图找到<color=#F0DC82>肖药儿</color>，浩气盟找到<color=#F0DC82>司空仲平</color>，开始绿林身份相关任务，完成任务后即可习得绿林身份。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "9,6,1",
		["szImage1"] = "TeachBox/Teach_134.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "技艺,绿林"
	},
	[125] =
	{
		["nID"] = 125,
		["szLink"] = "",
		["szName"] = "劫镖",
		["szDesc1"] = "在习得绿林身份后<color=#F0DC82>开启绿林</color>，可在敌对势力进行据点贸易（阵营跑商）时，在沿途埋设陷阱，敌方镖师或正在跑商的侠士踩上触发后将视线受阻、动弹不得。该陷阱会被镖师的技能识破。",
		["szDesc2"] = "使用哨声引人技能，召唤阿飞来到身边。可将抢夺来的物资和阵营货物交给阿飞送至行脚商换取威名与战阶。",
		["szDesc3"] = "埋设陷阱或劫镖可获取绿林经验来提升绿林等级，等级提升后将会习得更强大的陷阱技能。",
		["szDesc4"] = "",
		["szGroup"] = "9,6,1",
		["szImage1"] = "TeachBox/Teach_135.png",
		["szImage2"] = "TeachBox/Teach_136.png",
		["szImage3"] = "TeachBox/Teach_137.png",
		["szImage4"] = "",
		["szGroupDesc"] = "技艺,绿林"
	},
	[126] =
	{
		["nID"] = 126,
		["szLink"] = "",
		["szName"] = "分配方式",
		["szDesc1"] = "在首领战斗开始前，团长需要将队伍的<color=#F0DC82>分配模式</color>修改为<color=#F0DC82>拍团分配</color>，击败首领后则可以开始团队拍卖，在拍团分配模式下，只有<color=#F0DC82>团长</color>可以进行物品拍卖和分配的各项操作，其他团员只能通过出价竞拍物品。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,5,1",
		["szImage1"] = "TeachBox/Teach_138.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,团队拍卖"
	},
	[127] =
	{
		["nID"] = 127,
		["szLink"] = "",
		["szName"] = "拍卖入口",
		["szDesc1"] = "在击败首领后，可以通过<color=#F0DC82>拾取宝箱</color>或者点击主界面右上角<color=#F0DC82>团拍入口</color>打开掉落列表，开始团队拍卖。\n没有拾取权限的侠士将无法参与拍卖。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,5,2",
		["szImage1"] = "TeachBox/Teach_140.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,团队拍卖"
	},
	[128] =
	{
		["nID"] = 128,
		["szLink"] = "",
		["szName"] = "快速拍卖",
		["szDesc1"] = "<color=#F0DC82>开始拍卖</color>：一键开始道具拍卖，拍卖物品、起拍价格，加价幅度将由系统自动设置。\n<color=#F0DC82>一键0金分配</color>：一键分配材料、散件以及所有剩余物品，分配时系统会自动将价格设置为0。",
		["szDesc2"] = "除了一键拍卖和一键分配外，也可以单独针对某一件物品进行拍卖和分配。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,5,3",
		["szImage1"] = "TeachBox/Teach_144.png",
		["szImage2"] = "TeachBox/Teach_141.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,团队拍卖"
	},
	[129] =
	{
		["nID"] = 129,
		["szLink"] = "",
		["szName"] = "单件拍卖",
		["szDesc1"] = "<color=#F0DC82>出价</color>：对选中物品进行出价，当所出价格被超过时需要在结算前重新出价，否则将视作放弃对该物品的竞拍；\n<color=#F0DC82>结算</color>：团长可立即开始拍卖结算倒数，5秒后会自动将物品购买权分配给出价最高的侠士，接受分配的侠士将需要支付物品对应的金钱；\n<color=#F0DC82>重拍</color>：团长可重置拍卖，可以重新设置起拍价和加价，针对该物品的过往出价将作废；\n<color=#F0DC82>分配</color>：将物品直接分配给团队中的某位侠士，分配时可以设置物品价格，接受分配的侠士将需要支付物品对应的金钱。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,5,4",
		["szImage1"] = "TeachBox/Teach_142.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,团队拍卖"
	},
	[130] =
	{
		["nID"] = 130,
		["szLink"] = "",
		["szName"] = "拍卖付款",
		["szDesc1"] = "已经拍卖完成，还未付款的物品，侠士可以通过点击<color=#F0DC82>支付</color>来完成拍卖并获得物品，其他侠士可以通过选中物品，点击<color=#F0DC82>代付</color>按钮代为付款，付款后的物品依然会被分配给竞拍成功的侠士。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,5,5",
		["szImage1"] = "TeachBox/Teach_143.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,团队拍卖"
	},
	[131] =
	{
		["nID"] = 131,
		["szLink"] = "",
		["szName"] = "分配记录",
		["szDesc1"] = "拍卖中所有物品操作和金钱操作都可以在分配记录中查看。\n<color=#F0DC82>拍卖统计</color>：可查看所有的拍卖信息；\n<color=#F0DC82>收入分配</color>：可查看团员的消费情况以及收入情况；\n<color=#F0DC82>操作记录</color>：可查看所有分配记录和资金追加记录。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,5,6",
		["szImage1"] = "TeachBox/Teach_145.png",
		["szImage2"] = "TeachBox/Teach_146.png",
		["szImage3"] = "TeachBox/Teach_147.png",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,团队拍卖"
	},
	[132] =
	{
		["nID"] = 132,
		["szLink"] = "",
		["szName"] = "操作说明",
		["szDesc1"] = "当出现<color=#F0DC82>单击音符圈</color>时，当提示圈缩小到与判定圈<color=#F0DC82>重合</color>时单击该音符圈，提示圈越接近判定圈则评级越高。(使用键盘或手柄时有对应的快捷键)",
		["szDesc2"] = "当出现<color=#F0DC82>长按音符圈</color>时，当提示圈缩小到与判定圈<color=#F0DC82>重合</color>时<color=#F0DC82>长按</color>该音符圈，等待环形进度条<color=#F0DC82>完全消失</color>时<color=#F0DC82>松开</color>，提示圈越接近判定圈则评级越高。(使用键盘或手柄时有对应的快捷键)",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,2,1",
		["szImage1"] = "TeachBox/Teach_148.png",
		["szImage2"] = "TeachBox/Teach_149.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,尘世曼舞"
	},
	[133] =
	{
		["nID"] = 133,
		["szLink"] = "",
		["szName"] = "前往墨家机关城",
		["szDesc1"] = "在各大主城找到活动接引人<color=#F0DC82>陈只鱼</color>，接受任务<color=#F0DC82>六国异书</color>任务，并根据引导进入墨家机关城。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,3,1",
		["szImage1"] = "TeachBox/Teach_150.1.png",
		["szImage2"] = "TeachBox/Teach_150.2.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,故城墨影"
	},
	[134] =
	{
		["nID"] = 134,
		["szLink"] = "",
		["szName"] = "木偶加入编队",
		["szDesc1"] = "挑战关卡前，需要先进行阵型编队，<color=#F0DC82>选中</color>等待加入阵型的木偶，点击【<color=#F0DC82>目标进入阵型</color>】按钮，将该木偶加入阵型。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,3,2",
		["szImage1"] = "TeachBox/Teach_151.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,故城墨影"
	},
	[135] =
	{
		["nID"] = 135,
		["szLink"] = "",
		["szName"] = "木偶清出编队",
		["szDesc1"] = "已加入编队的木偶，可以通过<color=#F0DC82>选中</color>等待清出阵型的木偶，点击【<color=#F0DC82>目标清出阵型</color>】按钮可将目标清出阵型。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,3,3",
		["szImage1"] = "TeachBox/Teach_152.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,故城墨影"
	},
	[136] =
	{
		["nID"] = 136,
		["szLink"] = "",
		["szName"] = "开始关卡挑战",
		["szDesc1"] = "编队完成后，点击【<color=#F0DC82>开始关卡</color>】按钮随机开启一个可挑战的关卡。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,3,4",
		["szImage1"] = "TeachBox/Teach_153.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,故城墨影"
	},
	[137] =
	{
		["nID"] = 137,
		["szLink"] = "",
		["szName"] = "木偶控制",
		["szDesc1"] = "挑战关卡时，可通过调整<color=#F0DC82>木偶阵型</color>，<color=#F0DC82>攻击目标</color>以及<color=#F0DC82>跟随攻击</color>策略来提高效率。攻下当前关卡中所有的<color=#F0DC82>秦军据点</color>即可完成本次挑战。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,3,5",
		["szImage1"] = "TeachBox/Teach_156.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,故城墨影"
	},
	[138] =
	{
		["nID"] = 138,
		["szLink"] = "",
		["szName"] = "墨家机关沙盘",
		["szDesc1"] = "在沙盘可以查看所持墨卯数量、进行各类机关升级、领取阶段奖励、存储战略物资等操作。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,3,6",
		["szImage1"] = "TeachBox/Teach_154.png",
		["szImage2"] = "TeachBox/Teach_155.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,故城墨影"
	},
	[139] =
	{
		["nID"] = 139,
		["szLink"] = "",
		["szName"] = "墨卯获取",
		["szDesc1"] = "通过升级<color=#F0DC82>节用阁</color>可提高单位时间生成的墨卯数量，生成的墨卯会刷新在高渐离附近，需要<color=#F0DC82>靠近采集</color>。挑战关卡成功也可获得相应的墨卯。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,3,7",
		["szImage1"] = "TeachBox/Teach_157.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,故城墨影"
	},
	[140] =
	{
		["nID"] = 140,
		["szLink"] = "",
		["szName"] = "动态技能释放",
		["szDesc1"] = "动态技能释放除了点击右下角技能栏外，还可点击屏幕中间出现的技能图标，均可快速释放技能",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,9,1",
		["szImage1"] = "TeachBox/Teach_158.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,动态技能"
	},
	[141] =
	{
		["nID"] = 141,
		["szLink"] = "",
		["szName"] = "熬制腊八粥",
		["szDesc1"] = "活动期间，在主城的活动区找到【煮粥罐】，与之互动可开始熬制各式粥品。\n也可在背包中找到并使用各式粥料包（<color=#66CDAA>普通粥料包</color>、<color=#CD96CD>佳品粥料包</color>）进行熬制腊八粥操作。",
		["szDesc2"] = "选择消耗一种粥料包（<color=#66CDAA>普通粥料包</color>、<color=#CD96CD>佳品粥料包</color>）进行熬制。\n佳品粥料包相比普通粥料包在熬制时获得高品质腊八粥的概率更高。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,4,1",
		["szImage1"] = "TeachBox/Teach_159.png",
		["szImage2"] = "TeachBox/Teach_160.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,腊八节"
	},
	[142] =
	{
		["nID"] = 142,
		["szLink"] = "",
		["szName"] = "幻镜云图入口",
		["szDesc1"] = "玩家可通过快捷功能入口，打开幻镜云图功能，通过幻镜云图可以完成照片拍摄或视频拍摄。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,10,1",
		["szImage1"] = "TeachBox/Teach_162.png",
		["szImage2"] = "TeachBox/Teach_163.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,幻镜云图"
	},
	[143] =
	{
		["nID"] = 143,
		["szLink"] = "",
		["szName"] = "花灯巡游",
		["szDesc1"] = "在天街灯市场景中，找到花灯巡游队伍即可跟随参与花灯巡游。\n在巡游队伍范围内，选中范围内的花灯，使用焰火技能射中花灯即可获得巡游积分。若使用正确的技能击中对应的花灯可获得双倍积分！",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,5,1",
		["szImage1"] = "TeachBox/Teach_168.png",
		["szImage2"] = "TeachBox/Teach_169.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,春节"
	},
	[144] =
	{
		["nID"] = 144,
		["szLink"] = "",
		["szName"] = "巡游积分",
		["szDesc1"] = "使用<color=#F0DC82>焰火·月白</color>打中蓝色的灯笼，可获得两倍积分。\n使用<color=#F0DC82>焰火·红绯</color>打中红色和粉色的灯笼，可获得两倍积分。\n使用<color=#F0DC82>焰火·若竹</color>打中黄色和绿色的灯笼，可获得两倍积分。",
		["szDesc2"] = "和巡游队伍中的<color=#F0DC82>糖小乖</color>对话可获得糖葫芦，在巡游过程中将糖葫芦扔给路边<color=#F0DC82>要糖的小孩子</color>可获得积分！\n拾取<color=#F0DC82>烟花补给</color>，在巡游过程中点燃可获得积分！",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,5,2",
		["szImage1"] = "TeachBox/Teach_170.png",
		["szImage2"] = "TeachBox/Teach_171.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,春节"
	},
	[145] =
	{
		["nID"] = 145,
		["szLink"] = "",
		["szName"] = "主界面功能",
		["szDesc1"] = "在幻镜云图主界面中，可以选择拍照模式或视频模式，可通过滑动正上方的拉杆调整镜头远近，通过滑动右下的拉杆调整镜头倾斜角度，通过滑动右下的方向盘调整镜头方位。也可以通过点击暂停按钮来暂停角色动作进行抓拍。点击右下角的切换按钮可呼出角色技能面板。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,10,2",
		["szImage1"] = "TeachBox/Teach_164.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,幻镜云图"
	},
	[146] =
	{
		["nID"] = 146,
		["szLink"] = "",
		["szName"] = "高级功能",
		["szDesc1"] = "在功能设置界面中的基础分页中可以设置广角、景深、对焦距离等镜头高级参数。\n在显示分页中可以控制是否显示附近玩家、NPC以及控制外观各个部位的显示设置。\n在滤镜分页中可以选择喜欢的滤镜，同时还可以单独对滤镜进行微调。\n在灯光分页中可以选择在身边设置各种颜色的灯光。\n在知交分页中可以邀请已解锁的知交来到身边参与拍摄。",
		["szDesc2"] = "在表情动作界面中，可以选择已有的动作进行展示。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "1,10,3",
		["szImage1"] = "TeachBox/Teach_165.png",
		["szImage2"] = "TeachBox/Teach_166.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "基础,幻镜云图"
	},
	[147] =
	{
		["nID"] = 147,
		["szLink"] = "",
		["szName"] = "断线的风筝",
		["szDesc1"] = "在接取【断线的风筝】任务后，可在活动区域内选中<color=#F0DC82>灯笼或风筝</color>，使用<color=#F0DC82>踏云冲宵</color>技能可快速接近目标，每靠近一个未接触过的<color=#F0DC82>灯笼或风筝</color>即可获得对应的积分。积分在落地后会被记录并清除，只记录最高积分。积分达到500分以上可获得任务最高奖励。",
		["szDesc2"] = "使用<color=#F0DC82>踏宵迟坠</color>技能后，侠士可高高跃起减缓坠落，并重置一次跳跃，助力侠士扶摇之上，凌霄揽胜。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,6,1",
		["szImage1"] = "TeachBox/Teach_172.png",
		["szImage2"] = "TeachBox/Teach_173.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,元宵节"
	},
	[148] =
	{
		["nID"] = 148,
		["szLink"] = "",
		["szName"] = "识香匣",
		["szDesc1"] = "可在背包界面的<color=#F0DC82>玩具箱</color>中找到<color=#F0DC82>识香匣</color>并使用，即可打开使用香膏界面，点击香膏图标可查看香膏详细说明，点击效果按钮可直接使用香膏，点击调制香膏按钮可以打开香膏调制界面。通过家园储物箱的“使用香膏”按钮也可以快速打开玩具箱并定位到“识香匣”玩具",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "5,2,1",
		["szImage1"] = "TeachBox/Teach_174.png",
		["szImage2"] = "TeachBox/Teach_175.png",
		["szImage3"] = "TeachBox/Teach_176.png",
		["szImage4"] = "",
		["szGroupDesc"] = "家园,调香师"
	},
	[149] =
	{
		["nID"] = 149,
		["szLink"] = "",
		["szName"] = "调香",
		["szDesc1"] = "在调香界面中添加对应的<color=#F0DC82>香露和蜂蜡</color>即可开始调制香，可设置使用相同配方重复调制香膏多次。每调制一次需要消耗对应的<color=#F0DC82>香露、蜂蜡和精力值</color>。完成家园订单有概率获得香露，香露和蜂蜡均可在家园商店购买。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "5,2,2",
		["szImage1"] = "TeachBox/Teach_177.png",
		["szImage2"] = "TeachBox/Teach_178.png",
		["szImage3"] = "TeachBox/Teach_179.png",
		["szImage4"] = "",
		["szGroupDesc"] = "家园,调香师"
	},
	[150] =
	{
		["nID"] = 150,
		["szLink"] = "",
		["szName"] = "查看画卷",
		["szDesc1"] = "在接取“相逢不负·朝花描摹”后，可<color=#F0DC82>点击</color>快捷任务中的<color=#F0DC82>画卷图标</color>可查看画卷所示的地点。\n也可通过在背包中使用道具“<color=#F0DC82>江山如画</color>”来查看画卷所示的地点",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,7,1",
		["szImage1"] = "TeachBox/Teach_180.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,花朝节"
	},
	[151] =
	{
		["nID"] = 151,
		["szLink"] = "",
		["szName"] = "幻镜云图",
		["szDesc1"] = "可通过快捷功能入口，打开并使用幻镜云图功能。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,7,2",
		["szImage1"] = "TeachBox/Teach_181.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,花朝节"
	},
	[152] =
	{
		["nID"] = 152,
		["szLink"] = "",
		["szName"] = "云图概览",
		["szDesc1"] = "到达画卷所示位置后，可参照“<color=#F0DC82>云图概览”</color>来调整镜头角度，调整完镜头细节后点击拍照即可记录美景并完成任务。要在<color=#F0DC82>合适的位置附近</color>才能使用“云图概览”。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,7,3",
		["szImage1"] = "TeachBox/Teach_182.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,花朝节"
	},
	[153] =
	{
		["nID"] = 153,
		["szLink"] = "",
		["szName"] = "清明射柳",
		["szDesc1"] = "<color=#F0DC82>骑马状态</color>下与<color=#F0DC82>小蛋壳</color>对话并根据组队情况选择比赛模式，比赛开始后，需全程保持在小蛋壳身边，离开太远则会直接失败，需要重新对话开始比赛。到达终点后，积分越多，则获得的奖励也越多。",
		["szDesc2"] = "在赛道沿途会有<color=#F0DC82>鲜花</color>和<color=#F0DC82>陷阱</color>，踩到鲜花会增加积分，陷阱则会扣除积分，请尽量避开陷阱。\n此外侠士可对道路两侧的孔明灯释放射柳技能，射中柳枝孔明灯或桃枝孔明灯可获得更高积分。<color=#F0DC82>御风箭</color>释放速度更快但射程有限，<color=#F0DC82>穿林贯天</color>释放速度稍慢但射程更远。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,8,1",
		["szImage1"] = "TeachBox/Teach_183.png",
		["szImage2"] = "TeachBox/Teach_184.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,清明节"
	},
	[154] =
	{
		["nID"] = 154,
		["szLink"] = "",
		["szName"] = "玩法简介",
		["szDesc1"] = "侠士可在场景中搜索拾取宝藏，并在30分钟内，通过接应点撤离。在本玩法中，重伤敌对玩家可获得对方的物资，<color=#F0DC82>自身重伤则会损失除保险格以外的全部物资</color>。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,10,1",
		["szImage1"] = "TeachBox/Teach_185.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,寻宝模式"
	},
	[155] =
	{
		["nID"] = 155,
		["szLink"] = "",
		["szName"] = "战前-寻宝仓库",
		["szDesc1"] = "侠士在进入寻宝模式前，可先通过仓库-寻宝分页找到对应的寻宝仓库，在寻宝仓库中点击预设进入战前预设界面。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,10,2",
		["szImage1"] = "TeachBox/Teach_186.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,寻宝模式"
	},
	[156] =
	{
		["nID"] = 156,
		["szLink"] = "",
		["szName"] = "战前-装备预设",
		["szDesc1"] = "在战前预设界面中，可在预设装备中快捷购买并穿戴装备，在商店中购买对战物资完成开局预设。在界面中还可以查看预设的装备和物资的总价值。\n预设的装备和道具将会被带入寻宝玩法场景中。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,10,3",
		["szImage1"] = "TeachBox/Teach_187.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,寻宝模式"
	},
	[157] =
	{
		["nID"] = 157,
		["szLink"] = "",
		["szName"] = "被重伤侠士掉落",
		["szDesc1"] = "侠士被击败后，<color=#F0DC82>仅保留</color>背包中的保险格内的物资，不包括纷争宝箱和装备。其余物资掉落，可被其他玩家拾取。物资掉落时有概率损毁消失。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,10,4",
		["szImage1"] = "TeachBox/Teach_188.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,寻宝模式"
	},
	[158] =
	{
		["nID"] = 158,
		["szLink"] = "",
		["szName"] = "接应点",
		["szDesc1"] = "在场景内接应点的蓝色光圈内等待接应点的撤离倒计时结束后，将成功撤离结束本局游戏。侠士在场景中生存时间越长，在接应点所需的撤离时长就越短。每生存十分钟，所需撤离时长减少5秒。最短可在接应点内生存20秒后离开场景。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,10,5",
		["szImage1"] = "TeachBox/Teach_189.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,寻宝模式"
	},
	[159] =
	{
		["nID"] = 159,
		["szLink"] = "",
		["szName"] = "武器专属技能",
		["szDesc1"] = "侠士<color=#F0DC82>自身门派技能</color>不会带入本玩法中。侠士可通过使用不同门派的武器获得对应的不同门派技能。特殊腰坠、项链也带有技能。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,10,6",
		["szImage1"] = "TeachBox/Teach_190.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,寻宝模式"
	},
	[160] =
	{
		["nID"] = 160,
		["szLink"] = "",
		["szName"] = "宝藏及宝箱",
		["szDesc1"] = "在寻宝模式中，场景中有需要可以拾取的宝藏及宝箱供侠士探索。品质越高的宝藏或宝箱可获得更高价值的藏品。\n可在场景中直接拾取到神工宝藏；亦可通过拾取场景中的命定宝箱或其他宝藏，概率获得神工宝藏。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,10,7",
		["szImage1"] = "TeachBox/Teach_191.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,寻宝模式"
	},
	[161] =
	{
		["nID"] = 161,
		["szLink"] = "",
		["szName"] = "场内载具",
		["szDesc1"] = "场景中有专属载具，可较大提高侠士的行进速度。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,10,8",
		["szImage1"] = "TeachBox/Teach_192.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,寻宝模式"
	},
	[162] =
	{
		["nID"] = 162,
		["szLink"] = "",
		["szName"] = "救援队友",
		["szDesc1"] = "队友死亡后，在队伍界面中将显示等待救援倒计时。<color=#F0DC82>在倒计时结束前</color>.，可根据救援追踪抵达队友倒地处，并交互队友的【叹息风碑】救援队友，超时重伤队友将无法再被救援。\n请注意，每位队员只能被救治一次。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,10,9",
		["szImage1"] = "TeachBox/Teach_193.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,寻宝模式"
	},
	[163] =
	{
		["nID"] = 163,
		["szLink"] = "",
		["szName"] = "首领标记",
		["szDesc1"] = "游戏开始后，场景中会随机刷新<color=#F0DC82>区域事件</color>和<color=#F0DC82>首领</color>，击败后可获得事件奖励及掉落奖励。\n击败首领后会在附近刷新三个<color=#F0DC82>首领宝箱</color>.",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,10,10",
		["szImage1"] = "TeachBox/Teach_194.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,寻宝模式"
	},
	[164] =
	{
		["nID"] = 164,
		["szLink"] = "",
		["szName"] = "接应点条件",
		["szDesc1"] = "侠士可在地图中浏览本场次所有的接应点，不同的接应点开放条件不同。普通接应点无人数和时间限制，有限撤离点则必须<color=#F0DC82>完成对应的条件</color>才可撤离。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,10,11",
		["szImage1"] = "TeachBox/Teach_195.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,寻宝模式"
	},
	[165] =
	{
		["nID"] = 165,
		["szLink"] = "",
		["szName"] = "背包设置",
		["szDesc1"] = "在背包中点击设置按钮，可进入背包设置。在设置中可配置技能、自动拾取以及快捷丢弃的详细内容。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,10,12",
		["szImage1"] = "TeachBox/Teach_196.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,寻宝模式"
	},
	[166] =
	{
		["nID"] = 166,
		["szLink"] = "",
		["szName"] = "背包结算",
		["szDesc1"] = "在背包界面中可查看背包中所有物品以及所有装备的价值。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,10,13",
		["szImage1"] = "TeachBox/Teach_197.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,寻宝模式"
	},
	[167] =
	{
		["nID"] = 167,
		["szLink"] = "",
		["szName"] = "逃离结算",
		["szDesc1"] = "成功撤离时，<color=#F0DC82>装备栏中</color>的装备会被带出，背包中<color=#F0DC82>紫色</color>和<color=#F0DC82>橙色</color>品质的装备会被带出，其他品质的装备会被自动出售，绝大部分物资也会被自动出售，兑换为<color=#F0DC82>奇境宝钞</color>进行结算。之后根据装备及背包中的装备和物资的总价值进行评级。\n每次成功逃离将会积累相应的寻宝经验，升级寻宝等级后可获得奖励。寻宝等级对应的奖励每赛季更新。\n请注意，许多道具仅可在该模式场景中使用，如成功撤离时未使用这类道具，则会被结算为奇境宝钞。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,10,14",
		["szImage1"] = "TeachBox/Teach_198.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,寻宝模式"
	},
	[168] =
	{
		["nID"] = 168,
		["szLink"] = "",
		["szName"] = "赛季重置",
		["szDesc1"] = "赛季结束时将重置背包、仓库格子进度，并会废除所有寻宝道具、装备和奇境宝钞（宝箱及宝箱开出的非寻宝道具奖励如奇趣坐骑碎片、奇趣坐骑等除外）。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "10,10,15",
		["szImage1"] = "TeachBox/Teach_200.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "竞技,寻宝模式"
	},
	[169] =
	{
		["nID"] = 169,
		["szLink"] = "",
		["szName"] = "觅句成章",
		["szDesc1"] = "按顺序点击或拖动连接诗句，只有正确连接，诗句才会显示颜色。多次连接错误后，会触发正确提示。连出本关所有诗词，即可成功通关！",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,9,1",
		["szImage1"] = "TeachBox/Teach_201.png",
		["szImage2"] = "",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,觅句成章"
	},
	[170] =
	{
		["nID"] = 170,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelBaizhanMain)",
		["szName"] = "异象首领",
		["szDesc1"] = "在81至100层，部分首领可能会转化为异象首领，战力变得更为强大。\n击败异象首领后将获得全新的招式要诀、相当于精英首领级别的修罗之印以及其他特殊奖励。",
		["szDesc2"] = "若自感实力不足，可与剑圣对话将该层还原为异象变化前的原首领。\n但请注意，还原后在本秘境无法再次转化为异象首领。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,2,9",
		["szImage1"] = "TeachBox/Teach_202.png",
		["szImage2"] = "TeachBox/Teach_203.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,百战异闻录"
	},
	[171] =
	{
		["nID"] = 171,
		["szLink"] = "UIMgr.Open(VIEW_ID.PanelBaizhanMain)",
		["szName"] = "换将功能",
		["szDesc1"] = "现已支持在第90层或100层，将精英首领替换为其他首领。选中精英首领后，点击头像右下角的切换按钮，可选择首领替换。",
		["szDesc2"] = "击败替换的首领，需消耗换将点方可获得掉落奖励。该点数可通过完成百战周常任务或击败第100层首领获得。\n90层消耗10点，100层消耗20点。",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "3,2,10",
		["szImage1"] = "TeachBox/Teach_204.png",
		["szImage2"] = "TeachBox/Teach_205.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "秘境,百战异闻录"
	},
	[172] =
	{
		["nID"] = 172,
		["szLink"] = "",
		["szName"] = "宵宵乐-消除规则",
		["szDesc1"] = "基础消除：选中一个图案，按住滑动使其和上下左右相邻的一个其他图案交换位置，交换后如果有<color=#F0DC82>三个相同图案</color>的组成一行，即可成功消除获得积分。",
		["szDesc2"] = "相邻消除：在触发消除时，会同时消除<color=#F0DC82>全部相邻</color>的相同图案。",
		["szDesc3"] = "五连消除：在触发横向或纵向<color=#F0DC82>五个相同图案</color>消除时，会清除棋盘上所有相同图案。",
		["szDesc4"] = "",
		["szGroup"] = "11,6,2",
		["szImage1"] = "TeachBox/Teach_206.png",
		["szImage2"] = "TeachBox/Teach_207.png",
		["szImage3"] = "TeachBox/Teach_208.png",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,元宵节"
	},
	[173] =
	{
		["nID"] = 173,
		["szLink"] = "",
		["szName"] = "宵宵乐-侠客能量",
		["szDesc1"] = "在触发消除时，消除对应的图案可以给对应的侠客增加能量，能量满就可以自动触发侠客技能。侠客技能可以加速消除图案，不同侠客技能各有不同。",
		["szDesc2"] = "",
		["szDesc3"] = "",
		["szDesc4"] = "",
		["szGroup"] = "11,6,3",
		["szImage1"] = "TeachBox/Teach_209.png",
		["szImage2"] = "TeachBox/Teach_210.png",
		["szImage3"] = "",
		["szImage4"] = "",
		["szGroupDesc"] = "休闲,元宵节"
	}
}