--*************************************** 工具生成 ***************************************
UIWorldMapZoningTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["nSize"]=150,
        ["szName"]="明教",
        ["szFrame"]="UIAtlas2_Map_CityIcon_MingJiao.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetMingJiao",
        ["szChildCityMaps"]="{150}",
        ["szChildCopyMaps"]="{142}"
    },
    [2]=
    {
        ["nID"]=2,
        ["nSize"]=150,
        ["szName"]="恶人谷",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ERenGu.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_baohu.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetERenGu",
        ["szChildCityMaps"]="{27}",
        ["szChildCopyMaps"]="{}"
    },
    [3]=
    {
        ["nID"]=3,
        ["nSize"]=150,
        ["szName"]="龙门荒漠",
        ["szFrame"]="UIAtlas2_Map_CityIcon_LongMengHuangMo.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetLongMenHuangMo",
        ["szChildCityMaps"]="{23}",
        ["szChildCopyMaps"]="{34,668}"
    },
    [4]=
    {
        ["nID"]=4,
        ["nSize"]=150,
        ["szName"]="黑戈壁",
        ["szFrame"]="UIAtlas2_Map_CityIcon_HeiGeBi.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetHeiGeBi",
        ["szChildCityMaps"]="{217}",
        ["szChildCopyMaps"]="{}"
    },
    [5]=
    {
        ["nID"]=5,
        ["nSize"]=150,
        ["szName"]="昆仑",
        ["szFrame"]="UIAtlas2_Map_CityIcon_KunLun.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhanzheng.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetKunLun",
        ["szChildCityMaps"]="{30}",
        ["szChildCopyMaps"]="{793}"
    },
    [6]=
    {
        ["nID"]=6,
        ["nSize"]=150,
        ["szName"]="凌雪阁",
        ["szFrame"]="UIAtlas2_Map_CityIcon_LingXueGe.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetLingXueGe",
        ["szChildCityMaps"]="{419}",
        ["szChildCopyMaps"]="{431}"
    },
    [7]=
    {
        ["nID"]=7,
        ["nSize"]=150,
        ["szName"]="苍云",
        ["szFrame"]="UIAtlas2_Map_CityIcon_CangYun.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetCangYun",
        ["szChildCityMaps"]="{193}",
        ["szChildCopyMaps"]="{196}"
    },
    [8]=
    {
        ["nID"]=8,
        ["nSize"]=150,
        ["szName"]="五台山",
        ["szFrame"]="UIAtlas2_Map_CityIcon_WuTaiShan.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetWuTaiShan",
        ["szChildCityMaps"]="{214}",
        ["szChildCopyMaps"]="{209,452}"
    },
    [9]=
    {
        ["nID"]=9,
        ["nSize"]=150,
        ["szName"]="阴山大草原",
        ["szFrame"]="UIAtlas2_Map_CityIcon_YinShanDaCaoYuan.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetYinShanDaCaoYuan",
        ["szChildCityMaps"]="{216}",
        ["szChildCopyMaps"]="{204}"
    },
    [10]=
    {
        ["nID"]=10,
        ["nSize"]=150,
        ["szName"]="太原",
        ["szFrame"]="UIAtlas2_Map_CityIcon_TaiYuan.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetTaiYuan",
        ["szChildCityMaps"]="{194}",
        ["szChildCopyMaps"]="{191,192,203,283,284,298,299,521}"
    },
    [11]=
    {
        ["nID"]=11,
        ["nSize"]=150,
        ["szName"]="霸刀山庄",
        ["szFrame"]="UIAtlas2_Map_CityIcon_BaDao.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetBaDao",
        ["szChildCityMaps"]="{243}",
        ["szChildCopyMaps"]="{256,262,263,264,}"
    },
    [12]=
    {
        ["nID"]=12,
        ["nSize"]=150,
        ["szName"]="天策·战乱",
        ["szFrame"]="UIAtlas2_Map_CityIcon_TianCe.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~67",
        ["szWidgetName"]="WidgetTianCe",
        ["szChildCityMaps"]="{11,158}",
        ["szChildCopyMaps"]="{20,573}"
    },
    [13]=
    {
        ["nID"]=13,
        ["nSize"]=150,
        ["szName"]="洛阳·战乱",
        ["szFrame"]="UIAtlas2_Map_CityIcon_LuoYang.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~67",
        ["szWidgetName"]="WidgetLuoYang",
        ["szChildCityMaps"]="{8,151,239,152}",
        ["szChildCopyMaps"]="{639,32,240,241,160,175}"
    },
    [14]=
    {
        ["nID"]=14,
        ["nSize"]=150,
        ["szName"]="少林·乱世",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ShaoLin.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~100",
        ["szWidgetName"]="WidgetShaoLin",
        ["szChildCityMaps"]="{5,475}",
        ["szChildCopyMaps"]="{479,482,14,60,131}"
    },
    [15]=
    {
        ["nID"]=15,
        ["nSize"]=150,
        ["szName"]="金水镇",
        ["szFrame"]="UIAtlas2_Map_CityIcon_JinShuiZhen.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetJinShuiZhen",
        ["szChildCityMaps"]="{13}",
        ["szChildCopyMaps"]="{}"
    },
    [16]=
    {
        ["nID"]=16,
        ["nSize"]=150,
        ["szName"]="扬州",
        ["szFrame"]="UIAtlas2_Map_CityIcon_YangZhou.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetYangZhou",
        ["szChildCityMaps"]="{6}",
        ["szChildCopyMaps"]="{}"
    },
    [17]=
    {
        ["nID"]=17,
        ["nSize"]=150,
        ["szName"]="七秀·乱世",
        ["szFrame"]="UIAtlas2_Map_CityIcon_QiXiu.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~100",
        ["szWidgetName"]="WidgetQiXiu",
        ["szChildCityMaps"]="{16,474}",
        ["szChildCopyMaps"]="{477,18}"
    },
    [18]=
    {
        ["nID"]=18,
        ["nSize"]=150,
        ["szName"]="稻香村",
        ["szFrame"]="UIAtlas2_Map_CityIcon_DaoXiangCun.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetDaoXiangCun",
        ["szChildCityMaps"]="{653}",
        ["szChildCopyMaps"]="{}"
    },
    [19]=
    {
        ["nID"]=19,
        ["nSize"]=150,
        ["szName"]="南屏山",
        ["szFrame"]="UIAtlas2_Map_CityIcon_NanPingShan.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhanzheng.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetNanPingShan",
        ["szChildCityMaps"]="{22}",
        ["szChildCopyMaps"]="{33}"
    },
    [20]=
    {
        ["nID"]=20,
        ["nSize"]=150,
        ["szName"]="藏剑·乱世",
        ["szFrame"]="UIAtlas2_Map_CityIcon_CangJian.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~100",
        ["szWidgetName"]="WidgetCangJian",
        ["szChildCityMaps"]="{49,488}",
        ["szChildCopyMaps"]="{468,51,126}"
    },
    [21]=
    {
        ["nID"]=21,
        ["nSize"]=150,
        ["szName"]="长歌门",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ChangGeMen.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetChangGeMen",
        ["szChildCityMaps"]="{213}",
        ["szChildCopyMaps"]="{219}"
    },
    [22]=
    {
        ["nID"]=22,
        ["nSize"]=150,
        ["szName"]="千岛湖",
        ["szFrame"]="UIAtlas2_Map_CityIcon_QianDaoHu.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetQianDaoHu",
        ["szChildCityMaps"]="{215,621}",
        ["szChildCopyMaps"]="{218,220,221,629}"
    },
    [23]=
    {
        ["nID"]=23,
        ["nSize"]=150,
        ["szName"]="蔷薇列岛",
        ["szFrame"]="UIAtlas2_Map_CityIcon_QiangWeiLieDao.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetQiangWeiLieDao",
        ["szChildCityMaps"]="{444}",
        ["szChildCopyMaps"]="{}"
    },
    [24]=
    {
        ["nID"]=24,
        ["nSize"]=150,
        ["szName"]="洞天福地岛",
        ["szFrame"]="UIAtlas2_Map_CityIcon_DongTianFuDi.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetDongTianFuDi",
        ["szChildCityMaps"]="{325}",
        ["szChildCopyMaps"]="{337}"
    },
    [25]=
    {
        ["nID"]=25,
        ["nSize"]=150,
        ["szName"]="经首道源岛",
        ["szFrame"]="UIAtlas2_Map_CityIcon_JingShouDaoYuanDao.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetJingShouDaoYuanDao",
        ["szChildCityMaps"]="{334}",
        ["szChildCopyMaps"]="{339}"
    },
    [26]=
    {
        ["nID"]=26,
        ["nSize"]=150,
        ["szName"]="鲲鹏岛",
        ["szFrame"]="UIAtlas2_Map_CityIcon_KunPengDao.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetKunPengDao",
        ["szChildCityMaps"]="{411}",
        ["szChildCopyMaps"]="{406,364,368}"
    },
    [27]=
    {
        ["nID"]=27,
        ["nSize"]=150,
        ["szName"]="蓬莱",
        ["szFrame"]="UIAtlas2_Map_CityIcon_PengLai.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetPengLai",
        ["szChildCityMaps"]="{333}",
        ["szChildCopyMaps"]="{342,426}"
    },
    [28]=
    {
        ["nID"]=28,
        ["nSize"]=150,
        ["szName"]="侠客岛",
        ["szFrame"]="UIAtlas2_Map_CityIcon_XiaKeDao.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetXiaKeDao",
        ["szChildCityMaps"]="{332}",
        ["szChildCopyMaps"]="{358,341,347}"
    },
    [29]=
    {
        ["nID"]=29,
        ["nSize"]=150,
        ["szName"]="寇岛",
        ["szFrame"]="UIAtlas2_Map_CityIcon_KouDao.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetKouDao",
        ["szChildCityMaps"]="{10}",
        ["szChildCopyMaps"]="{28,61}"
    },
    [30]=
    {
        ["nID"]=30,
        ["nSize"]=150,
        ["szName"]="巴陵县",
        ["szFrame"]="UIAtlas2_Map_CityIcon_BaLing.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetBaLing",
        ["szChildCityMaps"]="{21}",
        ["szChildCopyMaps"]="{}"
    },
    [31]=
    {
        ["nID"]=31,
        ["nSize"]=150,
        ["szName"]="丐帮",
        ["szFrame"]="UIAtlas2_Map_CityIcon_GaiBang.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetGaiBang",
        ["szChildCityMaps"]="{159}",
        ["szChildCopyMaps"]="{169}"
    },
    [32]=
    {
        ["nID"]=32,
        ["nSize"]=150,
        ["szName"]="浩气盟",
        ["szFrame"]="UIAtlas2_Map_CityIcon_HaoQiMeng.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_baohu.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetHaoQiMeng",
        ["szChildCityMaps"]="{25}",
        ["szChildCopyMaps"]="{}"
    },
    [33]=
    {
        ["nID"]=33,
        ["nSize"]=150,
        ["szName"]="洛道",
        ["szFrame"]="UIAtlas2_Map_CityIcon_LuoDao.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetLuoDao",
        ["szChildCityMaps"]="{9}",
        ["szChildCopyMaps"]="{177,292,285}"
    },
    [34]=
    {
        ["nID"]=34,
        ["nSize"]=150,
        ["szName"]="枫华谷·战乱",
        ["szFrame"]="UIAtlas2_Map_CityIcon_FengHuaGu.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhanzheng.png",
        ["szShowLevel"]="0~67",
        ["szWidgetName"]="WidgetFengHuaGu",
        ["szChildCityMaps"]="{12,139}",
        ["szChildCopyMaps"]="{26,67,68,120}"
    },
    [35]=
    {
        ["nID"]=35,
        ["nSize"]=150,
        ["szName"]="纯阳",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ChunYang.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetChunYang",
        ["szChildCityMaps"]="{7}",
        ["szChildCopyMaps"]="{19}"
    },
    [36]=
    {
        ["nID"]=36,
        ["nSize"]=150,
        ["szName"]="帮会领地",
        ["szFrame"]="UIAtlas2_Map_CityIcon_BangHuiLingDi.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetBangHuiLingDi",
        ["szChildCityMaps"]="{}",
        ["szChildCopyMaps"]="{74}"
    },
    [37]=
    {
        ["nID"]=37,
        ["nSize"]=150,
        ["szName"]="万花·乱世",
        ["szFrame"]="UIAtlas2_Map_CityIcon_WanHua.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~100",
        ["szWidgetName"]="WidgetWanHua",
        ["szChildCityMaps"]="{2,473}",
        ["szChildCopyMaps"]="{489,17}"
    },
    [38]=
    {
        ["nID"]=38,
        ["nSize"]=150,
        ["szName"]="瞿塘峡",
        ["szFrame"]="UIAtlas2_Map_CityIcon_QuTangXia.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetQuTangXia",
        ["szChildCityMaps"]="{35}",
        ["szChildCopyMaps"]="{200,242,518}"
    },
    [39]=
    {
        ["nID"]=39,
        ["nSize"]=150,
        ["szName"]="白龙口",
        ["szFrame"]="UIAtlas2_Map_CityIcon_BaiLongKou.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetBaiLongKou",
        ["szChildCityMaps"]="{100}",
        ["szChildCopyMaps"]="{106}"
    },
    [40]=
    {
        ["nID"]=40,
        ["nSize"]=150,
        ["szName"]="唐门",
        ["szFrame"]="UIAtlas2_Map_CityIcon_TangMen.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetTangMen",
        ["szChildCityMaps"]="{122}",
        ["szChildCopyMaps"]="{123}"
    },
    [41]=
    {
        ["nID"]=41,
        ["nSize"]=150,
        ["szName"]="五毒",
        ["szFrame"]="UIAtlas2_Map_CityIcon_WuDu.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetWuDu",
        ["szChildCityMaps"]="{102}",
        ["szChildCopyMaps"]="{116}"
    },
    [42]=
    {
        ["nID"]=42,
        ["nSize"]=150,
        ["szName"]="融天岭",
        ["szFrame"]="UIAtlas2_Map_CityIcon_RongTianLing.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetRongTianLing",
        ["szChildCityMaps"]="{103}",
        ["szChildCopyMaps"]="{110}"
    },
    [43]=
    {
        ["nID"]=43,
        ["nSize"]=150,
        ["szName"]="苍山洱海",
        ["szFrame"]="UIAtlas2_Map_CityIcon_CangShanEr.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetCangShanErHai",
        ["szChildCityMaps"]="{105}",
        ["szChildCopyMaps"]="{140}"
    },
    [44]=
    {
        ["nID"]=44,
        ["nSize"]=150,
        ["szName"]="无量山",
        ["szFrame"]="UIAtlas2_Map_CityIcon_WuLiangShan.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetWuLiangShan",
        ["szChildCityMaps"]="{101}",
        ["szChildCopyMaps"]="{107}"
    },
    [45]=
    {
        ["nID"]=45,
        ["nSize"]=150,
        ["szName"]="黑龙沼",
        ["szFrame"]="UIAtlas2_Map_CityIcon_HeiLongZhao.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetHeiLongZhao",
        ["szChildCityMaps"]="{104}",
        ["szChildCopyMaps"]="{75,134}"
    },
    [46]=
    {
        ["nID"]=46,
        ["nSize"]=150,
        ["szName"]="长安",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ChangAn.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~67",
        ["szWidgetName"]="WidgetChangAn",
        ["szChildCityMaps"]="{701,15,156,172}",
        ["szChildCopyMaps"]="{706,710,711,161,179,163,184,187,164,182}"
    },
    [47]=
    {
        ["nID"]=47,
        ["nSize"]=150,
        ["szName"]="马嵬驿",
        ["szFrame"]="UIAtlas2_Map_CityIcon_MaWeiYi.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhanzheng.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetMaWeiYi",
        ["szChildCityMaps"]="{153}",
        ["szChildCopyMaps"]="{167}"
    },
    [48]=
    {
        ["nID"]=48,
        ["nSize"]=150,
        ["szName"]="成都",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ChengDu.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetChengDu",
        ["szChildCityMaps"]="{108}",
        ["szChildCopyMaps"]="{109,136}"
    },
    [49]=
    {
        ["nID"]=49,
        ["nSize"]=150,
        ["szName"]="龙泉府",
        ["szFrame"]="UIAtlas2_Map_CityIcon_LongQuanFu.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetLongQuanFu",
        ["szChildCityMaps"]="{330}",
        ["szChildCopyMaps"]="{340}"
    },
    [50]=
    {
        ["nID"]=50,
        ["nSize"]=150,
        ["szName"]="衍天宗",
        ["szFrame"]="UIAtlas2_Map_CityIcon_YanTianZong.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetYanTianZong",
        ["szChildCityMaps"]="{464}",
        ["szChildCopyMaps"]="{476}"
    },
    [51]=
    {
        ["nID"]=51,
        ["nSize"]=150,
        ["szName"]="北天药宗",
        ["szFrame"]="UIAtlas2_Map_CityIcon_BeiTianYaoZong.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetBeiTianYaoZong",
        ["szChildCityMaps"]="{526}",
        ["szChildCopyMaps"]="{563}"
    },
    [52]=
    {
        ["nID"]=52,
        ["nSize"]=150,
        ["szName"]="黑山林海",
        ["szFrame"]="UIAtlas2_Map_CityIcon_HeiShanLinHaiXin.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetHeiShanLinHai",
        ["szChildCityMaps"]="{525}",
        ["szChildCopyMaps"]="{559}"
    },
    [53]=
    {
        ["nID"]=53,
        ["nSize"]=150,
        ["szName"]="烂柯山",
        ["szFrame"]="UIAtlas2_Map_CityIcon_LanKeShan.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetLanKeShan",
        ["szChildCityMaps"]="{580}",
        ["szChildCopyMaps"]="{596}"
    },
    [54]=
    {
        ["nID"]=54,
        ["nSize"]=150,
        ["szName"]="百溪",
        ["szFrame"]="UIAtlas2_Map_CityIcon_BaiXi.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetBaiXi",
        ["szChildCityMaps"]="{579}",
        ["szChildCopyMaps"]="{598}"
    },
    [55]=
    {
        ["nID"]=55,
        ["nSize"]=150,
        ["szName"]="晟江",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ShengJiang.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetShengJiang",
        ["szChildCityMaps"]="{582}",
        ["szChildCopyMaps"]="{586}"
    },
    [56]=
    {
        ["nID"]=56,
        ["nSize"]=150,
        ["szName"]="楚州",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ChuZhou.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetChuZhou",
        ["szChildCityMaps"]="{581}",
        ["szChildCopyMaps"]="{622,636}"
    },
    [57]=
    {
        ["nID"]=57,
        ["nSize"]=150,
        ["szName"]="刀宗",
        ["szFrame"]="UIAtlas2_Map_CityIcon_DaoZong.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetDaoZong",
        ["szChildCityMaps"]="{578}",
        ["szChildCopyMaps"]="{606}"
    },
    [58]=
    {
        ["nID"]=58,
        ["nSize"]=150,
        ["szName"]="万灵山庄",
        ["szFrame"]="UIAtlas2_Map_CityIcon_WanLingShanZhuang.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetWanLingShanZhuang",
        ["szChildCityMaps"]="{642}",
        ["szChildCopyMaps"]="{658}"
    },
    [59]=
    {
        ["nID"]=59,
        ["nSize"]=150,
        ["szName"]="银霜口",
        ["szFrame"]="UIAtlas2_Map_CityIcon_YinShuangKou.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetYinShuangKou",
        ["szChildCityMaps"]="{647}",
        ["szChildCopyMaps"]="{648}"
    },
    [60]=
    {
        ["nID"]=60,
        ["nSize"]=256,
        ["szName"]="河西瀚漠",
        ["szFrame"]="UIAtlas2_Map_CityIcon_HeXiHanMo.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetHeXiHanMo",
        ["szChildCityMaps"]="{673}",
        ["szChildCopyMaps"]="{697,693,690,684,686,720}"
    },
    [61]=
    {
        ["nID"]=61,
        ["nSize"]=115,
        ["szName"]="南诏段氏",
        ["szFrame"]="UIAtlas2_Map_CityIcon_NanZhaoDuanShi.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetNanZhaoDuanShi",
        ["szChildCityMaps"]="{666}",
        ["szChildCopyMaps"]="{682}"
    },
    [62]=
    {
        ["nID"]=62,
        ["nSize"]=150,
        ["szName"]="永宁湾",
        ["szFrame"]="UIAtlas2_Map_CityIcon_YongNingWan.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_tingzhan.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetYongNingWan",
        ["szChildCityMaps"]="{718}",
        ["szChildCopyMaps"]="{726}"
    },
    [63]=
    {
        ["nID"]=63,
        ["nSize"]=150,
        ["szName"]="伊丽川",
        ["szFrame"]="UIAtlas2_Map_CityIcon_YiLiChuan.png",
        ["szCampFrame"]="UIAtlas2_Map_MapIcon_icon_zhengduo.png",
        ["szShowLevel"]="0~max",
        ["szWidgetName"]="WidgetYiLiChuan",
        ["szChildCityMaps"]="{713}",
        ["szChildCopyMaps"]="{722}"
    }
}
