--*************************************** 工具生成 ***************************************
UIWorldMapCityTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["nMapID"]=6,
        ["szType"]="主城",
        ["szFrame"]="UIAtlas2_Map_CityIcon_YangZhou.png",
        ["szComment"]="扬州",
        ["nTrafficID"]=6,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [2]=
    {
        ["nID"]=2,
        ["nMapID"]=2,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_WanHua.png",
        ["szComment"]="万花",
        ["nTrafficID"]=2,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [3]=
    {
        ["nID"]=3,
        ["nMapID"]=27,
        ["szType"]="阵营",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ERenGu.png",
        ["szComment"]="恶人谷",
        ["nTrafficID"]=27,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [4]=
    {
        ["nID"]=4,
        ["nMapID"]=25,
        ["szType"]="阵营",
        ["szFrame"]="UIAtlas2_Map_CityIcon_HaoQiMeng.png",
        ["szComment"]="浩气盟",
        ["nTrafficID"]=25,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [5]=
    {
        ["nID"]=5,
        ["nMapID"]=653,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_DaoXiangCun.png",
        ["szComment"]="稻香村",
        ["nTrafficID"]=1,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [6]=
    {
        ["nID"]=6,
        ["nMapID"]=16,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_QiXiu.png",
        ["szComment"]="七秀",
        ["nTrafficID"]=16,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [7]=
    {
        ["nID"]=7,
        ["nMapID"]=21,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_BaLing.png",
        ["szComment"]="巴陵县",
        ["nTrafficID"]=21,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [8]=
    {
        ["nID"]=8,
        ["nMapID"]=5,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ShaoLin.png",
        ["szComment"]="少林",
        ["nTrafficID"]=5,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [9]=
    {
        ["nID"]=9,
        ["nMapID"]=7,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ChunYang.png",
        ["szComment"]="纯阳",
        ["nTrafficID"]=7,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [10]=
    {
        ["nID"]=10,
        ["nMapID"]=8,
        ["szType"]="城市",
        ["szFrame"]="UIAtlas2_Map_CityIcon_LuoYang.png",
        ["szComment"]="洛阳",
        ["nTrafficID"]=8,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [11]=
    {
        ["nID"]=11,
        ["nMapID"]=9,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_LuoDao.png",
        ["szComment"]="洛道",
        ["nTrafficID"]=9,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [12]=
    {
        ["nID"]=12,
        ["nMapID"]=10,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_KouDao.png",
        ["szComment"]="寇岛",
        ["nTrafficID"]=10,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [13]=
    {
        ["nID"]=13,
        ["nMapID"]=11,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_TianCe.png",
        ["szComment"]="天策",
        ["nTrafficID"]=11,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [14]=
    {
        ["nID"]=14,
        ["nMapID"]=12,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_FengHuaGu.png",
        ["szComment"]="枫华谷",
        ["nTrafficID"]=12,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [15]=
    {
        ["nID"]=15,
        ["nMapID"]=13,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_JinShuiZhen.png",
        ["szComment"]="金水镇",
        ["nTrafficID"]=13,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [16]=
    {
        ["nID"]=16,
        ["nMapID"]=30,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_KunLun.png",
        ["szComment"]="昆仑",
        ["nTrafficID"]=30,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [17]=
    {
        ["nID"]=17,
        ["nMapID"]=22,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_NanPingShan.png",
        ["szComment"]="南屏山",
        ["nTrafficID"]=22,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [18]=
    {
        ["nID"]=18,
        ["nMapID"]=23,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_LongMengHuangMo.png",
        ["szComment"]="龙门荒漠",
        ["nTrafficID"]=23,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [19]=
    {
        ["nID"]=19,
        ["nMapID"]=35,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_QuTangXia.png",
        ["szComment"]="瞿塘峡",
        ["nTrafficID"]=35,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [20]=
    {
        ["nID"]=20,
        ["nMapID"]=15,
        ["szType"]="城市",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ChangAn.png",
        ["szComment"]="长安",
        ["nTrafficID"]=15,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [21]=
    {
        ["nID"]=21,
        ["nMapID"]=49,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_CangJian.png",
        ["szComment"]="藏剑山庄",
        ["nTrafficID"]=49,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [22]=
    {
        ["nID"]=22,
        ["nMapID"]=103,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_RongTianLing.png",
        ["szComment"]="融天岭",
        ["nTrafficID"]=432,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [23]=
    {
        ["nID"]=23,
        ["nMapID"]=104,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_HeiLongZhao.png",
        ["szComment"]="黑龙沼",
        ["nTrafficID"]=217,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [24]=
    {
        ["nID"]=24,
        ["nMapID"]=102,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_WuDu.png",
        ["szComment"]="五毒",
        ["nTrafficID"]=345,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [25]=
    {
        ["nID"]=25,
        ["nMapID"]=100,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_BaiLongKou.png",
        ["szComment"]="白龙口",
        ["nTrafficID"]=342,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [26]=
    {
        ["nID"]=26,
        ["nMapID"]=101,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_WuLiangShan.png",
        ["szComment"]="无量山",
        ["nTrafficID"]=435,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [27]=
    {
        ["nID"]=27,
        ["nMapID"]=108,
        ["szType"]="主城",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ChengDu.png",
        ["szComment"]="成都",
        ["nTrafficID"]=440,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [28]=
    {
        ["nID"]=28,
        ["nMapID"]=122,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_TangMen.png",
        ["szComment"]="唐门",
        ["nTrafficID"]=516,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [29]=
    {
        ["nID"]=29,
        ["nMapID"]=105,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_CangShanEr.png",
        ["szComment"]="苍山洱海",
        ["nTrafficID"]=9651,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [30]=
    {
        ["nID"]=30,
        ["nMapID"]=150,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_MingJiao.png",
        ["szComment"]="明教",
        ["nTrafficID"]=681,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [31]=
    {
        ["nID"]=31,
        ["nMapID"]=152,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_DaTangJianYu.png",
        ["szComment"]="大唐监狱",
        ["nTrafficID"]=152,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [32]=
    {
        ["nID"]=32,
        ["nMapID"]=159,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_GaiBang.png",
        ["szComment"]="丐帮",
        ["nTrafficID"]=961,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [33]=
    {
        ["nID"]=33,
        ["nMapID"]=153,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_MaWeiYi.png",
        ["szComment"]="马嵬驿",
        ["nTrafficID"]=894,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [34]=
    {
        ["nID"]=34,
        ["nMapID"]=172,
        ["szType"]="城市",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ChangAnCheng.png",
        ["szComment"]="长安城",
        ["nTrafficID"]=1136,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [35]=
    {
        ["nID"]=35,
        ["nMapID"]=194,
        ["szType"]="主城",
        ["szFrame"]="UIAtlas2_Map_CityIcon_TaiYuan.png",
        ["szComment"]="太原",
        ["nTrafficID"]=1390,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [36]=
    {
        ["nID"]=36,
        ["nMapID"]=193,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_CangYun.png",
        ["szComment"]="苍云",
        ["nTrafficID"]=1407,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [37]=
    {
        ["nID"]=37,
        ["nMapID"]=215,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_QianDaoHu.png",
        ["szComment"]="千岛湖",
        ["nTrafficID"]=1504,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [38]=
    {
        ["nID"]=38,
        ["nMapID"]=213,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ChangGeMen.png",
        ["szComment"]="长歌门",
        ["nTrafficID"]=1486,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [39]=
    {
        ["nID"]=39,
        ["nMapID"]=214,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_WuTaiShan.png",
        ["szComment"]="五台山",
        ["nTrafficID"]=1506,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [40]=
    {
        ["nID"]=40,
        ["nMapID"]=216,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_YinShanDaCaoYuan.png",
        ["szComment"]="阴山大草原",
        ["nTrafficID"]=1489,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [41]=
    {
        ["nID"]=41,
        ["nMapID"]=217,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_HeiGeBi.png",
        ["szComment"]="黑戈壁",
        ["nTrafficID"]=1485,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [42]=
    {
        ["nID"]=42,
        ["nMapID"]=243,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_BaDao.png",
        ["szComment"]="霸刀山庄",
        ["nTrafficID"]=1682,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [43]=
    {
        ["nID"]=43,
        ["nMapID"]=239,
        ["szType"]="城市",
        ["szFrame"]="UIAtlas2_Map_CityIcon_LuoYangCheng.png",
        ["szComment"]="洛阳城",
        ["nTrafficID"]=1693,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [44]=
    {
        ["nID"]=44,
        ["nMapID"]=151,
        ["szType"]="城市",
        ["szFrame"]="UIAtlas2_Map_CityIcon_LuoYangZhanLuan.png",
        ["szComment"]="洛阳·战乱",
        ["nTrafficID"]=902,
        ["szShowLevel"]="67~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [45]=
    {
        ["nID"]=45,
        ["nMapID"]=158,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_TianCeZhanLuan.png",
        ["szComment"]="天策·战乱",
        ["nTrafficID"]=913,
        ["szShowLevel"]="67~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [46]=
    {
        ["nID"]=46,
        ["nMapID"]=139,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_FengHuaGuZhanLuan.png",
        ["szComment"]="枫华谷·战乱",
        ["nTrafficID"]=928,
        ["szShowLevel"]="67~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [47]=
    {
        ["nID"]=47,
        ["nMapID"]=156,
        ["szType"]="城市",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ChangAnZhanLuan.png",
        ["szComment"]="长安·战乱",
        ["nTrafficID"]=891,
        ["szShowLevel"]="67~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [48]=
    {
        ["nID"]=48,
        ["nMapID"]=330,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_LongQuanFu.png",
        ["szComment"]="龙泉府",
        ["nTrafficID"]=2715,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [49]=
    {
        ["nID"]=49,
        ["nMapID"]=325,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_DongTianFuDi.png",
        ["szComment"]="洞天福地岛",
        ["nTrafficID"]=2632,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [50]=
    {
        ["nID"]=50,
        ["nMapID"]=333,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_PengLai.png",
        ["szComment"]="蓬莱",
        ["nTrafficID"]=2713,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [51]=
    {
        ["nID"]=51,
        ["nMapID"]=334,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_JingShouDaoYuanDao.png",
        ["szComment"]="经首道源岛",
        ["nTrafficID"]=2702,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [52]=
    {
        ["nID"]=52,
        ["nMapID"]=332,
        ["szType"]="主城",
        ["szFrame"]="UIAtlas2_Map_CityIcon_XiaKeDao.png",
        ["szComment"]="侠客岛",
        ["nTrafficID"]=2716,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [53]=
    {
        ["nID"]=53,
        ["nMapID"]=411,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_KunPengDao.png",
        ["szComment"]="鲲鹏岛",
        ["nTrafficID"]=2767,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [54]=
    {
        ["nID"]=54,
        ["nMapID"]=444,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_QiangWeiLieDao.png",
        ["szComment"]="蔷薇列岛",
        ["nTrafficID"]=2942,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [55]=
    {
        ["nID"]=55,
        ["nMapID"]=419,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_LingXueGe.png",
        ["szComment"]="凌雪阁",
        ["nTrafficID"]=2957,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [56]=
    {
        ["nID"]=56,
        ["nMapID"]=473,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_WanHuaZhanLuan.png",
        ["szComment"]="万花·乱世",
        ["nTrafficID"]=3068,
        ["szShowLevel"]="100~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [57]=
    {
        ["nID"]=57,
        ["nMapID"]=488,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_CangJianZhanLuan.png",
        ["szComment"]="藏剑·乱世",
        ["nTrafficID"]=3130,
        ["szShowLevel"]="100~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [58]=
    {
        ["nID"]=58,
        ["nMapID"]=475,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ShaoLinZhanLuan.png",
        ["szComment"]="少林·乱世",
        ["nTrafficID"]=3044,
        ["szShowLevel"]="100~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [59]=
    {
        ["nID"]=59,
        ["nMapID"]=474,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_QiXiuZhanLuan.png",
        ["szComment"]="七秀·乱世",
        ["nTrafficID"]=3071,
        ["szShowLevel"]="100~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [60]=
    {
        ["nID"]=60,
        ["nMapID"]=464,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_YanTianZong.png",
        ["szComment"]="衍天宗",
        ["nTrafficID"]=3099,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [61]=
    {
        ["nID"]=61,
        ["nMapID"]=526,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_BeiTianYaoZong.png",
        ["szComment"]="北天药宗",
        ["nTrafficID"]=3224,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [62]=
    {
        ["nID"]=62,
        ["nMapID"]=525,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_HeiShanLinHaiXin.png",
        ["szComment"]="黑山林海",
        ["nTrafficID"]=3260,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [63]=
    {
        ["nID"]=63,
        ["nMapID"]=578,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_DaoZong.png",
        ["szComment"]="刀宗",
        ["nTrafficID"]=3309,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [64]=
    {
        ["nID"]=64,
        ["nMapID"]=579,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_BaiXi.png",
        ["szComment"]="百溪",
        ["nTrafficID"]=3476,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [65]=
    {
        ["nID"]=65,
        ["nMapID"]=580,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_LanKeShan.png",
        ["szComment"]="烂柯山",
        ["nTrafficID"]=3446,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [66]=
    {
        ["nID"]=66,
        ["nMapID"]=581,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ChuZhou.png",
        ["szComment"]="楚州",
        ["nTrafficID"]=3486,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [67]=
    {
        ["nID"]=67,
        ["nMapID"]=582,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_ShengJiang.png",
        ["szComment"]="晟江",
        ["nTrafficID"]=3469,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [68]=
    {
        ["nID"]=68,
        ["nMapID"]=621,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_PanYuan.png",
        ["szComment"]="磐渊",
        ["nTrafficID"]=3498,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [69]=
    {
        ["nID"]=69,
        ["nMapID"]=642,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_WanLingShanZhuang.png",
        ["szComment"]="万灵山庄",
        ["nTrafficID"]=3613,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [70]=
    {
        ["nID"]=70,
        ["nMapID"]=647,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_YinShuangKou.png",
        ["szComment"]="银霜口",
        ["nTrafficID"]=3618,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [71]=
    {
        ["nID"]=71,
        ["nMapID"]=673,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_HeXiHanMo.png",
        ["szComment"]="河西瀚漠",
        ["nTrafficID"]=5180,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [72]=
    {
        ["nID"]=72,
        ["nMapID"]=666,
        ["szType"]="门派",
        ["szFrame"]="UIAtlas2_Map_CityIcon_NanZhaoDuanShi.png",
        ["szComment"]="南诏段氏",
        ["nTrafficID"]=5135,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [73]=
    {
        ["nID"]=73,
        ["nMapID"]=701,
        ["szType"]="城市",
        ["szFrame"]="UIAtlas2_Map_CityIcon_HuangCheng.png",
        ["szComment"]="皇城",
        ["nTrafficID"]=5324,
        ["szShowLevel"]="67~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [74]=
    {
        ["nID"]=74,
        ["nMapID"]=718,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_YongNingWan.png",
        ["szComment"]="永宁湾",
        ["nTrafficID"]=5584,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    },
    [75]=
    {
        ["nID"]=75,
        ["nMapID"]=713,
        ["szType"]="野外",
        ["szFrame"]="UIAtlas2_Map_CityIcon_YiLiChuan.png",
        ["szComment"]="伊丽川",
        ["nTrafficID"]=5564,
        ["szShowLevel"]="0~max",
        ["szEnemyLevel"]="0~max",
        ["szQuestLevel"]="0~max"
    }
}
