--*************************************** 工具生成 ***************************************
UIWorldMapCopyTab = 
{
    [1]=
    {
        ["nID"]=1,
        ["nMapID"]=26,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_DiHuaQianShan.png",
        ["szComment"]="荻花宫前山",
        ["szVersion"]="风起稻香",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="40"
    },
    [2]=
    {
        ["nID"]=2,
        ["nMapID"]=19,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_kongwufeng.png",
        ["szComment"]="空雾峰",
        ["szVersion"]="风起稻香",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="43"
    },
    [3]=
    {
        ["nID"]=3,
        ["nMapID"]=17,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_tiangongfang.png",
        ["szComment"]="天工坊",
        ["szVersion"]="风起稻香",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="37"
    },
    [4]=
    {
        ["nID"]=4,
        ["nMapID"]=32,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_ZhanBaoJiaLan.png",
        ["szComment"]="战宝迦兰",
        ["szVersion"]="风起稻香",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="46"
    },
    [5]=
    {
        ["nID"]=5,
        ["nMapID"]=20,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_sancaizhen.png",
        ["szComment"]="天地三才阵",
        ["szVersion"]="风起稻香",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="36"
    },
    [6]=
    {
        ["nID"]=6,
        ["nMapID"]=14,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_lingxiaoxia.png",
        ["szComment"]="灵霄峡",
        ["szVersion"]="风起稻香",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="45"
    },
    [7]=
    {
        ["nID"]=7,
        ["nMapID"]=33,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_tianzifeng.png",
        ["szComment"]="天子峰",
        ["szVersion"]="风起稻香",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="42"
    },
    [8]=
    {
        ["nID"]=8,
        ["nMapID"]=18,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_wuyandao.png",
        ["szComment"]="无盐岛",
        ["szVersion"]="风起稻香",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="41"
    },
    [9]=
    {
        ["nID"]=9,
        ["nMapID"]=28,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_rilunshancheng.png",
        ["szComment"]="日轮山城",
        ["szVersion"]="风起稻香",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="44"
    },
    [10]=
    {
        ["nID"]=10,
        ["nMapID"]=51,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_jianzhong.png",
        ["szComment"]="剑冢",
        ["szVersion"]="风起稻香",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="62"
    },
    [11]=
    {
        ["nID"]=11,
        ["nMapID"]=126,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_jianzhong.png",
        ["szComment"]="神剑冢",
        ["szVersion"]="巴蜀风云",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [12]=
    {
        ["nID"]=12,
        ["nMapID"]=61,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_GongZhongShenWu.png",
        ["szComment"]="宫中神武遗迹",
        ["szVersion"]="风起稻香",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="63,64"
    },
    [13]=
    {
        ["nID"]=13,
        ["nMapID"]=60,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_ChiGuoTianWang.png",
        ["szComment"]="持国天王殿",
        ["szVersion"]="风起稻香",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="65,66"
    },
    [14]=
    {
        ["nID"]=14,
        ["nMapID"]=67,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_DiHuaHouShan.png",
        ["szComment"]="荻花宫后山",
        ["szVersion"]="风起稻香",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="73"
    },
    [15]=
    {
        ["nID"]=15,
        ["nMapID"]=68,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_dihuashengdian.png",
        ["szComment"]="荻花圣殿",
        ["szVersion"]="巴蜀风云",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="69,70,72"
    },
    [16]=
    {
        ["nID"]=16,
        ["nMapID"]=107,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_wulianggong.png",
        ["szComment"]="无量宫",
        ["szVersion"]="巴蜀风云",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="114"
    },
    [17]=
    {
        ["nID"]=17,
        ["nMapID"]=75,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_dushendian.png",
        ["szComment"]="毒神殿",
        ["szVersion"]="巴蜀风云",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="112"
    },
    [18]=
    {
        ["nID"]=18,
        ["nMapID"]=106,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_fawangku.png",
        ["szComment"]="法王窟",
        ["szVersion"]="巴蜀风云",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="115"
    },
    [19]=
    {
        ["nID"]=19,
        ["nMapID"]=116,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_xianzonglin.png",
        ["szComment"]="仙踪林",
        ["szVersion"]="巴蜀风云",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="71,111"
    },
    [20]=
    {
        ["nID"]=20,
        ["nMapID"]=110,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_jimieting.png",
        ["szComment"]="寂灭厅",
        ["szVersion"]="巴蜀风云",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="113"
    },
    [21]=
    {
        ["nID"]=21,
        ["nMapID"]=109,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_longyuanze.png",
        ["szComment"]="龙渊泽",
        ["szVersion"]="巴蜀风云",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="117,118,119"
    },
    [22]=
    {
        ["nID"]=22,
        ["nMapID"]=120,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_dihuadongku.png",
        ["szComment"]="荻花洞窟",
        ["szVersion"]="巴蜀风云",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="130"
    },
    [23]=
    {
        ["nID"]=23,
        ["nMapID"]=123,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_tangmenmishi.png",
        ["szComment"]="唐门密室",
        ["szVersion"]="巴蜀风云",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="125"
    },
    [24]=
    {
        ["nID"]=24,
        ["nMapID"]=134,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_zhulongdian.png",
        ["szComment"]="烛龙殿",
        ["szVersion"]="巴蜀风云",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="133"
    },
    [25]=
    {
        ["nID"]=25,
        ["nMapID"]=142,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_guangmingdingmidao.png",
        ["szComment"]="光明顶秘道",
        ["szVersion"]="巴蜀风云",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="141"
    },
    [26]=
    {
        ["nID"]=26,
        ["nMapID"]=140,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_nanzhaohuanggong.png",
        ["szComment"]="南诏皇宫",
        ["szVersion"]="巴蜀风云",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="155"
    },
    [27]=
    {
        ["nID"]=27,
        ["nMapID"]=169,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_liulidao.png",
        ["szComment"]="流离岛",
        ["szVersion"]="安史之乱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="170"
    },
    [28]=
    {
        ["nID"]=28,
        ["nMapID"]=184,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_mojiamidian.png",
        ["szComment"]="墨家秘殿",
        ["szVersion"]="安史之乱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [29]=
    {
        ["nID"]=29,
        ["nMapID"]=182,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_QinHuangLin.png",
        ["szComment"]="秦皇陵",
        ["szVersion"]="安史之乱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="183"
    },
    [30]=
    {
        ["nID"]=30,
        ["nMapID"]=177,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_FengXueDXC.png",
        ["szComment"]="风雪稻香村",
        ["szVersion"]="安史之乱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="178"
    },
    [31]=
    {
        ["nID"]=31,
        ["nMapID"]=196,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_YanMenGuanZhiYi.png",
        ["szComment"]="雁门关之役",
        ["szVersion"]="安史之乱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="195"
    },
    [32]=
    {
        ["nID"]=32,
        ["nMapID"]=191,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_YeShouGuCheng.png",
        ["szComment"]="太原之战·夜守孤城",
        ["szVersion"]="安史之乱",
        ["szShowName"]="夜守孤城",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [33]=
    {
        ["nID"]=33,
        ["nMapID"]=192,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_ZhuHuQuLang.png",
        ["szComment"]="太原之战·逐虎驱狼",
        ["szVersion"]="安史之乱",
        ["szShowName"]="逐虎驱狼",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [34]=
    {
        ["nID"]=34,
        ["nMapID"]=200,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_CanTuiHaiTing.png",
        ["szComment"]="璨翠海厅",
        ["szVersion"]="安史之乱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [35]=
    {
        ["nID"]=35,
        ["nMapID"]=221,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_huayuebieyuan.png",
        ["szComment"]="永王行宫·花月别院",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="花月别院",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="230"
    },
    [36]=
    {
        ["nID"]=36,
        ["nMapID"]=220,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_xianlvtingyuan.png",
        ["szComment"]="永王行宫·仙侣庭园",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="仙侣庭园",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="231"
    },
    [37]=
    {
        ["nID"]=37,
        ["nMapID"]=203,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_tianqilin.png",
        ["szComment"]="天泣林",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="224"
    },
    [38]=
    {
        ["nID"]=38,
        ["nMapID"]=204,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_yinshanshengquan.png",
        ["szComment"]="阴山圣泉",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="227"
    },
    [39]=
    {
        ["nID"]=39,
        ["nMapID"]=219,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_weishanshuyuan.png",
        ["szComment"]="微山书院",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="225"
    },
    [40]=
    {
        ["nID"]=40,
        ["nMapID"]=209,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_fankongchanyuan.png",
        ["szComment"]="梵空禅院",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="228"
    },
    [41]=
    {
        ["nID"]=41,
        ["nMapID"]=218,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_yinxianshuixie.png",
        ["szComment"]="引仙水榭",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="229"
    },
    [42]=
    {
        ["nID"]=42,
        ["nMapID"]=242,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_BaiDiShuiGong.png",
        ["szComment"]="白帝水宫",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="244"
    },
    [43]=
    {
        ["nID"]=43,
        ["nMapID"]=256,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_xiyange.png",
        ["szComment"]="夕颜阁",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="257"
    },
    [44]=
    {
        ["nID"]=44,
        ["nMapID"]=240,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_GuanFengDian.png",
        ["szComment"]="上阳宫·观风殿",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="观风殿",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [45]=
    {
        ["nID"]=45,
        ["nMapID"]=241,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_ShuangYaoTing.png",
        ["szComment"]="上阳宫·双曜亭",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="双曜亭",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [46]=
    {
        ["nID"]=46,
        ["nMapID"]=263,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_duandaoting.png",
        ["szComment"]="风雷刀谷·锻刀厅",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="锻刀厅",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [47]=
    {
        ["nID"]=47,
        ["nMapID"]=264,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_qianleidian.png",
        ["szComment"]="风雷刀谷·千雷殿",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="千雷殿",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [48]=
    {
        ["nID"]=48,
        ["nMapID"]=262,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_daolunhaiting.png",
        ["szComment"]="刀轮海厅",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [49]=
    {
        ["nID"]=49,
        ["nMapID"]=167,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_yixiantian.png",
        ["szComment"]="一线天",
        ["szVersion"]="安史之乱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="157"
    },
    [50]=
    {
        ["nID"]=50,
        ["nMapID"]=160,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_ZhanBaoJiaLanJunXieKu.png",
        ["szComment"]="战宝军械库",
        ["szVersion"]="安史之乱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="171"
    },
    [51]=
    {
        ["nID"]=51,
        ["nMapID"]=161,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_huaqinggong.png",
        ["szComment"]="华清宫",
        ["szVersion"]="安史之乱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="162"
    },
    [52]=
    {
        ["nID"]=52,
        ["nMapID"]=163,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_HuaQingGongHuiYi.png",
        ["szComment"]="华清宫回忆录",
        ["szVersion"]="安史之乱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [53]=
    {
        ["nID"]=53,
        ["nMapID"]=164,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_daminggong.png",
        ["szComment"]="大明宫",
        ["szVersion"]="安史之乱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="165"
    },
    [54]=
    {
        ["nID"]=54,
        ["nMapID"]=179,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_zhichengmen.png",
        ["szComment"]="直城门",
        ["szVersion"]="安史之乱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [55]=
    {
        ["nID"]=55,
        ["nMapID"]=175,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_XueZhanTianCe.png",
        ["szComment"]="血战天策",
        ["szVersion"]="安史之乱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="176"
    },
    [56]=
    {
        ["nID"]=56,
        ["nMapID"]=187,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_ChunMingMen.png",
        ["szComment"]="春明门",
        ["szVersion"]="安史之乱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [57]=
    {
        ["nID"]=57,
        ["nMapID"]=283,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_ZhanShouShan.png",
        ["szComment"]="狼牙堡·战兽山",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="战兽山",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="286,288"
    },
    [58]=
    {
        ["nID"]=58,
        ["nMapID"]=284,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_YanRanFeng.png",
        ["szComment"]="狼牙堡·燕然峰",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="燕然峰",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="287,289"
    },
    [59]=
    {
        ["nID"]=59,
        ["nMapID"]=292,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_daoxiangmishi.png",
        ["szComment"]="稻香秘事",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="295"
    },
    [60]=
    {
        ["nID"]=60,
        ["nMapID"]=285,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_YinWuHu.png",
        ["szComment"]="银雾湖",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="290"
    },
    [61]=
    {
        ["nID"]=61,
        ["nMapID"]=298,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_HuiTianQian.png",
        ["szComment"]="狼牙堡·辉天堑",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="辉天堑",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="300"
    },
    [62]=
    {
        ["nID"]=62,
        ["nMapID"]=299,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_langshendian.png",
        ["szComment"]="狼牙堡·狼神殿",
        ["szVersion"]="剑胆琴心",
        ["szShowName"]="狼神殿",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="301,324"
    },
    [63]=
    {
        ["nID"]=63,
        ["nMapID"]=337,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_NiLanDongTian.png",
        ["szComment"]="泥兰洞天",
        ["szVersion"]="世外蓬莱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="356"
    },
    [64]=
    {
        ["nID"]=64,
        ["nMapID"]=339,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_DaYanPanSiDong.png",
        ["szComment"]="大衍盘丝洞",
        ["szVersion"]="世外蓬莱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="355"
    },
    [65]=
    {
        ["nID"]=65,
        ["nMapID"]=358,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_MiYuanDao.png",
        ["szComment"]="迷渊岛",
        ["szVersion"]="世外蓬莱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="343"
    },
    [66]=
    {
        ["nID"]=66,
        ["nMapID"]=341,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_huangxuelu.png",
        ["szComment"]="冰火岛·荒血路",
        ["szVersion"]="世外蓬莱",
        ["szShowName"]="荒血路",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="354,360,361"
    },
    [67]=
    {
        ["nID"]=67,
        ["nMapID"]=342,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_JiuBianGuan.png",
        ["szComment"]="九辩馆",
        ["szVersion"]="世外蓬莱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="359"
    },
    [68]=
    {
        ["nID"]=68,
        ["nMapID"]=340,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_JingBoHu.png",
        ["szComment"]="镜泊湖",
        ["szVersion"]="世外蓬莱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="357"
    },
    [69]=
    {
        ["nID"]=69,
        ["nMapID"]=347,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_qianlianyu.png",
        ["szComment"]="冰火岛·青莲狱",
        ["szVersion"]="世外蓬莱",
        ["szShowName"]="青莲狱",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="348,349,350"
    },
    [70]=
    {
        ["nID"]=70,
        ["nMapID"]=406,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_ZhouTianYu.png",
        ["szComment"]="周天屿",
        ["szVersion"]="世外蓬莱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="407"
    },
    [71]=
    {
        ["nID"]=71,
        ["nMapID"]=364,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_JuMingWan.png",
        ["szComment"]="尘归海·巨冥湾",
        ["szVersion"]="世外蓬莱",
        ["szShowName"]="巨冥湾",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="365,366"
    },
    [72]=
    {
        ["nID"]=72,
        ["nMapID"]=368,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_TaoTie.png",
        ["szComment"]="尘归海·饕餮洞",
        ["szVersion"]="世外蓬莱",
        ["szShowName"]="饕餮洞",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="369,370"
    },
    [73]=
    {
        ["nID"]=73,
        ["nMapID"]=131,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_ChiGuoHuiYiLu.png",
        ["szComment"]="持国天王回忆录",
        ["szVersion"]="巴蜀风云",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="148"
    },
    [74]=
    {
        ["nID"]=74,
        ["nMapID"]=34,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_fengyudaoxiangcun.png",
        ["szComment"]="风雨稻香村",
        ["szVersion"]="风起稻香",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="47"
    },
    [75]=
    {
        ["nID"]=75,
        ["nMapID"]=136,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_huizhantangmen.png",
        ["szComment"]="会战唐门",
        ["szVersion"]="巴蜀风云",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="138"
    },
    [76]=
    {
        ["nID"]=76,
        ["nMapID"]=431,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_XuanHeBieYuan.png",
        ["szComment"]="玄鹤别院",
        ["szVersion"]="世外蓬莱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="432"
    },
    [77]=
    {
        ["nID"]=77,
        ["nMapID"]=426,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_AoLongDao.png",
        ["szComment"]="敖龙岛",
        ["szVersion"]="世外蓬莱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="427,428"
    },
    [78]=
    {
        ["nID"]=78,
        ["nMapID"]=452,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_fanyangyebian.png",
        ["szComment"]="范阳夜变",
        ["szVersion"]="世外蓬莱",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="453,454"
    },
    [79]=
    {
        ["nID"]=79,
        ["nMapID"]=482,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_DaMoDong.png",
        ["szComment"]="达摩洞",
        ["szVersion"]="奉天证道",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="483,484"
    },
    [80]=
    {
        ["nID"]=80,
        ["nMapID"]=477,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_wutongshanzhuang.png",
        ["szComment"]="梧桐山庄",
        ["szVersion"]="奉天证道",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="478"
    },
    [81]=
    {
        ["nID"]=81,
        ["nMapID"]=479,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_LuoHanMen.png",
        ["szComment"]="罗汉门",
        ["szVersion"]="奉天证道",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="480"
    },
    [82]=
    {
        ["nID"]=82,
        ["nMapID"]=476,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_mengrujizhendao.png",
        ["szComment"]="梦入集真岛",
        ["szVersion"]="奉天证道",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="481"
    },
    [83]=
    {
        ["nID"]=83,
        ["nMapID"]=468,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_jianzhongjingbian.png",
        ["szComment"]="剑冢惊变",
        ["szVersion"]="奉天证道",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="469"
    },
    [84]=
    {
        ["nID"]=84,
        ["nMapID"]=489,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_yueluosanxing.png",
        ["szComment"]="月落三星",
        ["szVersion"]="奉天证道",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="490"
    },
    [85]=
    {
        ["nID"]=85,
        ["nMapID"]=521,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_ZhangShuiNanLu.png",
        ["szComment"]="漳水南路",
        ["szVersion"]="奉天证道",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="522"
    },
    [86]=
    {
        ["nID"]=86,
        ["nMapID"]=518,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_BaiDiJiangGuan.png",
        ["szComment"]="白帝江关",
        ["szVersion"]="奉天证道",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="519,520"
    },
    [87]=
    {
        ["nID"]=87,
        ["nMapID"]=563,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_WuShiBieYuan.png",
        ["szComment"]="武氏别院",
        ["szVersion"]="奉天证道",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="564"
    },
    [88]=
    {
        ["nID"]=88,
        ["nMapID"]=559,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_LeiYuDaZe.png",
        ["szComment"]="雷域大泽",
        ["szVersion"]="奉天证道",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="560,561"
    },
    [89]=
    {
        ["nID"]=89,
        ["nMapID"]=573,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_HeYangZhiZhan.png",
        ["szComment"]="河阳之战",
        ["szVersion"]="奉天证道",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="574,575"
    },
    [90]=
    {
        ["nID"]=90,
        ["nMapID"]=586,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_XiJinDu.png",
        ["szComment"]="西津渡",
        ["szVersion"]="横刀断浪",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="587,588"
    },
    [91]=
    {
        ["nID"]=91,
        ["nMapID"]=596,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_WoShiYuan.png",
        ["szComment"]="沃石院",
        ["szVersion"]="横刀断浪",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="597"
    },
    [92]=
    {
        ["nID"]=92,
        ["nMapID"]=606,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_YouTengGuan.png",
        ["szComment"]="幽藤馆",
        ["szVersion"]="横刀断浪",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="607"
    },
    [93]=
    {
        ["nID"]=93,
        ["nMapID"]=598,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_ZhenHaiGe.png",
        ["szComment"]="镇海阁地井",
        ["szVersion"]="横刀断浪",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="599"
    },
    [94]=
    {
        ["nID"]=94,
        ["nMapID"]=622,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_JiangTianYeYan.png",
        ["szComment"]="江天夜宴",
        ["szVersion"]="横刀断浪",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="623"
    },
    [95]=
    {
        ["nID"]=95,
        ["nMapID"]=629,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_GuJianTai.png",
        ["szComment"]="古剑台",
        ["szVersion"]="横刀断浪",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [96]=
    {
        ["nID"]=96,
        ["nMapID"]=639,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_LuQiaoYi.png",
        ["szComment"]="鹿桥驿",
        ["szVersion"]="横刀断浪",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="640"
    },
    [97]=
    {
        ["nID"]=97,
        ["nMapID"]=636,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_WuYuHeiLao.png",
        ["szComment"]="武狱黑牢",
        ["szVersion"]="横刀断浪",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="637,638"
    },
    [98]=
    {
        ["nID"]=98,
        ["nMapID"]=658,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_QiLingDongTian.png",
        ["szComment"]="栖灵洞天·旧事",
        ["szVersion"]="横刀断浪",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="659"
    },
    [99]=
    {
        ["nID"]=99,
        ["nMapID"]=648,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_TaiJiNiJing.png",
        ["szComment"]="九老洞",
        ["szVersion"]="横刀断浪",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="649,650"
    },
    [100]=
    {
        ["nID"]=100,
        ["nMapID"]=668,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_LengLongFeng.png",
        ["szComment"]="冷龙峰",
        ["szVersion"]="横刀断浪",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="669,670"
    },
    [101]=
    {
        ["nID"]=101,
        ["nMapID"]=682,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_TianLongShi",
        ["szComment"]="天龙寺",
        ["szVersion"]="丝路风语",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="683"
    },
    [102]=
    {
        ["nID"]=102,
        ["nMapID"]=684,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_BingChuanGongBaoKu",
        ["szComment"]="冰川宫宝库",
        ["szVersion"]="丝路风语",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="685"
    },
    [103]=
    {
        ["nID"]=103,
        ["nMapID"]=690,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_FengShaJiuLei",
        ["szComment"]="风砂旧垒",
        ["szVersion"]="丝路风语",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="691"
    },
    [104]=
    {
        ["nID"]=104,
        ["nMapID"]=693,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_BuRanKu",
        ["szComment"]="不染窟",
        ["szVersion"]="丝路风语",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="694"
    },
    [105]=
    {
        ["nID"]=105,
        ["nMapID"]=697,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_HeXiHanMo",
        ["szComment"]="跨服·河西瀚漠",
        ["szVersion"]="丝路风语",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [106]=
    {
        ["nID"]=106,
        ["nMapID"]=686,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_YiZhiKu",
        ["szComment"]="一之窟",
        ["szVersion"]="丝路风语",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="687,688"
    },
    [107]=
    {
        ["nID"]=107,
        ["nMapID"]=74,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_BangHuiLingDi",
        ["szComment"]="帮会领地",
        ["szVersion"]="帮会",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [108]=
    {
        ["nID"]=108,
        ["nMapID"]=706,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_TaiJiGong",
        ["szComment"]="太极宫",
        ["szVersion"]="丝路风语",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="707,708"
    },
    [109]=
    {
        ["nID"]=109,
        ["nMapID"]=710,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_KongChengDianSHang",
        ["szComment"]="空城殿",
        ["szVersion"]="丝路风语",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [110]=
    {
        ["nID"]=110,
        ["nMapID"]=711,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_kongchengdianxia",
        ["szComment"]="空城殿·下",
        ["szVersion"]="丝路风语",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [111]=
    {
        ["nID"]=111,
        ["nMapID"]=726,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_TaShanDao",
        ["szComment"]="獭山岛",
        ["szVersion"]="丝路风语",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [112]=
    {
        ["nID"]=112,
        ["nMapID"]=722,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_HuiZhanGongYueCheng",
        ["szComment"]="会战弓月城",
        ["szVersion"]="丝路风语",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="723,724"
    },
    [113]=
    {
        ["nID"]=113,
        ["nMapID"]=720,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_FuZuiZhiYuan",
        ["szComment"]="缚罪之渊",
        ["szVersion"]="丝路风语",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]=""
    },
    [114]=
    {
        ["nID"]=114,
        ["nMapID"]=793,
        ["szFrame"]="UIAtlas2_Map_DungeonIcon_LangFengXuanCheng",
        ["szComment"]="阆风悬城",
        ["szVersion"]="丝路风语",
        ["szShowName"]="",
        ["szShowLevel"]="0~max",
        ["szOtherMapID"]="794,795"
    }
}
