[Url]

; 国服cdn
AutoUpdate=true
RemoteUpdateUrl=http://10.11.96.137/jxo_dev/client/cn_auto_patch/


[Network]
; 修改登陆服务器
; 国服地址10.11.69.77:11051
GatewayAddr=10.11.69.77:11051

[Sdk]
;是否忽略渠道登陆
Skip=true

[Log]
;是否打开客户端日志界面
Open=true

[GM]
Open=true

[Global]
EnableAutoTest=true
