[Url]
;是否启动自动更新
AutoUpdate=true
RemoteUpdateUrl=http://10.11.96.137/jxo_dev/client/v5_auto_patch/

[Network]
; 修改登陆服务器10.11.184.109:11001
GatewayAddr=10.11.69.77:11051
;GatewayAddr=10.11.145.236:11001

[Sdk]
;是否忽略渠道登陆
Skip=true

[Log]
;是否打开客户端日志界面
Open=true

[GM]
Open=true

