[Url]
;是否启动自动更新
; 越南服cdn
;AutoUpdate=true
;RemoteUpdateUrl=http://10.11.96.137/jxo_dev/client/trunk_debug_patch/

; 国服cdn
AutoUpdate=true
RemoteUpdateUrl=http://10.11.96.137/jxo_dev/client/patch/

; 越南服需要开启AutoUpdate和RemoteUpdateUrl 取消  ; 注释就行  给国服加注释，
; 国服需要开启AutoUpdate和RemoteUpdateUrl 取消  ; 注释就行  给越南服加注释，


[Network]
; 修改登陆服务器
; 国服地址10.11.184.109:11011
GatewayAddr=10.11.69.77:11011

; 越南服地址10.11.69.77:11041
;GatewayAddr=10.11.69.77:11041

[Sdk]
;是否忽略渠道登陆
Skip=true

[Log]
;是否打开客户端日志界面
Open=true

[GM]
Open=true

[Global]
EnableAutoTest=true
